add Bricks Builder icon
simple-icons/simple-icons pull request #10022
Opened 2023-12-04 13:59 UTC by Mvlprem

![bricks](https://github.com/simple-icons/simple-icons/assets/54018894/c37a2379-49fd-4160-804f-b49016efbff0)

**Issue:** closes #9710

**Similarweb rank:** [192,471](https://www.similarweb.com/website/bricksbuilder.io/#overview)

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

Official svg can be downloaded from their website [Media kit](https://bricksbuilder.io/bricks-builder-brand-assets.zip)

Svg used ` bricks-favicon-b.svg ` from the downloaded kit. Hex taken from the logo.

2023-12-04 14:49 UTC, adamrusted commented
Thanks for this @Mvlprem!
I think I'd either expect to see some differentiation between the shades of yellow used in the icon or - as used on their website - the `b` letter in `bricks-favicon-b.svg`. What are your thoughts on this?

2023-12-04 15:20 UTC, adamrusted commented
That's fine on selecting the hex for us to use - but in terms of the icon, given we're a monochrome icon library I'd expect to either see some gaps between the colours in the icon you selected - or we should use the monochrome icon they provided, being the `b` one I mentioned above :)

2023-12-04 16:32 UTC, Mvlprem commented
> That's fine on selecting the hex for us to use - but in terms of the icon, given we're a monochrome icon library I'd expect to either see some gaps between the colours in the icon you selected - or we should use the monochrome icon they provided, being the `b` one I mentioned above :)

Initially i wanted to go with the **`b`** icon too but upon scaling down the icon it becomes `18.73 in width and 24 in height` now these dimensions throw linting error like this ` <path> must be centered at (12, 12); the center is currently (12.367, 12) ` I don't know how to get around this issue as for my understanding it's due to decimal points.

please let me know how to get around this as i was facing this issue with other icons too and i'll update it to **`b`** icon.

2023-12-06 07:46 UTC, Mvlprem commented
> Let me take a look at the `b` path. The linter can be a fickle beast - so we might just need to optimise to a higher precision...

Hello @adamrusted I've updated the icon to **`b`** logo please take a look.

2023-12-08 16:05 UTC, PeterShaggyNoble requested changes
SVG looks good to me now, @Mvlprem 👍🏻 Just 2 small suggestions for the data and this will be ready to merge.

2023-12-09 11:10 UTC, Mvlprem commented on _data/simple-icons.json
> +            "hex": "212121",
Hello @PeterShaggyNoble updated **hex** & **title**

2023-12-09 11:26 UTC, PeterShaggyNoble approved these changes

2023-12-09 11:27 UTC, merged