Add sidekiq svg
simple-icons/simple-icons pull request #10045
Opened 2023-12-07 17:59 UTC by RiteshK-611

**Issue:** closes #9886 

**Similarweb rank:**
Sidekiq has almost 13k stars in GitHub see https://github.com/sidekiq/sidekiq

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description
This commit resolves the issue #9886 by adding svg/icon for Sidekiq 

### Preview
![sidekiq](https://github.com/simple-icons/simple-icons/assets/61982298/9b4c62cb-e1eb-4857-a21f-0775381bf150)

2023-12-07 18:37 UTC, RiteshK-611 commented
Hi @adamrusted 
I tried tried everything from my side but this lint is failing on Github

we can see here locally lint is passing and I even ran formatter
![image](https://github.com/simple-icons/simple-icons/assets/61982298/b7239c8c-5460-414d-beff-d61807526195)

2023-12-09 14:26 UTC, RiteshK-611 commented
No, I haven't run `npm install` recently. Should I try running that?

2024-01-11 15:08 UTC, PeterShaggyNoble requested changes
I think we need to include the background circle here, @RiteshK-611; all the monochrome versions at the source URL include it.

2024-02-12 12:10 UTC, PeterShaggyNoble approved these changes

2024-02-12 12:11 UTC, merged