Update Private Internet Access
simple-icons/simple-icons pull request #10088
Opened 2023-12-13 14:39 UTC by PeterShaggyNoble

![image](https://github.com/simple-icons/simple-icons/assets/15157491/ace8eb4d-9c97-4067-9193-17c0ee51d5e8)

**Issue:** closes #9894

**Similarweb rank:** [43990](https://similarweb.com/website/privateinternetaccess.com)

### Checklist
- [ ] I updated the JSON data in `_data/simple-icons.json`
- [ ] I optimized the icon with SVGO or SVGOMG
- [ ] The SVG `viewbox` is `0 0 24 24`

### Description
Icon & colour from [SVG](https://assets-cms.privateinternetaccess.com/img/frontend/pia_menu_logo_light.svg) in [source](https://www.privateinternetaccess.com) header.

2023-12-14 09:37 UTC, adamrusted requested changes
I'm seeing a _slight_ mis-match on this, @PeterShaggyNoble.
Could you have another look please?
![image](https://github.com/simple-icons/simple-icons/assets/1830867/9cc9982f-23c3-4962-8918-5c4a7a16fcbc)

2023-12-22 15:28 UTC, adamrusted approved these changes

2023-12-22 15:29 UTC, adamrusted requested changes
![image](https://github.com/simple-icons/simple-icons/assets/1830867/656e391d-5070-4eaa-b259-9be28cc02ca3)

Still seeing a bit of a difference in the rounded shapes at the top @PeterShaggyNoble

2024-01-08 15:13 UTC, PeterShaggyNoble commented
Only getting back around to this one now, @adamrusted, and I'm not seeing the difference you mentioned above. Will request further reviews, though, to be sure.

2024-01-08 15:45 UTC, service-paradis commented
I'm seeing the difference stated by @adamrusted, but it is very subtle on my side:
![image](https://github.com/simple-icons/simple-icons/assets/12817388/a8bdcbd7-04f0-4c9b-b83e-06dd448dd1e5)


There is also a tiny difference inside the keyhole:
![image](https://github.com/simple-icons/simple-icons/assets/12817388/063758cc-4265-41f6-8ee0-055dc02f822f)

It might be small enough to let this go...

2024-01-10 06:10 UTC, PratyushJayachandran commented on icons/privateinternetaccess.svg
I see [some differences too!!!](https://github.com/simple-icons/simple-icons/assets/35000807/11172072-2167-4049-b541-6677e3e4d7b3)

2024-01-10 16:11 UTC, PeterShaggyNoble commented on icons/privateinternetaccess.svg
That just looks like an anti-aliasing issue between the white & the black to me, @PratyushJayachandran.

2024-01-22 20:07 UTC, merged