Update Instagram
simple-icons/simple-icons pull request #10153
Opened 2023-12-19 15:45 UTC by PeterShaggyNoble

![Instagram](https://github.com/simple-icons/simple-icons/assets/15157491/87b82e23-bb70-40df-9d1b-e0b21c09db74)

**Issue:** #10073

**Similarweb rank:** [4](https://similarweb.com/website/instagram.com)

### Checklist
- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

2023-12-19 16:01 UTC, adamrusted requested changes
Seeing slight differences in the curves here @PeterShaggyNoble when comparing to `IG_brand_asset_pack_2023.zip\01 Static Glyph\01 Gradient Glyph\Instagram_Glyph_Gradient.svg` - potentially either precision, or I'm losing my mind.
![image](https://github.com/simple-icons/simple-icons/assets/1830867/1e79dd94-e357-43c6-9f35-472012e3836a)

2023-12-19 16:29 UTC, PeterShaggyNoble commented
Sorry, @adamrusted, I should have mentioned that mine is based off `\01 Static Glyph\03 Black Glyph\Instagram_Glyph_Black.svg`; are you still seeing the same differences there?

2024-01-09 17:17 UTC, PeterShaggyNoble commented
Coming back to this one, @adamrusted, `\01 Static Glyph\01 Gradient Glyph\Instagram_Glyph_Gradient.svg` is actually a raster image embedded in an SVG - why would they do that?! 🙄

2024-01-11 13:04 UTC, adamrusted approved these changes

2024-01-11 13:05 UTC, merged