Add Zigbee2MQTT
simple-icons/simple-icons pull request #10212
Opened 2024-01-05 13:00 UTC by PeterShaggyNoble

![Zigbee2MQTT](https://github.com/simple-icons/simple-icons/assets/15157491/01918b17-6b6f-4282-8b69-219828839549)

**Issue:** closes #7766

**Similarweb rank:** [83607](https://similarweb.com/website/zigbee2mqtt.io)

### Checklist
- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description
"You've had 2 weeks off, your hands barely work, and you can't see straight; this looks like a nice easy icon to get you back into the swing of things before you start reviewing PRs again."

_**WRONG!**_ The [source file](https://github.com/Koenkk/zigbee2mqtt/blob/434981b567122c745c6a5228cd89b74694b15e4c/images/logo_vector.svg) is an absolute mess!

Colour from [website](https://www.zigbee2mqtt.io/) stylesheet (`--c-brand`).

2024-02-04 10:38 UTC, adamrusted commented on icons/zigbee2mqtt.svg
I would probably argue for inverting this - so keeping the fill on the octogon, and cutting the inner shapes out - for clarity sake. See below image, what do you think @PeterShaggyNoble?

![image](https://github.com/simple-icons/simple-icons/assets/1830867/47861b9a-a143-4979-afae-8e90a8a34c41)

2024-02-05 08:14 UTC, PratyushJayachandran commented on icons/zigbee2mqtt.svg
I agree with @adamrusted.
However, do you have a better suggestion @Koenkk?

2024-02-05 19:09 UTC, Koenkk commented on icons/zigbee2mqtt.svg
I'm fine, but why not keep the inner shapes black?

2024-02-06 12:43 UTC, adamrusted commented on icons/zigbee2mqtt.svg
Unfortunately @Koenkk we only deal in monochrome icons on this project - so it'd have to be a single shape with cut-outs. It's up to users of this project then how they display the icon.

2024-02-06 16:44 UTC, Koenkk commented on icons/zigbee2mqtt.svg
I see, then this is fine.

2024-02-14 04:29 UTC, PratyushJayachandran approved these changes
I see that you have did some corrections from the source @PeterShaggyNoble. I feel it looks good 😄

2024-02-15 09:41 UTC, adamrusted requested changes
![image](https://github.com/simple-icons/simple-icons/assets/1830867/26632037-c8f5-484f-81f6-0f960575c966)

Unsure if this is just Affinity Designer playing games with me - but I'm still seeing these differences!

2024-02-23 10:25 UTC, adamrusted requested changes
Seeing different differences in Illustrator - but they're still present!
Would you mind taking another look please @PeterShaggyNoble?

**EDIT:** If you include the stroke (I haven't, every time) it's only _slightly_ off in the centre there.

![image](https://github.com/simple-icons/simple-icons/assets/1830867/b8a21b1e-8fff-4662-812b-d9acc197bab7)

2024-03-13 10:04 UTC, PeterShaggyNoble commented
Took one more pass at it from scratch. The nested SVGs with differing `viewBox`es don't play nice with Inkscape at all but this version _should_ line up a little better.

2024-05-20 13:26 UTC, PratyushJayachandran approved these changes
I am okay with this rendition as the original source is not the cleanest!

2024-05-21 13:39 UTC, PeterShaggyNoble commented
Is this good to merge, so @PratyushJayachandran & @adamrusted?

2024-05-21 14:19 UTC, merged