Hyperskill - new logo addition
simple-icons/simple-icons pull request #10226
Opened 2024-01-07 22:04 UTC by durgeshgowdac

## Tasks Completed:
### 1. Added New Icon:
- Added the **hyperskill.svg** icon to the **simple-icons/icons** directory.

### 2. Updated JSON Data:
- Updated the JSON data in **_data/simple-icons.json** to include information about the new **hyperskill icon**.

</br>

## Additional Information:

### Icon Details:

* The hyperskill.svg icon represents the [Hyperskill](https://hyperskill.org/) brand.
- The icon follows the standard format and guidelines used in Simple Icons.

### Testing:
- I have tested the icon locally to ensure it displays correctly.

### Visual Inspection:
- Visually inspected the icon to confirm that it aligns with the Simple Icons style and quality.

2024-01-07 22:12 UTC, durgeshgowdac commented
### changed “” to "".
- Encountered a quotation mark mismatch in the JSON file. It might be due to different encoding or formatting issues.

2024-01-07 22:24 UTC, durgeshgowdac commented
Changed lowercase to uppercase in HEX

2024-01-07 22:30 UTC, durgeshgowdac commented
## Pull Request Summary
This pull request adds Hyperskill Logo.

### Changes Made
- Added the hyperskill.svg icon to the simple-icons/icons directory.
- Updated the JSON data in _data/simple-icons.json to include information about the new hyperskill icon.

### Issues while commiting
- There was a quotaion mismatch due to different encoding or formatting issue in JSON file.
- Had used lowercase for HEX.

### Resolved Issues
- Changed the quotaions to match the encodings.
- Changed the lowercase HEX to Uppercase HEX.

2024-01-08 13:02 UTC, PeterShaggyNoble requested changes
Thanks for the contribution, @durgeshgowdac 👍🏻 However, I'm seeing [some significant differences](https://github.com/simple-icons/simple-icons/assets/15157491/54e43bc0-68fd-4053-bf4e-90b08dd9be63) between your version (in red) and the [logo](https://assets-global.website-files.com/6522a1d9333be21b9e0bf97c/652933d887f235a01afae283_Logo-goal.svg) in their website's header. I notice, though, you based your version on a different file. Whereabouts on their site did you find that?

Also, for the colour, I think I'd expect a darker blue based on the website's colour scheme. Which one, I don't know, though. Perhaps `#5d72e9`?

2024-01-08 15:00 UTC, PeterShaggyNoble commented on _data/simple-icons.json
> +            "source": "https://assets-global.website-files.com/646bbfc4c8c88c7c71128456/646f959078117670eb2a9fd8_Hyperskill%20Logo.svg"
```suggestion
            "source": "https://hyperskill.org"
```

2024-01-08 15:01 UTC, PeterShaggyNoble approved these changes
Your new SVG lines up perfectly with the source, @durgeshgowdac, nice work.

Before I merge, though, what do you think of my suggested change to the colour?

2024-01-08 15:32 UTC, durgeshgowdac commented
![image](https://github.com/simple-icons/simple-icons/assets/65192493/89b5c3e9-1bc1-4f0a-8571-656e29286bc7)

Closes Issue https://github.com/simple-icons/simple-icons/issues/10182

Changes:
- Previously uploaded hyperskill.svg had scaling issue. I've resolved it and uploaded the new optimized hyperskill.svg
- I think Cornflower Blue `#6962F2` is a more dominant color. I've updated the Hex in simpleicons.json

2024-01-08 15:40 UTC, durgeshgowdac commented
> @durgeshgowdac, where did you source that new colour from? I'm not seeing it in their website's stylesheet.

I found an extension (site palette) which extracts color palette from the given website. It scanned the whole website and showed `#6962F2` to be the most dominant color.

2024-01-08 15:54 UTC, PeterShaggyNoble commented
The problem is, though, @durgeshgowdac, that that colour doesn't appear in their CSS varaiables 🤔
![](https://github.com/simple-icons/simple-icons/assets/15157491/e9d97acd-c59a-413b-ac96-4fc0a82bad07)

2024-01-08 15:57 UTC, durgeshgowdac commented
@PeterShaggyNoble Alright, I will change it back to #5D72E9

2024-01-08 16:18 UTC, durgeshgowdac commented
@PeterShaggyNoble Can I change it to `#6C63FF`?

2024-01-08 16:46 UTC, PeterShaggyNoble commented
From the variable names above, @durgeshgowdac, it looks to me like that colour is no longer in use.

2024-01-08 16:53 UTC, durgeshgowdac commented
> From the variable names above, @durgeshgowdac, it looks to me like that colour is no longer in use.

@PeterShaggyNoble What about `#8C5AFF`? 

If you have any other color in mind. Let me Know

2024-01-08 16:56 UTC, PeterShaggyNoble commented
👍🏻 That seems as good a choice as any to me; equally as valid as my suggestion.

2024-01-08 17:07 UTC, durgeshgowdac commented
@PeterShaggyNoble I've made all the changes. You can merge now. 

Thank You,
@durgeshgowdac

2024-01-08 17:11 UTC, PeterShaggyNoble approved these changes

2024-01-08 17:15 UTC, merged