Add Take-Two Interactive Icon
simple-icons/simple-icons pull request #10302
Opened 2024-01-17 06:20 UTC by Mvlprem

![taketwointeractive](https://github.com/simple-icons/simple-icons/assets/54018894/13442a53-b6fe-49d6-bd72-65f1a5ad473d)

**Similarweb rank:** [42,249](https://www.similarweb.com/website/take2games.com/#overview)

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

[svg](https://commons.wikimedia.org/wiki/File:Take-Two_Interactive_Logo.svg) used, Hex taken from [website](https://www.take2games.com/) stylesheet.

According to their stylesheet their ` --color-primary ` is ` rgb(20, 128, 99) ` but i don't think it represents their brand color i'm not really sure about this so i'm going with ` --color-black `

2024-01-17 16:35 UTC, PeterShaggyNoble requested changes
There are vector versions of the logo available in the PDFs available at https://www.take2games.com/ir and I'm seeing a slight difference between your version and the one on the first page of [the newest PDF](https://ir.take2games.com/static-files/7d453c73-84f1-4977-bb98-3237e6017d48). Would you mind updating to match, please, and changing the `source` to match?

Also, should we not be using the full name of "Take-Two Interactive Software"?

2024-01-18 03:49 UTC, Mvlprem commented
Updated name and source and redone the svg, but what about hex stick to ` --color-black ` or switch to ` --color-primary `

2024-01-18 11:06 UTC, PeterShaggyNoble approved these changes

2024-01-18 11:06 UTC, PeterShaggyNoble commented on icons/taketwointeractivesoftware.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Take-Two Interactive Software</title><path d="m17.012 16.776.417-.257 4.155-3.1c1.413-1.248 2.293-2.686 2.293-4.607-.006-
Yep, I'd agree with the colour choice, @Mvlprem. The SVG looks good to me now. Although, there is a redundant `m`ove command at the end of the path which we'll need to remove before merging.
```suggestion
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Take-Two Interactive Software</title><path d="m17.012 16.776.417-.257 4.155-3.1c1.413-1.248 2.293-2.686 2.293-4.607-.006-3.849-3.037-5.771-6.614-5.771-1.663 0-3.122.447-4.283 1.256V2.852L0 2.86l.007 4.395 3.85-.008.016 13.886 5.355-.008-.016-13.886h1.443a7.97 7.97 0 0 0-.516 2.02l4.518.884c.076-1.376.547-3.102 2.219-3.102 1.101 0 1.753.832 1.753 1.87 0 1.557-1.305 2.653-2.4 3.592l-6.082 4.56.006 4.085 13.642-.016.205-4.371-6.988.015Z"/></svg>
```

2024-01-18 11:08 UTC, merged