Magic
simple-icons/simple-icons pull request #10307
Opened 2024-01-17 15:12 UTC by durgeshgowdac

**Issue:** closes #10303

**Website:** https://www.magic.link/
**Guidelines:** https://magic.link/brand-assets

**Similarweb rank:** 83,573
**Similarweb link:** https://www.similarweb.com/website/magic.link/#overview

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

2024-01-17 17:13 UTC, durgeshgowdac commented
@PeterShaggyNoble All checks have passed. You can merge now

2024-01-18 11:42 UTC, PeterShaggyNoble requested changes
@durgeshgowdac, which file did you base your icon off? I'm seeing [significant differences](https://github.com/simple-icons/simple-icons/assets/15157491/85b2e18b-191e-4424-bcc7-e93d1c59755c) when comparing it (in red) to `\Magic Logo≡ƒ¬ä\SVG\01-Icon\2-Icon_Magic_Black.svg` from [the zip file](https://magic.link/brand-assets/magic-logos.zip) of logos they make available.

And we should update the `source` to match the `guidelines`.

2024-01-18 11:42 UTC, PeterShaggyNoble commented on _data/simple-icons.json
> +            "source": "https://magic.link",
```suggestion
            "source": "https://magic.link/brand-assets",
```

2024-01-18 13:53 UTC, durgeshgowdac commented
@PeterShaggyNoble I have made the changes, please check.

2024-01-18 14:37 UTC, PeterShaggyNoble approved these changes
Looks spot on now, @durgeshgowdac 👍🏻 Nice work.

2024-01-18 14:41 UTC, merged