Add note about SimilarWeb Login to Icon Request Issue Template
simple-icons/simple-icons pull request #10429
Opened 2024-02-10 12:00 UTC by adamrusted

I'm seeing a lot of Issues opened where people are saying they're unable to access SimilarWeb.
I've therefore added a note to the Issue Template which details how to bypass the sign-in form.

2024-02-10 19:04 UTC, PratyushJayachandran approved these changes

2024-02-10 20:50 UTC, PeterShaggyNoble requested changes
I'd not make any mention of logging in and instead phrase it in such a way as to direct people _straight_ to the site's SW URL. And, if I haven't done so already, it'd probably be good to also include this note in our contributing guidelines.

2024-02-20 10:29 UTC, PeterShaggyNoble approved these changes

2024-02-20 10:29 UTC, PeterShaggyNoble commented on .github/ISSUE_TEMPLATE/icon_request.yml
> +        > Similarweb is now trying to force users to login in order to view statistics. You can bypass this by going directly to:
```suggestion
        > Similarweb is now trying to force users to log in in order to view statistics. You can bypass this by going directly to:
```

2024-02-20 10:29 UTC, PeterShaggyNoble commented on CONTRIBUTING.md
> +> Similarweb is now trying to force users to login in order to view statistics. You can bypass this by going directly to:
```suggestion
> Similarweb is now trying to force users to log in in order to view statistics. You can bypass this by going directly to:
```

2024-02-20 16:57 UTC, merged