Add React-PDF
simple-icons/simple-icons pull request #10472
Opened 2024-02-15 11:17 UTC by nirvikpurkait

![reactpdf](https://github.com/simple-icons/simple-icons/assets/93871471/ddb6c45e-8b48-487f-90b6-4d045db02f8d)

**Issue:** closes #10471

**Similarweb rank:**
543,979

**GitHub star:**
13.9k

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

- png converted to svg with inkscape
- had multiple colors, all are red with slightly variation, so mixed all red colors.

2024-02-15 15:18 UTC, PeterShaggyNoble reviewed
Thanks for the contribution, @nirvikpurkait 👍🏻 However, I think we'll need some outlines around the top layer of shapes in order to maintain the integrity of and illusion of depth from the original. Would you be able to give that a try, please? Unfortunately, I can't find a vector version of the original, either.

2024-02-15 16:35 UTC, nirvikpurkait commented
Hey @PeterShaggyNoble , thanks for response. 

Ummm, I am not getting what are you asking for. Are you asking for something like this?

![Frame 3](https://github.com/simple-icons/simple-icons/assets/93871471/1a1638b9-9737-45fc-985d-7560c930c310)

2024-02-15 16:52 UTC, PeterShaggyNoble commented
If you take that white outline you have around the 3 shapes at the front, increase its width to 0.5dp and then cut it out of the main shape behind them, that should do the trick.

2024-02-16 18:30 UTC, nirvikpurkait commented
Hello @PeterShaggyNoble, I am facing an error. How can I get rid of it?

```shell
  x icon-size Size of <path> must be exactly 24 in one dimensi    
              on; the size is currently 23.999 x 21.571
  x icon-centered <path> must be centered at (12, 12); the cen    
                  ter is currently (12, 11.996)
```

2024-02-17 15:43 UTC, adamrusted commented
It looks like it's having an issue optimising the new path to 3 decimals. How're you optimising it? If you're using `npx svgo` you can add the flag `-p 4` to up the precision to 4 decimals. That might resolve your issue!

2024-02-17 16:25 UTC, nirvikpurkait commented
> It looks like it's having an issue optimising the new path to 3 decimals. How're you optimising it? If you're using `npx svgo` you can add the flag `-p 4` to up the precision to 4 decimals. That might resolve your issue!

@adamrusted thank you for the advise, I was using npx svgo to optimize the svg, but didn't know about the flag, so when ever I optimize the svg it gives error. 

How ever I successfully optimized the svg, and the outcome looks like this (with color for visualization) ,
![Frame](https://github.com/simple-icons/simple-icons/assets/93871471/4b1d8b80-4d30-4ef7-b8c0-8092627e0b81)

Is this the result you wanted @PeterShaggyNoble ? Or is there anything else we can improve?

2024-02-20 11:07 UTC, nirvikpurkait commented
![image](https://github.com/simple-icons/simple-icons/assets/93871471/87fb3a7a-1411-47c7-8b34-ea4a58754ca0)

2024-02-20 11:10 UTC, adamrusted commented
@nirvikpurkait - please don't feel the need to merge develop into this branch, it notifies everyone that has commented every time you do it. We'll merge develop into this when we come to review it.

2024-02-20 11:18 UTC, nirvikpurkait commented
> @nirvikpurkait - please don't feel the need to merge develop into this branch, it notifies everyone that has commented every time you do it. We'll merge develop into this when we come to review it.

Ohh, sorry, my bad. I thought that I always need to keep my branch updated. I won't do it next time.

2024-02-20 11:20 UTC, adamrusted commented
> Ohh, sorry, my bad. I thought that I always need to keep my branch updated.

No worries! It's good practice to keep your 'develop' branch up to date with ours - just so any new PRs you submit don't have any merge issues, but once you've submitted a PR you're fine to leave it unless you're changing somethin 😄

2024-02-23 16:29 UTC, nirvikpurkait commented
Sorry, I accidentally update this branch instead of another branch

2024-02-24 05:16 UTC, nirvikpurkait commented
Hello, @PeterShaggyNoble , @adamrusted if everything is fine, can you add this to the develop branch as this would motivate me to take on other issues too. 

Also I need this logo too, to add somewhere else.

Thank you.

2024-03-14 11:52 UTC, PeterShaggyNoble requested changes
It definitely works much better with the cut-outs, @nirvikpurkait, nice work. There are, however, a few issues which will need to be corrected before we can merge this.

1. Your version doesn't quite line up with the source (see comparison below, with yours in green),
2. The cut-outs should knocked out of the bottom layered shape (i.e., overlaying the shadows of the upper layers) and should be 0.5dp, and,
3. There are quite a few excess points which could be cleaned up.

![](https://github.com/simple-icons/simple-icons/assets/15157491/0f8af3fc-0ca6-4c69-80f4-1343bd42c583)

2024-03-14 11:52 UTC, PeterShaggyNoble commented on _data/simple-icons.json
> +            "source": "https://react-pdf.org/images/logo.png"
Also, just the website itself will do for the `source` URL.
```suggestion
            "source": "https://react-pdf.org"
```

2024-03-16 08:38 UTC, nirvikpurkait commented
![image](https://github.com/simple-icons/simple-icons/assets/93871471/90e3085f-741d-48d2-a284-f1bdb8263bcd)

2024-03-21 14:10 UTC, PeterShaggyNoble requested changes
That lines up nicely now, @nirvikpurkait 👍🏻

However, there are still a number of excess points that could be removed. Would you be able to give that a try, please?

![](https://github.com/simple-icons/simple-icons/assets/15157491/58dc25ad-3af9-48c2-a454-09225108f5d6)

2024-04-14 05:33 UTC, closed without merging