Add openmediavault
simple-icons/simple-icons pull request #10568
Opened 2024-03-04 02:42 UTC by uncenter

![preview](https://github.com/simple-icons/simple-icons/assets/47499684/4c1b5dab-c899-48c5-b505-d1774a8fa6e3)

<details>
	<summary>SVG with `fill="#5DACDF"`:</summary>

![png export](https://github.com/simple-icons/simple-icons/assets/47499684/9f6fd47a-4924-4610-8c38-ed619b3a6b50)

</details>

**Issue:** closes #7186.

**Similarweb rank:** https://www.similarweb.com/website/openmediavault.org/#overview.

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

2024-03-04 09:18 UTC, adamrusted commented
Hey @uncenter - where did you source this icon from? I can only see a PNG on the source page listed...

2024-03-04 11:28 UTC, uncenter commented
> Hey @uncenter - where did you source this icon from? I can only see a PNG on the source page listed...

There's an SVG file right above the png file that I grabbed.

![Screenshot 2024-03-04 at 06 27 27 (Arc)](https://github.com/simple-icons/simple-icons/assets/47499684/6c43836b-11b6-49e2-a9bf-d263adec6976)

https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/workbench/src/favicon.svg

2024-03-05 12:28 UTC, adamrusted requested changes
JSON looks spot on, just a query around the SVG.

2024-03-05 12:28 UTC, adamrusted commented on icons/openmediavault.svg
I'm spotting a [slight difference](https://github.com/simple-icons/simple-icons/assets/1830867/ed83d7a5-cffc-4575-9a8a-040806185ed6) in your PR (black) when compared to source (blue). I'd also argue we shouldn't have the box, and just the inner shape, which is excluded in your PR. The box appears to only be present because it's the favicon - and it's the shape inside there that is the actual icon. See preview below for a rough idea.
![image](https://github.com/simple-icons/simple-icons/assets/1830867/9f92b15b-5c98-4dc7-b138-34f346608a6b)

2024-03-05 14:53 UTC, uncenter commented on icons/openmediavault.svg
Sure. I'd make that change but it seems like you already have an SVG ready with that adjustment?

2024-03-05 14:55 UTC, adamrusted commented on icons/openmediavault.svg
I only generated an SVG for comparison sake - haven't kept it on my end.

2024-03-05 15:04 UTC, uncenter commented on icons/openmediavault.svg
No worries. I restarted from the beginning and I think I'm getting better at Inkscape! Took me only a few minutes. I'll update it in a moment.

2024-03-05 15:05 UTC, uncenter commented on icons/openmediavault.svg
![openmediavault](https://github.com/simple-icons/simple-icons/assets/47499684/5edf7f9e-1ce1-4a15-854b-ebed6105a3b0)

2024-03-15 14:31 UTC, PeterShaggyNoble submitted a review, later dismissed
I'm seeing [some small differences](https://github.com/simple-icons/simple-icons/assets/15157491/d7f4b0c8-02ff-4717-8cd2-7f4a4f94831b) in all 4 outer corners, as a result of Inkscape being crap at converting `stroke`s to `path`s. Could you see if you could tweak those manually to line up better? Or you may find it easier to redraw the shape from scrtach.

2024-03-15 14:31 UTC, PeterShaggyNoble commented on _data/simple-icons.json
> +            "source": "https://www.openmediavault.org"
Also, the source will need to be updated.
```suggestion
            "source": "https://github.com/openmediavault/openmediavault/blob/12f8ef70f19f967733b744d6fb6156a4181f1ddc/deb/openmediavault/workbench/src/favicon.svg"
```

2024-03-19 13:58 UTC, uncenter commented
> I'm seeing [some small differences](https://github.com/simple-icons/simple-icons/assets/15157491/d7f4b0c8-02ff-4717-8cd2-7f4a4f94831b) in all 4 outer corners, as a result of Inkscape being crap at converting `stroke`s to `path`s. Could you see if you could tweak those manually to line up better? Or you may find it easier to redraw the shape from scrtach.

Thanks for pointing that out! I just committed a refined version where the corners match up.

2024-05-18 15:12 UTC, adamrusted approved these changes
LGTM! Thanks @uncenter 🎉

2024-05-18 15:14 UTC, merged