Add: Audiobookshelf
simple-icons/simple-icons pull request #10605
Opened 2024-03-09 15:33 UTC by 21st-centuryman

**Issue:** closes #10604 

**Similarweb rank:**

Currently at 4.9K stars
https://github.com/advplyr/audiobookshelf
We can wait until it reaches 5.

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

![audiobookshelf](https://github.com/simple-icons/simple-icons/assets/60197499/2e70789f-4ae0-46d8-983a-43efc5d14609)

2024-03-09 21:30 UTC, PratyushJayachandran requested changes

2024-03-09 21:30 UTC, PratyushJayachandran commented on icons/audiobookshelf.svg
There is a slight misalignment near the head band of the headphone logo.  Can you please re-check if the vector got distorted while scaling or it could also be a SVGO precision issue.
[See comparison.](https://github.com/simple-icons/simple-icons/assets/35000807/2f0a4972-fb23-4d87-9286-64e526d910a5)

2024-03-09 21:30 UTC, PratyushJayachandran commented on icons/audiobookshelf.svg
![image](https://github.com/simple-icons/simple-icons/assets/35000807/27714bad-48a8-4c5e-9cb4-65f77d4c4d6c)

2024-03-11 08:42 UTC, adamrusted commented
Marking as pending given the GitHub stars metric is not yet meeting our criteria.

2024-04-09 12:44 UTC, 21st-centuryman commented
Hello @PeterShaggyNoble and @adamrusted would we be able to reassess the status of this pr?

they have reached the github stars threshold.

2024-05-18 15:16 UTC, adamrusted requested changes
Still spotting some _slight_ differences - which may just be a precision thing. Would you mind having another look please @21st-centuryman?
![image](https://github.com/simple-icons/simple-icons/assets/1830867/b80c7761-75f6-4861-9b02-101dfff88a18)

2024-05-20 20:16 UTC, adamrusted approved these changes

2024-05-20 20:17 UTC, merged