Update Issue Template
simple-icons/simple-icons pull request #10642
Opened 2024-03-14 08:42 UTC by PratyushJayachandran

I noticed that the issue template can be simplified for getting website rankings from Similarweb.

Simplified the instructions to make it more straightforward.

2024-03-14 08:51 UTC, LitoMore requested changes

2024-03-14 08:51 UTC, LitoMore commented on .github/ISSUE_TEMPLATE/icon_request.yml
> +        > In order to view website rankings on `similarweb.com``:
```suggestion
        > In order to view website rankings on `similarweb.com`:
```

Typo

2024-03-14 09:05 UTC, PratyushJayachandran commented on .github/ISSUE_TEMPLATE/icon_request.yml
> +        > In order to view website rankings on `similarweb.com``:
Oops. Applied.

2024-03-19 10:31 UTC, uncenter commented on .github/ISSUE_TEMPLATE/icon_request.yml
> +        > Or go to `https://similarweb.com/website`, enter the website address and click on Analyze Traffic.
```suggestion
        > Go to `https://similarweb.com/website`, enter the website address, and click on Analyze Traffic.
```

Is the first method necessary to include?

2024-03-21 12:42 UTC, PeterShaggyNoble commented
I think what we currently have is perfectly fine; gets people to the information they're looking for as quickly as possible. If we _are_ going to change it, though, then I agree with @uncenter's comments above.

2024-03-24 19:14 UTC, uncenter approved these changes

2024-05-18 15:04 UTC, adamrusted approved these changes

2024-05-18 15:06 UTC, merged