Add Decentraland
simple-icons/simple-icons pull request #10675
Opened 2024-03-20 15:07 UTC by PeterShaggyNoble

![Decentraland](https://github.com/simple-icons/simple-icons/assets/15157491/0ba16306-0f6e-409b-a634-acb775bfea22)

**Issue:** closes #7141
**Popularity metric:** Similarweb rank [97514](https://www.similarweb.com/website/decentraland.org)

### Checklist
- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description
Colour is from their [website](https://decentraland.org), referred to as `--primary` in the CSS variables.

2024-03-20 18:01 UTC, service-paradis requested changes
Thank you @PeterShaggyNoble, I left a few comments about the terms and conditions!

2024-03-20 18:01 UTC, service-paradis commented on icons/decentraland.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Decentraland</title><path d="M16.8883 18.9778h3.1112L16.8883 15.2ZM8.444 9.5556v6.6222h5.4667ZM12.0439 0C5.4661 0 .0883 5
According to https://decentraland.org/brand:

> Subject to these terms, you are only allowed to use the logo design that is available at the following link https://www.figma.com/file/pBiYuNALsSEFncGy3x6dIZ/DecentralandLogo?node-id=3162%3A117.

Note that the Figma link should be https://www.figma.com/file/L9CZTTRnkvBd4nQK8xiD85/Decentraland-Logo?type=design&node-id=3137-1051&mode=design&t=H8BCuBilLfwHcd5N-0 according to https://github.com/decentraland/catalyst/issues/1726.

To be compliant with their terms, I think we should use the logo in their Figma as source. When comparing your version to the "Filled, Isotype, Small, Light" version, I got some differences.

Also, just to be sure, was the precision of 4 necessary for this one?

2024-03-21 10:38 UTC, PeterShaggyNoble commented
Nice find on the GH issue, @service-paradis 👍🏻  I've used that as the `source` for now. The version I had used as a source was just squashed horizontally but I started from scratch using the same version as you did from the Figma file to be safe. A precision of 4 is, unfortunately, necessary here; I was getting a small shift in the circles at 3.

2024-03-22 11:53 UTC, service-paradis approved these changes
> Nice find on the GH issue, @service-paradis 👍🏻 I've used that as the source for now. The version I had used as a source was just squashed horizontally but I started from scratch using the same version as you did from the Figma file to be safe. A precision of 4 is, unfortunately, necessary here; I was getting a small shift in the circles at 3.

Great! In the next review of the letter D, we could take a look if they updated the link! The icon is now a perfect match!

2024-03-22 11:55 UTC, merged