Add Anki icon
simple-icons/simple-icons pull request #10708
Opened 2024-03-27 00:02 UTC by uncenter

![anki](https://github.com/simple-icons/simple-icons/assets/47499684/eb33733a-f85c-4ed0-8914-0ffc98c2f57a)

**Issue:** closes #8723.

**Popularity metric:** 16.9k stars (https://github.com/ankitects/anki).

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

Hex color from the midpoint of the gradient of the bottom left star. Their website looks outdated so I didn't see any other source for the hex.

2024-03-27 15:12 UTC, uncenter commented
There's also this option:

![anki (1)](https://github.com/simple-icons/simple-icons/assets/47499684/283c80a9-6723-4187-bf89-e6d7a0f24a6c)

I think it looks way better (especially at small sizes) and is more recognizable, but since it isn't "accurate" to the project's *actual* logo would it not be fit for consideration?

2024-05-20 11:23 UTC, adamrusted commented
Think we may be best to get someone from the Anki team (like @dae) to give some feedback on preferred approach here. How would you like the icon handled?

2024-05-24 10:14 UTC, dae commented
The Anki logo is AGPL3, so if this is a derivative work, it will need a compatible license.

2024-05-24 10:19 UTC, adamrusted commented
While this project is CC0 - we can (and do) list license details on a brand-by-brand basis, would that be suitable, @dae?
See our website:
![image](https://github.com/simple-icons/simple-icons/assets/1830867/c44d43a0-f352-4ae6-b687-a5647672a8de)

And in our JSON:
https://github.com/simple-icons/simple-icons/blob/4e4a29e74e2f67ad2e32bcb36ce378d0e55101e5/_data/simple-icons.json#L398-L405

2024-05-28 09:28 UTC, dae commented
If it's clearly marked as AGPL, no objections from me.

2024-05-28 09:29 UTC, adamrusted commented
Fab, thanks @dae - last question, which of @uncenter's treatments of the icon do you prefer?
![image](https://github.com/simple-icons/simple-icons/assets/1830867/f50bd1c9-e2f9-4b51-aa8b-bdd24e2923ff)
![image](https://github.com/simple-icons/simple-icons/assets/1830867/51f5be7e-8120-43ca-a254-c851d842e820)

2024-05-28 09:32 UTC, dae commented
The former is closer to the status quo, but looks a bit much when it's placed in something with its own frame like a button. I think it really depends on the context it's going to be used in.

2024-05-28 09:37 UTC, adamrusted commented
Most common usage (our main dependent) is shields.io - though users often use the package for their own websites, etc. I would think our general max size is <128px tall. @dae

2024-05-28 09:39 UTC, dae commented
Then maybe the latter, but I don't really have a preference.

2024-05-28 10:00 UTC, adamrusted commented
Thanks for the guidance, @dae - I've now merged the license and 'guidelines' (as mentioned on in the LICENSE file). @uncenter - would you be able to merge the latter treatment into this PR an I'll review it?

2024-05-28 10:51 UTC, adamrusted requested changes

2024-05-28 10:51 UTC, adamrusted commented on icons/anki.svg
@uncenter - I can see _some differences_ when comparing, either against the stars with the outline, or without. Could you advise how you created this variant, and I'll do the same on my end.

2024-05-28 11:20 UTC, uncenter commented on icons/anki.svg
> Could you advise how you created this variant, and I'll do the same on my end.

First I clear out all the extra symbols/shapes from the source icon, leaving just the logo with the two stars. I then delete everything in this shape as well, leaving just the stars themselves. I lock the aspect ratio, resize them to 24x24, and center them on the page. Then I convert the strokes to paths, fill in the inner part of the stars (fill tool + union) and finally merge the two stars together.

2024-05-28 11:27 UTC, adamrusted commented on icons/anki.svg
Just copying the stars out of source and resizing to 24px high, I'm still seeing differences:
![image](https://github.com/simple-icons/simple-icons/assets/1830867/b78682c1-06f8-447e-b30c-2178a251c7e9)

2024-05-28 11:38 UTC, uncenter commented on icons/anki.svg
This is so strange! Everything lines up in my editor, and then I save it, reopen it, and it no longer lines up :/

2024-05-28 11:43 UTC, adamrusted commented on icons/anki.svg
I blame @PeterShaggyNoble - he's usually the cause for my SVG woes 🤣

2024-05-28 11:44 UTC, uncenter commented on icons/anki.svg
Now for some reason my duplicate of the original stars that I left in to compare with aren't lining up with... the original stars once I import the original SVG file again. Arghhh what is going on!?

2024-05-28 12:26 UTC, uncenter reviewed
New path looks way better! Thanks @adamrusted - I can't approve but LGTM :)

2024-06-10 12:35 UTC, service-paradis approved these changes
LGTM 🎉

2024-06-10 12:36 UTC, merged