Add UiPath Icon
simple-icons/simple-icons pull request #10773
Opened 2024-04-05 04:11 UTC by Mvlprem

![uipath](https://github.com/simple-icons/simple-icons/assets/54018894/19d2d2d7-dd0e-46c5-ba9e-84789d537c69)

**Issue:** closes #9852

**Popularity metric:** [24,930](https://www.similarweb.com/website/uipath.com/#overview)

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

svg taken from [press resources](https://www.uipath.com/newsroom), hex taken from [guidelines](https://brandguidelines.uipath.com/) page

2024-04-05 04:12 UTC, Mvlprem commented
it's been a while

2024-04-05 13:49 UTC, PeterShaggyNoble requested changes
I think we can safely remove the registered trademark symbol here, as I can't find any explicit requirement in their guidelines that it be included. And, also, they use a regular trademark symbol in places themselves.

2024-04-06 02:24 UTC, Mvlprem commented
@PeterShaggyNoble  There is a README file in their media assets file, which says the logo includes the full UiPath name along with the ® mark.
[README.txt](https://github.com/simple-icons/simple-icons/files/14892039/README.txt)

2024-05-20 20:03 UTC, adamrusted approved these changes

2024-05-20 20:04 UTC, merged