Add: tinygrad
simple-icons/simple-icons pull request #10796
Opened 2024-04-09 12:43 UTC by 21st-centuryman

**Issue:** closes #10795

**Popularity metric:**
> 23k ✨

https://github.com/tinygrad/tinygrad

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

![tinygrad](https://github.com/simple-icons/simple-icons/assets/60197499/5b1e605a-4abb-4539-9f79-a32cefbff75e)

2024-04-16 14:36 UTC, service-paradis requested changes
The icon is looking great, thank you @21st-centuryman 🎉 

I left minor comments about the name. Once solved, I will merge this one!

2024-04-16 14:36 UTC, service-paradis commented on _data/simple-icons.json
> +            "title": "Tinygrad",
```suggestion
            "title": "tinygrad",
```
They always refer themselves as `tinygrad` with a lowercase `t`.

2024-04-16 14:36 UTC, service-paradis commented on icons/tinygrad.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Tinygrad</title><path d="M1.846 7.385V9.23H0v1.846h1.846v3.692h3.692v-1.846H3.692v-1.846h1.846V9.23H3.692V7.385zm5.539 0V
```suggestion
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>tinygrad</title><path d="M1.846 7.385V9.23H0v1.846h1.846v3.692h3.692v-1.846H3.692v-1.846h1.846V9.23H3.692V7.385zm5.539 0V9.23H9.23V7.385zm3.692 1.846v5.538h1.846v-3.692h1.846V9.23h-1.846zm3.692 1.846v3.692h1.846v-3.692zm3.693-1.846v3.692h3.692v1.846H24V9.231h-1.846v1.846h-1.846V9.23Zm3.692 5.538h-3.692v1.846h3.692zm-14.77-3.692v3.692h1.847v-3.692z"/></svg>
```

Same here about the title casing.

2024-04-16 19:47 UTC, 21st-centuryman commented
@service-paradis 
the changes have been submitted.

2024-04-22 12:29 UTC, service-paradis approved these changes

2024-04-22 12:32 UTC, merged