Add Blinq icon
simple-icons/simple-icons pull request #10816
Opened 2024-04-15 23:34 UTC by uncenter

![blinq](https://github.com/simple-icons/simple-icons/assets/47499684/bfc6999b-2192-48b2-8afa-4058daec4a35)

**Issue:** closes #10763.

**Popularity metric:** Ranked 72,813 globally on Similarweb. See https://www.similarweb.com/website/blinq.me/.

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

I linked to the Drive folder here which I'm not sure if goes against our guidelines on sources (https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#source-guidelines). The press kit is linked in the footer of the website but it links straight to the Drive folder and there is no intermediate page.

2024-04-16 14:57 UTC, service-paradis requested changes
I left a few comments, but I'm not even sure we can this one according to https://blinq.me/legal/website-terms-of-use

> Subject to the above, your use of, and access to, the Site and the Content does not grant or transfer to you any rights, title or interest to Our Intellectual Property. Unless otherwise permitted in these Terms, you must not:
> copy or use, in whole or in part, any of Our Intellectual Property;

2024-04-16 15:14 UTC, uncenter commented on icons/blinq.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Blinq</title><path d="M12 20.2667c2.2091 0 4-1.7908 4-4h-.8c0 1.7673-1.4327 3.2-3.2 3.2s-3.2-1.4327-3.2-3.2v2.4004c.7298.
Sounds good. I've updated the icon.

2024-04-16 15:14 UTC, uncenter commented
New preview:
![image](https://github.com/simple-icons/simple-icons/assets/47499684/415145f9-78c5-4740-9322-da58ae3822a0)

2024-04-22 13:25 UTC, adamrusted commented
I'd say the guidelines posted in https://github.com/simple-icons/simple-icons/pull/10816#pullrequestreview-2003892041 give us a pretty clear-cut answer. Sorry @uncenter!

2024-04-22 13:28 UTC, uncenter commented
> I'd say the guidelines posted in [#10816 (review)](https://github.com/simple-icons/simple-icons/pull/10816#pullrequestreview-2003892041) give us a pretty clear-cut answer. Sorry @uncenter!

No worries!

2024-04-22 13:28 UTC, closed without merging