Add FreshRSS icon
simple-icons/simple-icons pull request #10860
Opened 2024-04-26 13:24 UTC by 10xLaCroixDrinker

![FreshRSS simpleicons preview](https://github.com/simple-icons/simple-icons/assets/517295/ede42535-a60a-44c5-af14-3bd9a2aae36f)

**Issue:** closes #10698

**Popularity metric:** [8.4K stars](https://github.com/FreshRSS/FreshRSS)

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

2024-04-26 13:32 UTC, uncenter commented
I wonder if there is a way we can show the differences in shading of the original icon in a monochrome form. Maybe the lighter blue sections are outlined instead of solid?

2024-04-27 23:39 UTC, 10xLaCroixDrinker commented
> Maybe the lighter blue sections are outlined instead of solid?

Done. Updated prview in description

2024-04-28 00:10 UTC, uncenter requested changes
![Screenshot 2024-04-27 at 20 10 22 (Inkscape)](https://github.com/simple-icons/simple-icons/assets/47499684/04608016-5c1c-4034-8409-98fe73291dbe)

I'm seeing differences with the circle in the center.

2024-04-28 00:25 UTC, 10xLaCroixDrinker commented
> I'm seeing differences with the circle in the center.

Should be all good now 👍🏻

2024-04-28 01:32 UTC, uncenter requested changes
![Screenshot 2024-04-27 at 21 31 17 (Inkscape)](https://github.com/simple-icons/simple-icons/assets/47499684/af7b5f9c-6920-4597-8fba-5bf4f6e3ab3a)

Still seeing differences with the blue circle on my end.

2024-04-28 01:50 UTC, 10xLaCroixDrinker commented
> Still seeing differences with the blue circle on my end.

Okay _now_ it should be all set

2024-04-28 01:54 UTC, uncenter requested changes
![Screenshot 2024-04-27 at 21 53 50 (Inkscape)](https://github.com/simple-icons/simple-icons/assets/47499684/c5d5397f-838b-4f3a-a116-f6c5195cbf55)

Shoot, still seeing differences! The differences around the center circle are small enough to not matter but the differences around the outer rings needs to be fixed.

2024-04-28 01:55 UTC, uncenter commented
This may be an issue with the precision when you are optimizing it FYI. You can try a precision of 3 or 4 to see if that helps.

2024-04-28 03:15 UTC, 10xLaCroixDrinker commented
@uncenter I redid the whole thing and I used a precision of 3 when optimizing.

2024-05-18 18:41 UTC, uncenter submitted a review, later dismissed

2024-05-20 20:11 UTC, adamrusted commented on icons/freshrss.svg
Unfortunately I'm seeing some extra paths on this one, that can be removed in your Vector software by 'adding' the paths using the pathfinder tool.
![image](https://github.com/simple-icons/simple-icons/assets/1830867/d523f7f5-77bb-406b-bdd6-4f0d18248d14)

Would you mind having another look, @10xLaCroixDrinker?

2024-06-11 14:54 UTC, adamrusted commented on icons/freshrss.svg
Are you still working on this @10xLaCroixDrinker?

2024-07-03 08:27 UTC, closed without merging