Use `import.meta.dirname` & `import.meta.filename`
simple-icons/simple-icons pull request #10863
Opened 2024-04-26 21:00 UTC by LitoMore

This API requires Node.js 20.11 or later. See https://nodejs.org/api/esm.html#importmetadirname.

In the meantime, we can consider publishing the SDK with a new package, for example `@simple-icons/sdk`.

2024-04-26 21:55 UTC, mondeja commented
> In the meantime, we can consider publishing the SDK with a new package, for example @simple-icons/sdk.

But this would still be a breaking change, right? It would be nice to do it at v12.

2024-04-27 05:07 UTC, LitoMore commented
>.But this would still be a breaking change, right?

Yes. It's just a draft PR.

2024-04-27 11:14 UTC, mondeja commented
> > .But this would still be a breaking change, right?
> 
> Yes. It's just a draft PR.

I refer to publishing the SDK with a new package.

2024-05-02 23:42 UTC, mondeja approved these changes

2024-05-20 22:43 UTC, mondeja requested changes

2024-05-20 22:43 UTC, mondeja commented on sdk.mjs
> +  readmePath = path.join(import.meta.dirname, 'README.md'),
This change needs to be applied to the new function `getThirdPartyLibraries` too.

2024-05-24 09:08 UTC, adamrusted commented
@LitoMore - is this likely to be ready for v12, or should we push it out to v13?

2025-05-20 09:35 UTC, adamrusted commented
@LitoMore - reminder that this is still outstanding. Are you likely to get this completed for v15?

2025-05-23 00:56 UTC, mondeja commented on sdk.mjs
> +export const urlRegex = async () =>
I think that this function `urlRegex` can be moved to *scripts/add-icon-data.js*, which is the unique script that is using it. Could you do that on this PR and run again `node scripts/release/update-sdk-ts-defs.js`?

2025-05-23 00:56 UTC, mondeja commented on .xo-config.json
> +			"nodeVersion": "^20.11 || >=22",
Just letting a comment here for further reviews...

The version `20.11` added `import.meta.dirname` and `import.meta.filename` (see https://nodejs.org/es/blog/release/v20.11.0).

2025-05-23 11:00 UTC, LitoMore commented on .xo-config.json
> +			"nodeVersion": "^20.11 || >=22",
I'm unable to add a comment since it's a JSON file. But we can add the comment after the #13015.

2025-05-23 11:06 UTC, LitoMore commented on sdk.mjs
> +export const urlRegex = async () =>
Done!

2025-05-27 11:22 UTC, merged