Add n8n icon
simple-icons/simple-icons pull request #10909
Opened 2024-05-06 15:30 UTC by CodeShakingSheep

![image](https://github.com/simple-icons/simple-icons/assets/19874562/2e69e131-7264-454b-86b0-7715a9d4eb93)

**Issue:** closes https://github.com/simple-icons/simple-icons/issues/7993

**Popularity metric:**

The Similarwebrank is 60,987. See https://www.similarweb.com/fr/website/n8n.io

### Checklist

- [ ] I updated the JSON data in `_data/simple-icons.json`
- [ ] I optimized the icon with SVGO or SVGOMG
- [ ] The SVG `viewbox` is `0 0 24 24`

### Description

I forgot where I downloaded the original svg icon (had it on my computer for quite a while). I just combined the paths and applied the transformations to them. Then optimized it.

2024-05-06 20:09 UTC, uncenter requested changes

2024-05-06 20:09 UTC, uncenter commented on icons/n8n.svg
<img width="613" alt="image" src="https://github.com/simple-icons/simple-icons/assets/47499684/36cd6e4a-b710-4c4f-baf1-9fa80dbad551">

I'm seeing a bunch of differences as illustrated by the screenshot above. Are you using the logo from their website's header? Also I'd like to note that you said " I just combined the paths and applied the transformations to them." - there are no paths to combine for this logo!

2024-05-06 20:11 UTC, uncenter commented on icons/n8n.svg
They also have a press kit from which you can source the icon: https://n8n.io/press/. `n8n-symbol-only.svg` would be the file to grab.

2024-05-06 21:23 UTC, CodeShakingSheep commented on icons/n8n.svg
Hm, right. As I wrote I had this other n8n icon svg on my computer for a while (and don't know anymore from where I downloaded it). With the official svg icon you linked, I have a problem with removing `fill-rule="evenodd" clip-rule="evenodd"`, see screenshot. The problem is that 2 of the small circles get filled. I don't know how to solve that. Do you have any idea?

![image](https://github.com/simple-icons/simple-icons/assets/19874562/1d9a7a69-8c7d-40d7-87db-e90d7d0375f7)

2024-05-06 21:33 UTC, uncenter commented on icons/n8n.svg
Hmm I'm not sure. @PeterShaggyNoble I recall you helped me before with an icon that had `fill-rule="evenodd"`, how can we get rid of it here?

2024-05-18 18:40 UTC, adamrusted commented on _data/simple-icons.json
> +            "source": "https://n8n.io"
```suggestion
            "source": "https://n8n.io/press"
```

2024-05-18 18:40 UTC, adamrusted commented on icons/n8n.svg
I don't know the exact science with this - but I've always been able to 'split' the path in my editor, move the circle shapes up/down (changes per program) and then re-do the merging.

2024-05-19 18:56 UTC, CodeShakingSheep commented on icons/n8n.svg
Ok, I managed to solve this by breaking apart the path (in Inkscape), then creating 4 little circles in the size of the 4 small paths and then took the difference between the big path and the 4 little circles respectively. Is it good now?

2024-05-19 19:09 UTC, uncenter approved these changes

2024-05-20 19:40 UTC, adamrusted approved these changes

2024-05-20 19:40 UTC, merged