Add Wiz Icon
simple-icons/simple-icons pull request #10915
Opened 2024-05-08 04:57 UTC by MinnThikeTunn

![wiz (3)](https://github.com/simple-icons/simple-icons/assets/166204149/c47b772c-c212-4ddf-999b-d929cc4a1093)

**Issue:** closes #10612 

**Popularity metric:**  [~141.3k](https://www.similarweb.com/website/wiz.io/#overview)

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
-  [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

I found two variants according to issues. I didn't know anything about handling two variants and didn't see anything about how I deal with logo variants in contributing guidelines. So, according to the issue creator, I choose the recognized one. I am sorry if I made some mistakes.

//Edited
Since it is my first time, I am sorry that I caused any trouble.

2024-05-08 13:30 UTC, uncenter commented on _data/simple-icons.json
> +            "source": "https://www.wiz.io"
```suggestion
            "source": "https://www.wiz.io/newsroom#media-kit"
```

2024-05-08 13:35 UTC, uncenter requested changes

2024-05-08 13:35 UTC, uncenter commented on icons/wiz.svg
This isn't matching up with any of the logos from the [press kit](https://www.wiz.io/newsroom#media-kit), nor is it matching the one from the header (which is different then the press kit ones for some reason).

2024-05-09 09:48 UTC, MinnThikeTunn commented on icons/wiz.svg
Yeah,I will replace this with an appropriate press kit.

2024-06-10 18:14 UTC, adamrusted commented on icons/wiz.svg
Hey @MinnThikeTunn - are you still working on this?

2024-12-09 14:39 UTC, adamrusted commented
Closing this PR, given it's not had updates from the original creator  for some time. Will un-link from the issue so we can work on the issue fresh, should another contributor want to.

2024-12-09 14:39 UTC, closed without merging