Add React Bootstrap icon
simple-icons/simple-icons pull request #10921
Opened 2024-05-09 01:51 UTC by CodeShakingSheep

![image](https://github.com/simple-icons/simple-icons/assets/19874562/3bd5ef1a-338e-4157-b0db-797eb23d8b97)

**Issue:** closes https://github.com/simple-icons/simple-icons/issues/8334

**Popularity metric:**

> The website's Similarweb global rank in any one category is either:
In the top 50, or,
In the top 5k, with a global rank of 1m or better.

The Similarweb category rank in "Computers Electronics and Technology > Computers Electronics and Technology - Other (in Argentina)" is 2,085 and the global rank is 729,168, see https://www.similarweb.com/website/react-bootstrap.github.io .

22.2k stars on GitHub, see https://github.com/react-bootstrap/react-bootstrap .

### Checklist

- [ ] I updated the JSON data in `_data/simple-icons.json`
- [ ] I optimized the icon with SVGO or SVGOMG
- [ ] The SVG `viewbox` is `0 0 24 24`

### Description

Just resized and unified paths.

2024-05-18 19:02 UTC, adamrusted requested changes
Thanks for your work on this @CodeShakingSheep! Just a couple points below.

2024-05-18 19:02 UTC, adamrusted commented on _data/simple-icons.json
> +            "source": "https://react-bootstrap.github.io"
```suggestion
            "source": "https://github.com/react-bootstrap/react-bootstrap/blob/be23c304fa40ddb209919b0faac1e5dd8cef53ad/www/static/img/logo.svg"
```

2024-05-18 19:02 UTC, adamrusted commented on icons/reactbootstrap.svg
I'm seeing a slight difference when comparing the PR (black) to the source (blue).
![image](https://github.com/simple-icons/simple-icons/assets/1830867/3c5ac104-ce72-4acc-acf5-b956b7689eb8)

There are also extra paths inside the main shape that can be removed doing a 'add' action in your vector editor.
![image](https://github.com/simple-icons/simple-icons/assets/1830867/ca5b4fe0-53d2-4f61-b025-cc19110bfb33)

2024-05-21 00:08 UTC, CodeShakingSheep commented on icons/reactbootstrap.svg
Thanks for the hints. Now I used the Union tool in Inkscape instead of "Combine" to combine the paths. I also increased the precision to 4. Hope it's good now.

2024-05-22 07:05 UTC, adamrusted approved these changes

2024-05-22 07:06 UTC, merged