New icon: TypeORM
simple-icons/simple-icons pull request #10939
Opened 2024-05-12 22:13 UTC by davesagraf

**Issue:** closes #

**Popularity metric:**

### Checklist

- [ ] I updated the JSON data in `_data/simple-icons.json`
- [ ] I optimized the icon with SVGO or SVGOMG
- [ ] The SVG `viewbox` is `0 0 24 24`

### Description

2024-05-13 00:43 UTC, uncenter requested changes

2024-05-13 00:43 UTC, uncenter commented on _data/simple-icons.json
> +            "source": "https://raw.githubusercontent.com/typeorm/typeorm/master/resources/logo_big.png",
```suggestion
            "source": "https://github.com/typeorm/typeorm/blob/e7649d2746f907ff36b1efb600402dedd5f5a499/resources/logo_big.png",
```

2024-05-18 19:06 UTC, adamrusted approved these changes
I'm happy with this treatment, though I'll need another reviewer on it given it's a manual vector job. Thanks for your work @davesagraf! 🎉

2024-06-10 18:15 UTC, adamrusted commented
Not heard from other maintainers - so I'll merge this in. Thanks again @davesagraf!

2024-06-10 18:16 UTC, merged

2024-06-10 18:23 UTC, davesagraf commented
Hi @adamrusted !

Okay, got you, thanks a lot!