Add yabai icon
simple-icons/simple-icons pull request #10997
Opened 2024-05-22 09:24 UTC by anhthang

![Yabai icon](https://github.com/simple-icons/simple-icons/assets/10458061/1a0267b9-538b-480b-937f-299e6f38473f)

**Issue:** closes #10968 

**Popularity metric:**

22k ⭐ on GitHub

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

Hex value is from original svg here: https://github.com/koekeishiya/yabai/blob/86c759186d7c588dfd8c6a84aac1ebc4730e988e/assets/icon/icon.svg

2024-05-23 13:10 UTC, uncenter requested changes

2024-05-23 13:10 UTC, uncenter commented on icons/yabai.svg
![Screenshot 2024-05-23 at 09 09 44 (Inkscape)](https://github.com/simple-icons/simple-icons/assets/47499684/e1b91786-52cc-4581-aba8-10c861543df9)

Seeing some slight differences here when comparing to the original linked in the `source`. You might need to up the precision here to `4` or higher.

2024-05-23 16:37 UTC, anhthang commented on icons/yabai.svg
Hi @uncenter, there is some small issues with the original svg, so I just re-drawn to fix it. Is it ok to go, or I need to make it same as the original one?

2024-05-23 16:45 UTC, uncenter commented on icons/yabai.svg
What issues did you encounter? We'd prefer if you use the source SVG to start unless the last resort is redrawing.

2024-05-23 17:12 UTC, anhthang commented on icons/yabai.svg
> What issues did you encounter? We'd prefer if you use the source SVG to start unless the last resort is redrawing.

The green & `y` path has a very small space and the combination of green, yellow, red paths is not a perfect square.
I think it's why we see some slight differences when comparing

2024-05-23 17:24 UTC, uncenter commented on icons/yabai.svg
The combination doesn't need to be a perfect square. The larger dimension should be `24` and the aspect ratio should be preserved (at least two sides touching).

2024-05-24 11:11 UTC, uncenter commented on icons/yabai.svg
Is it exactly 24x24 in your editor? Try increasing the precision when optimizing maybe.

2024-05-24 11:33 UTC, anhthang commented on _data/simple-icons.json
> +            "hex": "00364B",
that's color for yabai/y text from banner/icon

2024-05-24 11:35 UTC, uncenter commented on _data/simple-icons.json
> +            "hex": "00364B",
Ah right. That works for me then.

2024-05-24 11:35 UTC, uncenter approved these changes

2024-05-27 01:36 UTC, anhthang commented
@uncenter Are there any additional changes needed for this pull request to be merged?

2024-05-27 05:49 UTC, uncenter commented
> @uncenter Are there any additional changes needed for this pull request to be merged?

Nope, just waiting on another reviewer.

2024-05-28 13:02 UTC, uncenter commented
No need to update this branch, it just pings us and we'll have to update it again before merging anyway.

2024-06-10 18:22 UTC, adamrusted commented on icons/yabai.svg
I see what you mean with having to redraw bits of this @anhthang - the joins not quite lining up is bothering me too. Perhaps worth reaching out to them to tidy up the icon, or adjusting that yourself?
![image](https://github.com/simple-icons/simple-icons/assets/1830867/f15907c1-abf5-4d24-b62f-d2cbd2a8dac9)

2024-06-11 06:45 UTC, anhthang commented on icons/yabai.svg
@adamrusted i have redrawn the green path a bit to fix the issue. hope its ok now. can you check again?

2024-06-11 14:57 UTC, adamrusted requested changes
Weirdly, whatever you did added _more_ differences!
![image](https://github.com/simple-icons/simple-icons/assets/1830867/5c7c6adb-331f-483b-aa34-95fa9be71bf1)

See the lines between the `y` shape and the diamond. Ideally they should be removed so it's just one solid path.

2024-06-11 16:25 UTC, anhthang commented
@adamrusted I slightly modified the green path to make it easier to combine it seamlessly with the Y shape. There shouldn't be any significant changes compared to the previous version. Could you please review it again to see if the issue is resolved?

2024-06-11 17:13 UTC, adamrusted commented on icons/yabai.svg
I'm now seeing a slight difference in the 'tail' of the 'y' - see below.
Would you be able to see what might be causing that? Potentially just a precision thing.
![image](https://github.com/simple-icons/simple-icons/assets/1830867/b12470e1-ae88-4ffc-aeb0-5af5da5d24b3)

2024-06-12 07:29 UTC, anhthang commented on icons/yabai.svg
fixed, it looks great from my end now. hope this is final 😅

2024-06-12 17:27 UTC, adamrusted approved these changes
YES! We've gotten there! Thanks for your patience @anhthang!

2024-06-12 17:29 UTC, merged