Added BambuLab icon metadata
simple-icons/simple-icons pull request #11009
Opened 2024-05-23 09:51 UTC by RaghavMaliwal

This pull request introduces the SVG icon for the brand "Bambu Lab" and updates the metadata accordingly in the _data/simple-icons.json file.

Changes Made:

    **1. SVG Icon Addition:**
Added the SVG icon file for the "Bambu Lab" brand, ensuring it meets the required guidelines for format, size, and design.

      **2. Metadata Update:**
Updated the metadata in the _data/simple-icons.json file to include details for the "Bambu Lab" icon. This includes the title, hex color, source URL, and any additional attributes such as slugs, guidelines, or licenses.

Request for Feedback:
I kindly request a review of the changes made in this pull request. If there are any issues or suggestions for improvement, please don't hesitate to provide feedback. Your input is greatly appreciated and will help ensure the accuracy and quality of the icon collection.

Thank you for your attention to this matter.

2024-05-23 10:01 UTC, uncenter commented
Please use the provided pull request template in the future!

2024-05-23 10:02 UTC, uncenter requested changes
You need to follow our contributing guidelines when adding an icon: https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon. The `source` you have provided is not official, and the icon itself is not optimized at all.

2024-05-23 10:20 UTC, RaghavMaliwal commented
Hello.. @uncenter I have changed the svg file and i think it should work fine now...And the source of the svg I have attached is the one provided in the issues section that's why I pasted it as it is....now where should I find its official source...?

2024-05-23 10:23 UTC, uncenter commented
> Hello.. @uncenter I have changed the svg file and i think it should work fine now

See the linter for why your current SVG is invalid. You also again need to read through the full contributing guidelines as there are quite a few steps you have missed.

> And the source of the svg I have attached is the one provided in the issues section that's why I pasted it as it is....now where should I find its official source...?

https://github.com/simple-icons/simple-icons/issues/10985#issuecomment-2124014386

2024-05-23 12:25 UTC, uncenter requested changes

2024-05-23 12:45 UTC, uncenter requested changes

2024-05-23 12:45 UTC, uncenter commented on _data/simple-icons.json
> +
```suggestion
        {
            "title": "Bambu Lab",
            "hex": "00ae42",
            "source": "https://github.com/bambulab/BambuStudio/blob/master/resources/images/BambuStudio.svg" 
        },
```

2024-05-26 12:19 UTC, adamrusted commented on _data/simple-icons.json
> +            "source": "https://github.com/bambulab/BambuStudio/blob/master/resources/images/BambuStudio.svg"
There is also an SVG available on the homepage of the website. I'd suggest we use that as a source.
```suggestion
            "source": "https://bambulab.com" 
```

2024-06-07 18:19 UTC, adamrusted reviewed
Looks like the icon isn't centered - and the hex is lowercase.
I'll merge these changes, if another maintainer can review?

2024-06-07 18:19 UTC, adamrusted commented on _data/simple-icons.json
> +            "hex": "00ae42",
```suggestion
            "hex": "00AE42",
```

2024-06-07 18:19 UTC, adamrusted commented on icons/bambulab.svg
> +<svg xmlns="http://www.w3.org/2000/svg" role="img" viewBox="0 0 24 24"><title>Bambu Lab</title><path d="M.099.216v14.77l11.045-3.306V.216Zm12.758 0v7.387l11.044 3.31V.216Zm0 8.798v14.77h11.044v-11.46
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" role="img" viewBox="0 0 24 24"><title>Bambu Lab</title><path d="M12.662 24V8.959l8.535 3.369V24zm-9.859-.003v-7.521l8.534-3.371-.001 10.892zM2.803 0h8.533l.001 11.672-8.534 3.369zm9.859 0h8.535v10.892l-8.535-3.371z"/></svg>
```

2024-06-07 19:38 UTC, uncenter approved these changes
Icon is a perfect match!

2024-06-07 19:49 UTC, merged

2024-06-08 07:50 UTC, RaghavMaliwal commented
Hi @adamrusted @uncenter ,

Thank you for merging the PR and for correcting the flaws I had missed. I appreciate your guidance and the improvements made.

Additionally, I have another PR (#11013) in which I have received permission from Maze(https://github.com/simple-icons/simple-icons/pull/11013#issuecomment-2144621025. I would be grateful if you could review it at your earliest convenience.

Thanks again for your support!

Best regards,
@RaghavMaliwal