Add Maze-icon
simple-icons/simple-icons pull request #11013
Opened 2024-05-23 17:59 UTC by RaghavMaliwal

![image](https://github.com/simple-icons/simple-icons/assets/141847608/52ad51c9-5a8c-4791-a6de-ed47280df6a7)

**Issue:** closes #10925

**Popularity metric:**

The similar web rank is 69,606. See: https://www.similarweb.com/website/maze.co/#overview

### Checklist

- [ ] I updated the JSON data in `_data/simple-icons.json`
- [ ] I optimized the icon with SVGO or SVGOMG
- [ ] The SVG `viewbox` is `0 0 24 24`

### Description

2024-05-24 07:42 UTC, adamrusted commented
See their [terms of service](https://maze.co/tos/#intellectual-property-rights), stating that they do not give permission for their logo to be used.  Could you please reach out to them to clarify the use-case @RaghavMaliwal? You can find info about requesting permission [in our guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-permission).
![image](https://github.com/simple-icons/simple-icons/assets/1830867/d9713822-d3c0-48b4-81ea-8a321a847957)

2024-05-24 08:18 UTC, RaghavMaliwal commented
@adamrusted Can you please tell whom to mail to ask for the permission...!

2024-05-24 08:21 UTC, RaghavMaliwal commented
Okay...

2024-05-24 08:32 UTC, RaghavMaliwal commented
@adamrusted I have submitted a request on their Contact Us page. Let's wait for their response
![Screenshot 2024-05-24 135835](https://github.com/simple-icons/simple-icons/assets/141847608/ff66c06b-4e21-44fa-8239-75444c4b729d)

2024-06-03 08:40 UTC, RaghavMaliwal commented
Hello @adamrusted, Received a positive response from their side...
![image](https://github.com/simple-icons/simple-icons/assets/141847608/d67dc120-25ef-49f9-a85a-57f2c95f65b8)

2024-06-08 15:15 UTC, uncenter requested changes

2024-09-08 02:41 UTC, uncenter requested changes

2024-09-08 02:41 UTC, uncenter commented on _data/simple-icons.json
> +            "source": "https://maze.co"
Press kit linked in the footer.
```suggestion
            "source": "https://mazedesign.notion.site/Press-Kit-421d405e76154662a547ce9ef2a3f018"
```

2024-09-08 02:41 UTC, uncenter commented on icons/maze.svg
Still seeing these hairline differences on the top and bottom. Make sure you use the SVG from the press kit source - your icon is a bit taller than my normalized version of the original for whatever reason, so maybe try recreating from scratch.

2024-09-08 02:44 UTC, uncenter commented on icons/maze.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Maze</title><path d="M16.07776 5.99642c-.9839 0-1.96769.37216-2.71839 1.11668L5.2038 15.20191c-.7507.74452-1.96809.74415-
```suggestion
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Maze</title><path d="M1.126 16.547c-1.5013-1.4881-1.5013-3.9009 0-5.389l4.0778-4.042c1.2692-1.258 3.205-1.4525 4.6803-.5836.4564.2687.4524.8852.077 1.2573-.3753.372-.988.34-1.4975.1923-.6524-.1891-1.386-.0287-1.9006.4813l-4.0777 4.0419a1.8935 1.8935 0 0 0 0 2.6945c.7506.744 1.9678.744 2.7184 0l8.1555-8.0836c1.5014-1.4882 3.9355-1.4882 5.437 0l4.0778 4.0418c1.5013 1.4881 1.5013 3.901 0 5.389-1.5014 1.4882-3.9356 1.4882-5.437 0l-1.3593-1.3472-1.699 1.684c-1.2692 1.258-3.205 1.4526-4.6804.5837-.4563-.2687-.4523-.8852-.077-1.2573.3754-.372.988-.34 1.4975-.1923.6524.1892 1.386.0287 1.9006-.4813l1.7476-1.7322c.724-.7175 1.8975-.7175 2.6214 0l1.4078 1.3954c.7507.744 1.9678.744 2.7186 0a1.8936 1.8936 0 0 0 0-2.6945l-4.0779-4.0419c-.7507-.744-1.9678-.744-2.7185 0L6.563 16.5471c-1.5014 1.4882-3.9356 1.4881-5.437 0"/></svg>
```

2024-11-30 12:59 UTC, mondeja commented on icons/maze.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Maze</title><path d="M16.07776 5.99642c-.9839 0-1.96769.37216-2.71839 1.11668L5.2038 15.20191c-.7507.74452-1.96809.74415-
Yeap, this solves the problem.

2024-11-30 13:00 UTC, mondeja approved these changes
Thanks both for the great work!

2024-11-30 13:01 UTC, merged