Add: lazyvim
simple-icons/simple-icons pull request #11028
Opened 2024-05-26 19:49 UTC by 21st-centuryman

**Issue:** closes #11027

**Popularity metric:**

> 13.7k ✨ [on github](https://github.com/LazyVim/LazyVim)

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

![lazyvim](https://github.com/simple-icons/simple-icons/assets/60197499/67d04417-9a94-4831-b2cc-9b931fcf4a55)

2024-05-26 20:29 UTC, uncenter requested changes

2024-05-26 20:29 UTC, uncenter commented on _data/simple-icons.json
> +            "source": "https://raw.githubusercontent.com/LazyVim/lazyvim.github.io/db7f1bd035de3f41a75a29f65f36819f6ac152af/static/img/icon.svg"
Please don't use a raw file contents link.

2024-05-26 20:37 UTC, 21st-centuryman commented on _data/simple-icons.json
> +            "source": "https://raw.githubusercontent.com/LazyVim/lazyvim.github.io/db7f1bd035de3f41a75a29f65f36819f6ac152af/static/img/icon.svg"
Fixed with latest commit

2024-05-28 07:51 UTC, adamrusted approved these changes
LGTM! Thanks @21st-centuryman!

2024-05-28 07:52 UTC, merged