Add Cryptomator icon
simple-icons/simple-icons pull request #11031
Opened 2024-05-27 05:05 UTC by CodeShakingSheep

![image](https://github.com/simple-icons/simple-icons/assets/19874562/06aeb32c-0211-408c-8183-f90aa2bbc4ef)

**Issue:** closes https://github.com/simple-icons/simple-icons/issues/10928

**Popularity metric:**

The Similarweb rank is 314,707. See https://www.similarweb.com/website/cryptomator.org

Also, Cryptomator has ~10.7k stars on GitHub, see https://github.com/cryptomator/cryptomator

### Checklist

- [ ] I updated the JSON data in `_data/simple-icons.json`
- [ ] I optimized the icon with SVGO or SVGOMG
- [ ] The SVG `viewbox` is `0 0 24 24`

### Description

Well, this one was a bit tricky. I decided to use the body outline to make it look as similar as possible to the original. There's a slight asymmetry between the left and right wheel (the right wheel has a hole between the body outline and the wheel while the left wheel doesn't have it). This was already present with the original logo. Let me know if my interpretation of the logo is ok. I'm open to suggestions / adoptions.

2024-05-28 08:00 UTC, adamrusted requested changes

2024-05-28 08:00 UTC, adamrusted commented on icons/cryptomator.svg
They have a good monochrome treatment in the [app icon](https://cryptomator.org/presskit/cryptomator-android-icon.png) available at source. Might be worth using that version as a base, minus the 'app icon' shape.
Also, have you manually vectorised this? If so - we'll need to tag it as such and get others in to review.

2024-05-28 16:25 UTC, CodeShakingSheep commented on icons/cryptomator.svg
Thanks for the feedback. The issue is that the Android App icon is only available as png. That means that I would have to manually vectorize it which I want to avoid as there is an svg of the regular logo available which I used as base for this PR. Also, the Android icon is slightly different in terms of margins and I would prefer to go with the regular icon. However, I could do some other variations from the regular icon (e.g. with the body filled). What do you think about that?

2024-06-11 15:02 UTC, adamrusted commented on icons/cryptomator.svg
I've been able to replicate the Android icon - see attached.
```svg
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg width="100%" height="100%" viewBox="0 0 24 24" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xml:space="preserve" xmlns:serif="http://www.serif.com/" style="fill-rule:evenodd;clip-rule:evenodd;stroke-linejoin:round;stroke-miterlimit:2;">
    <path d="M9.44,19.313C9.441,19.471 9.435,19.627 9.423,19.776C9.37,20.41 9.206,20.906 8.986,21.103L7.909,22.052C7.819,22.134 7.725,22.177 7.629,22.182L5.387,22.182C4.593,22.182 3.936,21.319 3.752,20.034C3.653,19.345 3.703,18.623 3.892,17.999C4.096,17.327 4.445,16.838 4.874,16.618C5.032,16.536 5.208,16.493 5.387,16.492L6.254,16.492C5.696,15.61 5.331,14.548 5.333,13.282C5.334,12.539 5.455,11.956 5.566,11.575C5.662,11.254 5.668,10.912 5.581,10.588C5.265,9.436 5.479,8.166 5.479,8.166C9.49,6.927 11.977,8.175 11.977,8.175C11.977,8.175 14.469,6.935 18.477,8.186C18.477,8.186 18.687,9.456 18.368,10.607C18.28,10.931 18.284,11.273 18.38,11.595C18.49,11.976 18.609,12.559 18.609,13.302C18.607,14.56 18.244,15.615 17.689,16.492L18.426,16.492C18.604,16.493 18.78,16.536 18.939,16.618C19.368,16.838 19.717,17.327 19.92,17.999C20.11,18.623 20.16,19.345 20.061,20.034C19.876,21.319 19.219,22.182 18.425,22.182L16.183,22.182C16.088,22.177 15.994,22.134 15.903,22.052L14.827,21.103C14.607,20.906 14.443,20.41 14.39,19.776C14.379,19.648 14.373,19.515 14.373,19.38C13.064,20.07 11.961,20.345 11.961,20.345C11.961,20.345 10.794,20.051 9.44,19.313ZM7.089,17.554C6.896,18.157 6.806,19.078 6.881,19.98C6.99,21.294 7.407,22.069 7.809,21.715L8.884,20.766C9.035,20.632 9.161,20.249 9.204,19.724C9.219,19.544 9.223,19.363 9.218,19.188C8.498,18.776 7.742,18.238 7.089,17.554ZM14.593,19.261C14.591,19.413 14.596,19.568 14.609,19.723C14.652,20.248 14.778,20.631 14.929,20.765L16.004,21.714C16.407,22.069 16.822,21.293 16.931,19.979C17.002,19.127 16.926,18.259 16.755,17.656C16.085,18.332 15.316,18.859 14.593,19.261ZM13.215,12.188L13.215,12.185C13.215,11.502 12.653,10.94 11.97,10.94C11.287,10.94 10.725,11.502 10.725,12.185C10.725,12.764 11.13,13.271 11.695,13.399L10.996,16.333L11.963,16.611L12.932,16.336L12.242,13.4C12.808,13.273 13.213,12.767 13.215,12.188ZM5.199,11.793C5.078,11.822 4.951,11.837 4.82,11.837C4.78,11.837 4.739,11.836 4.7,11.833L4.308,12.598C4.469,12.898 4.486,13.269 4.319,13.594L3.872,14.469C3.737,14.734 3.506,14.918 3.243,15.001C3.459,15.297 3.586,15.66 3.586,16.051C3.586,16.959 2.897,17.731 1.994,17.833C1.978,17.834 1.96,17.835 1.944,17.835C1.706,17.835 1.51,17.64 1.51,17.402C1.51,17.182 1.677,16.996 1.896,16.972C2.363,16.919 2.72,16.52 2.72,16.05C2.72,15.542 2.301,15.123 1.793,15.123C1.284,15.123 0.866,15.542 0.866,16.05C0.866,16.207 0.905,16.362 0.981,16.499C1.012,16.56 1.028,16.627 1.028,16.694C1.028,16.932 0.832,17.128 0.595,17.128C0.443,17.128 0.301,17.048 0.223,16.917C0.077,16.652 -0,16.354 -0,16.051C-0,15.068 0.808,14.259 1.79,14.258C1.704,13.996 1.718,13.701 1.854,13.436L2.301,12.562C2.463,12.244 2.763,12.043 3.09,11.992L3.509,11.173C3.312,10.903 3.195,10.571 3.195,10.212C3.195,9.314 3.923,8.586 4.82,8.586C4.926,8.586 5.029,8.596 5.129,8.615C5.093,9.115 5.086,9.915 5.292,10.667C5.363,10.936 5.359,11.221 5.279,11.489L5.278,11.491C5.252,11.581 5.225,11.682 5.199,11.793ZM6.293,7.634C6.432,4.707 8.438,1.818 11.97,1.818C15.257,1.818 17.497,4.716 17.646,7.647C14.56,6.918 12.503,7.628 11.977,7.847C11.451,7.626 9.391,6.908 6.293,7.634ZM10.466,6.538C10.328,6.538 10.216,6.65 10.216,6.787C10.216,6.925 10.328,7.037 10.466,7.037C10.603,7.037 10.715,6.925 10.715,6.787C10.715,6.65 10.603,6.538 10.466,6.538ZM11.446,6.538C11.309,6.538 11.197,6.65 11.197,6.787C11.197,6.925 11.309,7.037 11.446,7.037C11.584,7.037 11.696,6.925 11.696,6.787C11.696,6.65 11.584,6.538 11.446,6.538ZM13.913,4.657C13.192,4.657 12.599,5.25 12.599,5.97L15.226,5.97C15.226,5.25 14.633,4.657 13.913,4.657ZM12.427,6.538C12.289,6.538 12.178,6.65 12.178,6.787C12.178,6.925 12.289,7.037 12.427,7.037C12.565,7.037 12.677,6.925 12.677,6.787C12.677,6.65 12.565,6.538 12.427,6.538ZM9.853,4.657C9.132,4.657 8.539,5.25 8.539,5.97L11.166,5.97C11.166,5.25 10.573,4.657 9.853,4.657ZM13.408,6.538C13.27,6.538 13.159,6.65 13.159,6.787C13.159,6.925 13.27,7.037 13.408,7.037C13.546,7.037 13.658,6.925 13.658,6.787C13.658,6.65 13.546,6.538 13.408,6.538ZM18.825,8.625C18.939,8.599 19.058,8.586 19.179,8.586C20.076,8.586 20.805,9.314 20.805,10.212C20.805,10.571 20.687,10.904 20.489,11.174L20.906,11.989C21.234,12.04 21.534,12.242 21.696,12.559L22.143,13.434C22.279,13.699 22.293,13.995 22.206,14.257C23.19,14.257 24,15.067 24,16.051C24,16.354 23.923,16.652 23.777,16.917C23.703,17.063 23.553,17.155 23.39,17.155C23.152,17.155 22.957,16.96 22.957,16.722C22.957,16.643 22.978,16.566 23.019,16.499C23.094,16.362 23.134,16.207 23.134,16.05C23.134,15.542 22.716,15.123 22.207,15.123C21.699,15.123 21.28,15.542 21.28,16.05C21.28,16.52 21.637,16.919 22.104,16.972C22.322,16.996 22.49,17.182 22.49,17.402C22.49,17.64 22.293,17.835 22.056,17.835C22.039,17.835 22.022,17.834 22.006,17.833C21.103,17.731 20.413,16.959 20.413,16.051C20.413,15.659 20.541,15.296 20.757,15C20.493,14.917 20.261,14.732 20.125,14.466L19.677,13.592C19.511,13.266 19.527,12.895 19.689,12.596L19.299,11.833C19.259,11.836 19.219,11.837 19.179,11.837C19.026,11.837 18.878,11.816 18.737,11.776C18.715,11.68 18.691,11.591 18.668,11.511L18.667,11.509C18.588,11.241 18.584,10.955 18.657,10.685C18.867,9.929 18.86,9.123 18.825,8.625Z"  />
</svg>
```

You're welcome to use that (obviously it needs optimising) but we would then need another maintainer to review the PR.

2024-06-11 16:30 UTC, CodeShakingSheep commented on icons/cryptomator.svg
Oh nice. Did you manually vectorize it? Just curious how you did it. I just optimized and updated the svg with your path. Thanks :pray:

2024-06-11 17:08 UTC, adamrusted commented on icons/cryptomator.svg
I took the SVG available on their website, and then replicated the look of the Android icon by joining / intersecting the paths. Hopefully it's a close enough match (think I ended up with 0.2pt for the gap around the arms/face)

2024-09-27 21:49 UTC, uncenter reviewed
Everything looks great! The icon matches up well with the logo assets available. However, I was just taking a look around their GitHub repository and found https://github.com/cryptomator/docs/blob/main/source/img/logo-mono-white.svg - a monochrome version of the logo (and wordmark)! Should we give that a try?

2024-09-27 21:58 UTC, uncenter reviewed
Gave it a go with that source I mentioned!

2024-09-27 21:58 UTC, uncenter commented on icons/cryptomator.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Cryptomator</title><path d="M9.44 19.313c.001.158-.005.314-.017.463-.053.634-.217 1.13-.437 1.327l-1.077.949c-.09.082-.18
```suggestion
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Cryptomator</title><path d="M11.98 7.64c.41-.165 1.463-.51 3.016-.51.86 0 1.745.105 2.643.314-.212-2.883-2.434-5.69-5.668-5.69-3.476 0-5.473 2.799-5.668 5.677.894-.206 1.775-.31 2.63-.31 1.57 0 2.631.351 3.046.518m1.516-1.186a.25.25 0 1 1 .25-.25.25.25 0 0 1-.249.25zM14 4.073a1.313 1.313 0 0 1 1.313 1.314h-2.626a1.313 1.313 0 0 1 1.314-1.314zm-1.486 1.88a.25.25 0 1 1-.249.25.25.25 0 0 1 .25-.25Zm-1.961.5a.25.25 0 1 1 .25-.25.25.25 0 0 1-.25.25m.98-.5a.25.25 0 1 1-.249.25.25.25 0 0 1 .25-.25Zm-1.592-1.88a1.313 1.313 0 0 1 1.314 1.314H8.627a1.313 1.313 0 0 1 1.314-1.314M23.804 15.17a1.8 1.8 0 0 0-1.595-.976 1.07 1.07 0 0 0-.064-.821l-.448-.875a1.07 1.07 0 0 0-.79-.57l-.416-.817a1.625 1.625 0 0 0-1.531-2.573c.037.507.045 1.333-.174 2.121a1.4 1.4 0 0 0 .011.752q.043.146.087.336a1.6 1.6 0 0 0 .415.022l.392.766a1.07 1.07 0 0 0-.011.996l.447.874a1.07 1.07 0 0 0 .628.533 1.793 1.793 0 0 0 1.252 2.83l.05.003a.433.433 0 0 0 .047-.863.927.927 0 1 1 .915-.473.433.433 0 1 0 .758.418 1.8 1.8 0 0 0 .028-1.683m-19.93-.765.447-.874a1.07 1.07 0 0 0-.01-.997l.39-.765a1.6 1.6 0 0 0 .356-.013 6 6 0 0 1 .093-.367 1.4 1.4 0 0 0 .014-.751c-.215-.781-.206-1.6-.168-2.107a1.626 1.626 0 0 0-1.485 2.58l-.418.817a1.07 1.07 0 0 0-.79.57l-.447.875a1.07 1.07 0 0 0-.012.95 1.793 1.793 0 0 0-1.62 2.66.433.433 0 0 0 .758-.418.927.927 0 1 1 .914.473.433.433 0 0 0 .048.863l.05-.002a1.794 1.794 0 0 0 1.17-2.94 1.07 1.07 0 0 0 .71-.554m15.121 2.278a1.1 1.1 0 0 0-.513-.127h-.877a5.9 5.9 0 0 0 1.003-3.318 6 6 0 0 0-.227-1.707 1.8 1.8 0 0 1-.012-.988c.319-1.15.11-2.421.11-2.421-4.01-1.251-6.502-.01-6.502-.01s-2.486-1.249-6.497-.01c0 0-.214 1.27.102 2.422a1.8 1.8 0 0 1-.015.987c-.111.38-.232.964-.233 1.707a5.9 5.9 0 0 0 1.005 3.338h-.895a1.1 1.1 0 0 0-.513.127c-.429.22-.778.709-.981 1.38a4.8 4.8 0 0 0-.14 2.035c.183 1.285.84 2.148 1.635 2.148h2.241v-.002a.46.46 0 0 0 .28-.127l1.077-.95c.22-.197.384-.693.437-1.327a5 5 0 0 0 .016-.562c1.33.716 2.464 1.002 2.464 1.002s1.137-.282 2.471-.997a5 5 0 0 0 .016.557c.053.634.217 1.13.437 1.327l1.077.949a.46.46 0 0 0 .28.127v.001h2.241c.794 0 1.452-.863 1.636-2.148a4.8 4.8 0 0 0-.14-2.035c-.203-.67-.553-1.159-.983-1.378m-10.24 4.162c-.011.005-.562.495-.875.772a.242.242 0 0 1-.376-.07c-.455-.892-.504-2.705-.182-3.823.546.526 1.15.958 1.736 1.307.033.66-.094 1.692-.303 1.814m4.177-4.573-.968.275-.967-.278.699-2.934a1.245 1.245 0 1 1 .548 0zm3.496 5.274a.242.242 0 0 1-.376.071c-.313-.277-.864-.767-.875-.772-.208-.122-.336-1.15-.303-1.81a9.6 9.6 0 0 0 1.738-1.303c.32 1.118.27 2.926-.184 3.814"/></svg>
```

2024-09-27 21:58 UTC, uncenter commented on _data/simple-icons.json
> +            "source": "https://cryptomator.org/presskit"
```suggestion
            "source": "https://github.com/cryptomator/docs/blob/795a5a414b7e848cbfd4502a4ff63cfdb3adfb15/source/img/logo-mono-white.svg"
```

2024-12-09 14:44 UTC, adamrusted approved these changes
Still well within scope, and with those changes you suggested, a perfect match. Thanks @CodeShakingSheep for starting this, and @uncenter for finishing it off!

2024-12-14 16:17 UTC, LitoMore approved these changes

2024-12-14 16:19 UTC, merged