Add Organic Maps icon
simple-icons/simple-icons pull request #11057
Opened 2024-05-28 15:58 UTC by CodeShakingSheep

![image](https://github.com/simple-icons/simple-icons/assets/19874562/d285a091-5092-4bea-9d28-5ca4e84f4981)

**Issue:** closes https://github.com/simple-icons/simple-icons/issues/6094

**Popularity metric:**

Organic Maps now has ~8.7k stars on GitHub which puts it into scope. See https://github.com/organicmaps/organicmaps

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

Just resized and optimized it.

2024-06-07 20:08 UTC, adamrusted requested changes
Couple of issues on this one - would you mind having a look please @CodeShakingSheep?

2024-06-08 03:06 UTC, CodeShakingSheep commented
> Couple of issues on this one - would you mind having a look please @CodeShakingSheep?

Ah yes, just updated the source. Any other issues @adamrusted ?

2024-06-10 18:29 UTC, adamrusted commented on icons/organicmaps.svg
Sorry, yes @CodeShakingSheep - there's a difference between your PR (black) and the source icon (red) below. Looks like it's just been broken in optimization - might be worth another try?
![image](https://github.com/simple-icons/simple-icons/assets/1830867/d376e917-a027-4d68-9fa6-79291551e67c)

2024-06-10 18:48 UTC, CodeShakingSheep commented on icons/organicmaps.svg
Strange, I don't know how the difference was created. The source svg only has 1 path. So, the only things I did was removing the <g> element and resizing it. 

Anyway, I just edited the source svg from scratch in Inkscape but when using an optimization precision of 4, I end up with the exact same path. So, I increased the precision to 5 although not sure if that solves the difference. Is it better now?

2024-06-11 15:06 UTC, adamrusted requested changes
Still seeing exactly the same difference when using [this image](https://organicmaps.app/logos/green-on-transparent.svg) from the site header as source. Could you try re-generating please @CodeShakingSheep? 🙏
![image](https://github.com/simple-icons/simple-icons/assets/1830867/1eeccaeb-a8ac-4643-9a38-0517c1b8cdce)

2024-06-11 16:23 UTC, CodeShakingSheep commented
> Still seeing exactly the same difference when using [this image](https://organicmaps.app/logos/green-on-transparent.svg) from the site header as source. Could you try re-generating please @CodeShakingSheep? 🙏

Thanks for reviewing @adamrusted . I used exactly that image from the website's header. I think there's something odd with the your downloaded svg from this PR. You wrote that black is my PR, right? However, when I zoom into my svg in Inkscape the edge is sharp (not rounded as in your screenshot). See here:
![image](https://github.com/simple-icons/simple-icons/assets/19874562/943a37e2-3a43-469b-851a-54a5d04680f5)

Also, when you zoom into the svg on GitHub you can see that it's sharp and not rounded. So, I assume that somehow the svg from this PR was altered while you downloaded it? It's really weird.

2024-06-29 06:16 UTC, adamrusted approved these changes
You were right @CodeShakingSheep - viewing the source file in another software fixed the issue, and it's a perfect match! Thanks for you patience on this one!

2024-06-29 06:18 UTC, merged