Add Honeybadger icon
simple-icons/simple-icons pull request #11066
Opened 2024-05-29 17:14 UTC by anhthang

![image](https://github.com/simple-icons/simple-icons/assets/10458061/8d7b15bf-4d1c-4a76-be72-6331d2da1b70)

**Issue:** closes #10824 

**Popularity metric:**
Global Rank: 361,335
https://www.similarweb.com/website/honeybadger.io/#overview

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

Resources are from assets page

2024-06-07 20:18 UTC, adamrusted requested changes

2024-06-07 20:18 UTC, adamrusted commented on _data/simple-icons.json
> +            "guidelines": "https://www.honeybadger.io/assets"
```suggestion
            "source": "https://www.honeybadger.io/assets",
            "guidelines": "https://www.honeybadger.io/assets"
```

Might as well use the SVGs available on the `assets` page too :)

2024-06-07 20:18 UTC, adamrusted commented on _data/simple-icons.json
> +            "hex": "EA5A37",
```suggestion
            "hex": "EA5937",
```

Suggestion is the hex code given on the Assets page.

2024-06-07 20:19 UTC, adamrusted commented on icons/honeybadger.svg
Seeing quite a few differences when comparing your PR (black) with [this source file](https://honeybadger-static.s3.amazonaws.com/brand_assets/honeybadger_bolt/honeybadger_bolt.svg) (red)
![image](https://github.com/simple-icons/simple-icons/assets/1830867/6f3ba0b0-8028-4d86-bc96-867dbc6aee6f)

2024-06-07 23:35 UTC, anhthang commented on icons/honeybadger.svg
Thanks for your address, I think I forgot to use the logo from assets page. The icon in login page is different. PR updated just now

2024-06-11 00:13 UTC, anhthang commented on icons/honeybadger.svg
oh, this one seems new to me. do you know how to fix it? i'm using Inscape

2024-06-11 15:07 UTC, adamrusted commented on icons/honeybadger.svg
So if you go into your path editing tool, mine is the smaller white 'select' tool in Affinity, you can just select those individual points and hit 'delete' on your keyboard to remove them. Thankfully, because it's a straight line, it shouldn't cause us issues in this instance.

![image](https://github.com/simple-icons/simple-icons/assets/1830867/f6c1f23a-a47d-4e68-bd95-ec1f78be859a)

2024-06-12 07:55 UTC, anhthang commented on icons/honeybadger.svg
![Honeybadger icon](https://github.com/simple-icons/simple-icons/assets/10458061/2ab6eac3-b9a7-4aed-9f41-4af0ba983c8a)

Can you see if this one is ok? I tried to remove that point but the file size is increased

2024-10-01 15:00 UTC, uncenter requested changes

2024-10-01 15:00 UTC, uncenter commented on icons/honeybadger.svg
I got the same result. Removed some points and file size was increased unless I used precision of 3, where it was still only a few characters shorter and at the cost of some (small) differences with the original. I think we can go with how it is now @adamrusted?

2024-10-01 15:04 UTC, anhthang commented on _data/simple-icons.json
> +            "guidelines": "https://www.honeybadger.io/assets"
@uncenter should i remove the guidelines url?

2024-10-01 15:07 UTC, uncenter commented on _data/simple-icons.json
> +            "guidelines": "https://www.honeybadger.io/assets"
Yes go ahead, thank you.

2024-10-01 15:18 UTC, uncenter approved these changes

2024-11-30 16:08 UTC, mondeja approved these changes

2024-11-30 16:10 UTC, merged