Add Wagmi icon
simple-icons/simple-icons pull request #11065
Opened 2024-05-29 16:04 UTC by anhthang

![Wagmi icon](https://github.com/simple-icons/simple-icons/assets/10458061/660f76c7-eade-441a-85f6-7edf9d26aa55)

**Issue:** closes #10817  

**Popularity metric:**
Rank 425,059
5.7k ⭐ on Github

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

SVG extracted from the webstie

2024-06-07 20:15 UTC, adamrusted requested changes
There is a more icon-appropriate source in [this file](https://wagmi.sh/favicon.svg) which we should base our logo on. Don't need to update the source, as it's in the source code of the homepage!

2024-06-10 18:32 UTC, adamrusted commented on icons/wagmi.svg
Seeing a _slight_ difference between PR (black) and source (white) - probably down to precision when optimizing. Could you try with an additional point of precision, @anhthang?
![image](https://github.com/simple-icons/simple-icons/assets/1830867/eaa8a065-a8cf-43d6-bfca-010e34152078)

2024-06-11 09:57 UTC, anhthang commented on icons/wagmi.svg
Increased the precision, looks good from end, please review again

2024-06-11 14:34 UTC, adamrusted approved these changes
Perfect, thanks @anhthang! 🎉

2024-06-11 14:35 UTC, merged