Add the "LinkStack" Icon
simple-icons/simple-icons pull request #11146
Opened 2024-06-08 18:42 UTC by MuhammadZariyanAsif123

**Issue:** closes #

**Popularity metric:**

### Checklist

- [ ] I updated the JSON data in `_data/simple-icons.json`
- [ ] I optimized the icon with SVGO or SVGOMG
- [ ] The SVG `viewbox` is `0 0 24 24`

### Description

2024-06-08 18:44 UTC, MuhammadZariyanAsif123 commented
The "LinkStack" information has been added in _data/simple-icons.json.

2024-06-08 19:06 UTC, uncenter commented
Please read our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) about how to add an icon. You need to properly optimize and simplify the icon.

2024-06-08 19:07 UTC, uncenter requested changes

2024-06-08 19:07 UTC, uncenter commented on _data/simple-icons.json
There are extra formatting changes here, Please remove the unnecessary newlines.

2024-06-08 19:07 UTC, uncenter commented on icons/linkstack.svg
See earlier comment.

2024-06-08 19:12 UTC, MuhammadZariyanAsif123 commented on icons/linkstack.svg
Actually, there is some misunderstanding, these are not extra spaces.
The first screen is displaying the old code and the other one shows the updated code.

2024-06-08 19:37 UTC, uncenter requested changes

2024-06-08 19:37 UTC, uncenter commented on icons/linkstack.svg
What? You need to simplify this SVG, combine the paths, remove any fill/stroke colors, and optimize it.

2024-06-08 19:37 UTC, uncenter commented on _data/simple-icons.json
You have not removed the extra formatting. There is are extra newlines on line 8556 and line 8562.

2024-06-08 19:37 UTC, uncenter commented on _data/simple-icons.json
> +
```suggestion
        {
            "title": "LinkStack",
            "hex": "B6A272",
            "source": "https://linkstack.org"
        },
```

2024-10-10 20:47 UTC, uncenter commented
Closing as stale, and the brand/project is not within our popularity metrics - see original issue.

2024-10-10 20:47 UTC, closed without merging