Add ZeroTier icon
simple-icons/simple-icons pull request #11165
Opened 2024-06-09 16:27 UTC by anhthang

![image](https://github.com/simple-icons/simple-icons/assets/10458061/6146aafe-bc7a-48b4-878c-233f9bdc6b51)

**Issue:** closes #10877 

**Popularity metric:**

Global Rank: 30,460

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

SVG and hex value `#FFB441` extracted from the website header

2024-06-24 00:18 UTC, PratyushJayachandran requested changes

2024-06-24 00:18 UTC, PratyushJayachandran commented on icons/zerotier.svg
There is a small imperfection on right top corner:
[image](https://github.com/simple-icons/simple-icons/assets/35000807/8444f584-c0ca-4770-8286-3aac9579ba4a)
Rest of it matches well. Can you fix it @anhthang?

2024-06-24 03:41 UTC, anhthang commented on icons/zerotier.svg
I have fixed. Please review again

2024-07-23 05:24 UTC, PratyushJayachandran approved these changes
Matches perfectly! Thank you for your contribution @anhthang 🎉

2024-07-23 05:24 UTC, merged