Add Invidious icon
simple-icons/simple-icons pull request #11225
Opened 2024-06-15 14:55 UTC by CodeShakingSheep

![image](https://github.com/simple-icons/simple-icons/assets/19874562/6c29528c-b397-4470-b64d-8d07a8ebf4ca)

**Issue:** closes https://github.com/simple-icons/simple-icons/issues/11224

**Popularity metric:**

It has ~15.3k GitHub stars. See https://github.com/iv-org/invidious

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

2024-12-09 15:51 UTC, adamrusted commented on icons/invidious.svg
I would argue that we don't need the square outline on this - they use the circle-only variant as the favicon for the site.

2024-12-16 15:52 UTC, CodeShakingSheep commented on icons/invidious.svg
Alright, removed the square outline.

2024-12-17 11:35 UTC, adamrusted requested changes
It looks as though the path has been converted from curves to straight lines in the dot above the `A` shape...
![image](https://github.com/user-attachments/assets/e47f06ae-d712-413c-8268-bddb7291351f)

And the outer circle doesn't line up with the path at source:
![image](https://github.com/user-attachments/assets/51fac05f-d175-4ed1-8bbe-db47c370ed65)

Source in red, PR in black.

2025-05-20 09:42 UTC, adamrusted requested changes

2025-05-20 09:42 UTC, adamrusted commented on _data/simple-icons.json
> +					"hex": "E2007A"
Please undo these changes.

2025-05-20 09:42 UTC, adamrusted commented on _data/simple-icons.json
> +					"hex": "E20134"
Please undo these changes.

2025-05-20 09:42 UTC, adamrusted commented on _data/simple-icons.json
> +					"hex": "A90042"
Please undo these changes.

2025-05-22 10:48 UTC, adamrusted requested changes
I'm still seeing some _slight_ differences in the circle (yours in black, source in red) - would you mind taking another look please @CodeShakingSheep?
![image](https://github.com/user-attachments/assets/312a2999-2a1d-42d2-99f6-3ce450b47b37)

Might just be a precision thing.

2025-06-07 16:36 UTC, adamrusted approved these changes
LGTM, thanks @CodeShakingSheep and @PeterShaggyNoble!

2025-06-07 16:37 UTC, merged