Add Nano Stores Icon
simple-icons/simple-icons pull request #11234
Opened 2024-06-16 05:08 UTC by jrhaberland

![nanostores](https://github.com/simple-icons/simple-icons/assets/53405383/d7657610-820f-4dd1-ad86-e126b7a49941)

**Issue:** closes #11223

**Popularity metric:**
Almost 5k stars & Main Repository: https://github.com/nanostores/nanostores
56890 Weekly Downloads & Active: https://www.npmjs.com/package/nanostores

### Checklist

- [ ] I updated the JSON data in `_data/simple-icons.json`
- [ ] I optimized the icon with SVGO or SVGOMG
- [ ] The SVG `viewbox` is `0 0 24 24`

### Description
Color: `#000000`

2024-06-17 07:20 UTC, wontory commented
Thx!

2024-09-08 14:26 UTC, uncenter requested changes

2024-09-08 14:26 UTC, uncenter commented on icons/nanostores.svg
Seeing some misalignment. Try recreating from the original again maybe?
![CleanShot 2024-09-08 at 10 25 42](https://github.com/user-attachments/assets/d31cf663-714e-43a2-8efe-ed7bf3f97603)

2024-09-13 16:27 UTC, jrhaberland commented on icons/nanostores.svg
Yeah I'll give that a shot, not sure what happened. Might need to use more precision, but I'll play around with it to see what gives the best result.

2024-09-13 16:41 UTC, jrhaberland commented on icons/nanostores.svg
I think I accidentally used wrong precision last time. It should be better now

2024-09-14 02:02 UTC, uncenter approved these changes
Just waiting on a confirmation from another review that this is within our popularity metrics.

2024-09-14 03:37 UTC, wontory commented
> 8. Where applicable, the primary repository for the brand's GitHub project meets the following requirements (see note below):
>     - A minimum of 5k GitHub stars will be required for consideration, providing,
>     - The repository is still active, and,
>     - Its [star history](https://star-history.com/) is on a consistently upward trajectory.

I'm glad this icon was added to simple icons.
This library is a state management tool recommended by [Astro framework](https://docs.astro.build/en/recipes/sharing-state/).
The repository is 5.2k star, which has been well managed until recently.

[![Star History Chart](https://api.star-history.com/svg?repos=nanostores/nanostores&type=Date)](https://star-history.com/#nanostores/nanostores&Date)

2024-09-14 03:39 UTC, uncenter commented
Thanks, but the repository is barely within our criteria for GitHubs stars (just 200 over) and below our npm downloads metric. I'll need someone else from our team to check this out first.

2024-09-14 05:54 UTC, LitoMore approved these changes
LGTM.

2024-09-14 05:55 UTC, merged