Add Beekeeper Studio Icon
simple-icons/simple-icons pull request #11276
Opened 2024-06-19 03:40 UTC by jrhaberland

![beekeeperstudio](https://github.com/simple-icons/simple-icons/assets/53405383/c816c794-f1cf-49db-8831-2a6271354b40)

**Issue:** closes #8061

**Popularity metric:**
Beekeeper Studio has 15.6K GitHub stars
https://github.com/beekeeper-studio/beekeeper-studio

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

2024-06-19 19:11 UTC, uncenter requested changes

2024-06-19 19:11 UTC, uncenter commented on _data/simple-icons.json
> +            "source": "https://www.beekeeperstudio.io",
We should use their [press kit](https://www.beekeeperstudio.io/press/) as source here.

2024-06-19 19:11 UTC, uncenter commented on _data/simple-icons.json
Looks like their [trademark guidelines](https://www.beekeeperstudio.io/legal/trademark/) do allow us to display it this way (I would like a second read through though of those guidelines if you could @adamrusted), however we should link the page under `guidelines`.

2024-06-19 21:58 UTC, jrhaberland commented
Need to fix the color codes again I updated it to what it was on the brand guidlines page, then realized the colors don't line up with the hex codes ☹️ 
![image](https://github.com/simple-icons/simple-icons/assets/53405383/3237e058-8615-4e5c-b5d0-cce16c46dae9)

2024-06-19 22:07 UTC, uncenter commented
> Need to fix the color codes again I updated it to what it was on the brand guidlines page, then realized the colors don't line up with the hex codes ☹️ ![image](https://private-user-images.githubusercontent.com/53405383/341212462-3237e058-8615-4e5c-b5d0-cce16c46dae9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4MzUxMjMsIm5iZiI6MTcxODgzNDgyMywicGF0aCI6Ii81MzQwNTM4My8zNDEyMTI0NjItMzIzN2UwNTgtODYxNS00ZTVjLWI1ZDAtY2NlMTZjNDZkYWU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDIyMDcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2Yzc0NWJjN2U5YWE0OWZjMGJlYTI3Yzg3ZDJlZDk1OWZjMGJlZjJjM2Y4YjViYzZjZjc4Y2UyODg4ODU2YTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ORpLy9fB2ODQ8oISFj6RSLSqRK4Q3mCb7jnO5k83Qlw)

Ahah yeah I noticed that earlier and opened https://github.com/beekeeper-studio/beekeeper-studio/issues/2268!

2024-06-20 06:50 UTC, adamrusted commented on _data/simple-icons.json
Yep, happy with the reading on those guidelines - but would suggest we add a `guidelines` entry - as @uncenter says above.

2024-06-20 16:13 UTC, jrhaberland commented on _data/simple-icons.json
I added a guidelines entry, so should be all good to go

2024-06-20 17:25 UTC, uncenter requested changes
SVG looks good, just this one little change!

2024-06-20 17:33 UTC, uncenter approved these changes

2024-06-20 17:35 UTC, merged