Update: Ram #11306
simple-icons/simple-icons pull request #11309
Opened 2024-06-22 15:02 UTC by ahmadnadeem6236

fixes: #11306

-[x] Remove unnecessary text under the RAM icon

<img width="593" alt="Screenshot 2024-06-22 at 8 29 27 PM" src="https://github.com/simple-icons/simple-icons/assets/87973871/0e85a462-fa18-4b21-835b-e883c332e835">

2024-06-22 15:05 UTC, uncenter commented
Please do not ignore our pull request template.

2024-06-22 15:06 UTC, uncenter requested changes

2024-06-22 15:06 UTC, uncenter commented on icons/ram.svg
If you had followed the pull request template you'll have been asked to check a box stating whether you had optimized the icon. It is clear you have not, nor have you followed [that step in our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#3-optimize-the-icon).

2024-06-22 15:12 UTC, ahmadnadeem6236 commented on icons/ram.svg
Okay I will use the optimize tool to optimize the svg

2024-06-22 15:24 UTC, ahmadnadeem6236 commented
Please go through the change. I followed the pull request template

2024-06-22 15:49 UTC, uncenter commented on icons/ram.svg
The icon must be all on one line, not prettified/formatted like you have it here.

2024-06-22 17:07 UTC, ahmadnadeem6236 commented on icons/ram.svg
Done it

2024-06-22 17:10 UTC, uncenter commented
Please see the linter errors. You can run the linter locally with `npm run lint` (make sure to run `npm install` first).

2024-06-23 11:55 UTC, adamrusted commented
See https://github.com/simple-icons/simple-icons/pull/5014#issuecomment-779194896 - though that resource is no longer available, it still stands unless you've found guidelines that say otherwise.

2024-09-11 01:51 UTC, uncenter commented
@ahmadnadeem6236 are you still interested in working on this pull request?

2024-09-27 19:55 UTC, uncenter commented
Closing as no response from PR author, can reopen if you have still have an interest in working on it! Future contributors- feel free to pick up where this left off in a new PR.

2024-09-27 19:55 UTC, closed without merging