minGW
simple-icons/simple-icons pull request #11311
Opened 2024-06-22 22:44 UTC by MichaelHinrichs

**Popularity metric:**
https://www.similarweb.com/website/mingw-w64.org/#overview

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description
I got this from the official website.

2024-06-22 22:46 UTC, uncenter commented
Please add a preview image!

2024-06-22 22:47 UTC, uncenter requested changes

2024-06-22 22:47 UTC, uncenter commented on _data/simple-icons.json
> +            "title": "minGW",
```suggestion
            "title": "MinGW-w64",
```

2024-06-23 16:50 UTC, MichaelHinrichs commented
> Please add a preview image!

Dang it, I forgot!

2024-06-24 18:20 UTC, uncenter requested changes

2024-06-24 18:20 UTC, uncenter commented on icons/MinGW-w64.svg
The filename should be `icons/mingww64.svg` (see `npm run get-filename`).

2024-06-25 21:48 UTC, uncenter commented
Please see the linter errors. Same issue with precision as the other one.

2024-06-25 22:32 UTC, uncenter requested changes

2024-06-25 22:32 UTC, uncenter commented on icons/mingww64.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="m-.0003 9.4029 4.187-4.187 4.1869 4.187-4.187 4.187Zm0 10.417 4.187-4.1869 4.1869 4.187-4.187 4.1869zm5.2086-5.2085 4.1869-4.187 4
```suggestion
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="m-.0003 9.4029 4.187-4.187 4.1869 4.187-4.187 4.187Zm0 10.417 4.187-4.1869 4.1869 4.187-4.187 4.1869zm5.2086-5.2085 4.1869-4.187 4.187 4.187-4.187 4.187zm0-10.417 4.187-4.187 4.1869 4.187-4.187 4.1868Zm5.2085 5.2084 4.187-4.1869 4.1869 4.187-4.187 4.1869zm5.2085-5.2084 4.187-4.187 4.1869 4.187-4.187 4.1869zm-5.208 15.626 4.187-4.1869 4.1869 4.187-4.187 4.1869zm5.2086-5.2085 4.187-4.187 4.1868 4.187-4.1869 4.187z"/></svg>
```

2024-06-30 18:59 UTC, adamrusted commented on icons/mingww64.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="m-.0003 9.4029 4.187-4.187 4.1869 4.187-4.187 4.187Zm0 10.417 4.187-4.1869 4.1869 4.187-4.187 4.1869zm5.2086-5.2085 4.1
```suggestion
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>MinGW-w64</title><path d="m-.0003 9.4029 4.187-4.187 4.1869 4.187-4.187 4.187Zm0 10.417 4.187-4.1869 4.1869 4.187-4.187 4.1869zm5.2086-5.2085 4.1869-4.187 4.187 4.187-4.187 4.187zm0-10.417 4.187-4.187 4.1869 4.187-4.187 4.1868Zm5.2085 5.2084 4.187-4.1869 4.1869 4.187-4.187 4.1869zm5.2085-5.2084 4.187-4.187 4.1869 4.187-4.187 4.1869zm-5.208 15.626 4.187-4.1869 4.1869 4.187-4.187 4.1869zm5.2086-5.2085 4.187-4.187 4.1868 4.187-4.1869 4.187z"/></svg>
```

2024-07-07 17:47 UTC, MichaelHinrichs commented
I can't delete the newline!

2024-07-07 17:54 UTC, uncenter commented
Are you editing it on the GitHub website? It will always add one for you, so you can't remove it from there.

2024-07-25 19:35 UTC, MichaelHinrichs commented
That's better!

2024-08-03 13:19 UTC, LitoMore approved these changes

2024-08-03 13:19 UTC, merged