Add Arabica Coffee icon
simple-icons/simple-icons pull request #11416
Opened 2024-07-06 09:33 UTC by shindgewongxj

Fix: #11414

**Issue:** closes #

**Popularity metric:**

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

The original aspect ratio cannot be central in art board (24x) as (height: 21, width: 24), there should be an improvement.

2024-12-10 09:47 UTC, adamrusted requested changes

2024-12-10 09:47 UTC, adamrusted commented on icons/arabicacoffee.svg
I'm seeing some differences when comparing to the .ttf file they reference in their source code:
![image](https://github.com/user-attachments/assets/f4bbda44-5695-4962-9116-879df131f877)

To get the 'official' icon out of the font, you can copy-paste `` into your editor using the `.ttf` font found [here](https://arabica.coffee/wp-content/themes/arabica/fonts/arabica-icons.ttf)

2024-12-10 09:47 UTC, adamrusted commented on _data/simple-icons.json
> +            "source": "https://upload.wikimedia.org/wikipedia/commons/b/b7/%25_Arabica_percent_logo.svg"
If you're using Wikipedia as a source, you must link to the Wikimedia Commons version of the image. If that does not exist, we cannot use that image.

2024-12-10 09:48 UTC, adamrusted commented
> The original aspect ratio cannot be central in art board (24x) as (height: 21, width: 24), there should be an improvement.

When you optimise the SVG, you should be saving with 3 decimal places of precision, allowing a 21px tall icon to fit correctly in our icon size.

2025-05-16 10:30 UTC, PeterShaggyNoble commented
Are you still working on this one, @shindgewongxj?

It looks to me like the brand name is actually "**%** Arabica", so we'll probably need to update that.

2025-05-30 11:47 UTC, PeterShaggyNoble commented
Closing due to lack of activity.

2025-05-30 11:47 UTC, closed without merging