Added Telefonica Icon
simple-icons/simple-icons pull request #11468
Opened 2024-07-13 07:39 UTC by vanshaj-sharma

![image](https://github.com/user-attachments/assets/f741c847-4a5d-4a93-9e22-a89432cdadc5)

**Issue:** closes #11455 

**Popularity metric:**
Similiarweb Global Rank: [50,057](https://www.similarweb.com/website/telefonica.com)

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

I was able to remove the "Telefonica" part in the logo provided at #11455 and also at JSON data, I wrote Telefonica, as Telefónica which was creating issues in linting. Did a simlar sort of a thing in the svg while adding the title tag and also naming the svg. I request the moderators to take a look into this and I will be happy to make changes accordingly if needed

2024-08-15 13:58 UTC, adamrusted commented
@vanshaj-sharma - please tell us what issues you were getting when trying to save with the ó in the name. We can't help if you don't tell us what the issues were :)

2024-08-15 23:32 UTC, mondeja requested changes

2024-08-15 23:32 UTC, mondeja commented on icons/telefonica.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Telefonica</title><path d="M7.162 3.581a3.581 3.581 0 1 0-7.162 0 3.581 3.581 0 0 0 7.162 0m8.419 0a3.581 3.581 0 1 0-7.1
If you see the linter message is very clear:

```sh
x icons/telefonica.svg
  x icon-title Unencoded unicode characters found in title "Telefónica": rewrite it as "Telef&#243;nica".
```

2024-08-15 23:32 UTC, mondeja commented on _data/simple-icons.json
> +            "title": "Telefonica",
Here you don't need to encode it:

```suggestion
            "title": "Telefónica",
```

2024-12-10 10:03 UTC, adamrusted approved these changes
LGTM, thanks @vanshaj-sharma!

2024-12-10 10:03 UTC, merged