Added the wazuh logo and optimized it
simple-icons/simple-icons pull request #11465
Opened 2024-07-13 04:46 UTC by pontushenriksson

![image](https://github.com/user-attachments/assets/9bed52e4-e1f6-4355-adaf-56ccae61c456)

**Issue:** closes #11460

**Popularity metric:**
The Wazuh rank is 112,343. See [here](https://www.similarweb.com/website/wazuh.com/#overview).

### Checklist

* [x] I updated the JSON data in `_data/simple-icons.json`
* [x] I optimized the icon with SVGO or SVGOMG
* [x] The SVG `viewbox` is `0 0 24 24`

### Description

- I picked the color from their branding and trademark guidelines paper [here](https://wazuh.com/docs/Wazuh-logo-usage.pdf?ver=1712163498305). I also visited their [rebranding announcement page](https://wazuh.com/blog/wazuh-rebranding-announcement/) where they are using this hex color for more things like the bullet list and many other parts of the website seem to favor this color as their primary color.
- The SVG was taken from the footer on [their website](https://wazuh.com/) but the colors were doublechecked and the color on the dot in the footer is the same hex as they mention in the [guidelines](https://wazuh.com/docs/Wazuh-logo-usage.pdf?ver=1712163498305).

2024-07-14 15:13 UTC, runxel requested changes

2024-07-14 15:13 UTC, runxel commented on _data/simple-icons.json
See linter, please remove trailing slash "/". Thanks!

2024-12-10 10:06 UTC, adamrusted reviewed
The icon itself is a perfect match, though the guidelines you linked specifically say you are not allowed to re-colour the logo, which is required in order to make it monochrome. Can you please reach out to them seeking approval for this usage, @pontushenriksson?

2025-03-12 18:44 UTC, closed without merging

2025-03-12 18:44 UTC, adamrusted commented
Closing as no feedback from @pontushenriksson or brand. Feel free to message here if you'd like to proceed with this PR.