add Contabo icon
simple-icons/simple-icons pull request #11499
Opened 2024-07-20 23:18 UTC by youneskacel

![contabo (1)](https://github.com/user-attachments/assets/958e7b51-609b-4b6e-8b98-f2f8e0cfda32)

**Issue:** closes #11496

**Popularity metric:** similarweb rank : 29,963 
https://www.similarweb.com/website/contabo.com/#overview

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

Used the primary color of the logo

2024-07-20 23:21 UTC, uncenter requested changes

2024-07-20 23:21 UTC, uncenter commented on _data/simple-icons.json
> +            "guidelines": "https://contabo.com/"
```suggestion
```
Not seeing any guidelines here?

2024-07-20 23:21 UTC, uncenter commented on icons/contabo.svg
Hmm it kinda looks from just the naked eye like you squashed the image? Make sure to preserve the aspect ratio of the logo when shrinking to fit the document.

2024-07-21 11:09 UTC, youneskacel commented
@uncenter I fixed the issues

2024-07-21 12:01 UTC, uncenter requested changes

2024-07-21 12:01 UTC, uncenter commented on _data/simple-icons.json
> +            "source": "https://contabo.com/"
```suggestion
            "source": "https://contabo.com"
```

2024-07-21 12:07 UTC, uncenter requested changes

2024-07-21 12:07 UTC, uncenter commented on icons/contabo.svg
I'm seeing differences compared to the SVG in the website header:

![CleanShot 2024-07-21 at 08 06 49@2x](https://github.com/user-attachments/assets/115d3ee2-aea1-4996-9700-f1229392425e)

2024-07-21 12:25 UTC, youneskacel commented on icons/contabo.svg
well it is exactly the same with the one on the header, you can check it has no shadows

2024-07-21 12:28 UTC, uncenter commented on icons/contabo.svg
I'm comparing it. The black is your icon, the colorful is the original overlayed on top. It doesn't match up.

2024-07-21 12:38 UTC, youneskacel commented on icons/contabo.svg
well as you could see , its a matter of y value , i did it to center it better

2024-07-21 12:40 UTC, uncenter commented on icons/contabo.svg
Ah it is. Please make it perfectly centered.

2024-07-21 12:52 UTC, youneskacel commented on icons/contabo.svg
you can check now , i fixed it

2024-07-22 19:56 UTC, uncenter commented
> Email sent to request permission from Contabo , waiting for their response

As stated in the original issue I've already reached out, so we'll get two responses! 😅

2024-07-29 19:31 UTC, youneskacel commented
Permission given by the them

![Screenshot 2024-07-29 203040](https://github.com/user-attachments/assets/4c441c62-736c-4f5d-8cfa-6cb944ff4351)

2024-09-09 08:39 UTC, LitoMore approved these changes

2024-09-09 08:40 UTC, merged