Renamed "Tencent QQ" to "QQ"
simple-icons/simple-icons pull request #11535
Opened 2024-07-26 01:32 UTC by lsyversen

**Issue:** closes #11486

This product was called Tencent QQ decades ago. But now everyone just calls it QQ. Even the official QQ has changed the name "Tencent QQ" to "QQ" in many places.

This is similar to the relationship between "Mozilla Firefox" and "Firefox", "Facebook Messenger" and "Messenger".

The benefit is the name "QQ" would be more accurate in the modern.

2024-07-26 20:03 UTC, uncenter requested changes
You'll also need to rename https://github.com/simple-icons/simple-icons/blob/develop/icons/tencentqq.svg.

2024-10-01 14:30 UTC, uncenter commented
Need to remove that trailing newline locally.

2024-10-02 00:08 UTC, LitoMore commented
> Need to remove that trailing newline locally.

Simply use the `github.dev`. Just press <kbd>.</kbd> key on the PR page.

2024-10-02 00:26 UTC, uncenter approved these changes

2024-11-26 07:11 UTC, closed without merging