Add Apryse icon (simple-icons#9656)
simple-icons/simple-icons pull request #11558
Opened 2024-07-30 09:02 UTC by hammad-521

![image](https://github.com/user-attachments/assets/3423cfdf-9485-4e1c-b947-bbea0c674eb3)

**Issue:** closes #9656 

**Popularity metric:**  
The Similarweb rank is: 160,836. See: https://www.similarweb.com/website/apryse.com/

### Checklist
- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description
  - Got the logo from the Apryse website.
  - Removed the name "Apryse" from the SVG using Adobe Illustrator.
  - Optimized the SVG using SVGO.

2024-07-30 09:36 UTC, hammad-521 commented
@cwickham, Could you please approve the workflows for this pull request? Thank you!

2024-07-30 12:30 UTC, uncenter commented
Please don't ping people for reviews, especially people not on our team! We will get around to your PR at some point, please be patient.

2024-09-10 04:59 UTC, LitoMore requested changes
I can see slight differences compared with the resource home https://www.apryse.com homepage.

<img width="900" alt="image" src="https://github.com/user-attachments/assets/f846eb49-fe3d-494b-a0e6-ebc683429592">

Can you check this?

2024-09-10 16:18 UTC, hammad-521 commented
> I can see slight differences compared with the resource on https://www.apryse.com homepage.
> 
> <img alt="image" width="900" src="https://private-user-images.githubusercontent.com/8186898/365898638-f846eb49-fe3d-494b-a0e6-ebc683429592.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5ODIzOTcsIm5iZiI6MTcyNTk4MjA5NywicGF0aCI6Ii84MTg2ODk4LzM2NTg5ODYzOC1mODQ2ZWI0OS1mZTNkLTQ5NGItYTBlNi1lYmM2ODM0Mjk1OTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTBUMTUyODE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGIyMWNmNWM5OTYyYjQyNWNkMDNhODY5ZDI2NDg0N2Q4MjU0M2E5ZWI1YjZkZjZlMTQ0YTFiM2ZhZmM1ODU3MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.DltRhLfJX7tRPLi57IY09iMow_1W0RyMhQjZ5fQW8DM">
> Can you check this?

@LitoMore Thank you for pointing that out! I can see the differences as well. I'll investigate this further and work on resolving it. I'll update the PR once it's addressed.

2024-09-16 07:01 UTC, hammad-521 commented
@LitoMore I hope you're doing well. I’m encountering an issue while exporting the Apryse logo as a single path SVG in Adobe Illustrator. There’s a white shadow appearing on both sides of the logo, and I’m unsure why this is happening.

Could you kindly review the file and provide any suggestions or guidance on how to resolve this issue? I’d appreciate any advice or tips you might have for ensuring a clean export without the shadow effect.

Thanks in advance for your help!

![Screenshot 2024-09-16 120009](https://github.com/user-attachments/assets/3cb7462c-5130-4537-a75a-4a33bb216e12)

2025-03-12 21:31 UTC, LitoMore commented
@hammad-521 It looks like a problem with the SVG itself. We'd better find another better source to process to bypass this problem.

Or you could reach out to them to apply for a better resource.

2025-03-13 22:45 UTC, hammad-521 commented
> @hammad-521 It looks like a problem with the SVG itself. We'd better find another better source to process to bypass this problem.
> 
> Or you could reach out to them to apply for a better resource.

Thanks for the suggestion, @LitoMore! I'll look for an alternative source for the Apryse logo and see if I can find a cleaner version to work with. If I can't find one, I'll try reaching out to Apryse directly for a better resource. I'll update the PR once I have an improved version. Appreciate the guidance!

2025-05-19 23:01 UTC, hammad-521 commented
> Are you still working on this one, @hammad-521?

Hi @PeterShaggyNoble ,
I've spent quite a bit of time trying to resolve the shadow issue with this icon. I tried different sources, including the official icon pack from the Apryse website, but unfortunately, I couldn't get it to work as needed. At this point, I'm unable to continue working on this and will step away from this PR for now.

2025-05-20 09:46 UTC, closed without merging