Add Egyptair icon
simple-icons/simple-icons pull request #11587
Opened 2024-08-07 17:54 UTC by MohamedAsaad1

![egyptair](https://github.com/user-attachments/assets/0db8cc5f-c640-4545-9c62-4e51f95c8cb1)

**Issue:** closes #11566

**Popularity metric:**[ The Similarweb rank is 10,138.](https://www.similarweb.com/website/egyptair.com/)

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

2024-09-14 02:19 UTC, uncenter commented
@MohamedAsaad1 are you still interested in continuing this pull request? The CI checks are failing. We are available to help explain what went wrong if you want.

2024-09-16 14:09 UTC, MohamedAsaad1 commented
@uncenter 
yeah, I need help. why PR  failing

2024-09-16 14:15 UTC, uncenter commented
You are getting errors related to the optimization of the icon. Try running it through SVGO again (https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#3-optimize-the-icon) with `npx svgo@latest icons/egyptair.svg -p 4`

2024-09-16 15:07 UTC, MohamedAsaad1 commented
@uncenter 
when I run the "npm run test"  it passes the  test
28834 passing (1s)
why now failing

2024-09-16 16:26 UTC, uncenter commented
> @uncenter when I run the "npm run test" it passes the test 28834 passing (1s) why now failing

Run `npm run lint`.

2024-09-16 16:59 UTC, MohamedAsaad1 commented
@uncenter 
Lint Test passed

2024-09-16 19:27 UTC, uncenter commented
Please don't update this branch unnecessarily.

2024-09-16 19:29 UTC, MohamedAsaad1 commented
@uncenter 
okay

2024-12-01 18:13 UTC, mondeja requested changes
I don't know from where you've taken the source as the website does not offers SVGs. However, the source of the issue (blue) has less points than your version (black):

![image](https://github.com/user-attachments/assets/169db432-0e5a-4c39-8ac7-afb01f7586b7)


Please, optimize it and clarify the source.

2025-05-15 15:02 UTC, PeterShaggyNoble commented
Closing due to inactivity. @QHegazy, if you would like to continue working on this one then please leave a comment and we will reopen the PR for you.

2025-05-15 15:02 UTC, closed without merging