Add GNU Free Documentation License icon
simple-icons/simple-icons pull request #11601
Opened 2024-08-11 01:31 UTC by sebastien46

![gnufreedocumentationlicense-preview](https://github.com/user-attachments/assets/7b743884-5e21-42a4-9c2d-5a1df9d0660a)

**Issue:** Contributes to #3541

**Popularity metric:**

- Similarweb: [41,830 (gnu.org)](https://www.similarweb.com/website/gnu.org)

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

  - The hex value is from the main path of the SVG: `#2E439B`
  - The vector is from gnu.org's dedicated page: https://www.gnu.org/graphics/license-logos.html

2024-11-28 21:37 UTC, mondeja requested changes

2024-11-28 21:37 UTC, mondeja commented on _data/simple-icons.json
> +            }
Would you mind to put `aliases` after `license`?

```suggestion
            "hex": "2E439B",
            "source": "https://www.gnu.org/graphics/license-logos.html",
            "license": {
                "type": "GFDL-1.3-only"
            },
            "aliases": {
                "aka": [
                    "GFDL"
                ]
            }
```

2024-11-28 22:22 UTC, mondeja requested changes
I think that this treatment is editing the original source. The icon should be the black part of the logo, not the yellow one.

![image](https://github.com/user-attachments/assets/50823332-8d50-4bb5-b2b3-a812ef62d3ac)

2025-05-16 08:52 UTC, PeterShaggyNoble requested changes
Thanks for updating this, @sebastien46. However, I'm now noticing a number of differences between your version (in red below) and the source file in black.
- [the letters](https://github.com/user-attachments/assets/4c919611-849a-4374-9759-eb19a2c578f5)
- [the top of the scroll](https://github.com/user-attachments/assets/d9cecbbc-066f-4771-9d19-89a450e92aea)
- [the bottom of the scroll](https://github.com/user-attachments/assets/7280c42c-f07d-4a50-82df-cb50637d095a)

Would you mind trying again to see if you could clean those up, please?

2025-06-04 11:29 UTC, PeterShaggyNoble commented
Are you still working on this one, @sebastien46?

2025-06-18 11:39 UTC, PeterShaggyNoble commented
Closing due to inactivity.

2025-06-18 11:39 UTC, closed without merging