added pbs icon
simple-icons/simple-icons pull request #11635
Opened 2024-08-16 21:54 UTC by Rajat-Bansal3

**Issue:** closes #

**Popularity metric:**

### Checklist

- [0] I updated the JSON data in `_data/simple-icons.json`
- [0] I optimized the icon with SVGO or SVGOMG
- [0] The SVG `viewbox` is `0 0 24 24`

### Description

2024-08-16 23:01 UTC, uncenter requested changes

2024-08-16 23:01 UTC, uncenter commented on icons/pbsIcon.svg
This icon is not properly sized, centered, or optimized. I recommend you revisit https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#2-extract-the-icon-from-the-logo and the following steps.

2024-09-14 13:55 UTC, uncenter requested changes

2024-09-14 13:55 UTC, uncenter commented on _data/simple-icons.json
> +            "hex": "2135c5",
```suggestion
            "hex": "2638C4",
```
Not sure where you got this other hex from.

2024-09-14 13:55 UTC, uncenter commented on _data/simple-icons.json
> +            "source": "https://www.pbs.org/"
```suggestion
            "source": "https://www.pbs.org"
```

2024-09-14 13:55 UTC, uncenter commented on icons/pbs.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>PBS_watermark_QuarterOpac</title><g style="opacity:0.25"><path d="M175.588 72.548c-1.324 0-1.917.79-1.917 1.642 0 1.001.6
The `<title>` is incorrect here, you have extra attributes and styling, there is a `<g>` around the `<path>`, etc. Again, please read https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#2-extract-the-icon-from-the-logo and the following steps.

2025-03-12 19:05 UTC, adamrusted commented
Closing as contributor has not worked on this in 6mths. @Rajat-Bansal3 - if you wish to continue with this PR please let us know here and we can re-open it.

2025-03-12 19:05 UTC, closed without merging