Add Sway
simple-icons/simple-icons pull request #11687
Opened 2024-08-24 00:50 UTC by eeelbrens

![sway](https://github.com/user-attachments/assets/f68abbe1-ebd9-4e37-9dfc-646cb704a225)

~**Issue:** closes #~

**Popularity metric:**

[![Star History Chart](https://api.star-history.com/svg?repos=swaywm/sway&type=Date)](https://star-history.com/#swaywm/sway&Date)

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

Logo vectorized from [source](https://github.com/swaywm/sway/blob/master/assets/Sway_Tree.svg).
Hex value `#68751C` picked as most predominant in logo (there's no official designated brand color/identity in Sway, only logo versions present); if anything, blue in their assets/'s wallpaper is not chosen to distinguish them from i3 and Hyprland's colors.

2024-08-26 08:08 UTC, PratyushJayachandran requested changes
@eeelbrens please make the requested changes. The icon matches well otherwise. 👍

2024-08-26 08:08 UTC, PratyushJayachandran commented on _data/simple-icons.json
> +            "source": "https://github.com/swaywm/sway/blob/master/assets/Sway_Tree.svg",
```suggestion
            "source": "https://github.com/swaywm/sway/blob/77b9ddabe2a97c5d04c30929b0f8cbde3470fdd7/assets/Sway_Tree.svg",
```
Please change to permalink when linking from GitHub

2024-08-26 08:08 UTC, PratyushJayachandran commented on _data/simple-icons.json
> +            "hex": "68751C",
@simple-icons/pr-reviewers What do you guys think about the choice of color for this multi-color logo?

2024-08-26 09:11 UTC, PratyushJayachandran approved these changes
Thank you for your contribution @eeelbrens 🎉 
Just waiting for consensus on the color

2024-08-26 09:17 UTC, PratyushJayachandran requested changes

2024-08-26 09:17 UTC, PratyushJayachandran commented on icons/sway.svg
Please rearrange the attributes like this
`<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">`

2024-08-27 22:15 UTC, eeelbrens commented
@PratyushJayachandran okay so how it's going on your end?

2024-08-28 00:47 UTC, PratyushJayachandran commented
> @PratyushJayachandran okay so how it's going on your end?

I'm okay with the color choice that is why I marked the PR as approved. I wanted at least one more reviewer to confirm.

2024-08-28 00:48 UTC, uncenter commented
Will take a look tomorrow and hopefully get this through :)

2024-09-11 14:28 UTC, merged