Added TIM icon
simple-icons/simple-icons pull request #11764
Opened 2024-09-14 09:59 UTC by fransdhinta

![tim](https://github.com/user-attachments/assets/868b4be9-0200-4734-ab62-42bb6c4c8854)

**Issue:** [link](https://github.com/simple-icons/simple-icons/issues/11735#issue-2512475948)

**Popularity metric:**
Similarweb Global Rank: [1,147](https://www.similarweb.com/website/tim.it)

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

- chose that color `#eb0028` because it is the most prominent color in the logo.

2024-09-15 10:10 UTC, fransdhinta commented
hi @uncenter, i have adjusted the attribute order & centering the path

2024-09-15 13:57 UTC, LitoMore commented
I will help you guys out.

2024-09-16 08:46 UTC, LitoMore commented
I rebased and force force pushed to fix those conflicts for you.

I also fixed the missing title, and removed the unecessary `TIM` text part from the icon.

Here is the preview:

![](https://github.com/user-attachments/assets/067397c9-3e35-4875-8d17-0a1f03e3558b)

2024-09-16 18:59 UTC, uncenter requested changes

2024-09-16 18:59 UTC, uncenter commented on _data/simple-icons.json
> +            "source": "https://risorse.tim.it/content/dam/flytoco-areapubblica-aemfe/loghi/logo.svg"
As per https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#source-guidelines, this must be a link to the page containing the SVG - not directly to it.
```suggestion
            "source": "https://tim.it"
```

2024-09-16 19:03 UTC, uncenter commented
See https://github.com/simple-icons/simple-icons/issues/11735#issuecomment-2353695877. We will need to reach out and request permission from TIM (see https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-permission) before adding this. @fransdhinta would you be willing to send an email / contact them?

2024-09-17 00:41 UTC, fransdhinta commented
> See [#11735 (comment)](https://github.com/simple-icons/simple-icons/issues/11735#issuecomment-2353695877). We will need to reach out and request permission from TIM (see https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-permission) before adding this. @fransdhinta would you be willing to send an email / contact them?

yes i will send permission request

2024-09-18 02:47 UTC, fransdhinta commented
@uncenter i have sent the request but they reply like this:

> Messaggio rifiutato dal sistema
> La casella destinataria di seguito indicata riceve esclusivamente messaggi di posta elettronica certificata telecomitalia@pec.telecomitalia.it – casella che riceve solo Posta Certificata

2024-12-11 09:43 UTC, adamrusted commented
@fransdhinta - if we don't have a way of getting in touch with the brand, I'm afraid we'll have to close this PR. Would you be willing to reach out to them on social media, if their mailboxes aren't accepting external messages? If so, we can add a bit more time to the clock before closing - but if we've exhausted options, then we'll have to close the PR.

2024-12-11 22:33 UTC, fransdhinta commented
> @fransdhinta - if we don't have a way of getting in touch with the brand, I'm afraid we'll have to close this PR. Would you be willing to reach out to them on social media, if their mailboxes aren't accepting external messages? If so, we can add a bit more time to the clock before closing - but if we've exhausted options, then we'll have to close the PR.

Okay, I will try to contact them on social media.

2024-12-12 07:43 UTC, fransdhinta commented
@adamrusted  - I also can't contact them on social media, I think you can close this PR

2024-12-12 08:06 UTC, closed without merging