Add Standard Notes icon
simple-icons/simple-icons pull request #11798
Opened 2024-09-19 17:45 UTC by DerBraky

![Untitled-1](https://github.com/user-attachments/assets/930cba94-964b-45c5-9976-d94327b948f6)

**Issue:** closes #11613

**Popularity metric:**
Similarweb Global Rank: [150,951](https://www.similarweb.com/website/standardnotes.com)

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

I'm unsure about the hex value (`#086DD6`, from press kit https://standardnotes.com/press)

2024-09-23 13:02 UTC, uncenter requested changes

2024-09-23 13:02 UTC, uncenter commented on _data/simple-icons.json
> +            "source": "https://standardnotes.com"
Are you using the logo in the header? Not matching up for me:

![CleanShot 2024-09-23 at 09 02 19](https://github.com/user-attachments/assets/7d0d148c-53ad-40c5-89f7-a19947a90bf2)

2024-09-23 13:11 UTC, uncenter commented
See https://github.com/simple-icons/simple-icons/issues/11613#issuecomment-2368192923.

2024-12-11 09:39 UTC, adamrusted commented
Closing as not heard back from the brand. If we do hear back from them, comment here and we can re-open the PR. Thanks for your work on this @DerBraky!

2024-12-11 09:39 UTC, closed without merging