Add 1&1 icon
simple-icons/simple-icons pull request #11795
Opened 2024-09-19 12:50 UTC by DerBraky

![image](https://github.com/user-attachments/assets/fe401e1c-41f4-45b0-9c8f-b3c1741a4ef8)

**Issue:** closes #11442

**Popularity metric:**
Similarweb Global Rank: [5,089](https://www.similarweb.com/website/1und1.de)

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

Instead of using the file from Wikimedia Commons or the logo from the header, I converted the EPS from the [Media Centre](https://www.united-internet.de/en/newsroom/media-center/logos.html) into an SVG.

2024-09-20 22:56 UTC, uncenter requested changes

2024-09-20 22:56 UTC, uncenter commented on _data/simple-icons.json
> +        },
Looks like the linter is complaining about the order here, try moving this down below 1.1.1.1?

2024-11-28 17:30 UTC, mondeja requested changes
I would prefer to maintain the same style that the original logo, whose outer square hasn't an outline:

![image](https://github.com/user-attachments/assets/58e98a9f-262f-4460-809b-dd14b88bd2a8)

In Inkscape you can select one letter, then the square and use `Path > Fracture`:

![image](https://github.com/user-attachments/assets/590b5c68-329e-420f-a493-b33fdcbc96c4)

2024-11-30 13:59 UTC, mondeja approved these changes
Looks great! Thank you 🟦

2024-11-30 14:00 UTC, merged