Add Kiwix icon
simple-icons/simple-icons pull request #11815
Opened 2024-09-20 22:02 UTC by DerBraky

![image](https://github.com/user-attachments/assets/09019255-9f96-4fd4-acc3-908aa436b9bd)

**Issue:** closes #11780

**Popularity metric:**
Similarweb Global Rank: [179,827](https://www.similarweb.com/website/kiwix.org)

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

2024-12-17 20:07 UTC, service-paradis requested changes
Thank you @DerBraky for your contribution I left a few comments, can you take a lok?

2024-12-17 20:07 UTC, service-paradis commented on icons/kiwix.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Kiwix</title><path d="M18.298 15.359c-.663-2.037-2.906-3.167-5.014-2.526-2.107.64-3.277 2.809-2.614 4.845l.01.026H8.784a.
When comparing with https://wiki.kiwix.org/wiki/Logo#/media/File:Kiwix_logo_v3.svg I see the following differences (original in red, yours in black):
![image](https://github.com/user-attachments/assets/225c75a6-96db-41b0-8b7d-0e5f3faf0cc1)

2024-12-17 20:07 UTC, service-paradis commented on _data/simple-icons.json
> +            "source": "https://wiki.kiwix.org/wiki/Logo"
```suggestion
            "source": "https://wiki.kiwix.org/wiki/Logo",
            "license": {
                "type": "CC-BY-SA-4.0"
            }
```

According to https://wiki.kiwix.org/wiki/Logo#/media/File:Kiwix_logo_v3.svg, we can add the following license:
![image](https://github.com/user-attachments/assets/210cd5a0-f0fb-4b2b-b679-3e2def0fdcbd)

2025-02-08 12:13 UTC, LitoMore commented
@DerBraky Would you mind resolving the conflict yourself since you requested a review?

2025-02-17 13:49 UTC, service-paradis approved these changes
Great, thank you @DerBraky for your contribution! 🎉

2025-02-17 13:51 UTC, merged