Add MTN icon
simple-icons/simple-icons pull request #11859
Opened 2024-09-26 18:06 UTC by DerBraky

![Untitled](https://github.com/user-attachments/assets/7c3285f2-e3ee-4ebb-818c-7a14ed1c287c)

**Issue:** closes #11733

**Popularity metric:**
- Similarweb Global Rank: [7,297](https://www.similarweb.com/website/mtn.co.za)

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

2024-12-01 18:40 UTC, mondeja requested changes
Looks like the source (yellow) has changed to a better version and now has a huge difference compared with your version (green):

![image](https://github.com/user-attachments/assets/01accab5-e121-45b7-82c6-47145324e73a)

Could you redo this logo, please?

2024-12-17 14:22 UTC, mondeja commented
I'm still seeing some differences between your version and the source, so let's wait for another review.

2025-06-02 21:31 UTC, DerBraky commented
I've sent them an email now.

2025-09-14 11:46 UTC, adamrusted commented
Assuming you've not heard anything from them @DerBraky - I'm going to close this PR for now. Should you hear from the brand, let us know here and we can re-open here.

2025-09-14 11:46 UTC, closed without merging