Add PAYBACK icon
simple-icons/simple-icons pull request #11851
Opened 2024-09-25 21:06 UTC by DerBraky

![Untitled](https://github.com/user-attachments/assets/49bd0dbd-5d6c-4808-81ab-a90727a6f32c)

**Issue:** closes #11618

**Popularity metric:**
- Similarweb Global Rank: [4,944](https://www.similarweb.com/website/payback.de)

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

Adapted from: https://www.payback.de/resource/blob/97510/c1eeb7e245cad7fcef5a678547c9a713/prospektbox-logo-image-resdata4.svg

2025-05-15 09:08 UTC, PeterShaggyNoble requested changes
Thanks for the contribution, @DerBraky 👍🏻 However, I think we should go with the treatment below to maintain a better consistency with the source file; what do you reckon?

Also, we should change the `source` to https://www.payback.de/filialen-prospekte; I couldn't find the source file on their homepage.

![](https://github.com/user-attachments/assets/0b064997-74a1-493f-a3ee-9964313331a1)

2025-06-11 12:04 UTC, PeterShaggyNoble commented
Another possible treatment:
![](https://github.com/user-attachments/assets/1a851184-2bc5-40ea-b96d-119bdce19205)

2025-06-23 04:33 UTC, PratyushJayachandran commented
> 
> ![](https://private-user-images.githubusercontent.com/15157491/444036606-0b064997-74a1-493f-a3ee-9964313331a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTA2NTM0MzQsIm5iZiI6MTc1MDY1MzEzNCwicGF0aCI6Ii8xNTE1NzQ5MS80NDQwMzY2MDYtMGIwNjQ5OTctNzRhMS00OTNmLWEzZWUtOTk2NDMxMzMzMWExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNjIzVDA0MzIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiMTg2M2M3N2Y1NDE1Y2MxMDhjNTUyZjcwZGQzMTVjOGMxMjZjMDIxOTBkZDY3YjY5YWMwZmRjZTk5YTM3MTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bZaBz6aUSS0cfuFuHQ2GesZ9-dSCfvtBP7Mw2LLT9nk)


I like this version over the second option you posted as it matches with their favicon too

2025-06-23 04:46 UTC, PratyushJayachandran commented on icons/payback.svg
I am getting a much different icon when compared to their logo from the page mentioned as source: 
![image](https://github.com/user-attachments/assets/50e2d1e5-c7b6-4756-9e2c-baa045c24e68)

Direct link: https://www.payback.de/resource/blob/97510/c1eeb7e245cad7fcef5a678547c9a713/prospektbox-logo-image-resdata4.svg

2025-06-23 09:22 UTC, PeterShaggyNoble commented on icons/payback.svg
Are you including the outer white square, @PratyushJayachandran? I believe I omitted it, cropping the parts of the blue square that it overlaps.

2025-06-30 02:39 UTC, PratyushJayachandran commented on icons/payback.svg
You were correct. It matches up well now!

2025-06-30 02:40 UTC, PratyushJayachandran approved these changes
Thank you @DerBraky for starting the PR and @PeterShaggyNoble for finishing it up 🎉

2025-06-30 10:54 UTC, merged