Update Unilever icon
simple-icons/simple-icons pull request #11891
Opened 2024-09-29 04:34 UTC by LitoMore

This optimized the file size from 25.652 KiB to 20.747 KiB.

2024-10-03 12:07 UTC, PratyushJayachandran commented
The logo is now hosted in a different space now: [https://www.unilever.com/news/press-and-media/media-assets/](https://www.unilever.com/news/press-and-media/media-assets/)
Can we update that too?

2024-10-03 12:13 UTC, PratyushJayachandran requested changes
When comparing with the logo on their media assets page, I see some imperfections. Attaching the comparison below.
![unilever-comparison](https://github.com/user-attachments/assets/75ed4288-0f74-4b99-9b3c-797089690ecb)
![image](https://github.com/user-attachments/assets/ea3b4b50-f8eb-42fa-ad0f-9e65024dc723)
I used the white version from here: [Media Assets](https://www.unilever.com/news/press-and-media/media-assets/)

2024-10-04 01:01 UTC, LitoMore commented
Update. It only has a slight difference. You may have some misconfiguration on your image editor.

2024-10-04 04:55 UTC, PratyushJayachandran commented
> Updated. It only has a slight difference. You may have some misconfiguration on your image editor.

![unilever-comparison](https://github.com/user-attachments/assets/1ba12047-a913-4bf0-8fcf-8fb18d34cbf2)
It is better than before but some of the circles in the artwork aren't matching. Screenshot of the outline view attached:
![image](https://github.com/user-attachments/assets/ef0b6c75-271b-44f8-884d-d30639d614f3)

2024-10-04 05:01 UTC, LitoMore commented
> You may have some misconfiguration on your image editor.

Please use Inkscape or Figma to review this.

2024-11-28 19:34 UTC, mondeja commented
I'm using Inkscape and still seeing some significative differences.

2024-12-12 19:48 UTC, adamrusted commented on icons/unilever.svg
I'm also seeing issues with the circles in the right-hand side of the logo:
![image](https://github.com/user-attachments/assets/dbd9d8a7-bc0d-4851-990b-5edf8bbdf405)

The eye of the fish at the bottom:
![image](https://github.com/user-attachments/assets/cc40392e-39a7-4166-991a-3a784b86f1d7)

And some slight differences to the shapes in the top-left:
![image](https://github.com/user-attachments/assets/f9eb83c2-4be0-4f1f-85e1-82e2e1247849)

This is in Affinity Designer, with no snap-to-pixel or precision rules applied.

2024-12-12 20:11 UTC, LitoMore commented on icons/unilever.svg
Thanks. I just reprocessed the icon. I'm not sure what happened to the previous file.

Here is the difference preview:

![](https://github.com/user-attachments/assets/16bfa8ea-8b4e-4201-99d4-b276be0642e5)

2024-12-12 20:26 UTC, adamrusted commented on icons/unilever.svg
I would prefer to have a _slightly_ larger file for accuracy sake (I would always prefer we go that route, for the record). Comparing your version (black) with the source file (white) I'm seeing _more_ differences now than I was with the last version:

![image](https://github.com/user-attachments/assets/dc1b1a0a-baea-461f-af5a-7681d3dc84e7)
![image](https://github.com/user-attachments/assets/98e2f671-9905-4ff2-b3e6-d69763241cf4)

2024-12-12 20:55 UTC, LitoMore commented
Thanks for reviewing. The precision 3 looks not good on this icon. So let's keep the precision 4.

2024-12-12 20:55 UTC, closed without merging