Update dm icon
simple-icons/simple-icons pull request #11922
Opened 2024-10-03 16:42 UTC by DerBraky

![Untitled](https://github.com/user-attachments/assets/6d157219-358e-4287-9699-c0bc95b3e9d2)

**Issue:** closes #11556

**Popularity metric:**
- Similarweb Global Rank: [3,445](https://www.similarweb.com/website/dm.de) (German)

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

Adapted from: https://www.dm-jobs.com/dmTECH

2024-11-30 08:29 UTC, LitoMore requested changes

2024-11-30 08:29 UTC, LitoMore commented on _data/simple-icons.json
> +            "source": "https://www.dm-jobs.com/dmTECH",
This page is down. Please use the root instead.

2024-12-01 19:16 UTC, mondeja commented on _data/simple-icons.json
> +            "source": "https://www.dm-jobs.com/dmTECH",
```suggestion
            "source": "https://dm-jobs.com",
```

2024-12-01 19:20 UTC, mondeja requested changes
There are differences between your version (red) and the source of the issue (black):

![image](https://github.com/user-attachments/assets/957216a8-383e-4712-b483-41a3c93f1e3c)

Maybe the source has been updated. Would you mind to redo it?

2024-12-11 10:18 UTC, adamrusted requested changes

2024-12-11 10:18 UTC, adamrusted commented on _data/simple-icons.json
> +            "source": "https://www.dmtech.tech",
The main website still applies - dmtech is just the technology branch of the business.

```suggestion
            "source": "https://www.dm.de",
```

2024-12-11 10:18 UTC, adamrusted commented on icons/dm.svg
Seeing some differences between your icon (black) and the icon from the website header (red). Could you take another look please @DerBraky?

![image](https://github.com/user-attachments/assets/53a35177-0f2f-43df-bbc4-0887ff70189d)

2024-12-28 08:39 UTC, LitoMore approved these changes

2024-12-28 08:41 UTC, merged