Add Vencord icon
simple-icons/simple-icons pull request #11944
Opened 2024-10-06 18:09 UTC by somerand0mcatt

![vencord](https://github.com/user-attachments/assets/66b80734-d2be-42ca-8358-c40ca369e69f)

**Popularity metric:**
8.7k stars at https://github.com/Vendicated/Vencord
62,084 global rank at https://www.similarweb.com/website/vencord.dev/

### Checklist

- [X] I updated the JSON data in `_data/simple-icons.json`
- [X] I optimized the icon with SVGO or SVGOMG
- [X] The SVG `viewbox` is `0 0 24 24`

### Description
the accent color changes daily according to vencord's discord, so i had to use the current one (`#8E71D4`)
also, there was no svg of the official logo so i had to convert it to a svg at a website and then edit it

2024-10-06 18:28 UTC, uncenter requested changes

2024-10-06 18:28 UTC, uncenter commented on _data/simple-icons.json
> +	        "source": "https://raw.githubusercontent.com/Vencord/Vesktop/main/build/icon.png?format=webp&quality=lossless&width=662&height=662"
This does not follow https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#source-guidelines.

2024-10-06 18:28 UTC, uncenter commented on _data/simple-icons.json
Please keep the indentation consistent in this file.

2024-10-06 18:28 UTC, uncenter commented on icons/vencord.svg
This is not properly optimized as per our guidelines.

2024-10-06 18:36 UTC, uncenter commented on _data/simple-icons.json
> +	        "hex": "8E71D4",
```suggestion
	        "hex": "D3859B",
```
`#d3859b` seems like the Vencord theme primary accent.

2024-10-08 17:30 UTC, somerand0mcatt commented
> I also tried to convert and optimize the PNG manually, but without filling in the letters.
that looks alot more better, i'll use that svg

2024-11-30 15:20 UTC, mondeja approved these changes
This is an amazing work. Thank you all! 🥇

2024-11-30 15:24 UTC, merged