Update Stripe
simple-icons/simple-icons pull request #11967
Opened 2024-10-09 00:05 UTC by koehlertimo

**Issue:** closes #11936

**Popularity metric:** N/A

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description
Changed color of stripe. Now it matches the current color theme

2024-10-10 02:04 UTC, uncenter requested changes

2024-10-10 02:04 UTC, uncenter commented on _data/simple-icons.json
> +            "hex": "7069FE",
```suggestion
            "hex": "635BFF",
```

`#635BFF` is the hex code I'm seeing used in the logo assets. Where did you get `#7069FE` from?

2024-10-10 02:04 UTC, uncenter commented on _data/simple-icons.json
> +}
Please add the trailing newline back.

2024-10-10 02:13 UTC, uncenter commented on _data/simple-icons.json
>              "source": "https://stripe.com/about/resources"
```suggestion
            "source": "https://stripe.com/newsroom/information"
```
This link now redirects here.

2024-10-10 02:13 UTC, uncenter commented
Please see https://github.com/simple-icons/simple-icons/issues/11936#issuecomment-2403759546. If possible could you update the icon as well? You can use the same source as is linked right now, https://stripe.com/newsroom/information. See https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon for instructions on how to update the SVG/icon.

2024-12-11 09:20 UTC, adamrusted approved these changes
Thanks for your work on this, @koehlertimo!

2024-12-11 09:21 UTC, merged