Add Three icon
simple-icons/simple-icons pull request #11965
Opened 2024-10-08 20:46 UTC by DerBraky

![Untitled](https://github.com/user-attachments/assets/c423025e-a1ac-4eb1-a1c6-c55e8a8d4ce0)

**Issue:** closes #11326

**Popularity metric:**
- Similarweb Global Rank: [4,394](https://www.similarweb.com/website/three.co.uk) (UK)

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

- Includes aliases similar to #11912
- Brand guidelines: https://threebrandcentral.com/assets
- Logo adapted from https://www.three.co.uk/content/experience-fragments/threedigital/uk/en/site/header/master/_jcr_content/root/header/top/logo.coreimg.svg/1668177162294/three-logo.svg

2025-05-01 16:28 UTC, jcallaghan commented
Hi. Any way update on this?

2025-05-05 04:39 UTC, LitoMore requested changes
@DerBraky I used the resource from the guidelines page. And I found some differences. Can you check it?

![](https://github.com/user-attachments/assets/84411580-1608-4ea1-a698-129c58950af8)

2025-05-31 15:10 UTC, adamrusted commented
@DerBraky - can you please review the lint error before we merge?

2025-06-17 17:21 UTC, adamrusted commented
Doing some digging on this, it would appear we need permission to use their brand assets. [This page](https://assets.ctfassets.net/kcx1u0t4y3dl/K4vQbL3ZZuAzno1mrtLMj/7af7087522acb141950e92f17e89a746/terms-of-use.pdf) on the [parent company's media page](https://www.vodafonethree.com/news) states we cannot alter their brand assets without their explicit permission. Could you please reach out to them @DerBraky?

2025-09-14 11:31 UTC, adamrusted commented
Closing as no update given on permission request in nearly 3 months since asked for. @DerBraky - if you did reach out and hear from the brand, please let us know here and we can re-open.

2025-09-14 11:31 UTC, closed without merging