Add Speedrun.com icon
simple-icons/simple-icons pull request #11997
Opened 2024-10-12 17:40 UTC by DerBraky

![image](https://github.com/user-attachments/assets/9f31014f-bbbc-4267-b38b-184e6436def7)

**Issue:** closes #8521

**Popularity metric:**
- Similarweb Global Rank: [15,330](https://www.similarweb.com/website/speedrun.com)

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

Logo/icon adapted from website (`#FFD95C` one of the main colors)

2024-10-12 17:52 UTC, uncenter commented
Hmm I'm not seeing that shade of yellow anywhere on the website - only really seeing shades of green like `#178C6B`.

2025-05-15 11:42 UTC, PeterShaggyNoble requested changes
I'd agree with uncenter here that green is the _brand_ colour (or as close as we're going to get to one), which isn't always necessarily a colour used in a brand's logo/icon. More specifically, I'd go with the green from the website's header.

@uncenter, did you review the icon itself?

2025-05-15 11:48 UTC, uncenter commented
> @uncenter, did you review the icon itself?

No I don't believe I did.

2025-05-31 15:16 UTC, adamrusted commented
@DerBraky - please see [this page](https://www.speedrun.com/pages/terms-of-use), namely the 'Ownership of the website' section. We will require permission to add this icon. Could you please reach out to them?

2025-09-14 11:43 UTC, adamrusted commented
Given no feedback since asking for permission, I'm closing this one for now. Should we receive written permission - we can reopen this PR.

2025-09-14 11:43 UTC, closed without merging