add icon: smtp2go
simple-icons/simple-icons pull request #12064
Opened 2024-10-19 23:43 UTC by call-me-matt

![image](https://github.com/user-attachments/assets/7064e186-5341-42c5-a152-7c907f1130c1)

**Popularity metric:**
#183,865

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

This is my first contribution. Not sure the light color is a good choice, please check.

2025-05-15 11:52 UTC, PeterShaggyNoble requested changes
Thanks for the contribution, @call-me-matt 👍🏻 However, I'm seeing some significant differences between your version (in red below) and the source file (in black). Would you mind having another look at it, please?

I agree, though, that the colour you've selected is as good a choice as any; it's similar enough to the one used in their favicon and the colour I most associate with them.

Other than that, you'll need to revert the changes you made to package.json before this can be merged.

![](https://github.com/user-attachments/assets/4331264d-43b8-4fea-b45c-66b993c04f57)

2025-05-15 19:01 UTC, call-me-matt commented
I am impressed on your detailled verification! I compared it again to this file and could reproduce your finding: https://www.smtp2go.com/wp-content/themes/smtp2go/images/logo.svg
Will try again

2025-05-21 14:40 UTC, PeterShaggyNoble requested changes
Thanks, @call-me-matt. I am seeing some very small differences, though, when comparing to source. They're most apparent in the right edge of the "o" below (yours in red). You can most likely fix them by increasing the optimisation precision.

![](https://github.com/user-attachments/assets/5863d671-884f-4b3a-b873-50b52dac225e)

2025-06-11 14:33 UTC, PeterShaggyNoble commented
Closing due to inactivity

2025-06-11 14:33 UTC, closed without merging