Add Max (streaming service) icon
simple-icons/simple-icons pull request #12118
Opened 2024-11-07 22:14 UTC by Snakmagic

![max_preview](https://github.com/user-attachments/assets/9514a817-ed7f-4b50-a7db-4e3afe5eb5f9)

**Popularity metric:** Similarweb global rank 193

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

Icon for the popular streaming service Max.

Named the file max_streaming.svg per the guidelines because there is already a max.svg icon for another entity. Also added a 'slug' line with 'max_streaming' to the JSON entry for this icon.

2024-11-07 22:44 UTC, uncenter requested changes

2024-11-07 22:44 UTC, uncenter commented on _data/simple-icons.json
Looks like you are using the wrong quote character here, and some of the indentation is using tabs instead of spaces.

2024-11-07 22:44 UTC, uncenter commented on icons/max_streaming.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Max</title><path fill="#000" d="M3.784 9c-.655 0-1.32.291-2.173.946v-.78H0v6.236h1.715v-3.876c.749-.593 1.091-.78 1.372-.
```suggestion
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Max</title><path d="M3.784 9c-.655 0-1.32.291-2.173.946v-.78H0v6.236h1.715v-3.876c.749-.593 1.091-.78 1.372-.78.333 0 .551.208.551.728v3.928h1.715v-3.887c.748-.582 1.081-.769 1.372-.769.333 0 .55.208.55.728v3.928H8.99v-4.531C8.99 9.468 8.19 9 7.42 9c-.654 0-1.32.27-2.192.936C4.948 9.239 4.334 9 3.784 9Zm8.689 0c-1.705 0-3.118 1.466-3.118 3.284 0 1.82 1.413 3.285 3.118 3.285.842 0 1.57-.312 2.131-.988v.821h1.632V9.166h-1.632v.822C14.043 9.312 13.314 9 12.473 9Zm4.064.166c.707 1.102 1.507 2.09 2.443 3.077a26.593 26.593 0 0 0-2.443 3.16h2.069c.488-.79 1.039-1.508 1.673-2.183a14.067 14.067 0 0 1 1.632 2.182H24a25.142 25.142 0 0 0-2.432-3.159A23.918 23.918 0 0 0 24 9.166h-2.047c-.51.79-1.06 1.455-1.674 2.11a13.357 13.357 0 0 1-1.674-2.11h-2.068Zm-3.804 1.279c1.018 0 1.84.821 1.84 1.84 0 1.018-.822 1.839-1.84 1.839-1.019 0-1.84-.82-1.84-1.84 0-1.018.821-1.84 1.84-1.84Zm0 .415c-.78 0-1.414.634-1.414 1.424 0 .79.634 1.424 1.413 1.424.78 0 1.414-.634 1.414-1.424 0-.79-.634-1.424-1.414-1.424Z"/></svg>
```

No extra attributes (`fill`) are allowed.

2024-11-07 22:58 UTC, Snakmagic commented on _data/simple-icons.json
Good catch. First time doing this. Will be more vigilant next time.

2024-11-07 23:26 UTC, Snakmagic commented on _data/simple-icons.json
Thanks. Updated.

2024-11-13 19:45 UTC, Snakmagic commented
Apologies for the newbie question, but could you point me to some documentation on how to fix the Lint error the max_streaming.svg file generated?

     x icon-centered <path> must be centered at (12, 12); the center is currently (12, 12.285)

I've examined the contents of the svg file and cannot locate this so I can fix it. Hoping to do some good by contributing this icon, but am at a loss on how to fix it. Thank you!

2024-11-13 19:50 UTC, uncenter commented
> I've examined the contents of the svg file and cannot locate this so I can fix it. Hoping to do some good by contributing this icon, but am at a loss on how to fix it. Thank you!

You'll need to center the icon within the document. In Inkscape: **Object** > **Align and Distribute...**, set **Relative to:** to "Page", and click the center on vertical axis and center on horizonal axis buttons.

2024-11-14 00:29 UTC, Snakmagic commented
Thanks for the explanation and path to fix. I believe I've corrected the issue with the icon.

2024-11-14 01:46 UTC, uncenter commented on icons/max_streaming.svg
Not sure what this changed but this isn't what the linter is complaining about. This SVG file has a trailing newline after the SVG markup that needs to be removed (this cannot be done through the GitHub web editor, you must do it locally or in Codespaces if you use that).

2024-11-14 01:51 UTC, Snakmagic commented on icons/max_streaming.svg
Thanks, I'll give it another go. I appreciate your explanations and patience!

2025-05-15 13:49 UTC, PeterShaggyNoble approved these changes
Thanks for the contribution, @Snakmagic 👍🏻

2025-05-15 13:50 UTC, merged

2025-05-15 14:24 UTC, uncenter commented
I should note that HBO recently announced a rebrand from Max to the original HBO Ma?. I'm not sure if this has taken effect yet but we might want to update it down the road, or we could update it now before releasing this week (might be nice to have a `hbomax` slug instead of `max_streaming`).

2025-05-15 14:27 UTC, PeterShaggyNoble commented
Feck's sake! How many name changes is that, now?! 😆 

However far down the road it is, I'd be in favour of making that change to the slug now, too. That way, when they do update, it won't/shouldn't constitute a breaking change on our part.