Add Lime icon
simple-icons/simple-icons pull request #12132
Opened 2024-11-13 16:24 UTC by Alvin-Fung

Issue: closes #

Popularity metric: Similarweb Global Rank: 86,188

Checklist
[x] I updated the JSON data in _data/simple-icons.json
[x]I optimized the icon with SVGO or SVGOMG
[ ]The SVG viewbox is 0 0 24 24

Description
I added the Lime icon, sourced from the official brand website: https://www.li.me/. The primary brand color #00dd00 was used, which matches the color from the logo. The SVG path data was extracted and added to the JSON file in accordance with the Simple Icons guidelines.

Let me know if any further changes are required!

2024-11-16 18:16 UTC, uncenter commented on _data/simple-icons.json
> +}
Please do not change formatting.

2024-11-16 18:16 UTC, uncenter commented on _data/simple-icons.json
> +            "hex": "00dd00",
Hex codes must be capitalized. Please run `npm run lint` locally to catch mistakes like this before raising a PR.
```suggestion
            "hex": "00DD00",
```

2024-11-16 18:17 UTC, uncenter commented on icons/lime.svg
This SVG file is not at all [optimized](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#3-optimize-the-icon) or [annotated](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#5-check-the-icon) correctly as per our guidelines. Please read through our contributing documentation!

2024-11-17 18:36 UTC, Alvin-Fung commented on icons/lime.svg
Thank you for the feedback as this is my first public pull request! I will get to this tomorrow morning as soon as possible 👍

2024-11-18 16:34 UTC, Alvin-Fung commented on icons/lime.svg
@uncenter I have just committed the changes needed, please let me know if there are any further issues!

2024-11-18 16:47 UTC, uncenter requested changes
Please make sure to fully read the contributing instructions, it looks like you still skipped some steps.

2024-11-21 12:29 UTC, Alvin-Fung commented on _data/simple-icons.json
> +}
Yeahh that is my bad, I have VS Code set so that it auto formats upon save, that has been changed so this issue should not come up again.

2024-11-21 12:29 UTC, Alvin-Fung commented on icons/lime.svg
> +<svg role="img" viewBox="0 0 2937 4380" xmlns="http://www.w3.org/2000/svg"><path d="M790.383 3874.27H622.485v494.97h167.898zm-605.631 81.13c0-8.25.524-462.09.582-543.97H17.436c0 82.58.058 544.14.058
Thank you for the help!  I will be looking over the documentation before I push another commit.

2025-05-15 14:30 UTC, PeterShaggyNoble requested changes
From the [GitHub preview](https://raw.githubusercontent.com/simple-icons/simple-icons/7e369cf9477662c2c1f916c2143cbe52be192f43/icons/lime.svg), it looks like this has been squashed and cropped in an attempt to fit it to the canvas.

When resizing an icon, you should lock the dimensions relative to each other in your editor, change the largest of the 2 to `24` and then centre the result on the canvas.

2025-06-04 11:21 UTC, PeterShaggyNoble commented
Closing due to inactivity.

2025-06-04 11:21 UTC, closed without merging