Add CSS icon
simple-icons/simple-icons pull request #12134
Opened 2024-11-13 21:11 UTC by LitoMore

![](https://github.com/user-attachments/assets/f0fd6af8-73c4-433b-8450-dfe06d30f993)

**Popularity metric:** Popular enough no doubt

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

I'm adding this as a new icon. The `CSS3` in our collection can be removed from another PR.

Related:

- https://github.com/CSS-Next/css-next/issues/105
- https://github.com/CSS-Next/logo.css/issues/23

2024-11-16 00:17 UTC, uncenter commented
There were some minor but adjustments nonetheless made to the "CSS" lettering yesterday after you made this: https://github.com/CSS-Next/logo.css/commit/9e25cf1ea59f60d0601253a71c23c36c7db4819e. Would you mind updating to the latest version of the source?

2024-11-16 00:57 UTC, LitoMore commented
@uncenter Updated.

2024-11-16 01:39 UTC, uncenter requested changes

2024-11-16 01:39 UTC, uncenter commented on icons/css.svg
Seeing differences in the lettering still.
![CleanShot 2024-11-15 at 20 38 41](https://github.com/user-attachments/assets/a55c3a17-d0b0-4c2b-ac16-b3975b524bef)

2024-11-16 01:46 UTC, LitoMore commented on icons/css.svg
I'm using the `css.svg` one. Which one did you use?

2024-11-16 01:55 UTC, uncenter commented on icons/css.svg
The one linked as source. Went to the link, clicked download, opened your version of the SVG, added in the downloaded SVG. Are you sure you have updated the source SVG file on your end?

2024-11-21 07:21 UTC, PratyushJayachandran commented on _data/simple-icons.json
> +            "source": "https://github.com/CSS-Next/logo.css/blob/4e5bae2d287e5523dc30cbdd8d9f4885b307adc7/css.svg",
```suggestion
            "source": "https://github.com/CSS-Next/logo.css/blob/bacc20878227204b283c68a6b935f8279e06b0cd/css.svg",
```
Source changed. Attaching the wire frame of the comparison as a screenshot.
![image](https://github.com/user-attachments/assets/7707099c-0931-469a-925f-54846638774b)

2024-11-21 12:19 UTC, uncenter commented
Might want to just let this one set for a minute until they stop making frequent updates to it 😅

2024-11-21 12:31 UTC, LitoMore commented
We can update it anytime. Don't be blocked by them.

2024-11-21 12:46 UTC, uncenter commented
> This is also annoying for me every time I update this PR from their change.

Right, so I'm saying maybe we can take a pause for a bit and just let any other changes accumulate instead of repeating this 4 more times. I don't want to merge this and have an update PR tomorrow.

2024-12-21 11:37 UTC, PratyushJayachandran approved these changes

2024-12-21 12:47 UTC, merged