add ODIN PROGRAMMING LANGUAGE icon
simple-icons/simple-icons pull request #12146
Opened 2024-11-17 12:22 UTC by Anonav0

![odinprogramminglanguage](https://github.com/user-attachments/assets/7d2bb6d2-9410-40d6-945f-7fc321c3573d)

**Issue:** closes #12133

**Popularity metric:** Github stars : 7k

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

Odin is a general-purpose programming language with distinct typing, built for high performance, modern systems, and built-in data-oriented data types. The Odin Programming Language, the C alternative for the joy of programming.

2024-11-17 17:15 UTC, uncenter requested changes

2024-11-17 17:15 UTC, uncenter commented on _data/simple-icons.json
Please don't change any other formatting in this file.

2024-11-18 05:35 UTC, Anonav0 commented on _data/simple-icons.json
So will this get merged?

2024-11-18 05:41 UTC, uncenter commented on _data/simple-icons.json
You need to revert the formatting diff please.

2024-11-18 05:57 UTC, Anonav0 commented on _data/simple-icons.json
Understood where's the problem at. Could you tell me how can solve this re formatting issue? Should I disable Perttier and try again? Sorry for bothering this much.

2024-11-18 06:12 UTC, Anonav0 commented on _data/simple-icons.json
I updated the file. and made a new commit to it. Should I close this PR and create a new one with all the necessary changes?

2024-11-18 06:34 UTC, uncenter commented on _data/simple-icons.json
No need for a new PR, just push the commit with the changes to this branch.

2024-11-18 06:56 UTC, Anonav0 commented on _data/simple-icons.json
Done!

2024-11-18 06:57 UTC, uncenter commented on _data/simple-icons.json
Great thank you!

2024-11-18 17:15 UTC, uncenter requested changes
Actually, sorry for the hassle - let's rename the icon to "Odin", which will mean moving the `icons/odinprogramminglanguage.svg` file to `icons/odin.svg`, and updating the `<title>` element inside the SVG.

2024-11-19 06:17 UTC, Anonav0 commented
Alright

2024-11-20 05:56 UTC, Anonav0 commented
Made the changes.

2024-11-20 15:24 UTC, uncenter requested changes

2024-11-20 15:24 UTC, uncenter commented on _data/simple-icons.json
> +            "hex": "1E5085",
```suggestion
            "hex": "3882D2",
```
My apologies, I actually think the hex code should be this based on everything except the header of https://odin-lang.org/, and all the colors on https://pkg.odin-lang.org/.

2024-11-20 15:35 UTC, merged