Add AVM icon
simple-icons/simple-icons pull request #12140
Opened 2024-11-14 20:40 UTC by DerBraky

![Untitled](https://github.com/user-attachments/assets/20b50381-7206-4e47-a591-7ad058a03702)

**Issue:** closes #7992

**Popularity metric:**
- Similarweb Global Rank: [12,897](https://www.similarweb.com/website/avm.de) 

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

Icon was extracted from PDF: https://business.avm.de/fileadmin/user_upload/Content/Global/Gestaltungsrichtlinien_EN.pdf

2024-11-14 23:01 UTC, uncenter commented
There are logos in EPS format on https://en.avm.de/about-avm/press/press-media/?tx_solr%5Bfilter%5D%5B0%5D=topic:29, fwiw. Not sure how the process for extracting images from PDFs work but it might be more accurate or generally be a better source for future reference.

2024-11-14 23:03 UTC, uncenter commented
I would go with their "AVM blue" color instead of "AVM red", they use the blue shade almost everywhere.

2024-11-15 18:38 UTC, uncenter commented
![CleanShot 2024-11-15 at 13 37 39](https://github.com/user-attachments/assets/3e320f84-cd71-4e6a-99cd-e5c5debd3461)
![CleanShot 2024-11-15 at 13 38 09](https://github.com/user-attachments/assets/0c3c47b3-2308-4053-b9ae-ca19f9377c28)
![CleanShot 2024-11-15 at 13 38 28](https://github.com/user-attachments/assets/5d886d71-77f5-4c5e-9de3-08f1c0384225)

Fritz! should stay red, but this seems like it should be blue.

2025-05-26 13:33 UTC, PeterShaggyNoble requested changes
SVG lines up perfectly with the EPS uncenter found 👍🏻 And I agree with you on the choice of colour, @DerBraky.

Before merging, though, could you update the `source` to https://en.fritz.com/about-avm/press/press-media/, please, and the `guidelines` to a page on their site that links to that PDF?

2025-06-02 19:31 UTC, DerBraky commented
@PeterShaggyNoble I only found a page that links to the guideline PDF [in German](https://business.avm.de/de/data/allgemeine-nutzungsbedingungen-business-portal/) (→ https://business.avm.de/fileadmin/user_upload/Content/DE/Sonstiges/Gestaltungsrichtlinien.pdf), not in English. Therefore, I only updated the source URL for now.

2025-06-04 19:41 UTC, PeterShaggyNoble commented
That German page is perfectly fine, @DerBraky; we're a multilingual project 🙂

2025-06-11 15:35 UTC, PeterShaggyNoble approved these changes

2025-06-11 15:37 UTC, merged