add Mailfence icon
simple-icons/simple-icons pull request #12163
Opened 2024-11-21 07:22 UTC by Anonav0

![mailfence](https://github.com/user-attachments/assets/8b118e74-2d06-491e-87bc-53d40e928169)

**Issue:** closes #12159

**Popularity metric:** Similarweb Global Rank: [73,723](https://www.similarweb.com/website/mailfence.com/)

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

#### Official Resources for Icon and Color

* SVG: https://mailfence.com/en/press.jsp (Brand Guidelines)
* Color: #2070b8, from Brand Guidelines

2024-11-30 14:46 UTC, mondeja requested changes
Please, maintain the same aspect ratio than the original:

![image](https://github.com/user-attachments/assets/dc59d29e-152a-4840-8676-e37b90c94953)

You need to lock aspect ratio when resizing

![image](https://github.com/user-attachments/assets/0f44e3ba-7f19-4541-9a6a-bbf59da60791)

2024-12-02 06:50 UTC, Anonav0 commented
Thanks for the little guide. I tried to fix the proportion. Let me know if any other changes is needed or not.

2024-12-17 14:16 UTC, mondeja requested changes
As you can see in the next image, there is a line that cuts the geometry vertically.

![image](https://github.com/user-attachments/assets/ea3526a5-6229-4dc4-ab49-78515dfa26fa)

Please, could you apply an Union to the path? In Inkscape you can see at:

![image](https://github.com/user-attachments/assets/00754fab-1eda-48fd-973f-44a964a76d27)

2025-05-16 15:04 UTC, PeterShaggyNoble commented
Closing due to inactivity. Let us know if you'd like to continue working on this one, @Anonav0, and we'll reopen the PR for you.

2025-05-16 15:04 UTC, closed without merging