Added OCLC icon
simple-icons/simple-icons pull request #12279
Opened 2024-12-04 15:44 UTC by timmy471

![oclc](https://github.com/user-attachments/assets/003215d1-b339-4c5d-9fd1-2afa1f5d78d6)

**Issue:** closes #12183

**Popularity metric:** 3,737

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

2024-12-07 18:52 UTC, LitoMore requested changes
I can see some differences. Please don't stretch the icon while resizing.

![](https://github.com/user-attachments/assets/b7ba21bb-cacb-4408-a509-52c3e33c68fa)

2024-12-11 14:27 UTC, timmy471 commented
@LitoMore update the Icon, please review

2024-12-11 14:34 UTC, LitoMore requested changes

2024-12-11 14:34 UTC, LitoMore commented on _data/simple-icons.json
> +}
Please don't edit other lines. Can you revert this change?

2024-12-11 16:46 UTC, LitoMore commented on _data/simple-icons.json
> +}
I just updated this for you.

2024-12-11 18:48 UTC, merged