Add Ultralytics icon
simple-icons/simple-icons pull request #12330
Opened 2024-12-11 15:55 UTC by timmy471

![simpleicons (4)](https://github.com/user-attachments/assets/f0459335-a673-4825-9ff7-9bb0153fe0ea)

**Issue:** closes #12280

**Popularity metric:** 35,194

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

2024-12-12 09:09 UTC, adamrusted commented on _data/simple-icons.json
> +}
Please do not remove the newline at the end of this file

2024-12-17 11:40 UTC, adamrusted requested changes
Spotting a slight difference in the circle, which may just be a precision issue.
![image](https://github.com/user-attachments/assets/08d312a6-aa10-4afc-8b51-3564c41f1d17)

(Homepage SVG in red, PR in black)

Would you mind taking another look please @timmy471?

2024-12-31 10:42 UTC, timmy471 commented
Do you mind taking another look please?

2024-12-31 11:38 UTC, adamrusted commented
See https://github.com/simple-icons/simple-icons/pull/12457#issuecomment-2566373995 - we should probably reach out to the brand for permission before merging.

2025-01-02 12:00 UTC, timmy471 commented
@adamrusted Permission granted
<img width="1105" alt="Screenshot 2025-01-02 at 12 58 17" src="https://github.com/user-attachments/assets/743c93ce-82d6-454e-ac58-f4d4b941b7bc" />

2025-01-13 08:20 UTC, timmy471 commented
Hi @adamrusted, checking in again

2025-01-13 08:38 UTC, adamrusted commented
@timmy471 please don't ping maintainers - we'll review this when someone is available.

2025-01-14 14:31 UTC, glenn-jocher commented
Looks great guys! Thanks for submitting this and let us know if you need any assistance.

Glenn Jocher
Ultralytics

2025-01-15 08:51 UTC, LitoMore approved these changes
@timmy471 LGTM. Thanks for contributing.

2025-01-15 08:53 UTC, merged