Add Namelix icon
simple-icons/simple-icons pull request #12357
Opened 2024-12-15 09:25 UTC by yeetengang

![namelix](https://github.com/user-attachments/assets/295c401a-3273-4c73-b16d-33299c0b2fc4)

**Issue:** closes #12259 

**Popularity metric:**
43,255
https://similarweb.com/website/namelix.com

### Checklist

- [ ] I updated the JSON data in `_data/simple-icons.json`
- [ ] I optimized the icon with SVGO or SVGOMG
- [ ] The SVG `viewbox` is `0 0 24 24`

2024-12-16 13:13 UTC, adamrusted requested changes
Thanks for your first contributions @yeetengang - couple of issues showing up in the linters.

Your SVG does not have the necessary 'role' attribute, or a 'title'. You need both of those for the checks to pass.

2024-12-16 14:28 UTC, yeetengang commented
> Thanks for your first contributions @yeetengang - couple of issues showing up in the linters.
> 
> Your SVG does not have the necessary 'role' attribute, or a 'title'. You need both of those for the checks to pass.

Thanks for the kind review! Added title to the svg file.

2024-12-17 11:28 UTC, adamrusted requested changes
Hey @yeetengang - looks as though it's still failing because you've not added the 'role' attribute to the SVG. Take a look at some of the other icons in the library to see what should be where.

2025-05-16 15:02 UTC, PeterShaggyNoble commented
Are you still working on this one, @yeetengang?

I wonder could we get away with using _just_ the "n", as they do in their favicon. I know I'm always one to say we should never take a favicon at face value as a reflection of the branding, but I do _hate_ using wordmarks as icons so very, very much! What do you think, @simple-icons/maintainers?

2025-05-30 11:47 UTC, PeterShaggyNoble commented
Closing due to lack of activity.

2025-05-30 11:47 UTC, closed without merging