Update multiple broken source/guideline links
simple-icons/simple-icons pull request #12436
Opened 2024-12-24 07:39 UTC by achoo-o

Contributes to https://github.com/simple-icons/simple-icons/issues/11901

Checked most new links against previous link assets where available (marked as CPNR/Check probably not required), but would probably benefit with an integrity check against current files if somebody could lend a hand (I'm not confident in this area).

Notes
---
Link updates:
* **TUI** - CPNR source link is the original (now defunct) link's external site to download logo details. Second link's github links to .se ver of Tui Group
* **Groupon** - CPNR redirect link generated from prev. link used
* **SlideShare**
* **SmugMug** - CPNR redirect link generated from prev. link used
* **Qi**
* **Equinix** Metal
* **SCNF**
* **Fujitsu** - CPNR their own internal logo link doesn't work; fujitsu's official archived ver. applied (believe it matches prev. link asset)
* **Vitess**
* **Deviantart** - wikimedia .png ver added for downloadable brand asset. svg ver is user-made, and downloadable brand assets contain official .eps ver
* **Wolfram** - CPNR links fixed; missing end character "/"
* **Litecoin** - CPNR new dropbox files match prev link's files
* **Wattpad**

2025-01-02 16:36 UTC, LitoMore commented
Have you confirmed that those links have source files that can be used as references?

When the source changes, you should also check whether the new source files are consistent with the current icons.

Here is https://github.com/simple-icons/simple-icons/discussions/9351 so that you can check the difference locally.

2025-01-16 23:56 UTC, LitoMore commented
@achoo-o bump

2025-01-17 01:49 UTC, achoo-o commented
Sorry for the delayed response. I just checked using Inkscape and all the logos with new links do overlay, _except_ SlideShare. I'll remove it now.

2025-02-05 18:16 UTC, LitoMore requested changes

2025-02-05 18:16 UTC, LitoMore commented on _data/simple-icons.json
> +		"source": "https://commons.wikimedia.org/wiki/File:DeviantArt_mark_green.png"
I don't think the PNG asset it acceptable since they have an SVG on their homepage title.

2025-02-05 18:16 UTC, LitoMore commented on _data/simple-icons.json
> +		"source": "https://vitess.io"
The Vitess icon has changed. Please check that all icons are updated according to your new URL.

2025-02-08 10:22 UTC, achoo-o commented on _data/simple-icons.json
> +		"source": "https://commons.wikimedia.org/wiki/File:DeviantArt_mark_green.png"
Sorry could you clarify "homepage title"? Are you referring to the user-made SVG version on Wikimedia (https://commons.wikimedia.org/wiki/File:DeviantArt_mark_green.svg) or a different site? 

I originally used the Wikimedia .png version since it has the original brand asset pack linked, but it is an EPS file type.

2025-02-08 11:50 UTC, LitoMore commented on _data/simple-icons.json
> +		"source": "https://commons.wikimedia.org/wiki/File:DeviantArt_mark_green.png"
Ah, I mean the homepage header. I mis-typed the word.

2025-02-22 17:12 UTC, LitoMore commented
bump @achoo-o

2025-03-02 04:41 UTC, achoo-o commented on _data/simple-icons.json
> +		"source": "https://commons.wikimedia.org/wiki/File:DeviantArt_mark_green.png"
Sorry I still don't understand. To my understanding, I should use https://www.deviantart.com/? If not, could you please rephrase it for me?

2025-03-02 15:30 UTC, LitoMore commented on _data/simple-icons.json
> +		"source": "https://commons.wikimedia.org/wiki/File:DeviantArt_mark_green.png"
Yes. Use the SVG resource from deviantart.com. You should also check whether the new source files are consistent with the current icons.

![](https://github.com/user-attachments/assets/7cca1782-b68f-4522-86ff-b9d7c3954fe3)

2025-03-02 22:57 UTC, achoo-o commented on _data/simple-icons.json
> +		"source": "https://commons.wikimedia.org/wiki/File:DeviantArt_mark_green.png"
Oh thank you for the screenshot, I didn't think to check for images like that. I'll review the icons again and update today.

2025-03-06 07:04 UTC, LitoMore commented on _data/simple-icons.json
> +		"source": "https://commons.wikimedia.org/wiki/File:DeviantArt_mark_green.png"
See this below:

![](https://github.com/user-attachments/assets/27f1a798-1fa8-4f42-abea-5fe9b1d628fb)

I can see some differences between the SVG source on the homepage header and the resource in our codebase. In the meantime, you should update the SVG along with the URL update.

2025-03-11 13:11 UTC, achoo-o commented on _data/simple-icons.json
> +		"source": "https://vitess.io"
Will retry this logo update

2025-03-12 05:31 UTC, achoo-o commented on _data/simple-icons.json
> +		"source": "https://vitess.io"
@LitoMore I can't find an SVG version of the logo and I don't think I can make my recreation accurately enough since I'm new to SVG creation. Do I leave the link reverted ?

2025-04-14 13:54 UTC, closed without merging

2025-04-14 14:09 UTC, mondeja commented
This PR has been closed on #13050 because we don't allow to update multiple brands in one pull request anymore. Please, open different pull requests to update each brand separately. Sorry for the inconvenience and thanks for your contribution to Simple Icons.