Add Vinted icon
simple-icons/simple-icons pull request #12444
Opened 2024-12-27 20:19 UTC by AathifZahir

![vinted (1)](https://github.com/user-attachments/assets/6b3c2b0e-24ac-4d13-ba38-08c74f2ea17b)

**Issue:** closes #12268

**Popularity metric:** 11,400

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

Adding SVG for Vinted after fixing problems in last pull request.

2024-12-28 07:22 UTC, LitoMore requested changes

2024-12-28 07:22 UTC, LitoMore commented on _data/simple-icons.json
> +        "source": "https://vinted.com"
We're using tabs for indentation. Can you fix it?

2024-12-31 13:29 UTC, AlexHedley commented
Related: https://github.com/simple-icons/simple-icons/pull/12282

2024-12-31 14:11 UTC, LitoMore commented
I'm sorry I didn't notice there is already one for this icon.

I'm going to close this one, otherwise it will be unfair to others.

Feel free to contribute some other icons that didn't have a working PR.

2024-12-31 14:11 UTC, closed without merging