Add LangGraph icon
simple-icons/simple-icons pull request #12452
Opened 2024-12-28 18:39 UTC by syntaxticsugr

![image](https://github.com/user-attachments/assets/84fbcd80-35ac-4ba5-b93e-722b5c750c8d)

**Popularity metric:**
7.6K Stars on GitHub. See https://github.com/langchain-ai/langgraph

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

Sourced the SVG from LangGraph official website header. See https://www.langchain.com/langgraph

2025-01-12 22:45 UTC, LitoMore requested changes
I can see some differences. It looks the precision you used is 2 rather than 3. Please optimize the SVG with at least precision 3.

![](https://github.com/user-attachments/assets/8a2834d9-5aa5-462f-afce-1d3980f5d599)

2025-01-13 05:09 UTC, syntaxticsugr commented
[langgraph-p8](https://github.com/user-attachments/assets/1e1df141-44c9-4f41-9efe-a40fd5310562)
This is the file i am using as reference, it is the svg from header resiged to 24x24 and precision set to 8.

[langgraph-svgomg-p3](https://github.com/user-attachments/assets/2c96f65b-eaba-41da-b968-32d64ef2e23d)
As suggested this is the svg with precision 3 optimised with [svgomg](https://svgomg.net/).

And this is the difference (marked in red)
![image](https://github.com/user-attachments/assets/791c66e5-d888-40b1-b930-0a31c75ef986)

If it is acceptable i will commit the changes, or retry :)

2025-01-13 05:23 UTC, LitoMore commented
The [langgraph-svgomg-p3](https://github.com/user-attachments/assets/2c96f65b-eaba-41da-b968-32d64ef2e23d) looks good.

2025-01-16 23:50 UTC, LitoMore approved these changes

2025-01-16 23:51 UTC, merged