add crewai icon
simple-icons/simple-icons pull request #12456
Opened 2024-12-28 20:59 UTC by syntaxticsugr

![image](https://github.com/user-attachments/assets/a560cd3b-6144-4bb2-827e-3f55d86d7921)

**Issue:** closes #12181

**Popularity metric:**
23K Stars on GitHub. See https://github.com/crewAIInc/crewAI

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

Sourced the SVG from CrewAI GitHub. See https://github.com/crewAIInc/crewAI
Chosen color hex `FF5A50` is the most prominent color of the icon.

2024-12-30 20:09 UTC, LitoMore commented
Duplicate of #12332.

2025-01-11 10:47 UTC, syntaxticsugr commented
> Duplicate of #12332.

Sir, the mentioned PR is now closed by it's author. So can this be reconsidered for merge.

2025-01-12 22:26 UTC, LitoMore requested changes
@syntaxticsugr I can see some differences, can use theck this?

<img width="793" alt="image" src="https://github.com/user-attachments/assets/ed6087aa-820c-4a4f-a49c-b46093e8b43a" />

2025-01-13 06:17 UTC, syntaxticsugr commented
[crewai-svgomg-p3](https://github.com/user-attachments/assets/2a2272ea-3fc9-430b-8d60-58a827cc3e38)
Check this sir.

2025-01-16 23:55 UTC, LitoMore commented
The [crewai-svgomg-p3](https://github.com/user-attachments/assets/2a2272ea-3fc9-430b-8d60-58a827cc3e38) looks good.

2025-01-18 15:30 UTC, LitoMore approved these changes

2025-01-18 15:31 UTC, merged