Add Fyle icon
simple-icons/simple-icons pull request #12465
Opened 2024-12-29 10:41 UTC by shubham-fyle

![fyle](https://github.com/user-attachments/assets/84be35a7-9412-41df-87ba-2cd461365453)

**Issue:** closes #12398 

**Popularity metric: 287,267**
https://www.similarweb.com/website/fylehq.com

### Checklist

- [ ] I updated the JSON data in `_data/simple-icons.json`
- [ ] I optimized the icon with SVGO or SVGOMG
- [ ] The SVG `viewbox` is `0 0 24 24`

### Description

2024-12-29 17:39 UTC, LitoMore commented
Could you fix those errors?

You can run `npm run lint` on your local to see those errors.

2024-12-29 17:39 UTC, LitoMore requested changes
<!---->

2025-01-07 13:01 UTC, shubham-fyle commented
Hey @LitoMore, can you please check this out now? I fixed all the lint errors

2025-01-07 13:48 UTC, LitoMore commented
Hi @shubham-fyle, please don't ping us. We maintain this project in our free time. I will review your PRs when we have time.

Also, the `update branch` is unnecessary. We will help you update the branch after confirming that it can be merged.

I appreciate your patience.

2025-01-09 18:12 UTC, LitoMore requested changes

2025-01-09 18:12 UTC, LitoMore commented on _data/simple-icons.json
> +		"hex": "FF3366",
```suggestion
		"hex": "FF2E63",
```

According to their source file on the homepage header, the color should be `#FF2E63`.

2025-01-10 06:56 UTC, LitoMore approved these changes

2025-01-10 06:58 UTC, merged