Add Xilinx
simple-icons/simple-icons pull request #3424
Opened 2020-08-05 02:14 UTC by sharmavins23

This is a part of my original request for HDL oriented icons. This adds the branded Xilinx icon, creators of Xilinx Vivado (one of the more popular SystemVerilog and Verilog IDEs.)

![xilinx](https://user-images.githubusercontent.com/53274232/89364025-953a6e00-d69f-11ea-8f1b-13cb9404dab1.png)

**Issue:** #3422 
**Alexa rank:** 38,837

  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

The color was picked based on the two major colors that the logo originally had. This was the main color (not the shadow color.)
I vectorized the logo with Inkscape.

2020-08-06 10:49 UTC, NovaGL commented
Thanks for this. Where did you get the logo from or did you convert it from a PNG yourself.

Why did you choose that color? I would have gone with `#ec1c24` myself

2020-08-06 20:05 UTC, sharmavins23 commented
I went ahead and converted from a PNG. The color came from a screen select of that PNG's main color as well.

2020-08-07 02:03 UTC, NovaGL commented
@sharmavins23 

I managed to get a vector version of this logo and the color choices available are 
`#ed1c29` or `#b30838`

Here is the path I used
`M0.3,6l5.2-6h7.7L8,6 M0.3,6l5.2,6h7.7L8,6 M8,18l5.2-6H5.6l-5.2,6 M0.3,18l5.2,6h7.7L8,18 M13.3,0l5.2,6 l5.2-6 M23.7,24l-5.2-6l-5.2,6`

It can be found in this file
https://www.xilinx.com/support/documentation/user_guides/ug116.pdf

2020-08-07 21:43 UTC, sharmavins23 commented
@NovaGL added your changes, awaiting CI and approval

2021-01-01 13:59 UTC, adamrusted requested changes

2021-01-01 13:59 UTC, adamrusted commented on icons/xilinx.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Xilinx icon</title><path d="M23.7,0l-5.2,6l-5.2-6H23.7z M18.5,18l-5.2,6h10.4L18.5,18z M13.3,12L8,6l5.2-6H5.6L0.3,6l5.2,6l
Hi @sharmavins23, thanks for your work on this!
I'm still seeing some slight differences between your version (red) and source (black). They have an SVG in the header of their website, which is what I've used for my source - may be worth rebuilding to that?
![image](https://user-images.githubusercontent.com/1830867/103439919-1c811300-4c39-11eb-9e6d-858eb5e505ab.png)

I've included my SVG below, which passes the linter, should you want to use that one:
```svg
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Xilinx icon</title><path d="M8 18l5.241 6H5.586L.345 18l5.241-6L.345 6l5.241-6h7.655L8 6l5.241 6L8 18zM23.655 0H13.241l5.241 6 5.173-6zM13.241 24h10.414l-5.172-6-5.242 6z"/></svg>
```

I can also see a statement regarding their buyout by AMD - @simple-icons/maintainers should we still look to include this, on the assumption that AMD keep the brand going?

2021-01-04 10:34 UTC, PeterShaggyNoble commented
Welcome to Simple Icons, @sharmavins23 and thanks for the contribution 🙂

Further to the comments already made by the rest of the team above, I think we should also consider `#171c2d` for the brand colour as that was my first instinct on visiting their website.

@adamrusted, I think, in the absence of any statement to the contrary from either company, that we should work under the assumption that Xilink will continue to exist as a separate brand.

2021-01-04 12:39 UTC, adamrusted commented
@PeterShaggyNoble looking through the publications [here](https://www.xilinx.com/news/media-kits.html) and the favicon of the website, I'd suggest the red is more synonymous with the brand, especially when all their hardware is bright red too. Happy for another @simple-icons/maintainers to say otherwise though 😅

2021-01-06 13:31 UTC, adamrusted commented
![xilinx](https://user-images.githubusercontent.com/1830867/103773701-6005c380-5023-11eb-82b8-83b17c179b2b.png)

@simple-icons/maintainers due to lack of response by @sharmavins23, I've merged the newer path in that I'd suggested above, and pulled the hex value from the SVG on the homepage directly.

2021-01-06 13:48 UTC, fbernhart commented
@adamrusted Perfect! @sharmavins23 thanks as well for the initial work on this icon! 🏆

2021-01-06 13:50 UTC, merged