Add Rainmeter
simple-icons/simple-icons pull request #3554
Opened 2020-09-11 18:52 UTC by creepertron95

![rainmeter](https://user-images.githubusercontent.com/53346722/92961966-cb54d580-f435-11ea-84f3-4708a3752553.png)

**Issue:** Closes #3552
**Alexa rank:** [42,670](https://www.alexa.com/siteinfo/rainmeter.net)
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
 The hex value is picked from their blue logo from the branding sources. Icon is extracted from their original svg logo.

2020-09-25 15:01 UTC, runxel requested changes
The source remains unclear, so yours looks pretty off rn.
![rm](https://user-images.githubusercontent.com/2277182/94282897-aa6da380-ff50-11ea-8217-6637c000bc87.png)

I did my comparison to the [logo_blue.ai](https://github.com/rainmeter/rainmeter-www/blob/867fd905fda8d1b1083730adcb7f49f1775cb5b0/source/img/logo_blue.ai).

2020-09-25 15:17 UTC, creepertron95 commented
@runxel I used it's svg file in the source. (https://github.com/rainmeter/rainmeter-www/blob/master/source/img/logo_nav.svg)

The color is from (https://github.com/rainmeter/rainmeter-www/blob/master/source/img/logo_blue.ai)

2020-09-25 15:28 UTC, runxel commented
Maybe use the AI file for everything, since this seems to be the source.
Also the color in the AI is in fact `#19519b`... not `#12509C`? 🤔 Checked it twice now.

2020-10-27 18:17 UTC, creepertron95 commented
The svg was successful in the lint. @runxel

2021-01-01 12:52 UTC, adamrusted requested changes

2021-01-01 12:52 UTC, adamrusted commented on icons/rainmeter.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Rainmeter icon</title><path d="M12 0l-.7 1.088S9.49 3.91 7.677 7.205c-.908 1.647-1.818 3.413-2.51 5.025-.692 1.613-1.191
I'm spotting some slight differences between your PR (red) and source - built from the .AI file (black).
![image](https://user-images.githubusercontent.com/1830867/103438877-ea1ee800-4c2f-11eb-9490-a473c9e96966.png)

Having generated the path from in Illustrator, I've been able to get it working with a precision of 3 - would you mind altering the path to this, and we can merge this PR?
```svg
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Rainmeter icon</title><path d="M12.7 1.088L12 0l-.7 1.088c-.751 1.168-7.342 11.525-7.342 15.366C3.958 20.615 7.565 24 12 24s8.042-3.385 8.042-7.546c0-3.84-6.591-14.197-7.342-15.366zM12 22.335c-3.516 0-6.377-2.638-6.377-5.881C5.623 13.908 9.732 6.756 12 3.1c2.268 3.656 6.377 10.809 6.377 13.355 0 3.242-2.861 5.88-6.377 5.88zm4.957-6.017c0 2.548-2.22 4.615-4.957 4.615-2.737 0-4.957-2.067-4.957-4.615 0-.163.021-.347.058-.549 0 0 1.306-2.616 4.847 0 2.999 2.215 4.95 0 4.95 0 .038.202.059.386.059.549z"/></svg>
```

2021-01-04 12:37 UTC, adamrusted commented
@simple-icons/maintainers - just pushed the rebuilt icon to this branch.

2021-01-04 16:07 UTC, fbernhart commented
@adamrusted LGTM 💧 

Thanks as well to @creepertron95 for the initial work on this icon. 🥇

2021-01-04 16:07 UTC, merged