Add Lospec
simple-icons/simple-icons pull request #3560
Opened 2020-09-13 02:17 UTC by creepertron95

![lospec](https://user-images.githubusercontent.com/53346722/93008691-1dcce980-f53d-11ea-8ce0-b1921a9d666f.png)

**Name:** Lospec
**Website:** https://lospec.com/
**Alexa rank:** [318,564](https://www.alexa.com/siteinfo/lospec.com)
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
 The hex value is the logo color from the branding page. The logo was from the branding page as svg format.

2020-09-25 15:11 UTC, runxel requested changes
Hi, @creepertron95!
Your icon is sooooo slightly off 😅 
![lospec](https://user-images.githubusercontent.com/2277182/94283965-07b62480-ff52-11ea-86cf-9f037dc7eeaa.png)

2020-09-25 15:19 UTC, creepertron95 commented
@runxel Well then. How can that be fixed? I used the original svgs from their branding page and rescaled them and kept the exact dimensions when scaling. Also, what should I do about the usage section of their branding page?

2020-09-25 15:25 UTC, runxel commented
Mhm, maybe one of us made an error while rescaling...?
OR, most possible it's a problem with the precision of SVGO. Try to up it first :)

2020-09-25 15:26 UTC, runxel commented
Regarding the brand guide:
Well... The usage is not in our hands, so the only other way I see would to not include it at all. Don't worry too much.

2020-09-26 20:13 UTC, runxel reviewed
Thanks for your work on this one, @creepertron95! 💯

2020-09-26 20:14 UTC, merged