Add RedwoodJS icon
simple-icons/simple-icons pull request #3624
Opened 2020-10-01 14:35 UTC by kalpeshT101

![redwoodjs](https://user-images.githubusercontent.com/36229969/94823173-32581f80-0421-11eb-95a5-fe6410e0b909.png)

**Issue:**#3618
**Alexa rank:**[439,565](https://www.alexa.com/siteinfo/redwoodjs.com)
  

### Checklist

  - [x]  I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

2020-11-30 18:22 UTC, service-paradis requested changes
Thanks for your contribution 😃 
The logo looks different from the original found at https://redwoodjs.com/logos
![image](https://user-images.githubusercontent.com/12817388/100648530-08cb4f80-330f-11eb-9b5c-ceba79fa6cc1.png)
Can you take a look at it?

2020-11-30 18:22 UTC, service-paradis commented on _data/simple-icons.json
> +            "hex": "BC4424",
The color used in the SVG is `#BF4722`. Looks to be the primary color used in the website also. Where did you take this one?

2020-11-30 18:22 UTC, service-paradis commented on _data/simple-icons.json
> +            "source": "https://redwoodjs.com/"
Can you change the source for https://redwoodjs.com/logos?

2021-01-01 14:18 UTC, adamrusted commented
![redwoodjs](https://user-images.githubusercontent.com/1830867/103440289-193b5680-4c3c-11eb-8e1b-dc8414b5fab3.png)

Changed source, updated color and rebuilt from source - as @service-paradis' comments.

2021-01-02 18:53 UTC, service-paradis approved these changes
LGTM 🔴 🌳 🎉 
Thanks @kalpeshT101 and @adamrusted!

2021-01-02 18:55 UTC, merged