Add Veepee icon
simple-icons/simple-icons pull request #3626
Opened 2020-10-01 15:08 UTC by KarthikNayak024

**Issue:** #3462 
**Alexa rank:** 6,136 
  

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json`
  - [ ] I optimized the icon with SVGO or SVGOMG
  - [ ] The SVG `viewbox` is `0 0 24 24`

### Description

2020-11-30 19:25 UTC, service-paradis requested changes
Thanks for your contribution 😃 
Maybe they updated their logo, but it looks different when I compared your version with the one found in the website header:
![image](https://user-images.githubusercontent.com/12817388/100654460-d3772f80-3317-11eb-9bac-9024963af40d.png)
Can you take a look?

2020-11-30 19:25 UTC, service-paradis commented on _data/simple-icons.json
> +        },
I think you have changed the color at the wrong place in `simple-icons.json`.
Also, the color used in the logo and in the website is `#EC008C` (https://static.preprod.vente-privee.com/vp5/_web/site/vp/_common/img/00_int_door_logoBlack.svg).

2021-01-01 14:11 UTC, adamrusted commented
![veepee](https://user-images.githubusercontent.com/1830867/103440155-31f73c80-4c3b-11eb-8168-bb4884d58cc3.png)

Rebuilt from source using @service-paradis' suggestions.

2021-01-02 18:49 UTC, service-paradis commented
LGTM 🦋 🎉 
Thanks @KarthikNayak024 and @adamrusted!

2021-01-02 18:49 UTC, merged