Add TransferWise icon
simple-icons/simple-icons pull request #3637
Opened 2020-10-01 21:01 UTC by edensg

**Issue:** #3632 
**Alexa rank:** 1140
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Vector was extracted from the header at https://wetransfer.com, and hex value was extracted from the same vector (used in the logo).

2020-11-29 19:42 UTC, service-paradis commented
Thanks for your contribution.
Looking good 💯 
I would use https://brand.transferwise.com/logo as the source.
I would also change the color for `00b9ff` according to https://brand.transferwise.com/colour-palette

2020-11-29 21:36 UTC, edensg commented
Updated preview image:

![transferwise(1)](https://user-images.githubusercontent.com/5727389/100554176-ed097000-3260-11eb-9bde-1e170bb46afb.png)

2020-11-30 13:23 UTC, service-paradis requested changes

2020-11-30 13:23 UTC, service-paradis commented on _data/simple-icons.json
> +            "source": "https://transferwise.com"
Good job, thanks!
One last thing would be to change the source to https://brand.transferwise.com/logo and it will be ready to merge :)

2020-12-01 13:14 UTC, merged