Zoho
simple-icons/simple-icons pull request #3661
Opened 2020-10-06 21:43 UTC by d3ward

**Issue:** #3639 
**Alexa rank:** [215](https://www.alexa.com/siteinfo/zoho.com)
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Logo sourced from official website 
It was png so i manually vectorized from monochrome png version
Color sourced from the logo of first letter 'Z' which is a red tenue 

Preview
![zoho](https://user-images.githubusercontent.com/39910418/95261877-72594100-082b-11eb-8fab-6b1d2fb06034.png)

2020-11-29 19:28 UTC, service-paradis requested changes

2020-11-29 19:28 UTC, service-paradis commented on icons/zoho.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Zoho</title><path d="M8.283 15.193c-.74-.328-1.476-.663-2.208-1.007-.021-.02 1.912-4.483 1.982-4.576.004-.005.893.39 1.97
Hello
Thanks for the PR!
Also have a close look into our [CONTRIBUTING guidlines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and here to our standards. (the svg is not what the linter expects, thus the build is failing currently) (icon name and icon position)

2021-01-02 13:11 UTC, adamrusted commented
![zoho](https://user-images.githubusercontent.com/1830867/103458016-f2dcf000-4cfb-11eb-8a95-6585a9e9407e.png)

I've just rebuilt this from source with a gap of 0.35px between colours and blocks to make this look a bit clearer than the monochrome PNG shown on their site.

2021-01-04 04:47 UTC, fbernhart commented
LGTM! 👍🏼  Thanks @adamrusted and of course @d3ward for your work! 🏅

2021-01-04 04:48 UTC, merged