Correct PowerShell icon
simple-icons/simple-icons pull request #3804
Opened 2020-11-03 01:54 UTC by service-paradis

![image](https://user-images.githubusercontent.com/12817388/97937759-8cfcd800-1d4d-11eb-9b77-e35d517b6cf3.png)

**Issue:** #3169
**Alexa rank:**
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
- I took the already used SVG.
- I used Inkscape to fix size and center
- I used https://jakearchibald.github.io/svgomg/ to optimize the resulting SVG

2020-11-15 21:47 UTC, mondeja requested changes

2020-11-15 21:47 UTC, mondeja commented on .svglint-ignored.json
> -    "M6.815 15.128l4.704 2.715V12.41L6.813 9.696v5.433zM4.79 16.296l6.73 3.883V24L1.48 18.207V6.617l3.31 1.91v7.77zM12 6.146L7.297 8.864 12 11.58l4.705-2.717L12 6.147zM12 3.813l5.66 3.275 3.31-1.91L1
Fully corresponds to my version and looks good, but it seems that you've inserted another removal here.

2020-11-16 13:26 UTC, mondeja approved these changes
I finally merged with the marked removal because it's not getting conflicts :thinking: Thanks @service-paradis :+1:

2020-11-16 13:27 UTC, service-paradis commented
Looks like this was not removed as expected in the Nintendo Gamecube PR. The linter was removing it automatically.

2020-11-16 13:27 UTC, merged