Updated CloudBees
simple-icons/simple-icons pull request #4007
Opened 2020-11-20 16:03 UTC by fbernhart

![cloudbees](https://user-images.githubusercontent.com/70264417/99821441-54813a80-2b52-11eb-8834-702e1e0b5bcb.png)

**Issue:** #3169 
**Alexa rank:** -

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json` --> (wasn't necessary)
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I took the already used SVG.
I used Inkscape to fix size and center
I used https://jakearchibald.github.io/svgomg/ to optimize the resulting SVG

2020-12-21 22:37 UTC, adamrusted requested changes

2020-12-21 22:37 UTC, adamrusted commented on icons/cloudbees.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>CloudBees icon</title><path d="M3.5615 6.4196c0-1.203.732-2.284 1.884-2.805a3.516 3.516 0 013.5161.39l2.5241-2.3541a7.263
Any chance you can regenerate from source? Looks like the logo has changed.
Path below has been generated at 3 decimals...
```svg
M13.759 10.221zM24 16.97c0 3.73-3.093 6.747-6.904 6.747-3.812 0-6.908-3.017-6.908-6.747V6.979a3.215 3.215 0 00-.531-1.75c-.225-.352-.258-.239.065-.554l1.922-1.882a.358.358 0 01.029-.026c.416-.342.299-.351.649.054.923 1.156 1.437 2.664 1.437 4.158v3.242h-.001.001v.025-.025h3.337c3.811 0 6.904 3.02 6.904 6.749zm-3.565 0c0-1.745-1.405-3.158-3.167-3.246v.011h-3.509v3.22c0 1.803 1.495 3.279 3.337 3.279 1.842-.001 3.339-1.462 3.339-3.264zM3.549 7.05c0-1.804 1.488-3.27 3.319-3.27.735 0 1.378.188 1.929.565l2.511-2.472C10.059.812 8.579.283 6.869.283 3.081.283 0 3.32 0 7.05c0 3.732 3.081 6.767 6.869 6.767h2.429v-3.496H6.869c-1.831 0-3.32-1.467-3.32-3.271z
```

Red is PR, black is built from source.
![image](https://user-images.githubusercontent.com/1830867/102828601-ffe50f80-43dc-11eb-8d41-b0ba6395dafa.png)

2020-12-22 15:26 UTC, fbernhart commented
@adamrusted Fixed

2020-12-22 15:28 UTC, adamrusted approved these changes
Perfect! Thank You! 🤩

2020-12-22 15:29 UTC, merged