Updated EVRY
simple-icons/simple-icons pull request #4040
Opened 2020-11-20 17:17 UTC by fbernhart

![evry](https://user-images.githubusercontent.com/70264417/99829533-b21a8480-2b5c-11eb-95fd-118ba020ad7d.png)

**Issue:** #3169 
**Alexa rank:** -

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json` --> (wasn't necessary)
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I took the already used SVG.
I used Inkscape to fix size and center
I used https://jakearchibald.github.io/svgomg/ to optimize the resulting SVG

2020-12-22 13:30 UTC, adamrusted requested changes

2020-12-22 13:30 UTC, adamrusted commented on icons/evry.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>EVRY icon</title><path d="M.443 12.919c.102.255.113.426.072.692-.03.202-.068.404-.108.605-.035.174-.117.55.003.694.117.13
Looks like some differences between PR (red) and source (black) - would you mind rebuilding this one?
![image](https://user-images.githubusercontent.com/1830867/102893672-e46c1a00-4459-11eb-9095-ff7c3ea9a105.png)

2020-12-23 09:39 UTC, fbernhart commented
Seems like **EVRY** alone doesn't even exist anymore. They were bought by **Tieto** and the company is called **TietoEVRY** now. https://www.tietoevry.com/en/newsroom/all-news-and-releases/stock-exchange-releases/2019/12/merger-between-tieto-and-evry-completed--tietoevry-established/

They as well have a combined logo now, as can be seen [in the header here](https://www.tietoevry.com).


@simple-icons/maintainers how do we go about this one? Renaming a brand is a breaking change, right?

How about just updating the "EVRY" icon in this PR and then creating a new PR, marked as breaking change, to rename it?

2020-12-23 11:06 UTC, ericcornelissen commented
> @simple-icons/maintainers how do we go about this one? Renaming a brand is a breaking change, right?
> 
> How about just updating the "EVRY" icon in this PR and then creating a new PR, marked as breaking change, to rename it?

As renaming (=removing EVRY and adding TietoEVRY) is indeed a breaking change we cannot do that now. We could have both available for the duration of v4 and remove EVRY with [the v5 release](https://github.com/simple-icons/simple-icons/milestone/4), or could the rename only with the v5 release. Either are acceptable to me: having two icons for "one" brand is a bit weird, but having the Tieto-version available before v5 may help users switch before that.

2020-12-23 13:16 UTC, adamrusted commented
> but having the Tieto-version available before v5 may help users switch before that.

Agree with this, may be better for us to give users a decent run-up to the deprecation of the old icon.

2020-12-23 17:52 UTC, mondeja commented
Could you remove it using this pull and mark it as breaking change for the next v5 release @fbernhart?

2021-01-08 16:18 UTC, PeterShaggyNoble commented
@fbernhart, could you update the original post to clarify that this PR will remove the icon, please?

2021-05-24 09:08 UTC, PeterShaggyNoble approved these changes
Looks good to me 👍🏻 Once the conflicts have been resolved, this can be merged straight in.

2021-05-24 13:12 UTC, merged