Updated Genius
simple-icons/simple-icons pull request #4050
Opened 2020-11-20 22:03 UTC by fbernhart

![genius](https://user-images.githubusercontent.com/70264417/99854135-8dd29e00-2b84-11eb-952f-0066c4a6f40f.png)

**Issue:** #3169 
**Alexa rank:** -

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json` --> (wasn't necessary)
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I took the already used SVG.
I used Inkscape to fix size and center
I used https://jakearchibald.github.io/svgomg/ to optimize the resulting SVG

2020-12-22 21:58 UTC, adamrusted requested changes
It appears the link to the source is broken. Could you update to the [Genius website](), which includes the logo built into the header.

Might it also be worth re-orienting it so that it looks more like the 'G' shape? I'm not familiar with the brand, so not sure which method is preferred. @simple-icons/maintainers - any guidance here?

3 decimal path generated from header:
```svg
M22.678,2.361C22.678,2.361,22.678,2.164,22.678,2.361C21.104,0.787,19.333,0,17.169,0s-4.131,0.787-5.508,2.164 c-0.393,0.393-0.59,0.787-0.984,1.18v0.197c0,0.197,0.197,0.197,0.197,0.197c0.787-0.393,1.77-0.59,2.754-0.59 c2.164,0,4.328,0.984,5.705,2.361l3.148,0c0.197,0,0.197-0.197,0.197-0.197L22.678,2.361C22.874,2.361,22.678,2.361,22.678,2.361z M22.481,11.41l-2.951,0c-1.574,0-2.754-1.18-2.951-2.754c0.197,0,0-0.197,0-0.197c-0.59,0-1.18,0.393-1.574,0.787v0.393 c-1.18,3.541,0.197,4.721,1.77,4.721l2.164,0c0.197,0,0.197,0.197,0.197,0.197v0.787c0,0.197,0.197,0.197,0.197,0.197 c1.18-0.197,2.361-0.787,3.344-1.574v-2.361C22.874,11.607,22.678,11.41,22.481,11.41z M22.481,20.066 C22.481,20.066,22.284,20.066,22.481,20.066C22.284,20.066,22.284,20.066,22.481,20.066C22.284,20.066,22.284,20.066,22.481,20.066 c-1.574,0.59-3.148,0.984-4.918,0.984c-7.279,0-13.377-5.902-13.377-13.377c0-1.77,0.393-3.344,0.984-4.918 c0-0.197-0.197-0.197-0.393-0.197H4.579C2.415,4.918,1.235,7.869,1.235,11.41C1.235,18.492,6.94,24,13.825,24 c3.344,0,6.492-1.377,8.656-3.541v-0.197C22.678,20.262,22.481,20.066,22.481,20.066z
```

2020-12-23 10:59 UTC, ericcornelissen commented
I'm not terribly familiar with the brand either, but whenever I see just the "G" it is at a 90 degree angle. See for example the website favicon or the app icon in the Play Store or App store.

2020-12-23 13:10 UTC, adamrusted requested changes

2020-12-23 13:10 UTC, adamrusted commented on icons/genius.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Genius icon</title><path d="M12.8967 1.2348c-.36.001-.722.013-1.08.017-.218-.028-.371.225-.352.416-.035 1.012.023 2.0251-
Can this be reduced to 3 decimals at all? 😅

2020-12-23 18:36 UTC, fbernhart commented
@adamrusted Done

2020-12-23 18:41 UTC, adamrusted approved these changes
Amazing! Thanks @fbernhart 🎉

2020-12-23 18:41 UTC, merged