Updated ProtonMail
simple-icons/simple-icons pull request #4173
Opened 2020-11-29 23:31 UTC by fbernhart

![protonmail](https://user-images.githubusercontent.com/70264417/100556552-10511100-329b-11eb-90a8-e58dd8dfa7dd.png)

**Issue:** #3169 
**Alexa rank:** -

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json` --> (wasn't necessary)
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I took the already used SVG.
I used Inkscape to fix size and center
I used https://jakearchibald.github.io/svgomg/ to optimize the resulting SVG

2020-12-23 21:59 UTC, adamrusted requested changes

2020-12-23 21:59 UTC, adamrusted commented on icons/protonmail.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>ProtonMail icon</title><path d="M12 20.3518s-1.096-.108-1.9551-.705c-.86-.596-6.5804-4.6883-6.5804-4.6883v8.0984S3.5125 2
3 decimals would make this perfect! 😜

2020-12-26 00:12 UTC, fbernhart commented on icons/protonmail.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>ProtonMail icon</title><path d="M12 20.3518s-1.096-.108-1.9551-.705c-.86-.596-6.5804-4.6883-6.5804-4.6883v8.0984S3.5125 2
Fixed 🛠️

2020-12-26 10:58 UTC, adamrusted approved these changes
LGTM! 📬

2020-12-26 10:59 UTC, merged