Updated PureScript
simple-icons/simple-icons pull request #4174
Opened 2020-11-29 23:33 UTC by fbernhart

![purescript](https://user-images.githubusercontent.com/70264417/100556579-35de1a80-329b-11eb-9fdf-e5cdf710ad54.png)

**Issue:** #3169 
**Alexa rank:** -

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json` --> (wasn't necessary)
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I took the already used SVG.
I used Inkscape to fix size and center
I used https://jakearchibald.github.io/svgomg/ to optimize the resulting SVG

2020-12-23 22:02 UTC, adamrusted requested changes

2020-12-23 22:02 UTC, adamrusted commented on icons/purescript.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>PureScript icon</title><path d="M19.1652 4.5998l-1.24 1.24L21.8953 9.81l-3.9701 3.9702 1.24 1.24 4.5802-4.6001a.87.87 0 0
Icon looks great - 3 decimals though please! 😂

2020-12-26 00:16 UTC, fbernhart commented on icons/purescript.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>PureScript icon</title><path d="M19.1652 4.5998l-1.24 1.24L21.8953 9.81l-3.9701 3.9702 1.24 1.24 4.5802-4.6001a.87.87 0 0
Done

2020-12-26 11:01 UTC, adamrusted approved these changes
LGTM!

2020-12-26 11:01 UTC, merged