Add starship svg and update simple-icons.json.
simple-icons/simple-icons pull request #4514
Opened 2020-12-28 00:39 UTC by klu17

**Issue:** #4488
**Name:** Starship
**Website:** starship.rs
**Alexa rank:** 769,216

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json`
  - [ ] I optimized the icon with SVGO or SVGOMG
  - [ ] The SVG `viewbox` is `0 0 24 24`

### Description
  - Why did you pick the hex value? @skywarth mentioned #B30BB0 and #DD0B78 was used on the website. It appears that both colors are used in the gradient. I went with the last one mentioned in the issue: #DD0B78.
  - I manually combined the paths with Inkscape. Then, I ran it through SVGOMG

### Preview
![image](https://user-images.githubusercontent.com/20442297/103182652-28588800-487b-11eb-82f5-ab39fd9a2bab.png)

2020-12-28 10:44 UTC, adamrusted requested changes
Thanks for the contribution @klu17! 🎉
Just taking a quick look at it, it appears there are some slight differences between your SVG (red) and source (black). They could be as a result of the optimization process, but could you take another look - and optimize to 4 decimals if need be?

![image](https://user-images.githubusercontent.com/1830867/103208924-ae1b1880-48f9-11eb-84a7-b9f44f304b1f.png)

2020-12-29 11:01 UTC, adamrusted requested changes

2020-12-29 11:01 UTC, adamrusted commented on icons/starship.svg
> +<svg role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><title>Starship icon</title><path d="M11.01 23.9776c0-.022.0481-.0848.107-.1396.168-.1565.5759-.6751.8407-1.069.3082-.4584.6037-
This version is still showing some differences... :thinking:

I'll take a look and see if I'm able to get a path made up for this...

2020-12-29 11:05 UTC, adamrusted commented
Could another @simple-icons/maintainers take a look at this? The path I've included should be fine - but would be good to get your input before merging.

2020-12-29 14:02 UTC, mondeja commented
I'm able to optimize with 3 decimals and without seeing differences against the original resized to 24px. This is the path I got:

```svg
M12 0A12 12 0 0 0 0 12a12 12 0 0 0 4.684 9.512c4.1-.44 5.598-3.67 5.598-3.67l3.226 1.053s-.53 3.17-2.547 5.06A12 12 0 0 0 12 24a12 12 0 0 0 12-12A12 12 0 0 0 12 0zM6.597 4.575c.146 1.2.8 1.9 2.03 2.03-1.364.208-2.05.88-2.03 2.033-.2-1.114-.863-1.805-2.03-2.032 1.26-.15 1.89-.872 2.03-2.03zm8.584.992c1.626 1.994 2.345 3.763 1.234 6.246.92.997 1.314 2.598 1.3 4.094l-2.825-.65-.444 1.18-3.637-1.062.367-1.267-2.78-1.103c.887-1.083 1.773-1.615 3.148-2.29-.123-2.125 1.593-3.648 3.636-5.148zm-.716 2.995c-.584 0-1.057.474-1.057 1.058 0 .584.473 1.057 1.057 1.057s1.057-.473 1.057-1.057-.472-1.058-1.056-1.058z
```

Could you check it @adamrusted?

2020-12-29 14:04 UTC, adamrusted commented
> I'm able to optimize with 3 decimals and without seeing differences against the original resized to 24px. This is the path I got:
> 
> ```svg
> M12 0A12 12 0 0 0 0 12a12 12 0 0 0 4.684 9.512c4.1-.44 5.598-3.67 5.598-3.67l3.226 1.053s-.53 3.17-2.547 5.06A12 12 0 0 0 12 24a12 12 0 0 0 12-12A12 12 0 0 0 12 0zM6.597 4.575c.146 1.2.8 1.9 2.03 2.03-1.364.208-2.05.88-2.03 2.033-.2-1.114-.863-1.805-2.03-2.032 1.26-.15 1.89-.872 2.03-2.03zm8.584.992c1.626 1.994 2.345 3.763 1.234 6.246.92.997 1.314 2.598 1.3 4.094l-2.825-.65-.444 1.18-3.637-1.062.367-1.267-2.78-1.103c.887-1.083 1.773-1.615 3.148-2.29-.123-2.125 1.593-3.648 3.636-5.148zm-.716 2.995c-.584 0-1.057.474-1.057 1.058 0 .584.473 1.057 1.057 1.057s1.057-.473 1.057-1.057-.472-1.058-1.056-1.058z
> ```
> 
> Could you check it @adamrusted?

I've pushed a commit with a 3 decimal path above, could you check it and merge if it's good @mondeja?

2020-12-29 14:52 UTC, mondeja approved these changes
>I've pushed a commit with a 3 decimal path above, could you check it and merge if it's good @mondeja?

Oh, I didn't see the complete commit message :man_facepalming: Yes, It's perfect!
Thank you @adamrusted and @klu17 for this contribution! :pray:

2020-12-29 14:53 UTC, merged