Add Supabase
simple-icons/simple-icons pull request #4858
Opened 2021-01-25 14:15 UTC by adamalston

![supabase](https://user-images.githubusercontent.com/18297826/105717104-b614ab00-5eed-11eb-8804-ec0e4f214550.png)

Closes #4661 

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Color from source css

2021-01-29 11:59 UTC, adamrusted commented on icons/supabase.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Supabase icon</title><path d="M9.90318 23.12655c0 .48238.39086.87345.8731.87345.25854 0 .49092-.11244.65073-.29115l.03443
Thanks for submitting this @adamalston!
Looks like your PR version (red) is actually a fair bit thinner than the source icon (black). There's also a load of excess points showing up - would you mind looking to simplify this?
![image](https://user-images.githubusercontent.com/1830867/106272662-4d00a080-6229-11eb-972a-49714b21e859.png)


Is there also any chance you can get this down to 3 or 4 decimals of precision? While 5 passes the linter, we try and keep it to 3/4 decimals where possible.

2021-02-17 12:43 UTC, PeterShaggyNoble commented
Are you still working on this one, @adamalston?

2021-02-19 18:12 UTC, adamalston commented
Yes, I think I have fixed the issues now.

2021-02-20 15:50 UTC, adamrusted requested changes
Hi @adamalston, thanks for taking another look at this. Sizing-wise this now matches up to the original logo perfectly, however there are still a few extraneous paths that could potentially be removed, as well as the path down the middle remaining ([see red sections for extra points, green section for weird path](https://user-images.githubusercontent.com/1830867/108601181-374b4a80-7393-11eb-9f4f-fc84ebc469bf.png)). If you're not able to fix them, I can take a quick look to try and get this merged in for the weekend?

### Edit
Below is the path I was able to generate. You're welcome to use it if need be - though another maintainer will need to review it.
```svg
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Supabase icon</title><path d="M21.364 9.354H12V.438c.05-.395-.495-.603-.717-.278-.394.551-9.136 12.299-9.483 12.827-.511.647.001 1.686.836 1.659H12v8.916c-.05.395.495.602.717.278.394-.551 9.136-12.299 9.484-12.827.51-.646-.002-1.686-.837-1.659z"/></svg>
```

2021-02-20 16:14 UTC, adamalston commented
Let me know if that works. If not, I can use your path.

2021-02-20 16:17 UTC, adamrusted commented
Thanks for taking a look at this @adamalston - though unfortunately the corners are now quite different to the original ([see here](https://user-images.githubusercontent.com/1830867/108601897-010fca00-7397-11eb-9428-2d6f5fca1a68.png)) and the line across the center is still there. Not sure if it's down to editing tool keeping that in, because Illustrator removed that straight away for me.

2021-02-20 16:21 UTC, adamalston commented
Hmm that's a bit weird. I have illustrator and it's allowing me to simplify the path. I can submit your path in the meantime.

2021-02-20 16:23 UTC, adamrusted commented
Weird! I used the `Unite` pathfinder tool between the two large shaped, before simplifying individual segments of the path. Hopefully another @simple-icons/maintainers can look over this for inclusion this weekend. Thanks for your work @adamalston 🎉

2021-02-24 12:42 UTC, PeterShaggyNoble commented
I'm seeing [some small differences](https://user-images.githubusercontent.com/15157491/109001993-89df7c00-769d-11eb-904c-46c907bc10a3.png) in all 4 corners, @adamrusted.

2021-02-24 12:45 UTC, adamrusted commented
> I'm seeing [some small differences](https://user-images.githubusercontent.com/15157491/109001993-89df7c00-769d-11eb-904c-46c907bc10a3.png) in all 4 corners, @adamrusted.

That'll be from me simplifying paths. Let me rebuild and leave those points in.

2021-02-24 12:51 UTC, adamrusted commented
@PeterShaggyNoble give that a try. See if that's any better.

2021-02-25 14:57 UTC, PeterShaggyNoble approved these changes
Looks perfect now. Thanks for you work on this @adamalston & @adamrusted :+1: Going to update the source to the commit URL and then this will be ready to merge.

2021-02-25 15:00 UTC, merged