Simplify call to get icon slug
simple-icons/simple-icons pull request #5066
Opened 2021-02-19 14:19 UTC by ericcornelissen

**Issue:** n/a
**Alexa rank:** n/a
  

### Checklist
  - [n/a] I updated the JSON data in `_data/simple-icons.json`
  - [n/a] I optimized the icon with SVGO or SVGOMG
  - [n/a] The SVG `viewbox` is `0 0 24 24`

### Description

This changes and renames the `titleToSlug` (formerly `titleToFilename`) function once more to avoid having to do `icon.slug || titleToSlug(icon.title)` whenever you're calling the function.

There are two exceptions to this, one in the `get-filename.js` script where all we have is the brand name; and one in the `build-package.js` script which will be removed in #4920. For this reason we might choose to go with a slightly different approach to refactoring this, namely:

- Keep `titleToSlug` in the utilities file.
- Add `getIconSlug` and define it as `getIconSlug = icon => icon.slug || titleToSlug(icon.title)`.

Let me know if that is preferred, I'm happy either way.

2021-02-21 13:54 UTC, mondeja requested changes
> - Add `getIconSlug` and define it as `getIconSlug = icon => icon.slug || titleToSlug(icon.title)`.

For consistency, I think that this would be the right choice.

2021-02-21 13:54 UTC, mondeja commented on scripts/utils.js
> +   * @param {String} title The icon data as it appears in _data/simple-icons.json
```suggestion
   * @param {Object} icon The icon data as it appears in _data/simple-icons.json
```

2021-02-22 12:58 UTC, ericcornelissen commented
> For consistency, I think that this would be the right choice.

Fair enough, updated the Pull Request :+1:

2021-02-22 13:14 UTC, mondeja approved these changes
Perfect, lets go ahead with the merge :+1:

2021-02-22 13:15 UTC, merged