Upgrade SVGO to version 2
simple-icons/simple-icons pull request #5079
Opened 2021-02-20 15:43 UTC by mondeja

Closes #5078.

SVGO development comes back with the [v2 release](https://github.com/svg/svgo/releases/tag/v2.0.0), with the most important breaking change of the configuration definition in a `svgo.config.js` file. This pull migrates the previous configuration to the new file and updates the dependency in `package.json`.

2021-02-20 23:42 UTC, ericcornelissen requested changes
Thanks for picking this one up @mondeja :tada: 

One minor thing, you forgot to update [the `npm run svgo` script definition](https://github.com/simple-icons/simple-icons/blob/c4a4c7893845b91bcfcd0a306333c98808043992/package.json#L45). Following the [SVGO v2 release notes](https://github.com/svg/svgo/releases/tag/v2.0.0), we may omit specifying the configuration file (as `svgo.config.js`) is the default. Personally i would prefer we keep it explicit, but either way works for me :slightly_smiling_face: 

Another small point, I believe it is also supported to just have the name of the plugin in the array of plugins, I would prefer that for the _"Explicitly enable everything else"_ list (if it works, I can't test it right now).

2021-02-21 00:25 UTC, mondeja commented
> Another small point, I believe it is also supported to just have the name of the plugin in the array of plugins, I would prefer that for the "Explicitly enable everything else" list (if it works, I can't test it right now).

Tested and works :+1:

2021-02-21 12:28 UTC, ericcornelissen approved these changes
> Tested and it works :+1:

Awesome :tada: In theory this is good to merge now, thanks @mondeja 

Ideally, we would improve some of the other comments as well (for clarity and consistency, as per my suggestions below) now that we're editing the file anyway. And one other nitpick is that you used trailing commas everywhere except for the `params: { }` objects. If you want to change these thing @mondeja that would be nice, but feel free to merge this as is :smiley:

2021-02-21 12:28 UTC, ericcornelissen commented on svgo.config.js
> +    // Sort attributes on the <SVG>
```suggestion
    // Sort the attributes on the <svg> tag
```

2021-02-21 12:28 UTC, ericcornelissen commented on svgo.config.js
> +    // Convert basic shapes (such as <circle>) to <path>, including <arc>
```suggestion
    // Convert all basic shapes (such as <circle>) to <path>
```

2021-02-21 12:28 UTC, ericcornelissen commented on svgo.config.js
> +    // add it to the SVG if it's not
```suggestion
    // Keep the role="img" attribute and automatically add it
    // to the <svg> tag if it's not there already
```

2021-02-21 12:28 UTC, ericcornelissen commented on svgo.config.js
> +    // Keep the 'role' attribute, if is already defined
```suggestion
    // Keep the 'role' attribute if it's already defined
```

2021-02-21 12:28 UTC, ericcornelissen commented on svgo.config.js
> +    // Remove all attributes except 'role', 'viewBox' and 'xmlns' of <svg>s
```suggestion
    // Remove all attributes except 'role', 'viewBox', and 'xmlns' from
    // <svg> tags
```

2021-02-21 12:28 UTC, ericcornelissen commented on svgo.config.js
> +        // without space wrapping
Minor grammatical mistake, but still very much understandable

```suggestion
        // Some editors (e.g. Adobe Illustrator and Sketch) cannot parse flags
        // without space wrapping
```

2021-02-21 12:48 UTC, merged