Add Ask Ubuntu
simple-icons/simple-icons pull request #5148
Opened 2021-03-01 22:21 UTC by alagos

![askubuntu](https://user-images.githubusercontent.com/475834/109566396-aae61800-7b48-11eb-93d2-8054752707c3.png)

**Issue:** Closes #5095 
**Alexa rank:** [295k](https://www.alexa.com/siteinfo/askubuntu.com)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
No media kit found, but I used [this svg](https://cdn.sstatic.net/Sites/askubuntu/Img/logo.svg) as base (Logo located in the header of [askubuntu.com](https://askubuntu.com/)), then I cropped it to fit only the "ask" logo.
`#dc461d` used, as it was suggested [in the original ticket](https://github.com/simple-icons/simple-icons/issues/5095#issuecomment-785834263).

2021-03-02 12:09 UTC, PeterShaggyNoble commented
Welcome to Simple Icons, @alagos and thanks for taking this one on :+1:

Everything looks pretty good to me. However, before we merge it, could you see if you could clean up some of the points in the lettering?

2021-03-03 06:16 UTC, alagos commented
@PeterShaggyNoble with that you meant to tick all the checklist? because I already optimized the file, I just forgot to tick it (now is done)

2021-03-04 11:01 UTC, mondeja requested changes
Thanks for submit this pull @alagos 👍🏻

2021-03-04 11:01 UTC, mondeja commented on _data/simple-icons.json
> +            "source": "https://askubuntu.com/"
Could you add the https://stackoverflow.com/legal/trademark-guidance as the `guidelines` entry as it was added for the rest of the StackExchange icons in #5164?

```suggestion
            "source": "https://askubuntu.com/",
            "guidelines": "https://stackoverflow.com/legal/trademark-guidance"
```

2021-03-04 11:30 UTC, PeterShaggyNoble commented
Sorry, @alagos, should have been clearer on that: the letters in the source file consist of more points than are necessary (see below), which we should try to clean up if at all possible. This is as a result of them originally having been a `text` element that was later converted to a `path`. I'm unsure, though, if it's a software specific thing or just particular to Inkscape so, if you're using something else, it may be easier to install [this font](https://www.gnome.org/fonts/) and use the SVG @service-paradis found [here](https://stackapps.com/questions/347/svg-versions-of-the-logos) as a starting point, rather than trying to fix the version from their website manually.

![](https://user-images.githubusercontent.com/15157491/109957216-8b7ff400-7cdc-11eb-95ee-c58f05924bb5.png)

2021-04-14 11:59 UTC, PeterShaggyNoble commented
Took a run at cleaning this up myself but it turns out that Inkscape's "Simplify path" tool actually means "Butcher it mercilessly" and trying to do it manually, before or after simplification, is just insanity!

So, unless someone else can do a better job or recreate it from scratch, I say we merge this in as-is for now.

2021-04-26 23:43 UTC, alagos commented
@mondeja guidelines added

2021-04-28 15:10 UTC, PeterShaggyNoble commented
Thanks, @alagos. As quite some time has passed with nobody offering an improvement with regard to the number of points in the lettering, I'm going to merge this in as it is and if anyone can clean it up in the future then we can address that in a separate PR.

2021-04-28 15:11 UTC, merged