update fedora icon
simple-icons/simple-icons pull request #5610
Opened 2021-05-05 22:17 UTC by stefanobartoletti

Updated Fedora Linux Logo and brand color, as in their website https://getfedora.org/

The source of the SVG file is from [this link](https://pagure.io/fedora-logos/blob/master/f/fedora/fedora_logo.svg), marked as the source for the [logo on Wikipedia](https://commons.wikimedia.org/wiki/File:Fedora_logo_(2021).svg)

2021-05-11 16:09 UTC, PeterShaggyNoble commented
Thanks for the contribution, @stefanobartoletti. Did you intend to close this PR, though?

We're actually waiting on official approval from Fedora to update our icon so, if you'd still be interested in taking it on then please leave a comment in #5540 and we will assign the issue to you and let you know when we've heard back from them.

2021-05-11 21:22 UTC, stefanobartoletti commented
Yes, I closed this intentionally because I noticed the discussion in the issue you mentioned only after, and I was under the impression that their stance was already clear.

If you want you can repoen it, if they give their approval I'll gladly take care of this.

2021-12-26 18:57 UTC, sachinraja commented
Hi @stefanobartoletti, we now have legal approval from Fedora to add this icon! I'll reopen this and make a few suggestions on the data, but the icon matches perfectly already.

2021-12-26 19:02 UTC, mattdm requested changes
Please also add 

            "guidelines": "https://fedoraproject.org/wiki/Legal:Trademark_guidelines",
            "license": {
                "type": "custom",
                "url": "https://docs.fedoraproject.org/en-US/project/brand/"

2021-12-26 19:06 UTC, sachinraja requested changes

2021-12-26 19:06 UTC, sachinraja commented on _data/simple-icons.json
>              "source": "https://fedoraproject.org/wiki/Logo/UsageGuidelines"
```suggestion
            "source": "https://docs.fedoraproject.org/en-US/project/brand/"
```

2022-01-09 21:44 UTC, sachinraja approved these changes
made the changes to merge this so we can get this in, thanks @stefanobartoletti

2022-01-09 21:44 UTC, merged