Update ReadMe.md
simple-icons/simple-icons pull request #5675
Opened 2021-05-11 21:55 UTC by garyilayev

**Issue:** Resolves #5636

Removed a duplicate example inside of Node Usage.

### Description
  - Removed a duplicate example, Only show icon object once.

2021-05-12 16:02 UTC, PeterShaggyNoble requested changes
Welcome to Simple Icons, @garyilayev and thanks for taking this on 🙂 Couple of minor suggested edits below but otherwise this looks good to me.

2021-05-12 16:02 UTC, PeterShaggyNoble commented on README.md
>  NOTE: the `guidelines` entry will be `undefined` if we do not yet have guidelines data for the icon.
```suggestion
NOTE: the `guidelines` entry will be `undefined` if we do not yet have guidelines for the icon.
```

2021-05-12 16:02 UTC, PeterShaggyNoble commented on README.md
> +Either method will return an icon:
```suggestion
Either method will return an icon object:
```

2021-05-13 10:50 UTC, garyilayev commented
Glad I can help :+1: : .

2021-05-13 11:35 UTC, PeterShaggyNoble approved these changes
Thanks, @garyilayev, that all looks good to me now 👍🏻

2021-05-13 11:37 UTC, merged