Update: Microsoft Azure Icon and Color
simple-icons/simple-icons pull request #5745
Opened 2021-05-19 17:49 UTC by moodledan

![Microsoft Azure](https://user-images.githubusercontent.com/399215/118859970-bf79b700-b8d2-11eb-8d9b-6574d8d9a3fe.png)

**Issue:** #5661 
Alexa rank: N/A

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Outline added to the 'flick' element of the source icon to create the cut out effect so the logo could be displayed as a monochrome logo. 

I've updated the HEX value for the icon, its the only color that forms part of the sourced icon that isn't a gradient start/stop value, it's also the primary accent/link colour used on the Microsoft Azure portal.

2021-05-22 20:54 UTC, adamrusted commented on _data/simple-icons.json
> +            "source": "https://portal.azure.com"
While I'm reviewing the SVG - could you please update the source URL to the GitHub URL you used for this new version?

2021-05-22 20:58 UTC, adamrusted requested changes
Thanks for the updates @moodledan - the icon matches up perfectly, though there are a few [excess points in the paths](https://user-images.githubusercontent.com/1830867/119240625-c01b8300-bb48-11eb-9226-8d2e2ea48c53.png) which could probably be tidied up before optimization for an even smaller file.

2021-05-22 21:43 UTC, moodledan reviewed
Excess points removed and increased the floatPrecision value to 3 as per default for the project.

2021-05-23 18:25 UTC, moodledan reviewed
Tried to further optimise but then lint check fails so this is the compromise

2021-05-28 16:35 UTC, adamrusted approved these changes
Looks good to me, thank you for your work on this @moodledan!
There are a couple of minor points that _may_ be improved at some point, but as you say they look like they're likely to mess with the geometry, so let's leave them for now. It's worth noting that the word 'icon' is no longer required in the `<title>` tag - so if you could merge develop into your branch, and then remove the word - this'll be good to go!

2021-05-29 08:37 UTC, adamrusted commented
Thanks for merging develop in, @moodledan - though it looks like the Azure icon itself has also reverted!
Would you mind resubmitting your edited SVG?

2021-05-29 10:04 UTC, moodledan commented
What a n00b, resubmitted now.

2021-05-29 12:20 UTC, adamrusted approved these changes
Spot on, thanks for your work on this @moodledan 🚀

2021-05-29 12:20 UTC, merged