Add Red Bull
simple-icons/simple-icons pull request #6016
Opened 2021-06-23 15:51 UTC by wwwescape

![redbull](https://user-images.githubusercontent.com/651507/123128690-fbbbac80-d468-11eb-9ade-a2251e7f3db6.png)

**Issue:** Closes #6006
**Alexa rank:** 6,062
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

 - I used the SVG from the header of the website
 - I used Inkscape to remove the text, scale and adjust
 - I used https://jakearchibald.github.io/svgomg/ to optimize

2021-06-23 15:52 UTC, wwwescape commented
This icon was one of the more difficult ones that I have attempted.

2021-06-25 14:09 UTC, PeterShaggyNoble commented
Oh, that looks _very_ unfun to work with! Nice work getting it to this stage 👍🏻 I am, though, seeing a few differences around the a lot of the edges ([example from the bull's eye](https://user-images.githubusercontent.com/15157491/123436571-ac8b8e00-d5c6-11eb-8289-1a98546df810.png), with yours in red) when compared to [the website logo](https://resources.redbull.com/logos/redbullcom/v3/redbullcom-logo.svg). Maybe a precision issue when optimising?

I also wonder if all those gaps in the wave are intentional or if it's something we could clean up? 🤔 I'll have a look at a can of Red Bull when I get to work in a couple of hours and see if that can clarify things. If not, I think the safer option is to run with them. There are probably a few duplicate or excess points we could get rid of, though.

For the colour, I'm getting `#D2003C` from the wordmark in the logo and `#DB0A40` from the bull.

2021-06-25 14:52 UTC, wwwescape commented
Sure @PeterShaggyNoble. I'll take another look at it over the weekend.

2021-06-26 07:14 UTC, wwwescape commented
@PeterShaggyNoble Tried a few things but this one seems to be tricky. Perhaps take a quick look at the changes I pushed?

Also, I've noticed that Red Bull has different variants of its logo. The one on their energy drinks and their Formula 1 team has the one with 2 bulls. Not sure what's the right one actually.

2023-07-23 16:10 UTC, adamrusted commented
@wwwescape @LitoMore @dirien I've had a go at simplifying this one a fair bit. Achieved by adding a stroke to different elements in the right hand side. Please have a look, and if we want to use this version, I'll merge it in.

![redbull](https://github.com/simple-icons/simple-icons/assets/1830867/81718030-81a9-42f8-8fd5-0eca93b7f587)

2023-09-13 07:17 UTC, PratyushJayachandran requested changes

2023-09-13 07:17 UTC, PratyushJayachandran commented on icons/redbull.svg
I see [differences](https://github.com/simple-icons/simple-icons/assets/35000807/9ad9cd0f-de8c-4943-b6c3-b02aa2168a3a)
![image](https://github.com/simple-icons/simple-icons/assets/35000807/b77eb298-8244-480b-9538-d21c17370d2e)

2023-09-13 07:17 UTC, PratyushJayachandran commented on icons/redbull.svg
I used this from their website header
![redbullcom-logo](https://github.com/simple-icons/simple-icons/assets/35000807/37791204-1f1d-4c14-ad83-fc72fb6a1cc0)

2023-11-25 11:37 UTC, adamrusted commented
Unoptimized path below, if anyone else wants to tackle this:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd"><svg width="100%" height="100%" viewBox="0 0 24 24" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xml:space="preserve" xmlns:serif="http://www.serif.com/" style="fill-rule:evenodd;clip-rule:evenodd;stroke-linejoin:round;stroke-miterlimit:2;"><path id="bull" d="M22.381,11.374C21.992,12.618 21.362,13.704 20.239,14.456L19.909,14.707L19.645,14.943L19.554,15.05L19.529,15.091L19.518,15.119L19.514,15.135L19.514,15.148L19.515,15.157L19.517,15.164L19.519,15.17L19.524,15.177L19.526,15.179C19.529,15.182 19.532,15.185 19.536,15.187L19.548,15.194L19.559,15.198C19.572,15.202 19.588,15.204 19.605,15.204L19.629,15.204C19.807,15.197 20.141,15.063 20.258,14.959L20.119,15.096L19.955,15.245L19.782,15.391L19.602,15.532L19.417,15.668L19.22,15.802L19.016,15.932L18.81,16.055L18.597,16.173L18.374,16.288L18.148,16.396L17.923,16.496L17.687,16.593L17.642,16.611C15.672,17.374 13.315,17.465 11.728,16.171C12.081,16.515 12.515,16.899 12.927,17.151C12.676,17.108 12.498,16.914 12.261,16.84C12.265,16.848 12.836,17.591 14.543,17.786L14.859,17.818L15.339,17.849L15.803,17.863L16.251,17.854L16.691,17.815L17.155,17.731L17.556,17.624L18.155,17.443L18.449,17.362L18.577,17.329C18.681,17.303 18.791,17.277 18.91,17.252C18.923,17.249 18.937,17.246 18.951,17.243C19.024,17.274 18.427,17.582 17.607,17.813C17.246,17.945 16.868,18.013 16.488,18.04L16.219,18.052L16.003,18.053L15.785,18.048L15.521,18.033L15.206,18.006L14.896,17.972L14.84,17.965C14.439,17.916 14.059,17.858 13.718,17.822L13.717,17.822L13.712,17.822L13.718,17.822C13.748,17.837 13.927,17.918 14.785,18.224C14.724,18.246 14.439,18.285 13.249,17.776C15.666,19.168 18.237,18.535 20.515,17.191L20.867,16.976L20.92,16.942L21.214,16.751L21.365,16.648C21.543,16.527 21.718,16.402 21.891,16.274C21.891,16.283 21.887,16.295 21.887,16.305C21.91,16.309 21.939,16.313 21.962,16.315C21.948,16.356 21.948,16.356 21.748,16.594C22.183,16.243 22.407,15.698 22.868,15.369C22.632,15.842 22.33,16.182 21.768,16.73C21.801,16.706 21.832,16.679 21.863,16.652L21.891,16.626C21.881,16.635 21.872,16.643 21.863,16.652C21.016,17.435 19.901,18.209 18.181,18.617C18.307,18.603 18.432,18.578 18.554,18.544C18.334,18.605 18.327,18.612 18.234,18.643C18.292,18.636 18.292,18.636 18.592,18.575C18.417,18.661 18.215,18.702 17.727,18.801C20.533,18.357 23.448,16.23 23.683,13.352C23.676,13.353 23.669,13.353 23.662,13.352C23.587,13.346 23.53,13.283 23.531,13.209C23.54,12.647 23.384,12.227 23.111,11.907C22.948,12.487 22.698,13.043 22.084,13.979C21.824,14.372 21.364,14.389 21.079,14.75C21.071,14.746 21.064,14.741 21.058,14.737L21.026,14.709L21.021,14.706L21.017,14.704L21.016,14.703L21.013,14.703C21.011,14.703 21.008,14.703 21.006,14.704L21.003,14.704L21.002,14.705C20.989,14.71 20.972,14.725 20.944,14.756L21.006,14.686L21.073,14.594L21.089,14.563L21.094,14.549L21.096,14.539L21.096,14.529L21.095,14.52L21.094,14.517L21.092,14.513L21.091,14.51L21.088,14.507C21.087,14.505 21.085,14.503 21.083,14.501L21.074,14.495L21.034,14.476L21.028,14.472L21.024,14.468L21.022,14.465L21.02,14.463L21.019,14.46L21.018,14.457L21.018,14.454L21.018,14.451L21.019,14.444L21.023,14.433L21.046,14.399L21.06,14.383C21.682,13.696 22.252,13.077 22.498,12.155L22.504,12.134L22.477,12.166C22.39,12.269 22.33,12.313 22.237,12.431L22.347,12.041L22.382,11.914L22.447,11.654L22.499,11.429C22.482,11.419 22.465,11.41 22.447,11.401C22.425,11.392 22.403,11.383 22.381,11.374ZM20.124,17.573C19.772,17.777 19.399,17.965 19.019,18.12C18.639,18.275 18.251,18.399 17.867,18.474C18.636,18.279 19.393,17.965 20.124,17.573ZM13.619,17.776C13.636,17.783 13.653,17.79 13.67,17.796C13.669,17.792 13.669,17.788 13.669,17.784C13.651,17.781 13.634,17.779 13.619,17.776ZM17.263,14.969C16.891,14.768 16.748,14.339 16.519,14.024C15.919,13.404 15.818,12.343 15.661,11.475C15.503,10.632 14.783,10.008 14.283,9.356C13.84,8.995 12.684,7.899 12.138,7.724C11.418,7.425 10.79,7.991 10.191,8.268C9.704,8.469 9.189,8.526 8.759,8.898C8.085,9.763 7.68,9.071 6.898,9.756C5.733,10.976 5.292,9.902 3.691,11.331C3.262,11.588 2.86,11.846 2.343,11.818C1.52,11.779 1.24,10.673 1.884,10.185C2.333,9.683 3.436,9.166 2.888,8.354C2.318,7.846 1.648,8.062 0.97,7.496C0.657,7.986 1.057,8.651 1.571,8.814C1.782,8.945 2.272,8.736 2.373,9.041C2.156,9.475 1.563,9.71 1.285,10.13C0.592,10.93 1.276,12.242 2.258,12.303C2.621,12.42 3.083,12.124 3.318,12.246C3.346,12.532 3.318,12.79 3.375,13.048C3.402,13.33 3.723,13.632 3.547,13.906C3.262,14.151 2.893,14.276 2.517,14.253C2.322,14.478 2.289,14.733 2.173,14.997C2.031,15.255 1.745,15.369 1.544,15.484C1.411,15.685 1.279,15.908 0.999,15.942C0.828,16.143 0.799,16.4 0.742,16.658C1.458,16.848 1.612,16.752 2.002,16.143C2.145,16 2.346,16.114 2.488,16.143C2.895,16.094 3.199,15.822 3.491,15.57C4.533,15.298 4.523,15.98 5.724,15.198C5.925,15.112 6.011,14.883 6.097,14.711C6.197,14.519 6.475,14.149 6.125,14.053C5.226,15.872 3.661,14.391 2.46,15.768C2.276,15.819 2.419,15.533 2.46,15.481C3.322,14.225 5.283,15.331 5.953,13.705C6.07,13.455 6.004,12.458 6.296,12.473C6.325,12.473 6.411,12.502 6.411,12.559C6.133,13.773 6.317,14.15 7.613,13.937C8.057,13.809 9.329,14.262 9.303,13.651C9.303,13.537 9.188,13.48 9.303,13.394C9.331,13.365 9.417,13.394 9.446,13.422C9.527,13.912 9.957,14.272 10.365,14.482C11.188,15.042 10.855,15.773 9.906,15.742C9.591,15.57 9.506,15.255 9.276,14.997C9.009,14.763 8.643,14.875 8.332,14.94C8.177,15.173 8.544,15.451 8.618,15.685C8.761,15.771 8.962,15.627 9.076,15.799C9.191,15.97 9.248,16.143 9.42,16.257C9.916,16.733 10.952,15.897 11.481,15.856C11.944,15.907 12.155,15.485 12.312,15.14C12.573,14.663 11.878,14.192 11.825,13.766C11.667,13.722 11.457,13.599 11.338,13.766C11.426,13.979 11.917,14.759 11.882,14.997C11.818,15.17 11.672,15.569 11.453,15.541C11.511,15.341 11.597,15.113 11.597,14.883C11.492,14.638 11.032,13.93 10.995,13.68C11.087,13.438 11.557,13.578 11.739,13.336C11.94,13.021 11.997,12.707 12.055,12.306C12.067,12.264 12.099,12.232 12.141,12.219C12.42,12.399 12.136,13.261 11.969,13.451C11.953,13.748 12.537,13.549 12.656,13.451C12.877,13.497 13.326,13.276 13.429,13.422C13.295,13.591 13.197,13.786 13.143,13.995C12.971,14.195 12.685,14.339 12.685,14.625C12.716,14.805 12.958,14.515 12.971,14.739C12.722,15.056 12.753,15.133 12.828,15.484C13.089,15.852 13.589,15.549 13.916,15.456C14.468,15.239 15.088,15.582 15.52,14.997C15.636,15.007 15.742,15.071 15.806,15.169C16.125,15.504 16.575,15.682 17.037,15.656C17.225,15.526 16.815,15.423 16.751,15.369C16.55,15.255 16.292,15.083 16.235,14.854C16.16,14.534 15.929,14.241 15.777,13.938C16.446,13.948 16.516,15.344 17.493,15.141C17.541,15.108 17.536,15.072 17.522,15.026L17.263,14.969ZM0.397,15.656L0.398,15.656L0.397,15.656L0.397,15.656C0.058,15.795 0.238,16.214 0.026,16.429C0.026,16.457 -0.032,16.515 0.026,16.544C0.168,16.572 0.283,16.63 0.455,16.658C0.531,16.402 0.605,16.117 0.655,15.885C0.597,15.799 0.512,15.685 0.397,15.656ZM17.714,15.266C17.629,15.375 17.44,15.381 17.358,15.456C17.341,15.477 17.333,15.504 17.335,15.538C17.358,15.641 17.325,15.722 17.262,15.78C17.175,15.874 17.012,15.916 16.865,15.906C16.131,15.914 15.773,15.555 15.473,15.383C15.063,15.648 14.808,15.753 14.272,15.67C13.957,15.645 13.676,15.804 13.37,15.882C13.804,16.254 15.563,16.726 14.915,16.406C13.843,15.799 14.62,16.203 15.56,16.425C16.092,16.556 16.638,16.623 17.185,16.625C18.094,16.325 18.94,15.876 19.612,15.346C19.564,15.345 19.524,15.337 19.494,15.325C19.45,15.307 19.419,15.278 19.399,15.244C19.368,15.192 19.351,15.108 19.422,14.993C19.496,14.874 19.708,14.666 20.156,14.342C20.157,14.341 20.158,14.34 20.16,14.339C21.257,13.603 21.87,12.539 22.248,11.324C21.98,11.227 21.714,11.163 21.45,11.124C21.045,12.13 20.947,12.84 19.992,13.409C18.884,14.134 19.578,13.948 19.589,13.943C19.675,13.908 19.757,13.864 19.834,13.811C19.405,14.5 18.66,14.94 17.771,15.138C17.766,15.194 17.744,15.234 17.714, [...]

2023-11-25 23:54 UTC, PratyushJayachandran commented on icons/redbull.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Red Bull</title><path d="m22.358 11.72.021.009c.043.022.084.044.124.068l-.172.636c.094-.119.154-.162.241-.266l.027-.033c-
```suggestion
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Red Bull</title><path d="M.398 15.656H.396zm0 0c-.34.14-.16.558-.372.773 0 .028-.058.086 0 .115.142.028.257.086.429.114.076-.256.15-.54.2-.773-.058-.086-.143-.2-.258-.229zm.629 0c.2-.115.315-.315.4-.487-.06-.096-.135-.223-.285-.172-.137.106-.28.201-.43.287-.071.194.107.439.315.372zm10.454.2c-.53.04-1.565.877-2.061.401-.172-.114-.23-.287-.344-.458-.114-.172-.315-.028-.458-.114-.074-.234-.44-.512-.286-.745.31-.065.677-.177.944.057.23.258.315.573.63.745.949.031 1.282-.7.459-1.26-.408-.21-.839-.57-.92-1.06-.028-.028-.114-.057-.142-.028-.115.086 0 .143 0 .257.026.61-1.246.158-1.69.286-1.296.213-1.48-.164-1.202-1.378 0-.057-.086-.086-.115-.086-.293-.015-.226.982-.343 1.232-.67 1.626-2.631.52-3.493 1.776-.041.052-.184.338 0 .287 1.201-1.377 2.766.104 3.665-1.715.35.096.072.466-.028.658-.086.172-.172.4-.373.487-1.201.782-1.191.1-2.233.372-.292.252-.596.524-1.003.573-.142-.029-.343-.143-.486 0-.39.609-.544.705-1.26.515.057-.257.086-.515.257-.716.28-.033.412-.257.545-.458.2-.115.487-.23.63-.487.115-.264.148-.52.343-.744.376.023.745-.102 1.03-.347.176-.274-.146-.576-.172-.858-.057-.258-.029-.516-.057-.802-.235-.122-.697.174-1.06.057-.982-.061-1.666-1.373-.973-2.173.278-.42.87-.655 1.088-1.09-.1-.304-.591-.095-.802-.226C1.057 8.65.657 7.986.97 7.496c.678.566 1.348.35 1.918.858.548.812-.555 1.329-1.004 1.831-.644.488-.364 1.594.459 1.633.517.028.919-.23 1.348-.487 1.601-1.429 2.042-.355 3.207-1.575.782-.685 1.187.007 1.861-.858.43-.372.945-.43 1.432-.63.6-.277 1.227-.844 1.947-.544.546.175 1.702 1.27 2.145 1.632.5.652 1.22 1.276 1.378 2.119.157.868.258 1.929.858 2.549.229.315.372.744.744.945l.259.057c.014.046.019.082-.029.115-.977.203-1.047-1.193-1.716-1.203.152.303.383.596.458.916.057.23.315.4.516.515.064.054.474.157.286.287a1.577 1.577 0 0 1-1.231-.487.38.38 0 0 0-.286-.172c-.432.585-1.052.242-1.604.459-.327.093-.827.396-1.088.028-.075-.351-.106-.428.143-.744-.013-.225-.255.065-.286-.115 0-.286.286-.43.458-.63.054-.209.152-.404.286-.573-.103-.146-.552.075-.773.029-.119.098-.703.297-.687 0 .167-.19.45-1.052.172-1.232a.129.129 0 0 0-.086.087c-.058.4-.115.715-.316 1.03-.182.242-.652.102-.744.344.037.25.497.958.602 1.203 0 .23-.086.458-.144.658.219.028.365-.371.43-.544.034-.238-.457-1.018-.545-1.231.12-.167.33-.044.487 0 .053.426.748.898.487 1.374-.157.345-.368.767-.83.716zm3.033-3.178c.133.09.228-.639.601-.057.165.115.196.351.201.544-.003.066.024.056.086.057.062.001.111-.145.143-.2 0-.057 0-.115.029-.086.028-.28-.204-.557-.401-.802-.076-.209-.397-.41-.458-.057-.042.031-.054.076-.086.114-.069.142-.194.325-.115.487zm-.143 2.062h.029a1.71 1.71 0 0 0 .4-.058c.107-.081.134-.357.03-.4h-.087c-.188-.01-.541.301-.372.458zM12.08 9.843c.154.24.181.541.258.83.057 0 .086 0 .115-.028.028-.115.057-.287 0-.344-.009-.333-.053-.606-.315-.802a.137.137 0 0 0-.173.029c-.069.134.035.236.115.315zm-2.405 5.183c.114.143.114.343.258.458a.616.616 0 0 0 .486-.143c.086-.057-.028-.143-.057-.23-.086-.114-.028-.343-.229-.343-.217.05-.455-.012-.659.057 0 .087.172.087.2.201zm4.037 2.796h.006-.006zm8.835-5.804c.06.03.09.098.073.162-.25.94-.824 1.577-1.437 2.247l.003.004c.093-.065.19-.117.286-.168.183-.097.355-.188.471-.363.651-.982.883-1.53 1.038-2.11a1.749 1.749 0 0 0-.372-.28c-.038.164-.077.323-.123.493a.14.14 0 0 1 .061.015zm1.438-.657c-.306-2.281-1.087-4.283-3.87-5.019 1.72.416 1.85.63 2.075.78-1.337-1.236-3.49-1.665-5.667-1.296 1.27-.41 3.355-.36 4.66.447-3.112-1.92-6.853-1.09-9.153 1.103.43.083.806.366 1.157.637 2.61-1.42 7.996-1.808 9.787 1.663-.103.064-.184-.11-.26-.16-.014-.005-.046-.036-.06-.043-.852-.855-2.218-1.108-3.37-1.35.769.305 1.578.398 2.298.806 1.878 1.077 2.698 3.258 2.048 5.036l.006-.005c.29-.834.408-1.718.35-2.599zm-6.258 7.44c.215-.034.43-.092.644-.145a8.687 8.687 0 0 1-.644.145zm5.835-4.735h.002l-.003.008c-.565 2.297-2.84 3.998-5.19 4.582.084-.025.157-.05.22-.081-.3.06-.3.06-.357.068.093-.03.1-.038.32-.1a2.394 2.394 0 0 1-.372.074 7.877 7.877 0 0 0 3.709-1.991c-.04.037-.08.072-.123.104.562-.548.864-.888 1.1-1.361-.462.33-.685.874-1.12 1.225.2-.238.2-.238.214-.28a1.03 1.03 0 0 1-.075-.009c0-.01.004-.022.004-.03-2.58 1.91-5.723 3.182-8.642 1.5 1.19.51 1.475.471 1.536.45-.862-.309-1.038-.389-1.067-.402 1.097.114 2.597.462 3.89-.01.82-.231 1.416-.539 1.343-.57-1.624.343-1.766.759-4.092.575l-.316-.032c-1.707-.195-2.278-.938-2.282-.946.237.074.415.268.666.311-.412-.252-.846-.636-1.2-.98 1.586 1.292 3.936 1.198 5.905.438a6.882 6.882 0 0 1-2.072-.184c-.94-.222-1.717-.626-.645-.019.65.32-1.114-.153-1.544-.526.193-.05.377-.126.565-.172.043-.012.087-.02.13-.027a.908.908 0 0 1 .206-.01c.536.082.79-.023 1.2-.288.301.172.659.531 1.393.523a.553.553 0 0 0 .35-.09c.092-.059.148-.151.12-.278-.003-.047.02-.076.051-.101.08-.05.212-.073.295-.145a.205.205 0 0 0 .09-.154c.889-.198 1.634-.638 2.063-1.327a1.226 1.226 0 0 1-.245.132c-.011.005-.705.19.403-.534.988-.589 1.06-1.328 1.501-2.39-1.813-.278-3.518.602-4.984.812v-.014c-.119-.216.933-.44 1.072-.523.082-.085.222-.056.315-.132.091-.091.23-.11.353-.135.323-.165.68-.219 1.04-.226.126.019.244-.052.37-.043a.347.347 0 0 1 .19-.03c.384-.029.778-.065 1.11-.3.035-.02.153-.085.053-.098-.63-.17-.932.26-1.506-.256.01-.022-.18-.103-.208-.103-.304.06-.59.197-.905.202-.144.032-.2-.04-.345-.04-.193.045-.46.169-.657.184-.092-.017-.542.218-.55.056a.017.017 0 0 1-.01 0c-.049-.182 2.821-1.254 1.64-.532.065.056.447-.105.807-.132.404-.086.941.21 1.118-.185-.007-.065-.162-.046-.2-.02-.077.043-.16.015-.24.033-.136.016-.66-.079-.78-.07-.095-.082.528-.065.583-.074a19.1 19.1 0 0 0 .657-.115c.091-.011.183-.013.274-.006.186.044.683-.024.153-.153-.14-.027-.581-.041-.652-.019-.108.014-.576.153-.825.095-.225-.068.7-.106.59-.168-1.148-.145-2.457-.109-4.725 1a18.203 18.203 0 0 0-.2-.242c-.27-.344-.55-.729-.856-.962 1.392-.556 3.484-.539 4.658-.67-1.469-.353-3.54-.018-4.902.463l-.094-.08c.667-.3 1.766-.7 2.429-.833-.175-.027-2.16.25-2.65.648-.102-.087-.207-.171-.31-.254 1.615-.856 4.393-1.355 6.65-.664 1.12.345 1.983.934 2.572 1.755-.834-.691-2.011-.937-3.059-1.156l-.158-.033a.126.126 0 0 0-.148.087.127.127 0 0 0 .075.155c.311.124.63.213.938.3.475.133.923.26 1.343.498 1.482.85 2.304 2.446 2.171 3.974.001.021.007.043.008.064-.008.34-.057.67-.136.99zm-4.07-6.463c-.044.026.257.134.353.163-.008-.005.24.212.741.218-.19-.202-.775-.31-1.093-.381zm.766 7.356c-.123.11-.482.25-.652.244.136.017.433-.088.596-.192.017-.018.038-.034.056-.052zm.453-1.093c.566-.519 1.083-1.146 1.144-1.912-.079.07-.085.407-.33.449-.06 0-.216-.03-.195-.103-.142.494-.576.714-.762 1.123.185.088-.125.288-.101.432a.254.254 0 0 1 .244.011zm2.437-2.098a2.27 2.27 0 0 0-.639-.495c-.024-.01-.047-.012-.07-.021l.091.036a14.66 14.66 0 0 1-.293 1.143c.103-.13.165-.17.267-.297-.243.934-.817 1.557-1.444 2.249-.168.186.243-.013-.116.373.087-.093.067-.043.134-.006.286-.36.746-.378 1.006-.771.663-1.01.9-1.578 1.064-2.21z"/></svg>
```
I used the logo available at the website header from https://www.redbull.com/us-en/

2023-11-25 23:56 UTC, PratyushJayachandran commented
@simple-icons/icon-review Please take a look at the latest contribution. Please compare it against logo at the header on https://www.redbull.com/us-en/

2023-11-30 08:13 UTC, PratyushJayachandran commented on icons/redbull.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Red Bull</title><path d="M.398 15.656H.396zm0 0c-.34.14-.16.558-.372.773 0 .028-.058.086 0 .115.142.028.257.086.429.114.0
```suggestion
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Red Bull</title><path d="M12.8398 7.748c-.2487-.1715-.5118-.3201-.7998-.3759 2.3017-2.1945 6.0453-3.0256 9.16-1.1036-1.3058-.8072-3.3933-.8574-4.6635-.447 2.1783-.37 4.3333.0598 5.671 1.2957-.2246-.1486-.354-.3633-2.0764-.7797 2.7733.733 3.5593 2.7235 3.8689 4.994-.1653-.4903-.412-.9759-.738-1.413l.1925-.121-.1583-.3105c-.629-1.2322-1.7461-2.1222-3.2308-2.5746-2.4278-.7421-5.3888-.1845-7.061.7441l-.1646.0916zm4.9016 11.0585c.2005-.0317.4012-.0843.6017-.133-.1406.0381-.3215.076-.6017.133zm.0442-3.6655c-.0073.073-.043.1192-.0899.1533-.0834.0727-.2146.0948-.2955.1455-.0306.0248-.0544.0536-.0507.1014.0274.1263-.0288.2188-.1211.2776-.0919.0668-.2245.0988-.3501.0907-.7346.008-1.0922-.3517-1.3932-.5241-.4103.2657-.6647.3706-1.202.2878-.0699-.0057-.1376.0012-.205.0108a1.4027 1.4027 0 0 0-.1303.0266c-.1885.0469-.3732.123-.5664.1726.4305.3732 2.1957.8468 1.5461.5268-1.0732-.6083-.2952-.2039.645.0184.1797.0443.3639.061.5461.0906 1.042-.205 2.087-.6237 2.9298-1.1991-.1352-.4203.2-.7584.924-1.2833.24-.161.4587-.3425.6596-.5447-.004-.0254-.0103-.0503-.0477-.068.1868-.4095.6205-.6293.7632-1.1237-.0108.0377.026.0636.0722.08.1533-.287.2887-.6036.4106-.944-.151-.0386-.3016-.0629-.452-.0828-.3355.8862-.4891 1.532-1.3698 2.0569-1.1087.7253-.4147.5393-.4037.5338a1.228 1.228 0 0 0 .245-.1318c-.4287.6896-1.1748 1.1298-2.0642 1.3287zm6.0183-2.2025c.0024.3661-.0912.677-.1934 1.0389l.0067-.005c.0006.0044-.0386.1076-.0416.115.36-1.5508-.1451-2.3531-1.048-2.8145-2.1933-.9216-4.2666.309-6.0056.5585a.0598.0598 0 0 0 0-.0142c-.1188-.2169.934-.44 1.0736-.524.082-.0848.2223-.056.3153-.1315.0912-.0916.2302-.1113.3526-.1352.3238-.1652.68-.2193 1.0406-.2267.1267.019.2449-.0522.3716-.0424a.3468.3468 0 0 1 .1885-.0307c.385-.0283.7799-.0645 1.1122-.2992.0343-.0203.153-.0854.0527-.099-.6299-.1701-.9329.2605-1.507-.2561.0091-.0221-.1812-.1026-.2082-.1026-.3049.0602-.59.1966-.906.2021-.1438.032-.2007-.0405-.3452-.0405-.1928.0454-.4603.169-.658.1843-.0913-.0172-.5424.218-.551.0565a.0175.0175 0 0 1-.0097 0c-.0484-.1825 2.8243-1.2552 1.6417-.5333.0649.0565.4475-.105.808-.1321.4046-.0854.942.2114 1.119-.1843-.0067-.0651-.1623-.046-.2002-.0196-.0771.0417-.1597.014-.2412.0325-.1353.016-.6605-.0792-.7798-.0712-.0949-.0811.5288-.0646.584-.0738.2044-.0307.4523-.0762.6574-.1149.091-.011.1828-.0129.2742-.0055.1855.0436.6837-.024.1525-.1536-.1396-.0264-.5816-.0412-.652-.0185-.1083.0142-.5766.153-.8264.0953-.2246-.0682.701-.107.5908-.1684-1.1487-.1454-2.459-.109-4.7285 1.001a18.5987 18.5987 0 0 0-.201-.2426c-.269-.3447-.549-.7295-.8564-.963 1.3932-.5566 3.4873-.5388 4.662-.6696-1.4697-.3539-3.5436-.0184-4.9063.4626l-.0936-.0792c.6678-.3004 1.7672-.701 2.4308-.8344-.175-.027-2.1615.2507-2.6512.6488a11.8313 11.8313 0 0 0-.4383-.3582c2.5747-1.4309 7.986-1.8192 9.7672 1.6699-.1022.0652-.186-.1112-.2595-.161-.016-.0042-.0478-.0356-.0612-.0423-.849-.8626-2.2147-1.1127-3.3631-1.3584.7633.3047 1.575.4005 2.2937.811 1.4605.7956 2.473 2.6903 2.2373 4.029zm-4.2953-5.339c-.0453.0258.2564.1339.3526.1634-.008-.0055.2405.212.7418.2175-.191-.2021-.7755-.309-1.0944-.381zm3.6993 6.4026-.0035-.001c.2063-.888.0841-1.4385-.164-1.8084-.1665.4877-.4245 1.0051-.9386 1.7877-.2597.3935-.7207.4107-1.0062.7717-.0675-.0368-.0479-.087-.135.0061.3597-.3861-.0516-.1876.1166-.3733.6274-.6925 1.202-1.3165 1.4452-2.2512-.1026.128-.1646.168-.2677.2978.0778-.2653.1424-.5096.2037-.7603-.0347-.0195-.0692-.0414-.1037-.059-.0148-.0063-.0295-.009-.0443-.015-.3936 1.1477-1.0017 2.155-2.0552 2.8613-1.5102 1.0959-.2351.7294.019.5026-1.903 1.9398-6.1155 3.1872-8.5368 1.2136.3537.3438.7877.7281 1.2002.9807-.251-.043-.4297-.2373-.6666-.3114.0036.008.5758.7514 2.2837.9463.1098.0123.2148.0233.316.0325 2.3286.1839 2.4704-.2323 4.0954-.5755.073.0312-.5237.3389-1.3445.5706-1.2934.4723-2.7944.124-3.8921.0094.0285.0137.2048.0937 1.0676.4019-.0614.022-.3468.0613-1.5378-.4487 2.9221 1.6825 6.0671.4088 8.6491-1.5029 0 .0086-.0036.0209-.0036.0313a.9874.9874 0 0 0 .0749.0092c-.0142.041-.0142.041-.2143.2795.4359-.3512.6593-.8961 1.121-1.2258-.2364.4737-.5384.8133-1.1008 1.3625a1.4648 1.4648 0 0 0 .1228-.1048c-.8502.793-1.9718 1.58-3.7122 1.9932a2.3884 2.3884 0 0 0 .3727-.0736c-.2204.0613-.2266.0687-.3199.0993.0577-.0073.0577-.0073.358-.068-.0747.0366-.1592.0649-.2639.0932 2.1931-.5313 4.328-2.0379 5.0835-4.0974l-.4727.3377.254-.9118zm-9.485 3.8244.0066.0008a.0395.0395 0 0 0-.0018-.0008h-.0049zm3.813-2.7978c.0142.046.0191.0815-.0287.1147-.9776.2035-1.0482-1.194-1.7173-1.2037.1521.3035.3833.5966.4588.9167.057.2293.3152.401.5158.5157.0637.054.474.1563.2864.287a1.5782 1.5782 0 0 1-1.2322-.4875.3803.3803 0 0 0-.2864-.1717c-.4317.585-1.053.2422-1.605.4586-.3269.0932-.8273.3962-1.0892.0282-.0748-.3513-.1061-.428.1435-.745-.0129-.225-.2551.0656-.2864-.1146 0-.2864.2864-.4299.4581-.6304a1.5568 1.5568 0 0 1 .2864-.5733c-.103-.146-.552.0748-.7733.0288-.119.098-.7041.2968-.6882 0 .1675-.1901.4514-1.0529.1724-1.2325a.1288.1288 0 0 0-.0859.0864c-.0576.401-.1147.7162-.3158 1.0314-.1828.2422-.6532.1018-.7446.344.0368.2502.4974.9584.6017 1.2037 0 .23-.0859.4587-.1435.6592.219.0276.3649-.3722.4293-.5445.035-.2386-.457-1.0191-.5446-1.2325.1196-.1674.3293-.0436.4875 0 .0534.4267.7483.8983.487 1.3753-.1564.3453-.368.7671-.831.7169-.53.0404-1.5664.8774-2.0632.401-.1723-.1147-.2293-.287-.344-.4587-.1147-.1717-.3153-.0282-.4588-.114-.0736-.2337-.441-.512-.2864-.7457.3116-.065.6777-.1772.9457.0577.2294.2575.3153.5733.6305.745.9494.0313 1.2824-.7003.4587-1.2607-.4084-.2103-.839-.5703-.92-1.0608-.0281-.0282-.1146-.057-.1428-.0282-.1147.0858 0 .1428 0 .2575.0264.6107-1.2469.1576-1.6909.2864-1.2977.2127-1.4817-.1644-1.2033-1.3797 0-.057-.0858-.0859-.1147-.0859-.2931-.0147-.2263.9824-.344 1.2325-.6704 1.628-2.633.5213-3.4958 1.7783-.0411.0515-.184.3379 0 .287 1.2026-1.3779 2.769.1042 3.6687-1.717.3496.097.0718.4667-.0288.6586-.0859.1723-.1717.4016-.3729.4875-1.202.783-1.1922.1-2.2349.3728-.2925.252-.596.5243-1.0033.5727-.143-.0282-.3435-.1429-.487 0-.3907.6095-.544.7058-1.261.5163.0571-.2581.086-.5163.2577-.7168.2802-.0337.4121-.257.5446-.4587.2011-.1146.4875-.2293.6304-.4868.1153-.2643.1485-.52.3441-.745a1.4463 1.4463 0 0 0 1.0304-.3477c.176-.2735-.1454-.5764-.1718-.8585-.0576-.2581-.0288-.5163-.0576-.8027-.2343-.122-.6973.1748-1.0604.057-.9825-.0613-1.6676-1.374-.974-2.175.2785-.4193.8716-.6548 1.0887-1.0896-.1006-.3053-.5913-.0962-.8022-.2274-.5146-.1625-.9145-.8278-.6017-1.3184.6783.5666 1.3493.3501 1.9197.8585.5489.813-.555 1.33-1.0046 1.8328-.6452.488-.365 1.5949.4587 1.6335.5183.0288.92-.2293 1.3493-.4869 1.6025-1.43 2.0441-.355 3.2094-1.5765.7832-.6855 1.1886.0074 1.8632-.8584.43-.3728.9457-.4299 1.4327-.6304.5998-.2778 1.2284-.8443 1.949-.5445.5459.1754 1.7032 1.2718 2.1466 1.6335.4998.6525 1.2205 1.2767 1.3787 2.1204.157.869.2588 1.9304.8586 2.551.2294.315.3729.745.7452.9455l.2588.0576zm-5.0731-4.385c.0282-.1146.057-.2869 0-.344-.0086-.3329-.0528-.6064-.3153-.8026a.1368.1368 0 0 0-.1723.0288c-.0693.1343.0343.2367.1147.3152.1545.2398.1815.542.2582.8315.057 0 .0858 0 .1147-.0288m2.3495 4.0409c.1067-.0816.1337-.3581.0288-.4016h-.0858c-.1883-.0099-.5422.3023-.3723.4586h.0282a1.7083 1.7083 0 0 0 .4011-.057m.7452-1.6624c0-.057 0-.1146.0288-.0858.0282-.2808-.2036-.5574-.4011-.8027-.0754-.2085-.3974-.4096-.4587-.057-.0411.0313-.054.076-.086.1147-.0686.1416-.1943.325-.1146.4868.133.0902.2275-.6389.6016-.057.1644.1153.1957.352.2012.5445-.003.0662.024.0558.0859.057.062.0013.111-.1447.1429-.2005M1.0284 15.6591c-.208.0674-.387-.1779-.3153-.3729.1496-.0853.293-.181.4293-.2863.1503-.0515.2251.0754.2865.1717-.086.1723-.2006.3728-.4011.4875m-.6305 0c.1147.0288.2005.1428.2582.2293-.0497.2324-.1239.5175-.2006.7738-.1717-.0288-.2864-.0864-.4293-.1146-.0576-.0289 0-.0865 0-.1147.2122-.2152.032-.6347.3723-.7738m9.2848-.6304c-.0289-.1147-.2006-.1147-.2006-.2011.2042-.0693.4422-.0068.6593-.057.2006 0 .143.2293.2294.344.0282.0858.1429.1716.057.2293a.6164.6164 0 0 1-.487.1428c-.1435-.1146-.1435-.3151-.2581-.458"/></s [...]

2023-11-30 08:17 UTC, PratyushJayachandran commented on icons/redbull.svg
I retried as you suggested. Please note that the resulting logo was smaller, so I scaled it up to 24px width. So if you paste source scaled on top it won't match. I don't know how to reliably compare this :(

2023-11-30 08:18 UTC, adamrusted requested changes

2023-11-30 08:18 UTC, adamrusted commented on icons/redbull.svg
@PratyushJayachandran - I'm seeing some very _slight_ differences in the right-hand shapes, probably a precision thing. Could you have another look please?
![image](https://github.com/simple-icons/simple-icons/assets/1830867/f1b5db91-5bdf-41bc-9103-b66bc3a27392)

2023-12-08 15:49 UTC, PeterShaggyNoble requested changes
Jebus! This one's _still_ fecking here?! 😮 🙈 

Before even starting into the icon, I found 3 different official source quotes 3 different values for the hex of the primary red 🙄 So I quickly abandoned that endeavour! The one they use on the website is as good a choice as any.

In reviewing the latest version of the icon, I'm still seeing the same differences from the last review along with some new differences in the the bull. For me, the best attempt so far has been [this one by Adam](https://github.com/simple-icons/simple-icons/pull/6016#issuecomment-1826287802) - it's not perfect in its alignment but the original itself is far from perfect, so, in the interest of getting this one off our plate after ***2 and a half years(!)***, I think we allow ourselves a little bit of deviation on this one and run with it.

What do the other @simple-icons/maintainers think?

2023-12-11 10:37 UTC, PeterShaggyNoble approved these changes

2023-12-11 10:37 UTC, PeterShaggyNoble commented on icons/redbull.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Red Bull</title><path d="M12.83982 7.7481c-.24871-.17165-.5118-.32022-.79984-.37596 2.30167-2.19459 6.04528-3.02561 9.16-
OK, so, let's run with Adam's path for now 👍🏻 Thanks @wwwescape, and everyone else, for your work on & contributions to this one as well as your patience - has to be the longest, or at least close to, an icon PR has taken here!
```suggestion
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Red Bull</title><path d="M22.381,11.374C21.992,12.618 21.362,13.704 20.239,14.456L19.909,14.707L19.645,14.943L19.554,15.05L19.529,15.091L19.518,15.119L19.514,15.135L19.514,15.148L19.515,15.157L19.517,15.164L19.519,15.17L19.524,15.177L19.526,15.179C19.529,15.182 19.532,15.185 19.536,15.187L19.548,15.194L19.559,15.198C19.572,15.202 19.588,15.204 19.605,15.204L19.629,15.204C19.807,15.197 20.141,15.063 20.258,14.959L20.119,15.096L19.955,15.245L19.782,15.391L19.602,15.532L19.417,15.668L19.22,15.802L19.016,15.932L18.81,16.055L18.597,16.173L18.374,16.288L18.148,16.396L17.923,16.496L17.687,16.593L17.642,16.611C15.672,17.374 13.315,17.465 11.728,16.171C12.081,16.515 12.515,16.899 12.927,17.151C12.676,17.108 12.498,16.914 12.261,16.84C12.265,16.848 12.836,17.591 14.543,17.786L14.859,17.818L15.339,17.849L15.803,17.863L16.251,17.854L16.691,17.815L17.155,17.731L17.556,17.624L18.155,17.443L18.449,17.362L18.577,17.329C18.681,17.303 18.791,17.277 18.91,17.252C18.923,17.249 18.937,17.246 18.951,17.243C19.024,17.274 18.427,17.582 17.607,17.813C17.246,17.945 16.868,18.013 16.488,18.04L16.219,18.052L16.003,18.053L15.785,18.048L15.521,18.033L15.206,18.006L14.896,17.972L14.84,17.965C14.439,17.916 14.059,17.858 13.718,17.822L13.717,17.822L13.712,17.822L13.718,17.822C13.748,17.837 13.927,17.918 14.785,18.224C14.724,18.246 14.439,18.285 13.249,17.776C15.666,19.168 18.237,18.535 20.515,17.191L20.867,16.976L20.92,16.942L21.214,16.751L21.365,16.648C21.543,16.527 21.718,16.402 21.891,16.274C21.891,16.283 21.887,16.295 21.887,16.305C21.91,16.309 21.939,16.313 21.962,16.315C21.948,16.356 21.948,16.356 21.748,16.594C22.183,16.243 22.407,15.698 22.868,15.369C22.632,15.842 22.33,16.182 21.768,16.73C21.801,16.706 21.832,16.679 21.863,16.652L21.891,16.626C21.881,16.635 21.872,16.643 21.863,16.652C21.016,17.435 19.901,18.209 18.181,18.617C18.307,18.603 18.432,18.578 18.554,18.544C18.334,18.605 18.327,18.612 18.234,18.643C18.292,18.636 18.292,18.636 18.592,18.575C18.417,18.661 18.215,18.702 17.727,18.801C20.533,18.357 23.448,16.23 23.683,13.352C23.676,13.353 23.669,13.353 23.662,13.352C23.587,13.346 23.53,13.283 23.531,13.209C23.54,12.647 23.384,12.227 23.111,11.907C22.948,12.487 22.698,13.043 22.084,13.979C21.824,14.372 21.364,14.389 21.079,14.75C21.071,14.746 21.064,14.741 21.058,14.737L21.026,14.709L21.021,14.706L21.017,14.704L21.016,14.703L21.013,14.703C21.011,14.703 21.008,14.703 21.006,14.704L21.003,14.704L21.002,14.705C20.989,14.71 20.972,14.725 20.944,14.756L21.006,14.686L21.073,14.594L21.089,14.563L21.094,14.549L21.096,14.539L21.096,14.529L21.095,14.52L21.094,14.517L21.092,14.513L21.091,14.51L21.088,14.507C21.087,14.505 21.085,14.503 21.083,14.501L21.074,14.495L21.034,14.476L21.028,14.472L21.024,14.468L21.022,14.465L21.02,14.463L21.019,14.46L21.018,14.457L21.018,14.454L21.018,14.451L21.019,14.444L21.023,14.433L21.046,14.399L21.06,14.383C21.682,13.696 22.252,13.077 22.498,12.155L22.504,12.134L22.477,12.166C22.39,12.269 22.33,12.313 22.237,12.431L22.347,12.041L22.382,11.914L22.447,11.654L22.499,11.429C22.482,11.419 22.465,11.41 22.447,11.401C22.425,11.392 22.403,11.383 22.381,11.374ZM20.124,17.573C19.772,17.777 19.399,17.965 19.019,18.12C18.639,18.275 18.251,18.399 17.867,18.474C18.636,18.279 19.393,17.965 20.124,17.573ZM13.619,17.776C13.636,17.783 13.653,17.79 13.67,17.796C13.669,17.792 13.669,17.788 13.669,17.784C13.651,17.781 13.634,17.779 13.619,17.776ZM17.263,14.969C16.891,14.768 16.748,14.339 16.519,14.024C15.919,13.404 15.818,12.343 15.661,11.475C15.503,10.632 14.783,10.008 14.283,9.356C13.84,8.995 12.684,7.899 12.138,7.724C11.418,7.425 10.79,7.991 10.191,8.268C9.704,8.469 9.189,8.526 8.759,8.898C8.085,9.763 7.68,9.071 6.898,9.756C5.733,10.976 5.292,9.902 3.691,11.331C3.262,11.588 2.86,11.846 2.343,11.818C1.52,11.779 1.24,10.673 1.884,10.185C2.333,9.683 3.436,9.166 2.888,8.354C2.318,7.846 1.648,8.062 0.97,7.496C0.657,7.986 1.057,8.651 1.571,8.814C1.782,8.945 2.272,8.736 2.373,9.041C2.156,9.475 1.563,9.71 1.285,10.13C0.592,10.93 1.276,12.242 2.258,12.303C2.621,12.42 3.083,12.124 3.318,12.246C3.346,12.532 3.318,12.79 3.375,13.048C3.402,13.33 3.723,13.632 3.547,13.906C3.262,14.151 2.893,14.276 2.517,14.253C2.322,14.478 2.289,14.733 2.173,14.997C2.031,15.255 1.745,15.369 1.544,15.484C1.411,15.685 1.279,15.908 0.999,15.942C0.828,16.143 0.799,16.4 0.742,16.658C1.458,16.848 1.612,16.752 2.002,16.143C2.145,16 2.346,16.114 2.488,16.143C2.895,16.094 3.199,15.822 3.491,15.57C4.533,15.298 4.523,15.98 5.724,15.198C5.925,15.112 6.011,14.883 6.097,14.711C6.197,14.519 6.475,14.149 6.125,14.053C5.226,15.872 3.661,14.391 2.46,15.768C2.276,15.819 2.419,15.533 2.46,15.481C3.322,14.225 5.283,15.331 5.953,13.705C6.07,13.455 6.004,12.458 6.296,12.473C6.325,12.473 6.411,12.502 6.411,12.559C6.133,13.773 6.317,14.15 7.613,13.937C8.057,13.809 9.329,14.262 9.303,13.651C9.303,13.537 9.188,13.48 9.303,13.394C9.331,13.365 9.417,13.394 9.446,13.422C9.527,13.912 9.957,14.272 10.365,14.482C11.188,15.042 10.855,15.773 9.906,15.742C9.591,15.57 9.506,15.255 9.276,14.997C9.009,14.763 8.643,14.875 8.332,14.94C8.177,15.173 8.544,15.451 8.618,15.685C8.761,15.771 8.962,15.627 9.076,15.799C9.191,15.97 9.248,16.143 9.42,16.257C9.916,16.733 10.952,15.897 11.481,15.856C11.944,15.907 12.155,15.485 12.312,15.14C12.573,14.663 11.878,14.192 11.825,13.766C11.667,13.722 11.457,13.599 11.338,13.766C11.426,13.979 11.917,14.759 11.882,14.997C11.818,15.17 11.672,15.569 11.453,15.541C11.511,15.341 11.597,15.113 11.597,14.883C11.492,14.638 11.032,13.93 10.995,13.68C11.087,13.438 11.557,13.578 11.739,13.336C11.94,13.021 11.997,12.707 12.055,12.306C12.067,12.264 12.099,12.232 12.141,12.219C12.42,12.399 12.136,13.261 11.969,13.451C11.953,13.748 12.537,13.549 12.656,13.451C12.877,13.497 13.326,13.276 13.429,13.422C13.295,13.591 13.197,13.786 13.143,13.995C12.971,14.195 12.685,14.339 12.685,14.625C12.716,14.805 12.958,14.515 12.971,14.739C12.722,15.056 12.753,15.133 12.828,15.484C13.089,15.852 13.589,15.549 13.916,15.456C14.468,15.239 15.088,15.582 15.52,14.997C15.636,15.007 15.742,15.071 15.806,15.169C16.125,15.504 16.575,15.682 17.037,15.656C17.225,15.526 16.815,15.423 16.751,15.369C16.55,15.255 16.292,15.083 16.235,14.854C16.16,14.534 15.929,14.241 15.777,13.938C16.446,13.948 16.516,15.344 17.493,15.141C17.541,15.108 17.536,15.072 17.522,15.026L17.263,14.969ZM0.397,15.656L0.398,15.656L0.397,15.656L0.397,15.656C0.058,15.795 0.238,16.214 0.026,16.429C0.026,16.457 -0.032,16.515 0.026,16.544C0.168,16.572 0.283,16.63 0.455,16.658C0.531,16.402 0.605,16.117 0.655,15.885C0.597,15.799 0.512,15.685 0.397,15.656ZM17.714,15.266C17.629,15.375 17.44,15.381 17.358,15.456C17.341,15.477 17.333,15.504 17.335,15.538C17.358,15.641 17.325,15.722 17.262,15.78C17.175,15.874 17.012,15.916 16.865,15.906C16.131,15.914 15.773,15.555 15.473,15.383C15.063,15.648 14.808,15.753 14.272,15.67C13.957,15.645 13.676,15.804 13.37,15.882C13.804,16.254 15.563,16.726 14.915,16.406C13.843,15.799 14.62,16.203 15.56,16.425C16.092,16.556 16.638,16.623 17.185,16.625C18.094,16.325 18.94,15.876 19.612,15.346C19.564,15.345 19.524,15.337 19.494,15.325C19.45,15.307 19.419,15.278 19.399,15.244C19.368,15.192 19.351,15.108 19.422,14.993C19.496,14.874 19.708,14.666 20.156,14.342C20.157,14.341 20.158,14.34 20.16,14.339C21.257,13.603 21.87,12.539 22.248,11.324C21.98,11.227 21.714,11.163 21.45,11.124C21.045,12.13 20.947,12.84 19.992,13.409C18.884,14.134 19.578,13.948 19.589,13.943C19.675,13.908 19.757,13.864 19.834,13.811C19.405,14.5 18.66,14.94 17.771,15.138C17.766,15.194 17.744,15.234 17.714,15.266ZM1.027,15.656C1.227,15.541 1.342,15.341 1.428,15.169C1.366,15.073 1.292,14.946 1.142,14.997C1.005,15.103 0.862,15.198 0.713,15.284C0.641,15.478 0.82,15.723 1.028,15.656L1.027, [...]

2023-12-11 10:48 UTC, PeterShaggyNoble commented on icons/redbull.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Red Bull</title><path d="M22.381,11.374C21.992,12.618 21.362,13.704 20.239,14.456L19.909,14.707L19.645,14.943L19.554,15.0
```suggestion
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Red Bull</title><path d="M22.381,11.374C21.992,12.618 21.362,13.704 20.239,14.456L19.909,14.707L19.645,14.943L19.554,15.05L19.529,15.091L19.518,15.119L19.514,15.135L19.514,15.148L19.515,15.157L19.517,15.164L19.519,15.17L19.524,15.177L19.526,15.179C19.529,15.182 19.532,15.185 19.536,15.187L19.548,15.194L19.559,15.198C19.572,15.202 19.588,15.204 19.605,15.204L19.629,15.204C19.807,15.197 20.141,15.063 20.258,14.959L20.119,15.096L19.955,15.245L19.782,15.391L19.602,15.532L19.417,15.668L19.22,15.802L19.016,15.932L18.81,16.055L18.597,16.173L18.374,16.288L18.148,16.396L17.923,16.496L17.687,16.593L17.642,16.611C15.672,17.374 13.315,17.465 11.728,16.171C12.081,16.515 12.515,16.899 12.927,17.151C12.676,17.108 12.498,16.914 12.261,16.84C12.265,16.848 12.836,17.591 14.543,17.786L14.859,17.818L15.339,17.849L15.803,17.863L16.251,17.854L16.691,17.815L17.155,17.731L17.556,17.624L18.155,17.443L18.449,17.362L18.577,17.329C18.681,17.303 18.791,17.277 18.91,17.252C18.923,17.249 18.937,17.246 18.951,17.243C19.024,17.274 18.427,17.582 17.607,17.813C17.246,17.945 16.868,18.013 16.488,18.04L16.219,18.052L16.003,18.053L15.785,18.048L15.521,18.033L15.206,18.006L14.896,17.972L14.84,17.965C14.439,17.916 14.059,17.858 13.718,17.822L13.717,17.822L13.712,17.822L13.718,17.822C13.748,17.837 13.927,17.918 14.785,18.224C14.724,18.246 14.439,18.285 13.249,17.776C15.666,19.168 18.237,18.535 20.515,17.191L20.867,16.976L20.92,16.942L21.214,16.751L21.365,16.648C21.543,16.527 21.718,16.402 21.891,16.274C21.891,16.283 21.887,16.295 21.887,16.305C21.91,16.309 21.939,16.313 21.962,16.315C21.948,16.356 21.948,16.356 21.748,16.594C22.183,16.243 22.407,15.698 22.868,15.369C22.632,15.842 22.33,16.182 21.768,16.73C21.801,16.706 21.832,16.679 21.863,16.652L21.891,16.626C21.881,16.635 21.872,16.643 21.863,16.652C21.016,17.435 19.901,18.209 18.181,18.617C18.307,18.603 18.432,18.578 18.554,18.544C18.334,18.605 18.327,18.612 18.234,18.643C18.292,18.636 18.292,18.636 18.592,18.575C18.417,18.661 18.215,18.702 17.727,18.801C20.533,18.357 23.448,16.23 23.683,13.352C23.676,13.353 23.669,13.353 23.662,13.352C23.587,13.346 23.53,13.283 23.531,13.209C23.54,12.647 23.384,12.227 23.111,11.907C22.948,12.487 22.698,13.043 22.084,13.979C21.824,14.372 21.364,14.389 21.079,14.75C21.071,14.746 21.064,14.741 21.058,14.737L21.026,14.709L21.021,14.706L21.017,14.704L21.016,14.703L21.013,14.703C21.011,14.703 21.008,14.703 21.006,14.704L21.003,14.704L21.002,14.705C20.989,14.71 20.972,14.725 20.944,14.756L21.006,14.686L21.073,14.594L21.089,14.563L21.094,14.549L21.096,14.539L21.096,14.529L21.095,14.52L21.094,14.517L21.092,14.513L21.091,14.51L21.088,14.507C21.087,14.505 21.085,14.503 21.083,14.501L21.074,14.495L21.034,14.476L21.028,14.472L21.024,14.468L21.022,14.465L21.02,14.463L21.019,14.46L21.018,14.457L21.018,14.454L21.018,14.451L21.019,14.444L21.023,14.433L21.046,14.399L21.06,14.383C21.682,13.696 22.252,13.077 22.498,12.155L22.504,12.134L22.477,12.166C22.39,12.269 22.33,12.313 22.237,12.431L22.347,12.041L22.382,11.914L22.447,11.654L22.499,11.429C22.482,11.419 22.465,11.41 22.447,11.401C22.425,11.392 22.403,11.383 22.381,11.374ZM20.124,17.573C19.772,17.777 19.399,17.965 19.019,18.12C18.639,18.275 18.251,18.399 17.867,18.474C18.636,18.279 19.393,17.965 20.124,17.573ZM13.619,17.776C13.636,17.783 13.653,17.79 13.67,17.796C13.669,17.792 13.669,17.788 13.669,17.784C13.651,17.781 13.634,17.779 13.619,17.776ZM17.263,14.969C16.891,14.768 16.748,14.339 16.519,14.024C15.919,13.404 15.818,12.343 15.661,11.475C15.503,10.632 14.783,10.008 14.283,9.356C13.84,8.995 12.684,7.899 12.138,7.724C11.418,7.425 10.79,7.991 10.191,8.268C9.704,8.469 9.189,8.526 8.759,8.898C8.085,9.763 7.68,9.071 6.898,9.756C5.733,10.976 5.292,9.902 3.691,11.331C3.262,11.588 2.86,11.846 2.343,11.818C1.52,11.779 1.24,10.673 1.884,10.185C2.333,9.683 3.436,9.166 2.888,8.354C2.318,7.846 1.648,8.062 0.97,7.496C0.657,7.986 1.057,8.651 1.571,8.814C1.782,8.945 2.272,8.736 2.373,9.041C2.156,9.475 1.563,9.71 1.285,10.13C0.592,10.93 1.276,12.242 2.258,12.303C2.621,12.42 3.083,12.124 3.318,12.246C3.346,12.532 3.318,12.79 3.375,13.048C3.402,13.33 3.723,13.632 3.547,13.906C3.262,14.151 2.893,14.276 2.517,14.253C2.322,14.478 2.289,14.733 2.173,14.997C2.031,15.255 1.745,15.369 1.544,15.484C1.411,15.685 1.279,15.908 0.999,15.942C0.828,16.143 0.799,16.4 0.742,16.658C1.458,16.848 1.612,16.752 2.002,16.143C2.145,16 2.346,16.114 2.488,16.143C2.895,16.094 3.199,15.822 3.491,15.57C4.533,15.298 4.523,15.98 5.724,15.198C5.925,15.112 6.011,14.883 6.097,14.711C6.197,14.519 6.475,14.149 6.125,14.053C5.226,15.872 3.661,14.391 2.46,15.768C2.276,15.819 2.419,15.533 2.46,15.481C3.322,14.225 5.283,15.331 5.953,13.705C6.07,13.455 6.004,12.458 6.296,12.473C6.325,12.473 6.411,12.502 6.411,12.559C6.133,13.773 6.317,14.15 7.613,13.937C8.057,13.809 9.329,14.262 9.303,13.651C9.303,13.537 9.188,13.48 9.303,13.394C9.331,13.365 9.417,13.394 9.446,13.422C9.527,13.912 9.957,14.272 10.365,14.482C11.188,15.042 10.855,15.773 9.906,15.742C9.591,15.57 9.506,15.255 9.276,14.997C9.009,14.763 8.643,14.875 8.332,14.94C8.177,15.173 8.544,15.451 8.618,15.685C8.761,15.771 8.962,15.627 9.076,15.799C9.191,15.97 9.248,16.143 9.42,16.257C9.916,16.733 10.952,15.897 11.481,15.856C11.944,15.907 12.155,15.485 12.312,15.14C12.573,14.663 11.878,14.192 11.825,13.766C11.667,13.722 11.457,13.599 11.338,13.766C11.426,13.979 11.917,14.759 11.882,14.997C11.818,15.17 11.672,15.569 11.453,15.541C11.511,15.341 11.597,15.113 11.597,14.883C11.492,14.638 11.032,13.93 10.995,13.68C11.087,13.438 11.557,13.578 11.739,13.336C11.94,13.021 11.997,12.707 12.055,12.306C12.067,12.264 12.099,12.232 12.141,12.219C12.42,12.399 12.136,13.261 11.969,13.451C11.953,13.748 12.537,13.549 12.656,13.451C12.877,13.497 13.326,13.276 13.429,13.422C13.295,13.591 13.197,13.786 13.143,13.995C12.971,14.195 12.685,14.339 12.685,14.625C12.716,14.805 12.958,14.515 12.971,14.739C12.722,15.056 12.753,15.133 12.828,15.484C13.089,15.852 13.589,15.549 13.916,15.456C14.468,15.239 15.088,15.582 15.52,14.997C15.636,15.007 15.742,15.071 15.806,15.169C16.125,15.504 16.575,15.682 17.037,15.656C17.225,15.526 16.815,15.423 16.751,15.369C16.55,15.255 16.292,15.083 16.235,14.854C16.16,14.534 15.929,14.241 15.777,13.938C16.446,13.948 16.516,15.344 17.493,15.141C17.541,15.108 17.536,15.072 17.522,15.026L17.263,14.969ZM0.397,15.656L0.398,15.656L0.397,15.656C0.058,15.795 0.238,16.214 0.026,16.429C0.026,16.457 -0.032,16.515 0.026,16.544C0.168,16.572 0.283,16.63 0.455,16.658C0.531,16.402 0.605,16.117 0.655,15.885C0.597,15.799 0.512,15.685 0.397,15.656ZM17.714,15.266C17.629,15.375 17.44,15.381 17.358,15.456C17.341,15.477 17.333,15.504 17.335,15.538C17.358,15.641 17.325,15.722 17.262,15.78C17.175,15.874 17.012,15.916 16.865,15.906C16.131,15.914 15.773,15.555 15.473,15.383C15.063,15.648 14.808,15.753 14.272,15.67C13.957,15.645 13.676,15.804 13.37,15.882C13.804,16.254 15.563,16.726 14.915,16.406C13.843,15.799 14.62,16.203 15.56,16.425C16.092,16.556 16.638,16.623 17.185,16.625C18.094,16.325 18.94,15.876 19.612,15.346C19.564,15.345 19.524,15.337 19.494,15.325C19.45,15.307 19.419,15.278 19.399,15.244C19.368,15.192 19.351,15.108 19.422,14.993C19.496,14.874 19.708,14.666 20.156,14.342C20.157,14.341 20.158,14.34 20.16,14.339C21.257,13.603 21.87,12.539 22.248,11.324C21.98,11.227 21.714,11.163 21.45,11.124C21.045,12.13 20.947,12.84 19.992,13.409C18.884,14.134 19.578,13.948 19.589,13.943C19.675,13.908 19.757,13.864 19.834,13.811C19.405,14.5 18.66,14.94 17.771,15.138C17.766,15.194 17.744,15.234 17.714,15.266ZM1.027,15.656C1.227,15.541 1.342,15.341 1.428,15.169C1.366,15.073 1.292,14.946 1.142,14.997C1.005,15.103 0.862,15.198 0.713,15.284C0.641,15.478 0.82,15.723 1.028,15.656L1.027,15.656ZM9.675,15.026C9.789,15.169 9.789,15.369 9.933,15.484C10.108,15.508 10.285,15.456 10.419,15.341C10.505,15.284 10.391,15.198 10.362,15.112C10.276,14.997 10.334,14.768 10.133,14.768C9.916,14.819 9.678,14.756 9.474,14.825C9.474,14.912 9.6 [...]

2023-12-11 10:49 UTC, merged

2023-12-11 10:51 UTC, adamrusted commented
<img src="https://media3.giphy.com/media/dsGcvvBPzXJ9KSnLPg/200w.gif?cid=6c09b952zf8xg9j317zaolgcnevt3sbvqfes0ayv1g2h5664&ep=v1_gifs_search&rid=200w.gif&ct=g" />