Add Grab
simple-icons/simple-icons pull request #6086
Opened 2021-07-05 14:16 UTC by LitoMore

**Issue:** #6085 
**Alexa rank:** 10,985

### Checklist
- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

Source from https://en.wikipedia.org/wiki/Grab_(company)

2021-07-17 19:32 UTC, ericcornelissen requested changes
SVG looks spot on compared to the source. Just to be clear (e.g. in case this is questioned in the future), where did you source the hex value from? Other than that, just one request for a change and this is good to merge, nice work @LitoMore 👍

2021-07-17 19:32 UTC, ericcornelissen commented on _data/simple-icons.json
> +            "source": "https://en.wikipedia.org/wiki/Grab_(company)"
As per [our source guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#source-guidelines), this should be: 

```suggestion
            "source": "https://en.wikipedia.org/wiki/File:Grab_(application)_logo.svg)"
```

2021-07-18 03:40 UTC, LitoMore commented
@ericcornelissen OK. Let me check the hex value with my former colleague at Grab.

2021-07-18 15:55 UTC, LitoMore commented
@ericcornelissen Color updated. The color is picked from the Grab code base.

2021-07-18 15:57 UTC, LitoMore commented
@ericcornelissen Color updated.

2021-07-18 16:27 UTC, ericcornelissen commented on _data/simple-icons.json
> +            "source": "https://en.wikipedia.org/wiki/File:Grab_(application)_logo.svg)"
My apologies, something went wrong in my previous suggestion :sweat_smile: 

```suggestion
            "source": "https://en.wikipedia.org/wiki/File:Grab_(application)_logo.svg"
```

2021-07-18 16:29 UTC, ericcornelissen commented
@LitoMore, do you have any indication of where we might find this color publicly? If not, I'll leave this for another @simple-icons/maintainers to got their OK and merge it in :slightly_smiling_face:

2021-07-18 17:09 UTC, LitoMore commented
@ericcornelissen We could find their brand color `#00B14F` everywhere in the package.

For example the background of Download App button:

<img width="200" src="https://user-images.githubusercontent.com/8186898/126076000-5ef32d6c-ea25-4946-b0b0-1ff487d44634.png" />

2021-07-18 20:40 UTC, ericcornelissen approved these changes

2021-07-18 20:42 UTC, merged

2021-07-18 20:43 UTC, ericcornelissen commented
Thank you very much for your contribution @LitoMore :confetti_ball: