Add Mock Service Worker icon
simple-icons/simple-icons pull request #6166
Opened 2021-07-25 03:16 UTC by arcyopterix

**Issue:** Add Mock Service Worker (MSW) icon
**Alexa rank:** 422,601

### Checklist
  - [X] I updated the JSON data in `_data/simple-icons.json`
  - [X] I optimized the icon with SVGO or SVGOMG
  - [X] The SVG `viewbox` is `0 0 24 24`

### Description
Adding MSW icon as requested in issue #6160

2021-07-31 16:38 UTC, ericcornelissen requested changes
The Mock Service Worker SVG looks spot on, nice work @arcyopterix! I have one mall request for a change related to the metadata for Mock Service Worker though.

Also, as you already opened #6139 for the Skynet icon, could you remove the file and metadata related to that from this Pull Request? You can get fancy and cherrypick the commits in git, but from our side it's fine if you just remove the file and date in a new commit (this is because we sqaush-and-merge, so the commit history is lost anyway).

2021-07-31 16:38 UTC, ericcornelissen commented on _data/simple-icons.json
> +            "source": "https://github.com/mswjs/msw/blob/master/media/msw-logo.svg"
As per the [Contributing Guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#source-guidelines), this link should include the exact commit hash.
```suggestion
            "source": "https://github.com/mswjs/msw/blob/5e69e91f79af181a544dea290a7fa4391d8d2ad4/media/msw-logo.svg"
```

2023-06-30 12:25 UTC, adamrusted commented
After a _lot_ of dabbling, I've gotten this PR up to speed with a newer variation of the logo. @simple-icons/icon-review for reference.

![mockserviceworker](https://github.com/simple-icons/simple-icons/assets/1830867/3ff3c0e8-1bd6-4bda-90d3-13880acd7744)

2023-09-18 02:02 UTC, PratyushJayachandran approved these changes
Thank you for starting the PR @arcyopterix and thanks @adamrusted for finishing it up. Perfect match 🎉

2023-09-18 02:11 UTC, merged