Remove executable flag from file mode
simple-icons/simple-icons pull request #6185
Opened 2021-07-31 22:22 UTC by janniklasrose

I noticed that 5 svg files (`dgraph`, `django`, `homebrew`, `pagekit`, and `uikit`) have their mode set to `755` instead of `644`. This can lead to git annoyingly reporting changes depending on OS/gitconfig.

It is a very minor problem but also a very easy fix, so I made a PR for it.

2021-08-02 18:17 UTC, ericcornelissen reviewed
This is great! Thank you very much for updating this :smiley: 

I would merge it straight in but I'm wondering if we can catch this in the CI - and if so include that in this Pull Request. Any ideas @janniklasrose?

2021-08-02 18:31 UTC, janniklasrose commented
> I'm wondering if we can catch this in the CI

I had the same thought and including it in this PR would make sense.

Probably the most intuitive check is to use `find` with the `-executable` flag?

verify.yml could be changed to include the following:

```yml
# ...
jobs:
  # ...
  lint:
    steps:
      # ...
      - name: File permissions
        run: find icons/ -type f -executable
```

2021-08-02 18:34 UTC, janniklasrose commented
I don't have too much experience with what the commands in GitHub Actions need to do for it to fail, so perhaps this requires a check that `find` returns nothing?

2021-08-03 21:21 UTC, ericcornelissen requested changes
Thank you very much for looking into this :smiley: Your solution looks great, just have one suggestion to help contributors out when this causes their build to fail.


> verify.yml could be changed to include the following:

I think it makes sense to include it in the lint step of `verify.yml`, good choice :+1: 


> I don't have too much experience with what the commands in GitHub Actions need to do for it to fail, so perhaps this requires a check that find returns nothing?

Indeed, the current solution _should_ work but just to be sure you could include a commit with an executable bit set to verify the behavior (followed by a commit that revert that change, of course).

2021-08-03 21:21 UTC, ericcornelissen commented on .github/workflows/verify.yml
> +            echo "${EXE_FILES}"
I think we should add some additional message here to help people understand what's wrong and how to potentially fix this, e.g.:

```suggestion
            echo "Some files were detected to have their executable bit set, see the list below."
            echo "To fix this you can use 'chmod -x icon/FILE_NAME'\n"
            echo "${EXE_FILES}"
```

2021-08-03 22:43 UTC, janniklasrose commented
I have made the action more verbose as you suggested, including a message if everything goes as it should. I also added the `_data` directory to the `CHECK_DIRS` variable to include it in the test.

Tests for 58e5df5 and 804a182 fail and succeed as expected.

2021-08-04 08:21 UTC, ericcornelissen approved these changes
Cool, this is awesome @janniklasrose, thank you very much for this contribution 🎉 


> I have made the action more verbose as you suggested, including a message if everything goes as it should.

Nice, I like your approach better 😄 


> I also added the `_data` directory to the `CHECK_DIRS` variable to include it in the test.

That makes sense, thank you


> Tests for 58e5df5 and 804a182 fail and succeed as expected.

Awesome

2021-08-04 08:23 UTC, merged

2021-08-04 11:00 UTC, jankeromnes commented
> Cool, this is awesome @jankeromnes, thank you very much for this contribution 🎉

Agree that this is awesome! 🎉 Forwarding all the praise to @janniklasrose 😁

2021-08-04 14:09 UTC, ericcornelissen commented
Apologies for the incorrect at-mention 😅