adding Spring Security logo
simple-icons/simple-icons pull request #6206
Opened 2021-08-07 22:12 UTC by jorgeamadosoria

![springsecurity](https://user-images.githubusercontent.com/15719479/128615009-f4678495-b944-411b-ba33-f81a1d6dec0e.png)

**Issue:**
Adding Spring security logo: https://spring.io/projects/spring-security

### Description
Adding this one from existing svg on https://spring.io/images/projects/spring-security-b712a4cdb778e72eb28b8c55ec39dbd1.svg, which is the projects page for Spring. 
Spring trademark guidelines apply: same colors, same uses.
Added as part of the Spring ecosystem alongside Spring Framework and Spring boot, which already exist. It also has 5k+ stars on github: https://github.com/spring-projects/spring-security

2021-09-03 16:01 UTC, service-paradis requested changes
Thank you @jorgeamadosoria for your contribution 💯 🔑 
I made minor comments. Can you also revert the changes in `package-lock.json`?

2021-09-03 16:27 UTC, jorgeamadosoria commented on _data/simple-icons.json
> +            "hex": "6DB33F",
From the other spring projects. I believe they all should have the same green.

2021-09-03 16:56 UTC, service-paradis commented on _data/simple-icons.json
> +            "hex": "6DB33F",
Well... looks like the other icons on this page uses `#6DB33F`, while Spring security use `#6BB344`. Lets keep it this way.

2021-09-03 17:28 UTC, jorgeamadosoria commented on _data/simple-icons.json
> +            "hex": "6DB33F",
going by the color here: https://spring.io/trademarks
the trademark color is indedd `#6DB33F`. I guess the fill color in Spring Security is a mistake, or there is no established green shade for Spring projects.
We can do whatever, but for the sake of consistency I would stick with `#6DB33F` even if it contradicts the color in the source.

2021-09-03 17:39 UTC, service-paradis commented on _data/simple-icons.json
> +            "hex": "6DB33F",
Yep, this what I'm saying!

2021-09-17 12:43 UTC, service-paradis approved these changes
LGTM 💯 Thank you @jorgeamadosoria!

2021-09-17 12:48 UTC, merged