add docsify icon
simple-icons/simple-icons pull request #6239
Opened 2021-08-10 11:02 UTC by bmpickford

![docsify](https://user-images.githubusercontent.com/12684286/128854866-48aa5f47-701a-4e98-93be-28d4c12a1a9b.png)

**Issue:** https://github.com/simple-icons/simple-icons/issues/6182
**Alexa rank:** 223,023 

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
 * Source: https://github.com/docsifyjs/docsify/blob/develop/docs/_media/icon.svg
 * Used Inkscape to join the paths and resize
 * Hex value was chosen based on fill, not sure as to whether it should just be b/w though or stick with the green as the path shows up white?

2021-10-03 14:39 UTC, bmpickford commented on icons/docsify.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Docsify</title><path d="M11.998 3.214C5.376 3.214 0 8.384 0 14.75c0 1.594.355 2.806 1.025 3.703.67.897 1.639 1.456 2.775
Thanks for providing that @service-paradis. Went back and recreated it, hopefully looks a bit better now

![docsify_1](https://user-images.githubusercontent.com/12684286/135758675-e69b7f25-6665-4ad1-a344-6a08d9849ce5.png)
![docsify_2](https://user-images.githubusercontent.com/12684286/135758678-bf55b7ae-ec80-4bf8-9289-d9aacbbcd3ca.png)

2021-10-04 13:58 UTC, service-paradis commented on icons/docsify.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Docsify</title><path d="M11.998 3.214C5.376 3.214 0 8.384 0 14.75c0 1.594.355 2.806 1.025 3.703.67.897 1.639 1.456 2.775
Good job @bmpickford, looking way better now!
There is still a minor differences in th mouth, which maybe happens during the optimization process. You can try with a precision of 4 if it solves the problem.

![image](https://user-images.githubusercontent.com/12817388/135864579-dda6de9f-45a1-418b-a968-cd8e33a9e6fd.png)

2021-11-25 15:18 UTC, service-paradis requested changes

2021-11-25 15:18 UTC, service-paradis commented on icons/docsify.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Docsify</title><path d="M12 2.86c-6.622 0-12 5.377-12 12 0 1.659.355 2.918 1.025 3.852.669.933 1.64 1.513 2.776 1.864 2.2
Sorry for the delay!

A lot of improvements have being made so far! Ex.
![image](https://user-images.githubusercontent.com/12817388/143466693-4cd1f01e-5688-42c3-adc6-17ddc3bdab68.png)

There are still small differences around the mouth. You probably need to use a precision of 4 while optimizing the icon.

2022-08-25 22:57 UTC, closed without merging