Update Venmo Colour
simple-icons/simple-icons pull request #6284
Opened 2021-08-13 09:55 UTC by PeterShaggyNoble

![Venmo](https://user-images.githubusercontent.com/15157491/129339298-9f510ae0-7579-4d8a-8c6b-48272241696b.png)

**Issue:** n/a
**Alexa rank:** [~2.8k](https://www.alexa.com/siteinfo/venmo.com)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [ ] I optimized the icon with SVGO or SVGOMG
  - [ ] The SVG `viewbox` is `0 0 24 24`

### Description
Colour taken from base-64 encoded SVG in [website](https://venmo.com/) header. I also changed the source to the website as [the old source](https://venmo.com/about/brand/) looks to be outdated, but we should monitor it for updates.

2021-08-23 19:11 UTC, jorgeamadosoria commented
Why is the color different in the header than in the brand guidelines?
How are we decide which one takes precedence?

2021-10-10 07:15 UTC, adamrusted commented
I would say the new hex is sufficient. As @PeterShaggyNoble says, it appears the brand guidelines are outdated - as their app icons use the new colour. In that case, we should follow the brand's lead and use the _new_ colour.

Would it also be worth us considering changing to just the `v` in this PR?

2021-10-10 18:44 UTC, jorgeamadosoria commented
> I would say the new hex is sufficient. As @PeterShaggyNoble says, it appears the brand guidelines are outdated - as their app icons use the new colour. In that case, we should follow the brand's lead and use the _new_ colour.
> 
> Would it also be worth us considering changing to just the `v` in this PR?

I think the full wordmark is fine, but if we are going to change to just the v, I think it should be a white v over a blue background, like in their favicon.

2023-06-30 12:49 UTC, adamrusted commented
Updated to the app icon (had to construct it myself from the PNG found [here](https://venmo.com/about/brand/).

![venmo](https://github.com/simple-icons/simple-icons/assets/1830867/29b02ec7-daef-4e57-acc8-da3e7fc721f7)

2023-08-24 12:53 UTC, service-paradis requested changes

2023-08-24 12:56 UTC, adamrusted commented on icons/venmo.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Venmo</title><path d="M4.78 0v.016A5 5 0 0 0 .011 4.838H0v14.324h.012a5 5 0 0 0 4.767 4.822V24h14.325v-.008a5 5 0 0 0 4.8
You're right. I'd not properly read through this. I'll update _again_ to the full wordmark based on the SVGs at that link..

2023-08-24 19:08 UTC, service-paradis approved these changes
LGTM 🎉

2023-08-24 19:10 UTC, merged