Add Rossmann icon
simple-icons/simple-icons pull request #6459
Opened 2021-09-02 13:27 UTC by dirien

Signed-off-by: Engin Diri <engin.diri@mail.schwarz>

![image](https://user-images.githubusercontent.com/38325136/131851844-12b15600-58f9-4f6d-81ad-06b8ad04b589.png)

**Issue:** #6458 
**Alexa rank:** 33,902
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

2021-12-22 14:25 UTC, dirien commented
Create a comparison
![image](https://user-images.githubusercontent.com/38325136/147107639-2e08e78a-d25a-4d2a-841e-147008f4b1f6.png)

2022-01-14 01:19 UTC, sachinraja requested changes
![image](https://user-images.githubusercontent.com/58836760/149434740-cec8add8-bc06-464e-ba78-fe5f2ada8710.png)

2022-01-15 14:34 UTC, dirien commented
Hi @sachinraja, thanks for pointing out. Fixed it :)

2022-01-23 18:40 UTC, dirien commented
@sachinraja: I used this file -> https://www.rossmann.de/unternehmen/resources/templating-kit/themes/rsmn-corp/5.97.0-2021.08.16.05.53/images/layout/logo.svg

2022-01-25 01:05 UTC, sachinraja requested changes

2022-01-25 01:05 UTC, sachinraja commented on _data/simple-icons.json
> +            "guidelines": "https://www.rossmann.de/unternehmen/presse/media-downloads/logos.html"
Icon is a perfect match, but this page does not seem to exist. It just redirects to https://unternehmen.rossmann.de/presse/mediathek.html which is not a guidelines page.

2022-01-26 08:11 UTC, dirien commented
@sachinraja removed the guideline tags. Looks like they changed their HP

2022-01-28 05:31 UTC, sachinraja approved these changes

2022-01-28 05:34 UTC, merged