Add MinIO Icon
simple-icons/simple-icons pull request #6464
Opened 2021-09-03 18:09 UTC by RalXYZ

![minio](https://user-images.githubusercontent.com/19510622/132047529-9854a231-6f34-404d-abb3-8e082e788431.png)

**Issue:** #6423  
**For detailed information, please check out the issue mentioned above.**  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
This icon is the secondary icon of MinIO.  
From my perspective, the secondary icon is more beautiful than the primary one. What's more, this secondary icon has been widely used. It has been used in their website footer, their [GitHub organisation logo](https://github.com/minio), their [social media](https://twitter.com/Minio) and for their favicon.  
Also, @service-paradis mentioned that the secondary icon could be used.  
I downloaded this "bird" SVG from the footer of their website, followed the procedure written in contributing guidelines, and passed the `lint`.

2021-09-25 21:31 UTC, service-paradis requested changes
Thank you @RalXYZ for your contribution! 

I see some difference comparing with the original (original in red and yours in black):
![image](https://user-images.githubusercontent.com/12817388/134786418-14d9bffc-eb72-4f6f-aaa7-a04a13027e1c.png)
![image](https://user-images.githubusercontent.com/12817388/134786420-6a6ec686-3375-43c2-b192-46ac476a7a23.png)

Can you give this another try?

2021-11-25 15:13 UTC, service-paradis commented
@RalXYZ Do you still plan to work on this icon? If so, can you please give it another try according to comments? If not, I will close this PR for now.

2022-02-22 22:55 UTC, dirien commented
Hi @service-paradis and @RalXYZ,

can you use this svg please:

```svg
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>MinIO</title><path d="M13.2072.006c-.6216-.0478-1.2.1943-1.6211.582a2.15 2.15 0 0 0-.0938 3.0352l3.4082 3.5507a3.042 3.042 0 0 1-.664 4.6875l-.463.2383V7.2853a15.4198 15.4198 0 0 0-8.0174 10.4862v.0176l6.5487-3.3281v7.621L13.7794 24V13.6817l.8965-.4629a4.4432 4.4432 0 0 0 1.2207-7.0292l-3.371-3.5254a.7489.7489 0 0 1 .037-1.0547.7522.7522 0 0 1 1.0567.0371l.4668.4863-.006.0059 4.0704 4.2441a.0566.0566 0 0 0 .082 0 .06.06 0 0 0 0-.0703l-3.1406-5.1425-.1484.1425.1484-.1445C14.4945.3926 13.8287.0538 13.2072.006Zm-.9024 9.8652v2.9941l-4.1523 2.1484a13.9787 13.9787 0 0 1 2.7676-3.9277 14.1784 14.1784 0 0 1 1.3847-1.2148z"/></svg>
```

It should be a perfect fit!

![image](https://user-images.githubusercontent.com/38325136/155233441-eb2cd465-145c-47f5-a42b-e170f14a0723.png)


Otherwhise @service-paradis maybe I commit it into the PR?

2023-08-15 10:26 UTC, LitoMore approved these changes

2023-08-15 10:56 UTC, merged