Request to add Checkmk logo icon
simple-icons/simple-icons pull request #6518
Opened 2021-09-14 12:15 UTC by animesh-anand

Checkmk is a monitoring software.
website: www.checkmk.com
color (hex): #13d389

**Issue: Request to add Checkmk logo icon**
**Alexa rank:430,639**
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

2021-09-16 08:00 UTC, animesh-anand commented
Hi Simple-icons team,

I opened this request to add Checkmk Icon on your website. Can you please check it and let me know if everything is good ?

Thanks.

2021-09-30 16:10 UTC, service-paradis requested changes
Thank you @animesh-anand for your contribution 🎉 

I made some comments. Can you give this another try?

2021-09-30 16:10 UTC, service-paradis commented on _data/simple-icons.json
> +            "source": "https://github.com/animesh-anand/Checkmk-Logo/blob/main/checkmk.svg",
Since they provide official versions for their assets, it would be preferable to use it for the source:
https://checkmk.com/company/brand-assets

2021-09-30 16:10 UTC, service-paradis commented on icons/checkmk.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Checkmk</title><path d="M5.2,8.7v4l4.9-3.2v8.2L12,18.8l1.9-1.1V9.6l4.9,3.2v-4L12,4.5ZM12,0,22.4,6V18L12,24,1.6,18V6Z"/></
I downloaded the SVG assets and took `vertical/checkmk_logo_main_vertical.svg` file to do the comparison. Which file did you use exactly?

With this file, I got some differences in the arrow (original in green overlayed by your version in black):
![image](https://user-images.githubusercontent.com/12817388/135491842-98125361-ba1f-456f-b5ec-1d193b00424c.png)

2021-11-23 13:25 UTC, service-paradis commented on icons/checkmk.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Checkmk</title><path d="M5.2,8.7v4l4.9-3.2v8.2L12,18.8l1.9-1.1V9.6l4.9,3.2v-4L12,4.5ZM12,0,22.4,6V18L12,24,1.6,18V6Z"/></
Hello @animesh-anand,

Welcome to Github and Simple Icons and thank you for your contribution.

The next step would be top make the requested changes in your branch. Once done, you will need to commit those changes and push them again.

Let me know if there is something in particular you need help with!

2021-12-07 11:48 UTC, animesh-anand commented
hi @service-paradis, i am getting an error in a check, can you tell me how to fix this ?

2021-12-08 22:14 UTC, dirien commented
hi @animesh-anand, could you rebase your commit! there are many files in this commit.

and for the lint error, check the that the file is for linux/mac LF and not windows. Or scan the file for whitespaces. Cant see it right now as there are too much files in the commit

2022-01-19 19:05 UTC, closed without merging