Added curl call to auto-release.yml to be created in simple-icons-pdf
simple-icons/simple-icons pull request #6567
Opened 2021-09-19 01:56 UTC by jorgeamadosoria

Partial solution for the automatic release of the PDF repo.
This has been mentioned in several issues in several repos.
**Issues:**: 
#5804

2021-09-19 10:03 UTC, ericcornelissen requested changes
Some preliminary requests for changes

2021-09-19 10:03 UTC, ericcornelissen commented on .github/workflows/publish.yml
> +            -d '{"ref":"develop"}' \
At this stage this should be `master`, [simple-icons-repo](https://github.com/simple-icons/simple-icons-pdf/branches) does not have a `develop` branch.

```suggestion
            -d '{"ref":"master"}' \
```

2021-09-19 10:03 UTC, ericcornelissen commented on .github/workflows/publish.yml
> +    needs: npm
It probably makes more sense to make this depend on `sanity-check`, this is not technically dependent on the `npm` release.

```suggestion
    needs: sanity-check
```

(same for the `font` job)

2021-09-19 10:03 UTC, ericcornelissen commented on .github/workflows/publish.yml
>      needs: npm
This should probably depend on the new `pdf` job as well

```suggestion
    needs: [npm, pdf]
```

2023-07-23 16:29 UTC, adamrusted commented
Closing, as the PDF repo is being archived.

2023-07-23 16:29 UTC, closed without merging