adding Google Campaign Manager
simple-icons/simple-icons pull request #6648
Opened 2021-10-03 20:02 UTC by jorgeamadosoria

![googlecampaignmanager](https://user-images.githubusercontent.com/15719479/135769617-7e7a5285-f864-4ca4-aa44-e04bf1bbefc4.png)

**Issue:** #3601

Had to use precision 5 because the icon was change sizes after running npm run svgo every time. Precision 5 didn't had that issue. If someone makes it work with precision 3, then by all means.
Not happy with the white gaps, but I did what I can.

2023-07-09 14:03 UTC, adamrusted requested changes

2023-07-09 14:03 UTC, adamrusted commented on svgo.config.js
> +            floatPrecision: 5,
```suggestion
            floatPrecision: 3,
```

2023-07-09 14:03 UTC, adamrusted commented on _data/simple-icons.json
> +            "source": "https://www.gstatic.com/analytics-suite/header/suite/v2/ic_campaign_manager.svg"
I would suggest we need to find a better source than a static SVG. Where is this SVG visible?

2023-08-05 23:34 UTC, jorgeamadosoria commented
Closing as I have regrettably withdrawn from this project due to personal circumstances.

2023-08-05 23:34 UTC, closed without merging