Add Ask Different
simple-icons/simple-icons pull request #6666
Opened 2021-10-07 06:46 UTC by alagos

![askdifferent](https://user-images.githubusercontent.com/475834/136332119-de7c3eea-5599-4967-8853-cd524f52b2ee.png)

**Issue:** #6665 
**Alexa rank:** 135

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I picked the hex value from the logo itself, as it was the predominant color in the icon.
Also, I've added the Stack Overflow guidelines, which should apply for the rest of Stack Exchange sites.

2021-11-06 02:26 UTC, sachinraja requested changes
I would invert this svg so only the central logo can be seen and colored. Currently, the central logo is cut out and the background can be colored.
![image](https://user-images.githubusercontent.com/58836760/140594954-e449b751-5a79-4d2c-8f6a-712769d3777e.png)
So only this part remains.

2023-08-16 09:42 UTC, adamrusted commented
Marking as pending, awaiting outcome of #9294. That may determine this PR is out of scope.

2023-08-17 10:17 UTC, LitoMore commented
I think this symbol belongs to Apple. It's the command key symbol.

2023-08-22 16:05 UTC, LitoMore commented
Closing according to #9294.

2023-08-22 16:05 UTC, closed without merging