Optuna
simple-icons/simple-icons pull request #6801
Opened 2021-10-31 06:26 UTC by theUnrealSamurai

**Issue:**
**Alexa rank:**
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

2021-11-05 20:45 UTC, dirien requested changes

2021-11-05 20:45 UTC, dirien commented on icons/optuna.svg
> +<svg version="1.0" xmlns="http://www.w3.org/2000/svg" width="296" height="280" viewBox="0 0 24 24"><path d="M102.5 1.1c-17 2.2-35.1 8.7-50.2 18.1-10.2 6.3-27 22.3-33.3 31.7C-15.4 102.3-1.2 164.8 51.6
Can you check the icon file:

best thing is o run `npm run svgo -- icons/optuna.svg` and then `npm run lint`


```
  x attr-1 0:0 Expected attribute 'role', didn't find it
                 At node <svg> (0:0)
  x attr-1 0:0 Found extra attributes ["version","width","height"] with whiteli
               sting enabled
                 At node <svg> (0:0)
  x icon-title No icon with title "" found in simple-icons.json
  x icon-size Size of <path> must be exactly 24 in one dimension; the size is c
              urrently 219.579 x 209.824
  x extraneous Unexpected character(s), most likely extraneous whitespace, dete
               cted in SVG markup
  x icon-centered <path> must be centered at (12, 12); the center is currently 
                  (110.058, 105.088)
  x elm Found 0 elements for 'svg > title', expected 1
  x elm 0:99 Found 3 elements for 'svg > path', expected 1
               At node <path> (0:99)
  x elm 0:561 Found 3 elements for 'svg > path', expected 1
                At node <path> (0:561)
  x elm 0:1041 Found 3 elements for 'svg > path', expected 1
                 At node <path> (0:1041)
  x elm 0:99 Element disallowed
               At node <path> (0:99)
  x elm 0:561 Element disallowed
                At node <path> (0:561)
  x elm 0:1041 Element disallowed
                 At node <path> (0:1041)
```

2023-07-09 14:19 UTC, adamrusted commented
Even after tidying up this SVG, it doesn't quite line up to the raster (see red in background for SVG)

![image](https://github.com/simple-icons/simple-icons/assets/1830867/e32adc4c-be96-42c2-bf8e-6f4c2dc7605c)

2023-08-15 10:19 UTC, adamrusted commented
@theUnrealSamurai - could you please close this PR, or update based on feedback? I'll close this in a few days if we don't hear anything.

2023-08-20 16:44 UTC, adamrusted commented
Closing due to lack of activity.

2023-08-20 16:44 UTC, closed without merging