Unity update
simple-icons/simple-icons pull request #6875
Opened 2021-11-18 11:53 UTC by antonioo-c

![unity](https://user-images.githubusercontent.com/72902999/142410326-e7a2ae40-b220-4161-9df2-c772c69bdf37.png)

**Issue:** #6873
**Alexa rank:** 1,962
  

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json`   **(No Need)**
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Nothing

2021-11-19 16:29 UTC, dirien requested changes
hi @antonioo-c,

thanks for the contribution.

i see some slght differences. (pink is the original one)
![image](https://user-images.githubusercontent.com/38325136/142657629-e3cfcdd0-a382-45d8-9267-cb2b9667d1e7.png)

2021-11-20 05:51 UTC, antonioo-c commented
It should be OK now, @dirien

2021-11-22 12:01 UTC, antonioo-c commented
@dirien Can you take a look please?

2021-11-22 17:39 UTC, dirien commented
I would ask another @simple-icons/maintainers to review it. I use the svg on this side. https://blog.unity.com/news/say-hello-to-our-new-logo-and-product-identity-system and i get still a difference.

2021-11-22 17:39 UTC, dirien reviewed
I would ask another @simple-icons/maintainers to review it. I use the svg on this side. https://blog.unity.com/news/say-hello-to-our-new-logo-and-product-identity-system and i get still a difference.

2021-11-22 21:07 UTC, sachinraja requested changes
I am also seeing a few slight differences compared to the one from https://brandguide.brandfolder.com/unity/downloadbrandassets. Can you update the `"guidelines"` and `"source"` in `_data/simple-icons.json` to point to `https://brand.unity.com/` and use the icon from the brandfolder (which is linked from unity's brand page)?

2021-11-26 07:23 UTC, antonioo-c commented
OK! I'll try to work on that.

2021-11-26 08:29 UTC, antonioo-c commented
![image](https://user-images.githubusercontent.com/72902999/143550308-d375181e-aa2c-4911-b4ea-d7bdc0c75af2.png)
After deleting the colinear-segment directly, I got this slight differences.
Could you give me some suggestions on how to eliminate this?
Thanks a lot.
@sachinraja

2021-11-26 08:49 UTC, antonioo-c commented
I tried a few times again but found something strange...
I first downloaded the standard svg from the offical brandset you gave which I call it version1.0
secondly I adjust the size into 24x24 and deleted the text part, which i call it version2.0
finally I optimized it using SVGOMG online tool and manually deleted colinear segment, I call it version 3.0.

1.there are no difference between version1.0 and version2.0
2.there are no difference between version2.0 and version3.0
3.BUT there are that slight difference between version1.0 and version3.0, which i uploaded in the last comment.

Now I am REALLY confused, could anyone help me out?

2021-11-26 09:14 UTC, antonioo-c reviewed
forgot ,

2021-11-26 09:27 UTC, antonioo-c commented
I don't see any differences locally and I updated the json in _data, can you take a look again? thanks a lot.
@sachinraja

2021-12-11 15:42 UTC, antonioo-c commented
@sachinraja can you take a look please?

2021-12-11 15:55 UTC, sachinraja requested changes
Great job, the icon is a perfect match. Just one small suggestion

2021-12-11 15:55 UTC, sachinraja commented on _data/simple-icons.json
>              "hex": "000000",
```suggestion
            "hex": "FFFFFF",
```
I think white is used more prominently than black.

2021-12-13 05:08 UTC, antonioo-c commented
> Great job, the icon is a perfect match. Just one small suggestion

done

2021-12-14 00:06 UTC, sachinraja approved these changes

2021-12-14 00:08 UTC, merged