Upgrade SVGLint dependency
simple-icons/simple-icons pull request #6970
Opened 2021-12-19 14:18 UTC by ericcornelissen

### Description

Opening this PR to upgrade the [SVGLint](https://github.com/birjolaxew/svglint) dependency to `v2.0.0`, the major version bump requires a higher minimum NodeJS version for development than is currently mentioned in this project's Contributing Guidelines.

2021-12-19 15:30 UTC, sachinraja commented
I think we should do this in #6946

2021-12-19 15:39 UTC, sachinraja commented
Nevermind, I'll merge from develop in the other PR.

2021-12-19 15:39 UTC, sachinraja requested changes
I think we should update `"engines"` in package.json too

2021-12-19 15:42 UTC, ericcornelissen commented
> I think we should update "engines" in package.json too

I don't think so because that also affects people with `simple-icons` as a dependency, and to them the v12.20.0 restriction does not apply.

2021-12-19 15:45 UTC, sachinraja commented
Ah ok, this looks good to me then.

2021-12-19 15:45 UTC, sachinraja approved these changes

2021-12-19 16:11 UTC, LitoMore approved these changes
> I think we should update "engines" in package.json too

@ericcornelissen is right. We don't need to update the `engines` field. We have already documented the the requirement in readme for developers.

Good job! I will move our `.svglintrc.js` to ESM in another PR.

2021-12-19 16:31 UTC, LitoMore commented on CONTRIBUTING.md
> +* Make sure you have [NodeJS](https://nodejs.org/en/download/) installed. At least version 12.20.0 is required.
I'm thinking about this part. The exact version range should be `^12.20.0 || ^14.13.1 || >=16.0.0`.

```suggestion
* Make sure you have [Node.js](https://nodejs.org/en/download/) installed. At least version `^12.20.0 || ^14.13.1 || >=16.0.0` is required.
```

2021-12-19 21:50 UTC, sachinraja commented
> Good job! I will move our .svglintrc.js to ESM in another PR.

I'll do that in #6946

2021-12-21 18:13 UTC, mondeja approved these changes
Great!

2021-12-21 18:14 UTC, merged