Add Odoo icon
simple-icons/simple-icons pull request #6980
Opened 2021-12-24 14:56 UTC by lucas-louis

![odoo](https://user-images.githubusercontent.com/72020723/147360167-bbf8b5ac-a34f-4c0f-a62c-cfa06500ca09.png)

**Issue: #6961**
**Alexa rank: 1,429**
  

### Checklist
  - [X] I updated the JSON data in `_data/simple-icons.json`
  - [X] I optimized the icon with SVGO or SVGOMG
  - [X] The SVG `viewbox` is `0 0 24 24`

### Description

The color hex value is from: https://www.odoo.com/page/brand-assets
I optimized the lofo with SVGO

2021-12-25 16:30 UTC, dirien commented on _data/simple-icons.json
> +            "source": "https://www.odoo.com/fr_FR/page/brand-assets#part_6",
Can you enter just the root for the source?

2021-12-25 16:31 UTC, dirien submitted a review, later dismissed
hi @lucas-louis,

thanks for this contribution.

I see some differences, maybe up the precision?
![image](https://user-images.githubusercontent.com/38325136/147389402-d6200ba3-bf30-4920-a72d-882ae07fd465.png)


And i used as reference the original one from Odoo website.

https://odoocdn.com/openerp_website/static/src/img/2016/logos/odoo_logo.svg

2023-08-15 10:46 UTC, LitoMore submitted a review, later dismissed
<img width="556" alt="image" src="https://github.com/simple-icons/simple-icons/assets/8186898/8f87a06b-286d-4d80-94fd-6a76b7498d87">

@adamrusted This looks not correct in the preview. Could you check those shapes?

2023-08-15 10:47 UTC, adamrusted commented
Sure can. Bear with.

2023-08-15 11:11 UTC, LitoMore commented
<img width="744" alt="image" src="https://github.com/simple-icons/simple-icons/assets/8186898/0e66f2be-32c6-45b6-94be-257c86cf0e34">

It's kind of weird, the icon width shown in Inkscape is not `24.000` but it passed our CI.

2023-08-15 11:16 UTC, adamrusted commented
> It's kind of weird, the icon width shown in Inkscape is not `24.000` but it passed our CI.

Very odd. The compound paths in this one were really playing up for me...

2023-09-14 08:16 UTC, PratyushJayachandran approved these changes

2023-09-14 08:16 UTC, PratyushJayachandran commented on icons/odoo.svg
I tried to recreate and ended up with the exact same SVG code.

2023-10-02 07:07 UTC, PratyushJayachandran approved these changes

2023-10-02 07:07 UTC, PratyushJayachandran commented on icons/odoo.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Odoo</title><path d="M11.224 8.184a.576.576 0 0 0-.576.576v1.845a2.896 2.896 0 1 0 1.152 2.312V8.76a.576.576 0 0 0-.576-.
```suggestion
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Odoo</title><path d="M2.9 10C1.3 10 0 11.3 0 12.9c0 1.6 1.3 2.9 2.9 2.9s2.9-1.3 2.9-2.9c0-1.6-1.3-2.9-2.9-2.9zm0 4.6c-.9 0-1.7-.8-1.7-1.7s.8-1.7 1.7-1.7 1.7.8 1.7 1.7-.8 1.7-1.7 1.7zm8.4-6.4c-.3 0-.6.3-.6.6v1.7c-.5-.4-1.1-.5-1.7-.5-1.7 0-2.9 1.2-2.9 2.9s1.3 2.9 2.9 2.9 2.9-1.3 2.9-2.9V8.8c0-.3-.3-.6-.6-.6zM9 14.6c-.9 0-1.7-.8-1.7-1.7S8 11.2 9 11.2s1.7.8 1.7 1.7-.8 1.7-1.7 1.7zM21.1 10c-1.6 0-2.9 1.3-2.9 2.9 0 1.6 1.3 2.9 2.9 2.9s2.9-1.3 2.9-2.9c0-1.6-1.3-2.9-2.9-2.9zm0 4.6c-.9 0-1.7-.8-1.7-1.7s.8-1.7 1.7-1.7 1.7.8 1.7 1.7-.8 1.7-1.7 1.7zM15 10c-1.6 0-2.9 1.3-2.9 2.9 0 1.6 1.3 2.9 2.9 2.9s2.9-1.3 2.9-2.9c0-1.6-1.3-2.9-2.9-2.9zm0 4.6c-.9 0-1.7-.8-1.7-1.7s.8-1.7 1.7-1.7 1.7.8 1.7 1.7-.7 1.7-1.7 1.7z"/></svg>
```

2023-10-02 07:09 UTC, PratyushJayachandran commented
@adamrusted @LitoMore please re review the PR

2023-11-18 13:10 UTC, adamrusted submitted a review, later dismissed
![image](https://github.com/simple-icons/simple-icons/assets/1830867/8625e1dc-f753-4452-a302-0c2525a9147f)
@PratyushJayachandran - could you take another look please?

2023-11-20 07:33 UTC, PratyushJayachandran commented on icons/odoo.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Odoo</title><path d="M21.101 15.787A2.899 2.899 0 1 1 24 12.89c0 1.6-1.298 2.898-2.899 2.898zm0-1.198a1.7 1.7 0 1 0 0-3.4
```suggestion
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Odoo</title><path d="M21.1 15.796a2.9 2.9 0 1 1 0-5.8 2.9 2.9 0 0 1 0 5.8zm0-1.2a1.7 1.7 0 1 0 .002-3.4H21.1a1.7 1.7 0 0 0 0 3.4zm-6.065 1.2a2.9 2.9 0 1 1 2.9-2.9c0 1.6-1.3 2.9-2.9 2.9zm0-1.2a1.7 1.7 0 0 0 .001-3.4h-.001a1.7 1.7 0 0 0 0 3.4zm-3.17-1.738c0 1.62-1.298 2.938-2.898 2.938s-2.9-1.314-2.9-2.936S7.247 10 8.967 10c.636 0 1.224.134 1.7.484v-1.68a.6.6 0 0 1 1.2 0v4.054h-.002zm-2.898 1.74a1.7 1.7 0 0 0 .002-3.4h-.002a1.7 1.7 0 0 0 0 3.4zM2.9 15.796a2.9 2.9 0 1 1 2.9-2.9c0 1.6-1.3 2.9-2.9 2.9zm0-1.2a1.7 1.7 0 0 0 .001-3.4H2.9a1.7 1.7 0 0 0 0 3.4z"/></svg>
```
Fix errors

2023-11-20 07:35 UTC, PratyushJayachandran commented
> @PratyushJayachandran - could you take another look please?

I fixed the icon but running into that new line error. Please check the icon again.

2023-11-20 08:48 UTC, adamrusted requested changes
Looks like there's a precision issue here. The paths are a pretty close match, but only slightly out across the board. Could you regenerate using `npx svgo icons/odoo.svg --p 4` and see if that gives us a better outcome?

2023-11-20 09:12 UTC, PratyushJayachandran commented on icons/odoo.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Odoo</title><path d="M21.1 15.796a2.9 2.9 0 1 1 0-5.8 2.9 2.9 0 0 1 0 5.8zm0-1.2a1.7 1.7 0 1 0 .002-3.4H21.1a1.7 1.7 0 0
```suggestion
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Odoo</title><path d="M21.1002 15.7957c-1.6015 0-2.8997-1.2983-2.8997-2.8998s1.2983-2.8997 2.8997-2.8997c1.6015 0 2.8998 1.2982 2.8998 2.8997 0 1.5999-1.2979 2.8998-2.8998 2.8998zm0-1.2c.9388.0006 1.7003-.7601 1.7008-1.6989.0004-.9388-.7602-1.7003-1.699-1.7007h-.0018c-.9388.0004-1.6994.7619-1.699 1.7007.0005.9381.761 1.6985 1.699 1.699zm-6.0655 1.2c-1.6014 0-2.8997-1.2983-2.8997-2.8998s1.2983-2.8997 2.8997-2.8997c1.6015 0 2.8998 1.2982 2.8998 2.8997 0 1.5999-1.2999 2.8998-2.8998 2.8998zm0-1.2c.9389.0006 1.7003-.7601 1.7008-1.6989.0005-.9388-.7602-1.7003-1.699-1.7007h-.0018c-.9388.0004-1.6994.7619-1.699 1.7007.0005.9381.761 1.6985 1.699 1.699zM11.865 12.858c0 1.6199-1.2979 2.9378-2.8977 2.9378s-2.8998-1.314-2.8998-2.9358 1.1799-2.8597 2.8998-2.8597c.6359 0 1.2239.134 1.6998.484v-1.68a.6.6 0 0 1 1.2 0v4.0537h-.002zm-2.8977 1.7399c.9388.0005 1.7002-.7602 1.7007-1.699.0005-.9388-.7602-1.7003-1.699-1.7007h-.0017c-.9389.0004-1.6995.7619-1.699 1.7007.0004.9381.7608 1.6985 1.699 1.699zm-6.0675 1.1979C1.2983 15.7957 0 14.4974 0 12.8959s1.2983-2.8997 2.8998-2.8997 2.8997 1.2982 2.8997 2.8997c0 1.5999-1.2999 2.8998-2.8997 2.8998zm0-1.2c.9388.0006 1.7002-.7601 1.7007-1.699.0005-.9387-.7602-1.7002-1.699-1.7006h-.0017c-.9388.0004-1.6995.7619-1.699 1.7007.0004.9381.7608 1.6985 1.699 1.699z"/></svg>
```

2023-11-20 09:13 UTC, PratyushJayachandran commented
> Looks like there's a precision issue here. The paths are a pretty close match, but only slightly out across the board. Could you regenerate using `npx svgo icons/odoo.svg --p 4` and see if that gives us a better outcome?

Done. Please check again :)

2023-11-22 15:07 UTC, adamrusted approved these changes

2023-11-22 15:08 UTC, merged