Brand name update to Wise
simple-icons/simple-icons pull request #7003
Opened 2021-12-30 15:32 UTC by adsingh14

Official link: https://wise.com/gb/blog/world-meet-wise

**Issue:** #7002 
**Alexa rank:**
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [ ] I optimized the icon with SVGO or SVGOMG
  - [ ] The SVG `viewbox` is `0 0 24 24`

### Description

2022-01-02 14:59 UTC, dirien requested changes
Hi @adsingh14,

Can you check the logo again? I used the officel svg `https://wise.com/public-resources/assets/logos/wise/brand_logo_inverse.svg`

![image](https://user-images.githubusercontent.com/38325136/147879795-41b6a4c7-dea6-400c-b405-cb6594d8b36d.png)

2022-01-03 15:19 UTC, adamrusted commented
We also won't be able to merge this until a major release in it's current state. Could you please split this into _two_ PRs? One with the new Wise icon, and another removing TransferWise? That way we can implement the new icon sooner, and deprecate the old icon from v7.

2022-01-03 15:24 UTC, adsingh14 commented
> Hi @adsingh14,
> 
> Can you check the logo again? I used the officel svg `https://wise.com/public-resources/assets/logos/wise/brand_logo_inverse.svg`
> 
> ![image](https://user-images.githubusercontent.com/38325136/147879795-41b6a4c7-dea6-400c-b405-cb6594d8b36d.png)
> 

Okay, I'll create a new branch.

2022-01-03 15:35 UTC, adsingh14 commented
> We also won't be able to merge this until a major release in it's current state. Could you please split this into _two_ PRs? One with the new Wise icon, and another removing TransferWise? That way we can implement the new icon sooner, and deprecate the old icon from v7.

Okay, I'll create a new PR with current name.

2022-01-03 15:41 UTC, adamrusted commented
@adsingh14 we can keep this open, but repurpose the PR for the removal of TransferWise. That way, we'll remember it needs doing when we are working on the next big release!

2022-01-03 15:43 UTC, adamrusted commented
If you restore the branch, we can reopen the PR and use the base from this to implement the removal. Do you want to do that, or shall I open a new PR for its removal?

2022-01-03 15:46 UTC, adamrusted requested changes
@adsingh14 - I've just highlighted the two segments of code that'd need to go in order for this to be a 'removal' PR. Once that's done, I'll tag this as a v7 PR and we can leave it until the next release!

2022-01-03 15:46 UTC, adamrusted commented on icons/wise.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Wise</title><path d="m3.6426 0 3.7383 6.3594-6.6602 6.3613H12.043l1.1816-2.7734H7.4883l3.5879-3.588-2.084-3.5878h9.7324L9
```suggestion
```

2022-01-03 15:46 UTC, adamrusted commented on _data/simple-icons.json
> +        },
```suggestion
```

2022-01-03 15:50 UTC, adsingh14 commented
> @adsingh14 - I've just highlighted the two segments of code that'd need to go in order for this to be a 'removal' PR. Once that's done, I'll tag this as a v7 PR and we can leave it until the next release!

I think this PR is unnecessary because of recent 'Wise' PR ! Removing this branch would automatically target to the current 'TransferWise' icon. Therefore, I'm removing this branch.

2022-01-03 15:52 UTC, closed without merging