adding NetBox icon
simple-icons/simple-icons pull request #7087
Opened 2022-01-23 20:14 UTC by jorgeamadosoria

![netbox](https://user-images.githubusercontent.com/15719479/150696333-d06c9371-4682-4169-b984-eaefd7f8a990.png)

issue: #7084 

Gaps are on purpose to keep the 3D perspective of the icon.

2022-01-25 01:10 UTC, sachinraja requested changes
Differences along the edges on the right side:
![image](https://user-images.githubusercontent.com/58836760/150891770-27aa82f1-cb2e-4f38-822b-26c907838944.png)

2022-01-25 19:37 UTC, jorgeamadosoria commented
I've removed the gaps. The icon is now exactly the same one as it is in the svg source.

2022-02-05 12:58 UTC, dirien requested changes
Hi @jorgeamadosoria 

I see some differences:

![image](https://user-images.githubusercontent.com/38325136/152643095-97a4d22f-94c6-49c9-9061-053756f6c4f5.png)


I use https://netbox.readthedocs.io/en/stable/netbox_logo.svg as base

2022-03-05 20:48 UTC, jorgeamadosoria commented
I updated the icon with precision 5. I don't see differences. Please check @dirien

2022-03-18 00:55 UTC, sachinraja commented
Still seeing differences:
![image](https://user-images.githubusercontent.com/58836760/158917188-b2fc1960-69fa-455e-b519-cf3b891da1dd.png)

Not sure what's going on

2022-03-18 04:30 UTC, jorgeamadosoria commented
> Still seeing differences: ![image](https://user-images.githubusercontent.com/58836760/158917267-da19f18e-cc7e-4e41-9e33-f494991945bb.png)
> 
> Not sure what's going on

what are you using for comparison?

2022-03-19 06:04 UTC, sachinraja commented
I used https://netbox.readthedocs.io/en/stable/netbox_logo.svg

2023-07-09 14:25 UTC, adamrusted requested changes

2023-07-09 14:25 UTC, adamrusted commented on _data/simple-icons.json
> +            "source": "https://netbox.readthedocs.io/en/stable/development/style-guide/",
```suggestion
            "source": "https://netbox.readthedocs.io",
```

The logo SVG itself can be found on the homepage.

2023-07-09 14:25 UTC, adamrusted commented on icons/netbox.svg
This might be better with gaps to delineate the different colours?

2023-08-05 23:34 UTC, jorgeamadosoria commented
Closing as I have regrettably withdrawn from this project due to personal circumstances.

2023-08-05 23:34 UTC, closed without merging