Added Meta logo
simple-icons/simple-icons pull request #7318
Opened 2022-04-12 23:40 UTC by timcole

![](https://t.pics/hiMr4hZE6Oo.png)

**Issue:** closes #6791

**Similarweb rank:** [3](https://www.similarweb.com/website/facebook.com/#overview)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
The hex value was picked by using the middlemost colour of their looping gradient.

2022-04-15 00:21 UTC, sachinraja requested changes
There are slight differences all around (red is yours):
![image](https://user-images.githubusercontent.com/58836760/163496568-5c041b37-357a-4469-bb45-a1db88a484cf.png)

This is a tough one to convert. Not sure how to fix it.

2022-04-15 02:31 UTC, timcole commented
I'm honestly not too sure how to fix this. I believe this is only because it had to make the height a whole number since the center lint complained being it was a fraction of a pixel. I can take a better look on Monday. (OOO for the holiday this weekend)

2022-04-24 02:49 UTC, sachinraja commented
I had some problem trying to add it before so I'm glad you were able to figure it out. Great job!

2022-04-24 02:49 UTC, sachinraja approved these changes

2022-04-24 02:51 UTC, merged