Add 7Zip icon
simple-icons/simple-icons pull request #7334
Opened 2022-04-16 22:29 UTC by zrfisaac

![7zip](https://user-images.githubusercontent.com/16006294/163693202-cedec46e-2a12-40d4-a093-af8fcc7b1e69.png)

**Issue:** #5872

**Similarweb rank:** [27,788](https://www.7-zip.org/download.html)

### Checklist
  - [X] I updated the JSON data in `_data/simple-icons.json`
  - [X] I optimized the icon with SVGO or SVGOMG
  - [X] The SVG `viewbox` is `0 0 24 24`

### Description
7-Zip is a file archiver with a high compression ratio.

2022-04-24 02:43 UTC, sachinraja commented
Yes, we do need more info on how you obtained the SVG icon (for your other PRs too)

2022-04-24 21:04 UTC, zrfisaac commented
Year I didn't find the icon either, there is no SVG official file, so I made one by myself.
Now I have a question, can I do that?
Or must exist an official publication of the SVG file?

2022-04-24 21:21 UTC, zrfisaac commented
I've created An [issue](https://github.com/jinfeihan57/p7zip/issues/175) in the official 7zip github repository to upload the SVG file with the logo.
You can see in [7zip page](https://www.7-zip.org/links.html) that this [repository](https://github.com/jinfeihan57/p7zip) is official :
![image](https://user-images.githubusercontent.com/16006294/164997014-c3819aff-97bd-46f6-9bd5-b20c4adc0a62.png)
Or you need that this SVG file must be uploaded in [Source Forge](https://sourceforge.net/projects/sevenzip/) repository ?

2022-04-26 20:26 UTC, sachinraja commented
I think we can use Source Forge as a source so that could work

2022-04-26 20:30 UTC, zrfisaac commented
I asked them, but apparently they don't have a svg file.
I’m working with that.
After they publish one I will ask you to merge.

Wait a while until I get it done.
🙌

2022-04-27 06:39 UTC, antermin commented
jinfeihan57's repo isn't really official - being mentioned in the official 7-Zip website does not make it official, and it is actually a fork of p7zip, while p7zip is a port of 7-Zip to POSIX systems.

The official repo should be the one [on SourceForge by Igor Pavlov](https://sourceforge.net/projects/sevenzip/).

-----

Igor Pavlov created 7-Zip but it was Windows-only, so someone ported 7-Zip to POSIX systems (Linux, macOS, etc.) as [p7zip](https://sourceforge.net/projects/p7zip/).

However, p7zip is abandoned for several years already (no updates since 2016), so jinfeihan57 started a new fork. A few Linux distros (e.g. Arch Linux) switched to jinfeihan57's fork.

As Igor Pavlov has recently added official Linux/BSD/macOS support in 7-Zip, openSUSE Tumbleweed dropped p7zip and switched to upstream 7-Zip 21.07, and Debian, FreeBSD, etc. are now offering 7-Zip 21.07.

2022-04-28 15:09 UTC, zrfisaac commented
Okey, I'm working on updating the official repository with this svg file, I will inform you when it is done.

2023-07-09 15:04 UTC, adamrusted commented
Hey @zrfisaac - any joy getting an official SVG hosted for 7Zip?
No stress if not - just running through older PRs!

2023-07-12 10:24 UTC, zrfisaac commented
> Hey @zrfisaac - any joy getting an official SVG hosted for 7Zip? No stress if not - just running through older PRs!

I've been off these days due to my job, but I'm back now. I will work on this and answer you as soon as possible! 🙌

2023-11-21 16:58 UTC, PeterShaggyNoble commented
Any update on this, @zrfisaac? If not then I think we should just proceed with reviewing this PR as-is.

2023-12-07 10:42 UTC, PeterShaggyNoble requested changes
Would you mind having another look at this, please, @zrfisaac? In the absence of anything better to go on, we'll have to run with [their primary logo](https://www.7-zip.org/7ziplogo.png) and I'm seeing [major differences](https://github.com/simple-icons/simple-icons/assets/15157491/2d565cf9-3923-4a9c-b7a3-815b99cf523d) in your version , in red.

There's actually [an SVG on Wikimedia](https://commons.wikimedia.org/wiki/File:7ziplogo.svg) that might provide a better starting point.

2023-12-14 14:32 UTC, PeterShaggyNoble requested changes

2023-12-14 14:32 UTC, PeterShaggyNoble commented on _data/simple-icons.json
> +            "source": "https://www.7-zip.org/download.html"
```suggestion
            "source": "https://commons.wikimedia.org/wiki/File:7ziplogo.svg"
```

2023-12-14 14:32 UTC, PeterShaggyNoble commented on icons/7zip.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>7Zip</title><path d="M0 4.479v15.043h24V7.836H10.757V4.479zm1.39 1.326h8.074V7.48c-.665.638-1.345 1.557-2.033 2.755a15.95
```suggestion
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>7Zip</title><path d="M0 18.858h24V8.181H10.717V5.142H0ZM2.021 7.271h6.657v1.994c-1.74 2.09-2.84 4.502-2.948 7.404H3.477c.09-2.501.353-4.954 2.283-6.994l.033-.033H2.021Zm8.45 1.253h13.215v10.143H10.47Zm6.01 1.213v6.871h1.482v-6.87Zm2.755.043v6.912h1.616v-2.42h1.029c.43-.001.754-.29.969-.716.427-.848.429-2.257-.024-3.092-.227-.419-.571-.697-1.033-.684zm-7.924.002v1.596h2.217l-2.304 3.736v1.54h4.287V15.1h-2.698l2.786-3.909v-1.41Zm9.452 1.512h.595c.164-.006.287.081.371.217.17.273.172.736.004.99a.364.364 0 0 1-.373.176l-.55.047z"/></svg>
```

2024-01-09 09:29 UTC, adamrusted approved these changes

2024-01-09 09:30 UTC, merged