Add Rubocop icon
simple-icons/simple-icons pull request #7380
Opened 2022-05-05 01:12 UTC by zrfisaac

![rubocop](https://user-images.githubusercontent.com/16006294/166850637-ecfc379a-664c-4e99-9f87-a0ce38f3942c.png)

**Issue:** #7368

**Similarweb rank:** [1,379,435](https://www.similarweb.com/website/rubocop.org/#overview)

### Checklist
  - [X] I updated the JSON data in `_data/simple-icons.json`
  - [X] I optimized the icon with SVGO or SVGOMG
  - [X] The SVG `viewbox` is `0 0 24 24`

### Description
RuboCop is a Ruby code style checker (linter) and formatter based on the community-driven [Ruby Style Guide](https://rubystyle.guide/).
RuboCop is extremely flexible and most aspects of its behavior can be tweaked via various configuration options. In practice RuboCop supports pretty much every (reasonably popular) coding style that you can think of.
Apart from reporting problems in your code, RuboCop can also automatically fix some of the problems for you.

2022-05-05 13:58 UTC, pboling commented
CC @bbatsov the final SVG logo!

2022-05-05 15:12 UTC, sisp requested changes

2022-05-07 21:58 UTC, zrfisaac commented
Thanks for the help @sisp I didn't notice this, next time I will be more careful.

2022-05-08 12:44 UTC, sisp approved these changes
LGTM now! :tada: Thanks for making the requested changes, @zrfisaac.

This PR can be merged IMO.

/cc @sachinraja

2022-05-08 17:30 UTC, merged