Swr icon
simple-icons/simple-icons pull request #7399
Opened 2022-05-09 21:14 UTC by deepmalamittal

![swr](https://user-images.githubusercontent.com/79153420/167499240-4c6e9bda-1821-4c6c-b8b2-f7a4db6150e6.png)

**Issue:** https://github.com/simple-icons/simple-icons/issues/7384

**Similarweb rank:**
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

2022-05-10 14:30 UTC, sisp requested changes

2023-09-15 06:26 UTC, PratyushJayachandran commented on icons/swr.svg
I see [very slight difference](https://github.com/simple-icons/simple-icons/assets/35000807/68373cad-f86b-4f68-a7e4-f5da4b12f05c)

I think we can merge this, what say @adamrusted ?

2023-09-15 06:27 UTC, PratyushJayachandran approved these changes

2023-09-15 07:32 UTC, adamrusted commented on icons/swr.svg
If you're happy with it, go for it! 😅

2023-09-15 07:55 UTC, merged