Mixpanel icon
simple-icons/simple-icons pull request #7404
Opened 2022-05-10 19:52 UTC by deepmalamittal

![mixpanel](https://user-images.githubusercontent.com/79153420/167710576-841b14f7-e41f-4340-9f69-1dfd5bceabbd.png)
**Issue:** closes https://github.com/simple-icons/simple-icons/issues/7354

**Similarweb rank:** 23,003
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

2022-05-11 09:02 UTC, sisp commented
A number of unrelated commits leaked into this PR which makes the commit history in this PR a bit polluted. Could you remove them? I guess you could rebase the branch to the latest state of develop.

2022-05-12 14:31 UTC, sisp requested changes

2022-05-12 14:31 UTC, sisp commented on icons/mixpanel.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Mixpanel</title><path d="M23.684 12.717a.316.316 0 0 1-.315-.32V8.32c0-.186.131-.32.315-.32.185 0 .316.15.316.32v4.077c0
I think the icon should be just the three circles without the wordmark. You can use the official `Brand Mark-Purple.svg` from the [press kit](https://www.notion.so/mxpnl/Mixpanel-Brand-Guidelines-538928c3ee9c4f2a9b330c5bfc38b5b9) whose link you can find near the bottom of https://mixpanel.com/news/. From looking at the press kit, I even think that the official icon isn't just three circles but a square with rounded corners and three circles inside.

2022-05-12 14:31 UTC, sisp commented on _data/simple-icons.json
> +            "source": "https://mixpanel.com"
I think the [press kit](https://www.notion.so/mxpnl/Mixpanel-Brand-Guidelines-538928c3ee9c4f2a9b330c5bfc38b5b9) should be provided as a source. Unfortunately, the URL isn't very beautiful and has a different domain. :man_shrugging:

Also, please add the URL to the press kit as a brand guidelines reference.

```suggestion
            "source": "https://www.notion.so/mxpnl/Mixpanel-Brand-Guidelines-538928c3ee9c4f2a9b330c5bfc38b5b9",
            "guidelines:" "https://www.notion.so/mxpnl/Mixpanel-Brand-Guidelines-538928c3ee9c4f2a9b330c5bfc38b5b9"
```

2022-05-12 14:31 UTC, sisp commented on _data/simple-icons.json
> +            "hex": "111111",
I think the hex value should be `#7856FF` as that's the primary color according to the [press kit](https://www.notion.so/mxpnl/Mixpanel-Brand-Guidelines-538928c3ee9c4f2a9b330c5bfc38b5b9).

```suggestion
            "hex": "7856FF",
```

2023-09-15 06:31 UTC, PratyushJayachandran approved these changes
Perfect match 🎉 
Their website is so cool!

2023-09-15 06:34 UTC, merged