Add Electron Builder icon
simple-icons/simple-icons pull request #7589
Opened 2022-07-13 17:36 UTC by PaulaBarszcz

![electronbuilder](https://user-images.githubusercontent.com/31891675/178793826-707f2536-d752-4cc1-9c13-ef5c2e757ed0.png)

**Issue:** closes #6115 
There was a PR opened before but it was closed without merge - https://github.com/simple-icons/simple-icons/pull/6177

**Similarweb rank:** 528,375

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

  - Why did you pick the hex value?
I chose  #2094f3 as a primary colour - it is the colour of the header on https://www.electron.build/ 
![image](https://user-images.githubusercontent.com/31891675/178795872-260bef86-9f71-467c-805e-39c557df8586.png)

  - Did you manually vectorize the logo?
  No, I used an SVG version of the logo from https://www.electron.build/, 
  resized it in Inkscape so that 2 sides touch the border,
  centred horizontally & vertically,
  added `title` and `role`,
  and ran SVGO.
  
  - Have you used multiple sources?
  No.

2022-07-13 17:45 UTC, PaulaBarszcz commented
I see that running 'Minify SVG' in VSCode removed some of its properties (role and title), I will add them ;)

2022-07-13 18:15 UTC, PaulaBarszcz commented
I see that I will have to slightly modify the icon's dimensions in Inkscape - I will do that when I have some time :)

2022-07-17 10:56 UTC, PaulaBarszcz commented
Hi @sisp,
When you have time, could you please take a look and let me know if anything is missing in this PR for it to be merge-ready for the develop branch?
If everything seems ok, it would be great if you could merge it (or hint as to who might do it instead) :)
Thanks a lot!

2022-07-19 14:44 UTC, sisp requested changes
Thanks for your contribution, @PaulaBarszcz! :pray:

I see no notable difference between your icon and the original one :+1::
<img src="https://user-images.githubusercontent.com/2206639/179778956-55cf2112-3d93-416a-8648-4ffbf9b49283.svg" width="384"/>

I left some comments though.

2022-07-19 14:44 UTC, sisp commented on _data/simple-icons.json
> +            "title": "Electron Builder",
It seems the official spelling is "electron-builder".

```suggestion
            "title": "electron-builder",
```

2022-07-19 15:59 UTC, PaulaBarszcz commented on _data/simple-icons.json
> +            "hex": "2094F3",
```suggestion
            "hex": "FFFFFF",
```

2022-07-21 19:00 UTC, sachinraja commented on _data/simple-icons.json
> +            "hex": "2094F3",
hello, I agree, the brand color is white

2022-07-22 10:48 UTC, sisp approved these changes
LGTM now! :tada: Thank you! :pray:

2022-07-22 10:49 UTC, merged