Add Bookalope icon
simple-icons/simple-icons pull request #7645
Opened 2022-08-03 13:39 UTC by jenstroeger

Bookalope is a SaaS platform for AI-assisted manuscript analysis, accessible ebook conversion, and more.

![bookalope](https://user-images.githubusercontent.com/12053937/182621772-c4aa15df-e9ba-43e9-b454-16613eaea138.png)

**Issue:** closes #7644 

**Similarweb rank:** n/a and https://github.com/bookalope/
  

### Checklist
  - [X] I updated the JSON data in `_data/simple-icons.json`
  - [X] I optimized the icon with SVGO or SVGOMG
  - [X] The SVG `viewbox` is `0 0 24 24`

### Description

Color and logo have been in use since around 2016 when the project started.

2022-08-12 14:58 UTC, dirien requested changes
Hi @jenstroeger,

Thanks for your contribution. Could you check the errors in the lint run please?

Best start is to check the contribution guidlines.

https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md

2022-08-12 21:46 UTC, jenstroeger commented
@dirien thank you for the poke. I tried to fix the problems but I’m unable to interpret the “Test package” failures. Also, after following the CONTRIBUTION guidelines lint still fails and I’m not sure how to address these two failures.

I’d be grateful for suggestions!

2022-08-13 08:55 UTC, dirien requested changes
Can you check the LF/CR? And center the icon please (in inkscape I use 
![image](https://user-images.githubusercontent.com/38325136/184476642-8ef56b0a-3bdd-4616-b958-a2821cd90e73.png)
)

Last thing, remove the `slug` field from the `simple-icons.json`

2022-08-13 08:55 UTC, dirien commented on _data/simple-icons.json
> +            "slug": "bookalope",
Please remove the slug

2022-08-13 14:08 UTC, jenstroeger commented
> Can you check the LF/CR?

It wasn’t that, but `hexdump -C bookalope.svg` showed a trailing LF—removed.

> And center the icon please (in inkscape I use ![image](https://user-images.githubusercontent.com/38325136/184476642-8ef56b0a-3bdd-4616-b958-a2821cd90e73.png) )

Done.

> Last thing, remove the `slug` field from the `simple-icons.json`

Done.

2022-08-13 14:29 UTC, dirien approved these changes
Perfect fit!

![image](https://user-images.githubusercontent.com/38325136/184498655-8fccb111-aa73-41e0-9f25-3349f488064f.png)

2022-08-13 14:29 UTC, merged

2022-08-13 21:29 UTC, jenstroeger commented
@dirien oh great, thank you for merging! I look forward to the next release then 🤓