Add Wasmer icon
simple-icons/simple-icons pull request #7646
Opened 2022-08-03 14:49 UTC by syrusakbary

![image](https://user-images.githubusercontent.com/188257/182722968-5ff76234-d69a-4e02-b468-38a66ff6f5eb.png)

**Issue:** closes #7643

**Similarweb rank:** 291,242 (https://www.similarweb.com/website/wasmer.io)
**Github Stars:** 12,700 (https://github.com/wasmerio/wasmer/)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

  - Why did you pick the hex value? Is the brand color
  - Did you manually vectorize the logo? No

2022-08-09 09:49 UTC, sisp requested changes
Thanks for your contribution, @syrusakbary! :pray:

The icon is perfectly identical with the source SVG image (almost identical data path even). :+1:

I have only a few minor requests.

2022-08-09 09:49 UTC, sisp commented on _data/simple-icons.json
> +            "guidelines": "https://wasmer.io/"
I can't find the logo guidelines on this website. Unless I've overlooked it somewhere, please delete this field.

2022-08-09 09:49 UTC, sisp commented on _data/simple-icons.json
> +            "title": "wasmer",
I think it's spelled with a capital W.

```suggestion
            "title": "Wasmer",
```

2022-08-09 09:49 UTC, sisp commented on icons/wasmer.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>wasmer</title><path d="M18.111 3.537c-.011.822-.5 1.208-1.111.86-.611-.353-1.106-1.307-1.111-2.146L12 0v4.651l5.561 3.222
Capital W (see above):

```suggestion
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Wasmer</title><path d="M18.111 3.537c-.011.822-.5 1.208-1.111.86-.611-.353-1.106-1.307-1.111-2.146L12 0v4.651l5.561 3.222.55.32v7.763L22 18.206V5.794l-3.889-2.256Zm-5 3.034c-.011.822-.5 1.208-1.111.86-.611-.352-1.106-1.307-1.111-2.145l-3.89-2.252V7.41l5.562 3.222.55.32v8.038L17 21.241V8.828L13.11 6.57Zm-5 2.759c-.011.822-.5 1.208-1.111.86-.611-.353-1.106-1.307-1.111-2.146L2 5.794v12.413L12 24V11.586L8.111 9.33Z"/></svg>
```

2022-08-16 19:43 UTC, syrusakbary commented on _data/simple-icons.json
> +        },
```suggestion
        },
```

2022-08-16 19:46 UTC, syrusakbary commented
I just fixed the suggestions @sisp . Thanks for reviewing and looking forward to having the PR merged!

2022-08-17 05:32 UTC, sisp commented
@syrusakbary The tests are failing beause of the trailing comma after the source URL. When you remove it, they should pass.

2022-08-31 17:56 UTC, sisp commented
/ping @syrusakbary :wink:

2022-08-31 18:09 UTC, syrusakbary commented
@sisip Thanks for following up :)
It should be fixed now!

2022-08-31 19:38 UTC, sisp approved these changes
LGTM now! :tada:

Thanks again for your contribution, @syrusakbary! :pray:

2022-08-31 19:38 UTC, merged