Add Akaunting icon
simple-icons/simple-icons pull request #7660
Opened 2022-08-09 11:57 UTC by Barannaslann

![simpleicons](https://user-images.githubusercontent.com/91828883/183641222-7f55c24c-7cbb-4d65-b4c4-f073833b75bd.png)

**Issue:** #7659

**Similarweb rank:** 141,388
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

2023-07-06 05:55 UTC, PratyushJayachandran requested changes
Please merge the changes to fix build failure

2023-07-06 05:55 UTC, PratyushJayachandran commented on icons/akaunting.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Akaunting</title><path d="M12,19.3c-1.7,0-3.3-0.6-4.5-1.6l-3,3.5c2.1,1.7,4.7,2.7,7.5,2.7c1.9,0,3.7-0.4,5.3-1.2l-2.2-4.1
```suggestion
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Akaunting</title><path d="M7.047 17.482a7.311 7.311 0 0 1-2.374-5.131H.078a11.894 11.894 0 0 0 3.976 8.618l2.993-3.487zm8.078 1.226c-.978.461-2.046.7-3.127.697a7.3 7.3 0 0 1-4.51-1.55l-2.992 3.488A11.874 11.874 0 0 0 11.998 24a11.88 11.88 0 0 0 5.292-1.236l-2.165-4.056zm8.796-6.632V24h-4.593v-2.526c-.482.378-.99.722-1.528 1.022l-2.162-4.054a7.329 7.329 0 1 0-10.963-6.668H.076C.159 5.19 5.564-.082 12.15.001s11.856 5.488 11.773 12.074l-.002.001z"/></svg>
```

2023-07-09 14:59 UTC, adamrusted requested changes
I'm spotting a slight difference between your PR (black) and the source file (red). This could just be a precision issue, so it'd be worth trying with a precision of 4 instead of 3.

![image](https://github.com/simple-icons/simple-icons/assets/1830867/9955af1c-5bfd-4b0f-8723-812c9cab79d2)

Would you mind taking a look at that, @Barannaslann?

2023-09-15 06:51 UTC, PratyushJayachandran approved these changes
Thank you for your contribution @Barannaslann 
Thank you for the correction @adamrusted 
LGTM 🎉

2023-09-15 06:51 UTC, merged