Added Cairo Graphics icon in /icons and _data/simple-icons.json
simple-icons/simple-icons pull request #7668
Opened 2022-08-12 15:34 UTC by s-kond

![cairographics](https://user-images.githubusercontent.com/79710919/184387785-06677d06-fc64-4c6e-98c9-598ba3103c75.png)

To create the svg-icon, I used inkscape and a svg-file from the github-repository that was linked in the issue:
https://github.com/freedesktop/cairo/blob/44f808fce9f437e14f2b0ef4e1583def8ab578ae/doc/tutorial/slides/cairo-title.svg

There were two primary colors:
     - the blue background ("#162284")
     - and the yellow/orange scarabaeus ("#f39914")

I picked the yellow/orange "#f39914", because the blue color is just used for the background - but I wasn't sure about that.

2022-08-12 15:38 UTC, dirien commented
Hi @s-kond,

thanks for the contribution! Could you check the lint error so I can review your PR? Thanks.

2022-08-12 15:47 UTC, s-kond commented
Hi @dirien,
I checked the lint error and it shows me this: 

```
Data file is formatted incorrectly:
   {
       "icons": [
@@ 12469 more lines
       ]
   }
+
```
So there should be a formatting error, but I don't know what's wrong or how I can solve this... Can you help me?

2022-08-12 16:29 UTC, dirien commented
Maybe and Windows / Linux CR/LF issue?

2022-08-13 02:07 UTC, mondeja requested changes

2022-08-13 02:07 UTC, mondeja commented on _data/simple-icons.json
> +}
You need to add a newline character here:

```suggestion
}

```

2022-08-13 08:33 UTC, s-kond commented
Simply adding a new line at the end solved the problem, thx!
But it seems I have to change some more things - I'm working on that

2022-08-13 09:10 UTC, dirien requested changes
HI @s-kond,

I see some little differences

![image](https://user-images.githubusercontent.com/38325136/184477155-5e342276-f7d7-4102-88ea-9b7414e11e60.png)

Maybe try up the precision to 5?

2022-09-29 20:34 UTC, dirien approved these changes
Hi @s-kond,

Thanks for your contribution to simple-icons!

I think it's a very close fit!

2022-09-29 20:34 UTC, merged