Add Guacamole Icon
simple-icons/simple-icons pull request #7674
Opened 2022-08-14 01:56 UTC by zrfisaac

![guacamole](https://user-images.githubusercontent.com/16006294/184519335-49dbb9dc-9a8f-4fe4-a32c-df625699d403.png)

**Issue:** #7649

**Similarweb rank:** [--](https://www.similarweb.com/website/guacamole.apache.org/#overview)

### Checklist
  - [X] I updated the JSON data in `_data/simple-icons.json`
  - [X] I optimized the icon with SVGO or SVGOMG
  - [X] The SVG `viewbox` is `0 0 24 24`

### Description
Apache Guacamole is a clientless remote desktop gateway. It supports standard protocols like VNC, RDP, and SSH.

2023-07-09 15:07 UTC, adamrusted requested changes

2023-07-09 15:07 UTC, adamrusted commented on _data/simple-icons.json
> +            "source": "https://github.com/apache/guacamole-website/blob/7b832798bb43f9047d0725b10604e09fd3245cbd/images/guac-logo.png"
Official SVG source is available at [this link](https://www.apache.org/logos/#guacamole) which can be used for this.

2023-07-09 15:07 UTC, adamrusted commented on _data/simple-icons.json
> +            "title": "Guacamole",
```suggestion
            "title": "Apache Guacamole",
```

2023-09-15 07:02 UTC, PratyushJayachandran approved these changes
Thank you for the contribution @zrfisaac and the correction @adamrusted 
However I see [some slight differences!](https://github.com/simple-icons/simple-icons/assets/35000807/83718c14-9705-4589-bd96-930dabad9157)
However, we can merge it if you are okay with it @adamrusted

2023-11-08 08:05 UTC, PratyushJayachandran commented
> Thank you for the contribution @zrfisaac and the correction @adamrusted However I see [some slight differences!](https://github.com/simple-icons/simple-icons/assets/35000807/83718c14-9705-4589-bd96-930dabad9157) However, we can merge it if you are okay with it @adamrusted

Merging this one as the differences are very minor!

2023-11-08 08:06 UTC, merged