Update Proton VPN
simple-icons/simple-icons pull request #7795
Opened 2022-09-17 16:55 UTC by adamrusted

![protonvpn](https://user-images.githubusercontent.com/1830867/190867935-3914ad18-9eee-436d-a5f6-c4205fc01bf4.png)

**Issue:** contributes to #7451 

**Similarweb rank:** [951](https://www.similarweb.com/website/proton.me/#overview)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Hex is pulled from the fourth gradient example on [this page](https://proton.me/blog/new-visual-universe). For context, the paragraph above discusses the visual identity of each 'app'.

> **ℹ️ Note:**
> This update renames the icon from `ProtonVPN` to `Proton VPN` (adding a space). This should not cause an issue, as the slug removes the space anyway.

2023-04-29 11:23 UTC, dirien requested changes
Hi @adamrusted,

I see a difference in the overall shape/outline

![image](https://user-images.githubusercontent.com/38325136/235300042-ca0eda82-f22f-4d83-aa1e-a687d728d5db.png)

2023-05-25 12:58 UTC, mondeja commented
Hi @dirien. I'm moving this PR to the v10 milestone. If you and @adamrusted are capable of updating it before this Sunday, the change could be included in v9. In that case move it to the v9 milestone and merge when is ready. Thanks.

2023-06-30 07:46 UTC, adamrusted commented
@mondeja and @dirien - I've updated this PR to just change the title of the icon from `ProtonVPN` to `Proton VPN`. Feel free to review and merge as/when appropriate :)

2023-08-07 17:53 UTC, dirien commented
@adamrusted is this good to review and there is an issue with the `_data/simple-icons.json` file

2023-11-21 17:02 UTC, mondeja requested changes

2023-11-21 17:02 UTC, mondeja commented on sdk.mjs
> +      (_, ref) => ({ quot: '"', amp: '&', lt: '<', gt: '>' })[ref],
I think that this change was done by a previous version of Prettier. We commited it a few weeks ago and then failed again. Could you reformat?

2023-11-23 09:25 UTC, PeterShaggyNoble approved these changes

2023-11-23 09:25 UTC, merged