Add l'Équipe icon
simple-icons/simple-icons pull request #7857
Opened 2022-09-24 09:11 UTC by Poukame

![lequipe](https://user-images.githubusercontent.com/93629281/192090001-5e7e240c-c300-401f-bc85-11631b21784a.png)

**Issue:** none

**Similarweb rank:**
[Ranked #776](https://www.similarweb.com/website/lequipe.fr/#overview)

### Checklist
  - [X] I updated the JSON data in `_data/simple-icons.json`
  - [X] I optimized the icon with SVGO or SVGOMG
  - [X] The SVG `viewbox` is `0 0 24 24`

### Description
Picked the hex color from header on official website

2023-07-09 15:18 UTC, adamrusted requested changes
Some minor differences when comparing to [this SVG](https://commons.wikimedia.org/wiki/File:L%27%C3%89quipe_wordmark.svg), with your PR in black and the source file in red. Would you mind updating the source, and taking another shot at this one @Poukame? You may need to increase the precision of SVGO to 4 decimals in order to get it spot on.

![image](https://github.com/simple-icons/simple-icons/assets/1830867/3c63e6c2-d29f-4269-8a11-8236d6379006)

2023-10-08 06:38 UTC, PratyushJayachandran reviewed
Logo matches perfectly @adamrusted 
Just the color seems different

2023-10-08 06:38 UTC, PratyushJayachandran commented on _data/simple-icons.json
> +            "hex": "D61E00",
```suggestion
            "hex": "E42829",
```
From the source logo, this was the color I saw.

2023-11-21 14:59 UTC, adamrusted approved these changes
Given @PratyushJayachandran's review of the icon, and update to the hex code, I'll get this merged in.

2023-11-21 15:00 UTC, merged