Main
simple-icons/simple-icons pull request #7866
Opened 2022-09-25 16:31 UTC by priyal32

![image](https://user-images.githubusercontent.com/87373155/192154501-973daecc-9197-497f-904b-efe6b25d5a49.png)

**Issue:** closes #7539 

**GitHub stars**:  20349
  

### Checklist
  - [ √] I updated the JSON data in `_data/simple-icons.json`
  - [ √] I optimized the icon with SVGO or SVGOMG
  - [ √] The SVG `viewbox` is `0 0 24 24`

2022-09-27 18:30 UTC, LitoMore requested changes

2022-09-27 18:30 UTC, LitoMore commented on _data/simple-icons.json
> +            "source": "https://github.com/zyedidia/micro/blob/master/assets/micro-logo-mark.svg"
```suggestion
            "source": "https://github.com/zyedidia/micro/blob/48645907ec55798b75723019dad75dba51bd97d7/assets/micro-logo-mark.svg"
```

Let's use the permalink instead.

2022-09-29 02:15 UTC, LitoMore commented
There are so many projects named `Micro` https://github.com/search?q=micro. Maybe we could change its name here to `Micro Editor`.

@simple-icons/icon-review What do you think?

2023-07-18 17:59 UTC, adamrusted approved these changes
Icon was spot on - and after updating the title as per @LitoMore's suggestion, I'm happy to merge this in as `Micro Editor`!

2023-07-18 18:00 UTC, merged