Add Falco icon
simple-icons/simple-icons pull request #7867
Opened 2022-09-25 19:35 UTC by LoganFernandez

GitHub stars: 5200

**Issue:** closes #

**Similarweb rank:**
  

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json`
  - [ ] I optimized the icon with SVGO or SVGOMG
  - [ ] The SVG `viewbox` is `0 0 24 24`

### Description

2022-09-26 15:15 UTC, LitoMore commented
@LoganFernandez The failing CI needs to be resolved.

2022-09-26 15:16 UTC, LitoMore requested changes

2022-09-26 15:16 UTC, LitoMore commented on .vs/ProjectSettings.json
> +}
Please don't commit your personal files to our repo.

2022-10-07 03:04 UTC, thepushp commented
Hi, Is this issue still open can i work on it

2023-05-13 13:55 UTC, closed without merging