add billboard icon
simple-icons/simple-icons pull request #7892
Opened 2022-09-30 19:03 UTC by Anmol-Baranwal

![billboard](https://user-images.githubusercontent.com/74038190/193338735-c4cbbbc0-a79e-402c-9957-3d815ba51211.png)

**Issue:** closes #7885 

**Similarweb rank:**
Global rank: 4,506 &nbsp; `https://www.similarweb.com/website/billboard.com/#overview`

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
SVG logo is retrieved from: https://www.billboard.com/
The hex value is extracted from the official website & company logo from Facebook.

2022-10-01 13:15 UTC, Anmol-Baranwal commented
May I please know, how much time it takes for the PRs to merge once all the checks have passed?

2022-10-01 14:41 UTC, LitoMore commented
@Anmol-Baranwal There is no exact time. We maintain this project when we are free.

After all the checks have passed, we need to review your icon to ensure the processed shape perfectly fits the original shape.

For example this: #7752.

2022-10-01 14:56 UTC, LitoMore requested changes
![CleanShot 2022-10-01 at 22 45 16@2x](https://user-images.githubusercontent.com/8186898/193414994-fcdeedeb-ac79-425e-bedc-5af3d886b969.png)

@Anmol-Baranwal I see some differences. Could you re-process with precision 4? Use the command below:

```shell
npm run svgo -- -p 4 icons/billboard.svg
```

2022-10-01 17:01 UTC, Anmol-Baranwal commented
Is this precision satisfactory?
![preview_precision](https://user-images.githubusercontent.com/74038190/193420019-27851911-30e0-4c40-a9e3-4fd8c048d097.jpg)
With precision 3, below
![preview_precision_3](https://user-images.githubusercontent.com/74038190/193420134-b34bfd80-f8c3-41c1-8d7e-7b11af2248e0.jpg)

2022-10-03 11:01 UTC, LitoMore commented
<img width="354" alt="CleanShot 2022-10-03 at 18 50 16@2x" src="https://user-images.githubusercontent.com/8186898/193560024-5b29850f-845d-49b3-963b-7d81f80b1140.png">

@Anmol-Baranwal I still see some differences. Let's use this below directly:

```html
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Billboard</title><path d="M3.69685 11.02465h1.12413v3.41864H3.69685Zm1.35662-1.33669h1.12381v4.75533H5.05347Zm1.35641 0H7.5337v4.75533H6.40988Zm13.22037 1.68925v-.35256h-1.12397v3.41864h1.12397v-1.6293c0-.41916.21904-.64528.61843-.64528h.133v-1.17728c-.33918.01334-.58533.11975-.75143.38579zM4.2588 9.50287c-.35974 0-.65171.29187-.65171.65182 0 .35994.29197.65192.6517.65192.36006 0 .65182-.29198.65182-.65192 0-.35995-.29176-.65182-.65181-.65182zm12.89058 1.78207c-.15798-.17233-.52558-.31455-.80468-.31455-.84888 0-1.45782.55964-1.6069 1.39153-.1625-.79809-.8581-1.41215-1.70633-1.41215-.85636 0-1.55753.62123-1.71082 1.4343-.1488-.84507-.81354-1.40519-1.6379-1.40519-.30589 0-.55874.06655-.7783.21936v-1.5097H7.78063v4.75528h1.10409v-.3127c.26603.24615.55194.3592.90456.3592.75922 0 1.39843-.59433 1.53517-1.41357.1611.80168.85261 1.4111 1.70707 1.4111.84713 0 1.52653-.5965 1.69943-1.37761.14296.8532.81898 1.38689 1.62698 1.38689.2791 0 .58527-.0934.79145-.24615v.19284h1.12381v-1.49616a8.92817 8.92817 0 0 0-.0016-.1796 8.7632 8.7632 0 0 0 .0016-.17955v-1.55806H17.1494zm-7.58627 2.11732c-.35995 0-.6517-.29187-.6517-.65192 0-.35984.29175-.65165.6517-.65165.35984 0 .6517.29181.6517.65165.00006.36005-.2918.65192-.6517.65192zm3.46836-.0522c-.35973 0-.65181-.29208-.65181-.65192 0-.35978.29208-.65165.65181-.65165.35984 0 .6517.29187.6517.65165.00006.35979-.2917.65192-.6517.65192zm3.3773.02067c-.35995 0-.65145-.29208-.65145-.65192 0-.35978.29145-.65165.65145-.65165.36026 0 .6517.29187.6517.65165.00006.35984-.29144.65192-.6517.65192zm6.46693-3.6833v1.50976c-.21915-.15292-.4719-.21936-.77816-.21936-.93767 0-1.66916.72485-1.66916 1.76914 0 .98418.70492 1.7424 1.56307 1.7424.35224 0 .6382-.11315.90445-.35915v.3126H24V9.68743Zm-.66194 3.7064c-.35947 0-.65144-.29208-.65144-.65166 0-.36005.29187-.65202.65144-.65202.36005 0 .65192.29197.65192.65202 0 .35958-.29187.65166-.65192.65166zm-20.31164-2.415c-.306 0-.55864.06655-.77832.21936V9.68854H0v4.75528h1.10399v-.3127c.26603.24615.55204.3592.90466.3592.85783 0 1.5628-.75843 1.5628-1.74261 0-1.04393-.7316-1.76888-1.66932-1.76888zm-.11965 2.42343c-.35984 0-.6517-.29187-.6517-.65192 0-.35984.29186-.65165.6517-.65165.35995 0 .65171.29181.65171.65165 0 .36005-.29176.65192-.6517.65192z"/></svg>
```

I have already reviewed the difference:

<img width="699" alt="CleanShot 2022-10-03 at 19 00 28@2x" src="https://user-images.githubusercontent.com/8186898/193561811-0b07749e-66fb-4c41-9ace-047900f01338.png">

2022-10-03 14:00 UTC, Anmol-Baranwal commented
Do I have to use precision 5 on this processed one:
```
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Billboard</title><path d="M3.69685 11.02465h1.12413v3.41864H3.69685Zm1.35662-1.33669h1.12381v4.75533H5.05347Zm1.35641 0H7.5337v4.75533H6.40988Zm13.22037 1.68925v-.35256h-1.12397v3.41864h1.12397v-1.6293c0-.41916.21904-.64528.61843-.64528h.133v-1.17728c-.33918.01334-.58533.11975-.75143.38579zM4.2588 9.50287c-.35974 0-.65171.29187-.65171.65182 0 .35994.29197.65192.6517.65192.36006 0 .65182-.29198.65182-.65192 0-.35995-.29176-.65182-.65181-.65182zm12.89058 1.78207c-.15798-.17233-.52558-.31455-.80468-.31455-.84888 0-1.45782.55964-1.6069 1.39153-.1625-.79809-.8581-1.41215-1.70633-1.41215-.85636 0-1.55753.62123-1.71082 1.4343-.1488-.84507-.81354-1.40519-1.6379-1.40519-.30589 0-.55874.06655-.7783.21936v-1.5097H7.78063v4.75528h1.10409v-.3127c.26603.24615.55194.3592.90456.3592.75922 0 1.39843-.59433 1.53517-1.41357.1611.80168.85261 1.4111 1.70707 1.4111.84713 0 1.52653-.5965 1.69943-1.37761.14296.8532.81898 1.38689 1.62698 1.38689.2791 0 .58527-.0934.79145-.24615v.19284h1.12381v-1.49616a8.92817 8.92817 0 0 0-.0016-.1796 8.7632 8.7632 0 0 0 .0016-.17955v-1.55806H17.1494zm-7.58627 2.11732c-.35995 0-.6517-.29187-.6517-.65192 0-.35984.29175-.65165.6517-.65165.35984 0 .6517.29181.6517.65165.00006.36005-.2918.65192-.6517.65192zm3.46836-.0522c-.35973 0-.65181-.29208-.65181-.65192 0-.35978.29208-.65165.65181-.65165.35984 0 .6517.29187.6517.65165.00006.35979-.2917.65192-.6517.65192zm3.3773.02067c-.35995 0-.65145-.29208-.65145-.65192 0-.35978.29145-.65165.65145-.65165.36026 0 .6517.29187.6517.65165.00006.35984-.29144.65192-.6517.65192zm6.46693-3.6833v1.50976c-.21915-.15292-.4719-.21936-.77816-.21936-.93767 0-1.66916.72485-1.66916 1.76914 0 .98418.70492 1.7424 1.56307 1.7424.35224 0 .6382-.11315.90445-.35915v.3126H24V9.68743Zm-.66194 3.7064c-.35947 0-.65144-.29208-.65144-.65166 0-.36005.29187-.65202.65144-.65202.36005 0 .65192.29197.65192.65202 0 .35958-.29187.65166-.65192.65166zm-20.31164-2.415c-.306 0-.55864.06655-.77832.21936V9.68854H0v4.75528h1.10399v-.3127c.26603.24615.55204.3592.90466.3592.85783 0 1.5628-.75843 1.5628-1.74261 0-1.04393-.7316-1.76888-1.66932-1.76888zm-.11965 2.42343c-.35984 0-.6517-.29187-.6517-.65192 0-.35984.29186-.65165.6517-.65165.35995 0 .65171.29181.65171.65165 0 .36005-.29176.65192-.6517.65192z"/></svg>
```
or use precision 5 on the svg from scratch ?

Uptill now, I have been doing it from scratch, and both of the above gives a slight different result.

2022-10-04 07:12 UTC, LitoMore commented on icons/billboard.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Billboard</title><path d="M3.69685 11.02465h1.12413v3.41864H3.69685Zm1.35662-1.33669h1.12381v4.75533H5.05347zm1.35641 0H7
```suggestion
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Billboard</title><path d="M3.69685 11.02465h1.12413v3.41864H3.69685Zm1.35662-1.33669h1.12381v4.75533H5.05347Zm1.35641 0H7.5337v4.75533H6.40988Zm13.22037 1.68925v-.35256h-1.12397v3.41864h1.12397v-1.6293c0-.41916.21904-.64528.61843-.64528h.133v-1.17728c-.33918.01334-.58533.11975-.75143.38579zM4.2588 9.50287c-.35974 0-.65171.29187-.65171.65182 0 .35994.29197.65192.6517.65192.36006 0 .65182-.29198.65182-.65192 0-.35995-.29176-.65182-.65181-.65182zm12.89058 1.78207c-.15798-.17233-.52558-.31455-.80468-.31455-.84888 0-1.45782.55964-1.6069 1.39153-.1625-.79809-.8581-1.41215-1.70633-1.41215-.85636 0-1.55753.62123-1.71082 1.4343-.1488-.84507-.81354-1.40519-1.6379-1.40519-.30589 0-.55874.06655-.7783.21936v-1.5097H7.78063v4.75528h1.10409v-.3127c.26603.24615.55194.3592.90456.3592.75922 0 1.39843-.59433 1.53517-1.41357.1611.80168.85261 1.4111 1.70707 1.4111.84713 0 1.52653-.5965 1.69943-1.37761.14296.8532.81898 1.38689 1.62698 1.38689.2791 0 .58527-.0934.79145-.24615v.19284h1.12381v-1.49616a8.92817 8.92817 0 0 0-.0016-.1796 8.7632 8.7632 0 0 0 .0016-.17955v-1.55806H17.1494zm-7.58627 2.11732c-.35995 0-.6517-.29187-.6517-.65192 0-.35984.29175-.65165.6517-.65165.35984 0 .6517.29181.6517.65165.00006.36005-.2918.65192-.6517.65192zm3.46836-.0522c-.35973 0-.65181-.29208-.65181-.65192 0-.35978.29208-.65165.65181-.65165.35984 0 .6517.29187.6517.65165.00006.35979-.2917.65192-.6517.65192zm3.3773.02067c-.35995 0-.65145-.29208-.65145-.65192 0-.35978.29145-.65165.65145-.65165.36026 0 .6517.29187.6517.65165.00006.35984-.29144.65192-.6517.65192zm6.46693-3.6833v1.50976c-.21915-.15292-.4719-.21936-.77816-.21936-.93767 0-1.66916.72485-1.66916 1.76914 0 .98418.70492 1.7424 1.56307 1.7424.35224 0 .6382-.11315.90445-.35915v.3126H24V9.68743Zm-.66194 3.7064c-.35947 0-.65144-.29208-.65144-.65166 0-.36005.29187-.65202.65144-.65202.36005 0 .65192.29197.65192.65202 0 .35958-.29187.65166-.65192.65166zm-20.31164-2.415c-.306 0-.55864.06655-.77832.21936V9.68854H0v4.75528h1.10399v-.3127c.26603.24615.55204.3592.90466.3592.85783 0 1.5628-.75843 1.5628-1.74261 0-1.04393-.7316-1.76888-1.66932-1.76888zm-.11965 2.42343c-.35984 0-.6517-.29187-.6517-.65192 0-.35984.29186-.65165.6517-.65165.35995 0 .65171.29181.65171.65165 0 .36005-.29176.65192-.6517.65192z"/></svg>
```

I mean use my one directly.

2022-10-04 07:20 UTC, Anmol-Baranwal commented on icons/billboard.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Billboard</title><path d="M3.69685 11.02465h1.12413v3.41864H3.69685Zm1.35662-1.33669h1.12381v4.75533H5.05347zm1.35641 0H7
I have updated the SVG file

2022-10-04 08:39 UTC, LitoMore approved these changes

2022-10-04 08:39 UTC, merged