Update Next.js icon and data
simple-icons/simple-icons pull request #7921
Opened 2022-10-05 05:41 UTC by sisp

![Next.js icon](https://user-images.githubusercontent.com/2206639/193989195-145eb88f-c171-432b-b9b9-403b25bda846.png)

**Issue:** closes #7742, closes #7626

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

The new Next.js wordmark uses gradient transitions which cannot be converted to a monochromatic icon. We've discussed in #7742 that it might be better to use the full wordmark instead. I've also updated the guidelines link as suggested in #7626.

2022-10-05 09:04 UTC, LitoMore commented
I'd prefer just `N`.

[Next.js](https://github.com/vercel/next.js/blob/canary/packages/next/README.md?plain=1#L22) is using the logo on their main project. The full trademark looks not good on a badge.

2022-10-05 10:05 UTC, LitoMore commented
Let's ask Next.js for help. Just let them  know Simple Icons does not support gradient colors.

It would be good if they can design a specific version for Simple Icon.

2022-10-05 15:51 UTC, sisp commented
I've started a discussion over at Next.js: https://github.com/vercel/next.js/discussions/41193

2023-07-18 12:13 UTC, adamrusted commented
Hey @ijjk - is there currently a monochrome (including without the gradient) version of the NextJS `N` icon? If we're able to use it here - any chance you can share somewhere it's publicly available?

2023-09-08 09:52 UTC, adamrusted commented
Should we just include the full wordmark until we've heard back from them? That way, we're up to date, albeit with a non-ideal icon.

2023-09-08 09:58 UTC, adamrusted reviewed
The SVG itself is a perfect match, if we go ahead with the full wordmark until Next update their icon format. Just a quick change to the JSON, seems they've updated URLs since this PR was put in. Once that's done, let's get this merged in!

2023-09-08 09:58 UTC, adamrusted commented on _data/simple-icons.json
> +            "guidelines": "https://vercel.com/design#next-js"
```suggestion
            "source": "https://vercel.com/design/brands#next-js",
            "guidelines": "https://vercel.com/design/brands#next-js"
```

2023-09-08 14:50 UTC, LitoMore commented
I want to keep their icon visual at https://github.com/vercel/next.js.

BTW, the Next.js Conf will be back in October. They should revise the logo again.

2023-09-08 17:59 UTC, adamrusted commented
> I want to keep their icon visual at https://github.com/vercel/next.js.

Oh I totally agree, but in the absence of an official monochrome treatment for the 'new' icon - we should go with a safe monochrome treatment from the brand. Let's hold fire until Next Conf, and if there's no significant re-brand I'd look to merge this one in.

2023-11-24 03:10 UTC, PratyushJayachandran commented
> > I want to keep their icon visual at https://github.com/vercel/next.js.
> 
> Oh I totally agree, but in the absence of an official monochrome treatment for the 'new' icon - we should go with a safe monochrome treatment from the brand. Let's hold fire until Next Conf, and if there's no significant re-brand I'd look to merge this one in.

So I was looking their Readme and saw them using Next.js icon hosted in simple-icons.
It is the same as their favicon on https://nextjs.org/
So why are we changing it to wordmark?

2023-12-05 10:48 UTC, adamrusted requested changes
Still no official monochrome treatment from what I can see. We can _either_ proceed with the wordmark, as that's the only monochrome treatment offered by the brand at this time - or we adapt their currently used icon (as I imagine we had to do with the old version too!)

2023-12-05 12:47 UTC, PeterShaggyNoble commented
I vote to give the icon our own treatment. But, then, I'll always vote in favour of an icon over a wordmark!

2023-12-14 14:04 UTC, PeterShaggyNoble commented
So, @simple-icons/maintainers, where have we landed on this?

2023-12-14 15:50 UTC, service-paradis commented
They have a monochrome version of their favicon buried in their Github:
https://github.com/vercel/next.js/blob/6b3d145e7e7e88037f4e326cc63038814ab5fd76/examples/cms-prepr/public/favicon/safari-pinned-tab.svg?plain=1#L4

So, I think we're safe!

2023-12-14 15:52 UTC, adamrusted commented
@service-paradis - that looks to be the _old_ version of the icon. The new one is a much chunkier font.

2024-01-11 14:58 UTC, PeterShaggyNoble commented
It's been well over a year since Lito started the discussion in their repo and there's been no response so I think it's time we make an executive decision. Consensus seems to be that we use the icon rather than the wordmark so could you update the PR accordingly, @sisp? The best option is probably just to use the same treatment as for our existing icon.

2024-02-08 19:14 UTC, adamrusted commented on icons/nextdotjs.svg
If we take the `icon` found at the new source URL, and apply the gaps in the same way we did with the previous one, we end up with:
![image](https://github.com/simple-icons/simple-icons/assets/1830867/b0f97936-4850-4dce-a314-ae2707d0f376)

I can submit this version if it'd be preferred?

2024-02-12 11:13 UTC, PeterShaggyNoble requested changes
I think the diagonal of the "N" should still touch the edge of the circle here, @adamrusted.

2024-02-13 13:47 UTC, adamrusted commented on icons/nextdotjs.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Next.js</title><path d="M12 0c6.623 0 12 5.377 12 12s-5.377 12-12 12S0 18.623 0 12 5.377 0 12 0m3.571 13.549 1.715 2.208v
```suggestion
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Next.js</title><path d="M18.665 21.978C16.758 23.255 14.465 24 12 24 5.377 24 0 18.623 0 12S5.377 0 12 0s12 5.377 12 12c0 3.583-1.574 6.801-4.067 9.001L9.219 7.2H7.2v9.596h1.615V9.251l9.85 12.727Zm-3.332-8.533 1.6 2.061V7.2h-1.6v6.245Z"/></svg>
```

2024-02-13 15:17 UTC, PeterShaggyNoble approved these changes

2024-02-13 15:21 UTC, merged