Add Golang lib
simple-icons/simple-icons pull request #7952
Opened 2022-10-13 02:34 UTC by marcopollivier

**Issue:** closes #7951 

### Description
Adding new lib to list of 3rd-party libs

2022-10-13 13:49 UTC, LitoMore requested changes

2022-10-13 13:49 UTC, LitoMore commented on .gitignore
> +.idea
Do not append your personal settings.

You could use global ignore instead, see [**Configuring ignored files for all repositories on your computer**](https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files#configuring-ignored-files-for-all-repositories-on-your-computer).

2022-10-13 13:49 UTC, LitoMore commented on README.md
> +| <img src="https://raw.githubusercontent.com/simple-icons/simple-icons/develop/icons/go.svg#gh-light-mode-only" alt="Go" align=left width=24 height=24><img src="https://raw.githubusercontent.com/sim
The filename should be `go-white.svg`

2022-10-13 14:08 UTC, LitoMore commented on README.md
> +| <img src="https://raw.githubusercontent.com/simple-icons/simple-icons/develop/icons/go.svg#gh-light-mode-only" alt="Go" align=left width=24 height=24><img src="https://raw.githubusercontent.com/sim
The `go-white.svg` needs to be added.

You need to copy-paste one from `icons/go.svg` and add `fill="white"` to `go-white.svg`

2022-10-13 14:13 UTC, LitoMore commented on README.md
> +| <img src="https://raw.githubusercontent.com/simple-icons/simple-icons/develop/icons/go.svg#gh-light-mode-only" alt="Go" align=left width=24 height=24><img src="https://raw.githubusercontent.com/sim
```suggestion
| <img src="https://raw.githubusercontent.com/simple-icons/simple-icons/develop/icons/go.svg#gh-light-mode-only" alt="Go" align=left width=24 height=24><img src="https://raw.githubusercontent.com/simple-icons/simple-icons/develop/assets/readme/go-white.svg#gh-dark-mode-only" alt="Go" align=left width=24 height=24> [Golang plugin](https://github.com/marcopollivier/go-simple-icons/) | [@marcopollivier](https://github.com/marcopollivier) |
```

2022-10-16 12:40 UTC, LitoMore commented
@marcopollivier What is your plan for bumping the version of Simple Icons? I see you just copy-paste the JSON file to your project and unmarshal it.

It would be better if you could add some automation work to sync our release to your project.

2022-10-16 12:41 UTC, LitoMore commented on README.md
> +| <img src="https://raw.githubusercontent.com/simple-icons/simple-icons/develop/icons/go.svg#gh-light-mode-only" alt="Go" align=left width=24 height=24><img src="https://raw.githubusercontent.com/sim
```suggestion
| <img src="https://raw.githubusercontent.com/simple-icons/simple-icons/develop/icons/go.svg#gh-light-mode-only" alt="Go" align=left width=24 height=24><img src="https://raw.githubusercontent.com/simple-icons/simple-icons/develop/assets/readme/go-white.svg#gh-dark-mode-only" alt="Go" align=left width=24 height=24> [Golang plugin](https://github.com/marcopollivier/go-simple-icons) | [@marcopollivier](https://github.com/marcopollivier) |
```

2022-10-16 13:59 UTC, marcopollivier commented
> @marcopollivier What is your plan for bumping the version of Simple Icons? I see you just copy-paste the JSON file to your project and unmarshal it.
> 
> It would be better if you could add some automation work to sync our release to your project.

Good question. I'm thinking yet a better approach to do it. 
I thought of some options but I'm not sure about Them yet. 

- Create a submodule of the core lib and uses it as a reference. 
  - I'm not sure because I'm not a git-submodules big fan
  - I think if I do it I'll necessary import all of your codebase and it's not good
- if the submodule is the best option, ask you all if it's possible to isolate data in another repo (but it's not good too IMHO)
- Create a routine to copy and paste periodically from the main repo. Looks weird to me; or 

So, I really don't know yet. I'm looking another libs to understand their approach

2022-10-16 14:20 UTC, LitoMore commented
@marcopollivier I created an issue for your project. Let's discuss this there: https://github.com/marcopollivier/go-simple-icons/issues/2.

2023-08-29 08:07 UTC, adamrusted commented
Given no major update on this since Oct 22, I'm going to close this down. Feel free to open once issues reported by @LitoMore are resolved, @marcopollivier!

2023-08-29 08:07 UTC, closed without merging