Add Wayland icon, fixes #5056
simple-icons/simple-icons pull request #7967
Opened 2022-10-17 00:26 UTC by unrelentingtech

![wayland](https://user-images.githubusercontent.com/208340/196066402-cd85e11c-b160-4490-be47-f18a7fbdfbc9.png)

**Issue:** closes #5056

**Similarweb rank:** :shrug: 

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

See #5056

2022-10-19 08:19 UTC, sisp reviewed
Thanks for your contribution, @unrelentingtech! :pray:

I wonder whether there is a way to retain the shapes outside the circle. Currently, everything outside the circle is removed. Since I can't find an official monochromatic icon for Wayland, we might need to come up with something ourselves.

I imagine we could add inset strokes for the missing part of the "W" above the circle. And perhaps the sprinkles above the circle could be filled shapes. WDYT, @unrelentingtech  and also @simple-icons/icon-review?

2022-10-19 22:39 UTC, unrelentingtech commented
Sprinkles would look okay filled (inverted) but I think the parts of the W would look awkward no matter what, so I went with just the stuff inside the circle.

2022-10-25 11:26 UTC, sisp commented
Okay, I agree. Would you mind updating icon to include the inverted sprinkles?

2022-10-25 19:32 UTC, valpackett commented
test:

![waylandtest](https://user-images.githubusercontent.com/208340/197865074-a0980467-1cee-4f3c-99df-ab9806ada2f3.png)

I don't think this is better. The extra sprinkles are silly, they don't add much but make the circle necessarily smaller.

2022-10-28 08:18 UTC, sisp commented
Agreed. That actually doesn't look good.

I'll accept your proposed icon, just found some differences between the original one and yours:

<img src="https://user-images.githubusercontent.com/2206639/198539397-ee4e1373-2915-468b-abef-459a59534ad0.svg" width="384"/>

Would you checking your conversion steps?

2022-10-28 08:19 UTC, sisp requested changes
Agreed. That actually doesn't look good.

I'll accept your proposed icon, just found some differences between the original one and yours:

<img src="https://user-images.githubusercontent.com/2206639/198539397-ee4e1373-2915-468b-abef-459a59534ad0.svg" width="384"/>

Would you mind checking your conversion steps?

2022-10-29 19:49 UTC, valpackett commented
I used Inkscape to subtract the `W` path from the circle path and resize the result to fit the 24x24 viewbox, and used SVGO to trim the path precision down to 3 decimals. I think. I might have actually involved rsvg-convert to resize the viewbox specifically which would've been a bit silly in retrospect. These don't seem like major differences :shrug: but I can redo everything I guess

2022-11-01 16:00 UTC, LitoMore commented
@valpackett Could you try with precision 4? You could refer to this https://github.com/simple-icons/simple-icons/pull/7908#issuecomment-1266943734.

2022-11-02 14:49 UTC, valpackett commented
Updated with higher precision

2022-11-03 19:11 UTC, sisp requested changes
Thanks for the updated icon. Unfortunately, there are still notable differences when I compare it with the original one:
<img src="https://user-images.githubusercontent.com/2206639/199810572-70aa3571-2c0e-45d9-982e-24f0182f18d9.svg" width="384"/>

When I derive the icon, my steps are:
1. Ungroup all paths.
2. Subtract the "W" (+ sprinkles) path from the circle path.
3. Change the height to 24 while retaining the aspect ratio. The aspect ratio of the original icon is not exactly 1:1, its height is slightly larger than its width.
4. Change the viewport to 24x24 and center the path.

I perform all conversion steps with the highest possible precision in Boxy SVG.

When I compare this icon with optimized versions using SVGOMG, I get the following difference with a precision of 3
<img src="https://user-images.githubusercontent.com/2206639/199812184-759c1eb7-b42c-4d08-b391-5a821c4fee1a.svg" width="384"/>
and with a precision of 4:
<img src="https://user-images.githubusercontent.com/2206639/199812376-2ea67105-72e9-4b96-8bf1-d8e69107da13.svg" width="384"/>

There are some tiny negligible differences with a precision of 3 and practically no differences with a precision of 4.

I've suggested the path data of my derivation with a precision of 3 in case you're interested.

2022-11-03 19:11 UTC, sisp commented on icons/wayland.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Wayland</title><path d="M12 0a12 12 0 0 0-5.5996 1.42h2.3223v.1581c-.3184.0152-.5358.1001-.6504.252-.242-.1671-.4778-.252
```suggestion
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Wayland</title><path d="M23.982 12c0 9.224-9.985 14.989-17.973 10.377A11.982 11.982 0 0 1 .018 12c0-3.386 1.346-6.306 3.444-8.418v.675l.553 3.413v1.07l.077 1.365c-.23 0-.344.053-.344.159v.09l.344-.09h.076v2.366c.178 1.578.509 2.981.992 4.21.05.864.146 1.297.286 1.297.229.864.394 1.297.496 1.297a5.494 5.494 0 0 0 2.422 1.865c.344 0 .63-.432.859-1.296.292-1.866.528-3.004.706-3.414.165.167.451.281.858.342v-.091c0-.152-.26-.311-.782-.478.14-.728.33-1.35.572-1.866.038-.88.49-2.1 1.354-3.663l.344.09c.05.714.146 1.305.286 1.776.521 1.061.782 2.063.782 3.003 0 .364.407 1.585 1.22 3.663.204 1.366.465 2.17.783 2.412h.152c.42 0 .916-.538 1.488-1.615.56-1.214 1.011-1.889 1.354-2.025 0-.106-.12-.16-.362-.16v-.09c.19 0 .286-.054.286-.16v-.068l-.076-.091.801-.319c0-.273-.095-.41-.286-.41v-.09h.572v-.16c-.292 0-.483-.159-.572-.477h.133v-.319l-.076-.091c.432 0 .649-.083.649-.25v-.069h-.134v-.09c.153 0 .267-.16.343-.478-.42-.137-.629-.273-.629-.41l.553-1.615c0-.82.146-1.715.439-2.685.33-.94.566-1.965.706-3.072.304-1.064.617-1.787.938-2.17A11.979 11.979 0 0 1 23.982 12Zm-5.99-10.377c.587.34 1.138.724 1.65 1.148a33.45 33.45 0 0 0-.157 1.736c-.458 1.077-.96 2.594-1.507 4.55h-1.411l-.725.07v.181h.362l.286-.09 1.202.158v.092c-.343 1.183-.553 1.774-.63 1.774-.445 2.215-.8 3.322-1.068 3.322h-.229c-.318-.288-.674-.88-1.068-1.774a.861.861 0 0 0-.21-.57L13.42 9.855c-.216-1-.502-1.752-.858-2.252-.115-.334-.305-.5-.572-.5h-.134c-.42 0-.826.295-1.22.887l.076.25c-.178.607-.465 1.312-.859 2.116-.61 1.775-1.01 2.662-1.201 2.662h-.153l-.286-.227c-.483-1.305-.814-3.224-.992-5.757h-.134v-.16h.058a1.33 1.33 0 0 1 .515-.75v-.069l-.077-.09-.076.09-.076-.09-.344.09h-.152c-.09 0-.23-.348-.42-1.046v-.182h.496v-.16h-.648c-.139-.698-.545-1.53-1.218-2.494.296-.206.601-.398.915-.577h.016l.077.068.438-.068h.783c.228 0 .464.083.705.25.115-.152.33-.235.649-.25v-.16h-2.38c3.11-1.667 6.947-1.99 10.51-.392l-.443.142v.16c.24 0 .4-.095.482-.284.368.166.734.354 1.095.562Zm3.477 3.203h-.134l.035-.295.179.23-.08.065ZM9.719 1.595h.572l.133.159.363-.16.42.069.438-.068v-.16H9.72v.16Zm3.7 1.297v.159l.21.09v-.09l.076-.091c.14 0 .21-.053.21-.16v-.068h-.21l-.286.16Zm-1.144.887h-.058l-.076-.068-.42.227v.16c.61-.137.916-.266.916-.387V3.62l-.362.159Zm-2.842.978c0 .167-.051.25-.153.25v.16c.598-.197 1.03-.417 1.297-.66V4.44l-1.144.318Zm4.482.57v.068l.153.182h.076l.134-.182v-.069l-.077-.09-.286.09Zm2.785.159v.09h.076l.134-.181v-.069h-.076l-.134.16Zm-1.354 1.206.152.25c.23 0 .37-.084.42-.25l-.286-.228c-.19.076-.286.152-.286.228Zm1.85.978v.091h.153l.057-.091v-.068l-.057-.091-.153.159Zm-3.128.978v.091h.21l.362-.34v-.07c-.382.077-.572.183-.572.32ZM2.24 12.13v.341h.153c.14-.106.305-.41.496-.91v-.068h-.076l-.573.637Zm9.328 3.413v.159l.076.091.572-.341v-.16h-.076l-.572.25Zm-7.267.887.21.82h.152l-.229-.888h-.133v.068Zm7.63 1.07.133.227h.076l.076-.068-.228-.25h-.058v.09Z"/></svg>
```

2023-01-09 19:38 UTC, sisp commented
/ping @valpackett

2023-01-10 05:18 UTC, valpackett commented
oh, sorry. Okay, merged your suggestion, now the linter complains that it's `23.964 x 23.999` and no dimension is exactly 24. oops..

2023-01-11 09:01 UTC, sisp requested changes
@valpackett Apologies for my negligence. I've made tiny change in the path data and `svglint` now passes locally for me.

2023-01-12 05:07 UTC, valpackett commented
Thanks, merged everything now

2023-01-12 14:14 UTC, merged