Add RTM icon
simple-icons/simple-icons pull request #8066
Opened 2022-11-27 17:18 UTC by jamu3l

![rtm](https://user-images.githubusercontent.com/119085608/204148755-69364b36-8923-4298-9b17-ccdc8f51e194.png)

**Similarweb rank:** 61,282
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
I picked the hex value from the logo in the Wikipedia article. They use different colours on their website and their social media logos and there is no brand guidelines available.

2022-12-02 21:09 UTC, dirien reviewed
Hi @jamu3l,

thanks for the contribution. Can you please open an issue for this PR too? 

Thanks!

2022-12-02 23:28 UTC, jamu3l commented
Hey @dirien, I opened an issue (#8095) for this PR and #8062, #8072 and #8073.

2022-12-05 11:01 UTC, dirien requested changes
hi @jamu3l,

can you check the precision of the icon? Maybe up to 4?

I see some differences!
![image](https://user-images.githubusercontent.com/38325136/205621496-05ac1507-fcb5-4b34-8019-7fd5e80e8538.png)

2023-09-18 11:27 UTC, runxel commented
Hi @jamu3l, are you still on this? :)

2023-11-09 05:03 UTC, PratyushJayachandran reviewed
I am taking up this PR as it seems abandoned

2023-11-09 05:03 UTC, PratyushJayachandran commented on _data/simple-icons.json
> +            "hex": "244FA2",
```suggestion
            "hex": "36474F",
```
Picked color from the SVG logo on their website https://www.rtm.fr

2023-11-09 05:03 UTC, PratyushJayachandran commented on icons/rtm.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>RTM</title><path d="M5.584 9.053H1.98l-.487 1.414h3.408c.54 0 .594.25.51.494-.084.244-.18.322-.719.322h-3.43L0 14.947h1.9
```suggestion
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>RTM</title><path d="M5.584 9.054H1.98l-.487 1.413h3.408c.54 0 .594.25.51.494-.084.244-.18.323-.719.323h-3.43L0 14.946h1.917l.892-2.454c.263 0 .33.024.436.257l1.043 2.197h2.084l-1.148-2.46c1.368-.15 1.985-.822 2.206-1.698.211-.837-.173-1.734-1.846-1.734m2.817 0-.487 1.413H10l-1.541 4.48 2.036-.001 1.54-4.479h1.94l.486-1.413H8.4zm7.89 0h-1.306l-.485 1.414h.624c.272 0 .416.22.322.493l-1.368 3.985h2.036l1.37-3.988c.37-1.08.053-1.905-1.194-1.904m3.186 0h-1.16l-.486 1.414h.48c.271 0 .415.22.322.493l-1.368 3.985H19.3l1.37-3.988c.37-1.08.053-1.904-1.194-1.904m3.185 0h-1.16l-.485 1.414h.479c.272 0 .416.22.323.493l-1.369 3.985h2.036l1.37-3.988c.37-1.08.054-1.904-1.194-1.904"/></svg>
```

SVG available on their website header https://www.rtm.fr

2023-11-09 05:03 UTC, PratyushJayachandran commented on _data/simple-icons.json
> +            "source": "https://commons.wikimedia.org/wiki/File:Logortmcdm.svg",
```suggestion
            "source": "https://www.rtm.fr",
```

2023-11-09 05:08 UTC, PratyushJayachandran commented
> I am taking up this PR as it seems abandoned

@simple-icons/icon-review can someone review this?
![rtm](https://github.com/simple-icons/simple-icons/assets/35000807/a0de7737-5d2f-4d0c-a6ef-dcb845a47bbf)

2023-11-21 15:02 UTC, adamrusted approved these changes

2023-11-21 15:04 UTC, merged