Newicon interworks
simple-icons/simple-icons pull request #8086
Opened 2022-11-30 04:11 UTC by simrahnb

Added InterWorks icon to icons folder and updated the simple-icons.json file. 

**Issue:** closes #7615 

**Similarweb rank:**296,503

### Checklist
  - [✓ ] I updated the JSON data in `_data/simple-icons.json`
  - [ ✓] I optimized the icon with SVGO or SVGOMG
  - [ ✓] The SVG `viewbox` is `0 0 24 24`

### Description
Everything seems good except for a "Data File formatted incorrectly" error that I'm getting when I run npm lint.

2022-11-30 09:02 UTC, simrahnb commented
Fixed formatting issue.

2023-07-16 10:55 UTC, adamrusted requested changes
Not checked the icon on this one yet, but the source could be updated to their website.
What was the popularity metric for this, as their website is currently sitting at [523,692](https://www.similarweb.com/website/interworks.com/#overview) which would put it squarely out of scope.

2023-07-16 10:55 UTC, adamrusted commented on _data/simple-icons.json
> +            "source": "https://user-images.githubusercontent.com/109748036/180245879-0c831ea8-0ee3-4223-bbf1-0ae216740692.svg"
```suggestion
            "source": "https://interworks.com"
```

SVG icon now available at the homepage, could you please update the source, and double check your contribution matches up to this version?

2023-11-21 11:11 UTC, PeterShaggyNoble commented
Closing this as the rank has fallen even further to 834155, putting it well outside our scope. If the rank recovers or there's another metric of popularity we can use that would put this back within our scope then please comment in the linked issue above and we can revisit.

2023-11-21 11:11 UTC, closed without merging