[ADD] Icon Vega Altair
simple-icons/simple-icons pull request #8090
Opened 2022-11-30 16:33 UTC by apluquet

![vegaaltair](https://user-images.githubusercontent.com/92380416/204852339-955798db-1c01-4529-974d-169d60b63312.png)

**Issue:** closes #8064

**Similarweb rank:**
  
The project has 7.9k stars on [its github](https://github.com/altair-viz/altair).

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

- I picked this hexadecimal value because it is the most represented color on the logo of vega altair (light version, currently used on their [website](https://altair-viz.github.io/)).
- I filled in the license in the .json file as "custom" because "BSD-3-Clause" (from [SPDX License ID](https://spdx.org/licenses/)) would not pass the linter with "npm run lint".

2023-07-16 11:28 UTC, adamrusted requested changes
Thanks for this contribution @apluquet!
I've suggested a couple changes below, do you think you'd be able to take a look?

2023-07-16 11:28 UTC, adamrusted commented on icons/vegaaltair.svg
As per our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) I would expect to see gaps between the different elements of this logo, similar to the red overlay [here](https://github.com/simple-icons/simple-icons/assets/1830867/2c52eda6-8b19-4c90-8e92-fff3db3f455c). In that example, I've used an outer stroke of 1pt on each shape to create this effect.

2023-07-16 11:28 UTC, adamrusted commented on _data/simple-icons.json
> +                "url": "https://github.com/altair-viz/altair/blob/master/LICENSE"
```suggestion
                "url": "https://github.com/altair-viz/altair/blob/68d197e8783db5a53a49a246fc2c2ce0f0205ef7/LICENSE"
```
I'd also version your license, just to play it safe!

2023-07-16 11:32 UTC, sisp requested changes

2023-07-16 11:34 UTC, adamrusted commented on _data/simple-icons.json
> +                "url": "https://github.com/altair-viz/altair/blob/master/LICENSE"
Well spotted!

2023-11-21 11:06 UTC, PeterShaggyNoble commented
Closing this due to lack of activity. @apluquet, if you would like to continue working on this then we can reopen this PR or you can create a new one.

2023-11-21 11:06 UTC, closed without merging