Toll
simple-icons/simple-icons pull request #8203
Opened 2023-01-03 06:27 UTC by chrimaho

![toll](https://user-images.githubusercontent.com/44449504/210308853-e9da7734-4a0b-4f14-a642-43dff05f0a68.png)

**Issue:** closes #8198

**Similarweb rank:** 258,785
https://www.similarweb.com/website/tollgroup.com

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Icon as as per Company website.

2023-07-16 11:00 UTC, adamrusted requested changes
Couple changes needed before we can merge this one in, thanks for your work to date @chrimaho - and sorry a review has taken this long!

2023-07-16 11:00 UTC, adamrusted commented on icons/toll.svg
From the SVG in the website header, there seems to be [quite a few differences](https://github.com/simple-icons/simple-icons/assets/1830867/dfc399bd-50c7-468d-a7b2-43c1847114f9) between your PR in black, and the source icon in red. Would you mind taking another look?

2023-07-28 05:06 UTC, chrimaho commented
Hi @adamrusted , thanks for the feedback 👍  
I've now fixed it up.

2023-07-28 05:26 UTC, chrimaho commented
![image](https://github.com/simple-icons/simple-icons/assets/44449504/0e896300-933b-45ea-8e99-52d60d297ebe)

2023-11-21 11:00 UTC, adamrusted approved these changes

2023-11-21 11:13 UTC, merged