New Icon: yr
simple-icons/simple-icons pull request #8216
Opened 2023-01-04 07:31 UTC by FSund

**Issue:** closes #8215

**Similarweb rank:** 1226

### Checklist
  - [X] I updated the JSON data in `_data/simple-icons.json`
  - [X] I optimized the icon with SVGO or SVGOMG
  - [X] The SVG `viewbox` is `0 0 24 24`

### Description

The hex value was retrieved from the original PDF/vector file.

The svg was simplified as much as I was able to.

2023-07-16 11:06 UTC, adamrusted requested changes
Couple of changes needed on this one before we can merge it. Would you mind taking another look @FSund?

2023-07-16 11:06 UTC, adamrusted commented on icons/yr.svg
I'm seeing [some differences](https://github.com/simple-icons/simple-icons/assets/1830867/82dad94d-851b-4bbf-86ac-f7734f0edc47) between your PR in black and the SVG found in their website header (code below). Would you mind taking another look at this one?
```html
<svg width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xml:space="preserve" xmlns:serif="http://www.serif.com/" style="fill-rule:evenodd;clip-rule:evenodd;stroke-linejoin:round;stroke-miterlimit:2;"><path d="M33.642,26.523C33.642,26.523 32.853,26.743 32.265,26.113C31.573,25.373 30.48,23.883 30.48,23.883C31.433,23.623 32.303,23.12 33.003,22.423C34.11,21.322 34.713,19.762 34.707,18.083C34.723,16.338 33.957,14.77 32.747,13.787C31.542,12.792 29.988,12.33 28.372,12.328L25.523,12.328C22.867,12.334 20.682,14.518 20.677,17.175L20.677,29.135L23.907,29.135L23.907,25.742C23.918,24.86 24.641,24.137 25.523,24.127L26.81,24.127L30.285,28.383L30.528,28.683C30.792,28.935 31.137,29.1 31.522,29.133L31.522,29.135L31.592,29.135C31.636,29.141 31.681,29.141 31.725,29.135L33.637,29.135L33.642,26.523ZM14.598,29.635C15.927,28.893 18.565,27.418 18.58,23.44L18.58,12.848L15.385,12.848L15.382,18.07C15.322,20.017 13.498,20.647 12.047,20.667C10.388,20.643 8.64,19.723 8.64,17.195L8.64,12.848L5.488,12.848L5.488,17.195C5.488,19.168 6.17,20.853 7.462,22.07C8.63,23.17 10.232,23.788 11.982,23.818L12.112,23.818C13.287,23.797 15.013,23.03 15.348,22.353L15.348,23.792C15.348,25.698 12.923,26.942 12.27,27.268L12.317,27.325L12.27,27.348L14.3,29.803L14.6,29.635L14.598,29.635ZM28.37,15.56C29.378,15.56 30.187,15.855 30.687,16.273C31.178,16.702 31.46,17.203 31.477,18.082C31.472,19.027 31.17,19.682 30.72,20.138C30.262,20.59 29.608,20.892 28.663,20.895L25.522,20.895C25.035,20.897 24.567,21.067 24.123,21.228L23.907,21.307L23.907,17.175C23.918,16.293 24.641,15.571 25.523,15.56L28.37,15.56ZM20,0C8.955,0 0,8.953 0,20C0,31.045 8.955,40 20,40C31.047,40 40,31.045 40,20C40,8.953 31.047,0 20,0Z" style="fill:#fff;"/></svg>
```

2023-07-16 11:06 UTC, adamrusted commented on _data/simple-icons.json
> +            "source": "https://info.nrk.no/design/profiler/yr/"
```suggestion
            "source": "https://www.yr.no"
```

2023-07-16 19:12 UTC, FSund commented on icons/yr.svg
Strange. They might have tweaked the icon since I opened the PR. I have updated the icon to the latest version now. Please have a look at your leisure.

2023-11-24 03:21 UTC, PratyushJayachandran requested changes
Taking up this PR

2023-11-24 03:21 UTC, PratyushJayachandran commented on _data/simple-icons.json
> +            "hex": "00B8F1",
```suggestion
            "hex": "00B9F1",
```
Taken from their logo on their website

2023-11-24 03:21 UTC, PratyushJayachandran commented on icons/yr.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Yr</title><path d="M12 0C5.373 0 0 5.372 0 12c0 6.627 5.373 12 12 12 6.628 0 12-5.373 12-12 0-6.628-5.372-12-12-12zm3.314
```suggestion
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Yr</title><path d="M18.264 9.648c.288.264.456.552.48 1.08 0 .552-.192.936-.456 1.224a1.83 1.83 0 0 1-1.224.432h-1.848c-.336 0-.648.144-.96.24v-2.448c0-.528.432-.96.96-.96h1.68c.6 0 1.08.168 1.368.432zM24 12c0 6.627-5.373 12-12 12S0 18.627 0 12 5.373 0 12 0s12 5.373 12 12zM11.112 7.632H9.216v3.096c-.048 1.152-1.104 1.536-1.968 1.536-.984-.024-2.016-.552-2.016-2.064V7.632H3.36V10.2c0 1.176.408 2.16 1.176 2.88.696.648 1.632 1.008 2.664 1.032h.096c.696-.024 1.704-.456 1.92-.864v.84c0 1.128-1.44 1.872-1.824 2.064l.024.024s-.024 0-.024.024l1.2 1.44c.696-.408 2.52-1.224 2.52-3.768v-6.24zm7.032 6.504a3.435 3.435 0 0 0 1.488-.864c.648-.648 1.008-1.584 1.008-2.568 0-1.032-.456-1.968-1.152-2.544-.72-.576-1.632-.864-2.592-.864h-1.68a2.848 2.848 0 0 0-2.856 2.856v7.08h1.92v-2.016c0-.528.432-.96.96-.96h.768l2.016 2.544.144.168c.144.144.36.24.576.264h1.272v-1.536s-.48.144-.816-.24c-.408-.432-1.056-1.32-1.056-1.32z"/></svg>
```
Re-did icon from their website.

2023-11-24 03:22 UTC, PratyushJayachandran commented
> Still spotting a [minor difference](https://github.com/simple-icons/simple-icons/assets/1830867/3332f5d9-da1e-4a22-a8a6-ea45777f9809) between your PR in black and the logo on the site in red. Looks like they've just sharpened the leg of that `R` up a bit. Would you mind reprocessing with the current version on the homepage?

I brough it up to spec. PLease review @adamrusted

2023-11-25 11:41 UTC, adamrusted requested changes
@PratyushJayachandran - see below differences...
![image](https://github.com/simple-icons/simple-icons/assets/1830867/9750a106-a0bb-45e3-8f6d-e88c97147fcb)

SVG from source:
```xml
<svg id="icon-logo-yr"><path fill="#fff" fill-rule="evenodd" d="M12 0C5.373 0 0 5.372 0 12c0 6.627 5.373 12 12 12 6.628 0 12-5.373 12-12 0-6.628-5.372-12-12-12z" clip-rule="evenodd"></path><path fill="currentColor" fill-rule="evenodd" d="M20.185 15.914s-.473.132-.826-.246c-.415-.444-1.071-1.338-1.071-1.338a3.427 3.427 0 0 0 1.514-.876c.664-.661 1.026-1.597 1.022-2.604.01-1.047-.45-1.988-1.176-2.578-.723-.597-1.655-.874-2.625-.875h-1.709a2.914 2.914 0 0 0-2.908 2.908v7.176h1.938v-2.036a.982.982 0 0 1 .97-.969h.772l2.085 2.554.146.18c.158.151.365.25.596.27v.001h.042a.282.282 0 0 0 .08 0h1.147l.003-1.567zM8.759 17.781c.797-.445 2.38-1.33 2.389-3.717V7.709H9.231l-.002 3.133c-.036 1.168-1.13 1.546-2.001 1.558-.995-.014-2.044-.566-2.044-2.083V7.709H3.293v2.608c0 1.184.409 2.195 1.184 2.925.701.66 1.662 1.031 2.712 1.049h.078c.705-.013 1.741-.473 1.942-.879v.863c0 1.144-1.455 1.89-1.847 2.086l.028.034a.477.477 0 0 0-.01.005l-.018.009 1.218 1.473.18-.101zm8.263-8.445c.605 0 1.09.177 1.39.428.295.257.464.558.474 1.085-.003.567-.184.96-.454 1.234-.275.271-.667.452-1.234.454h-1.885c-.292.001-.573.103-.839.2l-.13.047v-2.479a.982.982 0 0 1 .97-.969h1.708zM12 0C5.373 0 0 5.372 0 12c0 6.627 5.373 12 12 12 6.628 0 12-5.373 12-12 0-6.628-5.372-12-12-12z" clip-rule="evenodd"></path></svg>
```

2023-11-26 02:49 UTC, PratyushJayachandran commented on icons/yr.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Yr</title><path d="M18.264 9.648c.288.264.456.552.48 1.08 0 .552-.192.936-.456 1.224a1.83 1.83 0 0 1-1.224.432h-1.848c-.3
```suggestion
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Yr</title><path d="M20.185 15.914s-.473.132-.826-.246c-.415-.444-1.071-1.338-1.071-1.338a3.427 3.427 0 0 0 1.514-.876c.664-.661 1.026-1.597 1.022-2.604.01-1.047-.45-1.988-1.176-2.578-.723-.597-1.655-.874-2.625-.875h-1.709c-1.6047.0033-2.9047 1.3033-2.908 2.908v7.176h1.938v-2.036a.982.982 0 0 1 .97-.969h.772l2.085 2.554.146.18c.158.151.365.25.596.27v.001h.042a.282.282 0 0 0 .08 0h1.147l.003-1.567zM8.759 17.781c.797-.445 2.38-1.33 2.389-3.717V7.709H9.231l-.002 3.133c-.036 1.168-1.13 1.546-2.001 1.558-.995-.014-2.044-.566-2.044-2.083V7.709H3.293v2.608c0 1.184.409 2.195 1.184 2.925.701.66 1.662 1.031 2.712 1.049h.078c.705-.013 1.741-.473 1.942-.879v.863c0 1.144-1.455 1.89-1.847 2.086l.028.034a.4766.4766 0 0 0-.01.005l-.018.009 1.218 1.473.18-.101h-.001zm8.263-8.445c.605 0 1.09.177 1.39.428.295.257.464.558.474 1.085-.003.567-.184.96-.454 1.234-.275.271-.667.452-1.234.454h-1.885c-.292.001-.573.103-.839.2l-.13.047v-2.479a.982.982 0 0 1 .97-.969h1.708zM12 0C5.373 0 0 5.372 0 12c0 6.627 5.373 12 12 12 6.628 0 12-5.373 12-12 0-6.628-5.372-12-12-12z"
```

2023-11-26 02:50 UTC, PratyushJayachandran commented
@adamrusted Please check again, I redid from the source you attached with precision 4.

2023-11-26 03:01 UTC, PratyushJayachandran commented on icons/yr.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Yr</title><path d="M20.185 15.914s-.473.132-.826-.246c-.415-.444-1.071-1.338-1.071-1.338a3.427 3.427 0 0 0 1.514-.876c.66
```suggestion
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Yr</title><path d="M20.185 15.914s-.473.132-.826-.246c-.415-.444-1.071-1.338-1.071-1.338a3.427 3.427 0 0 0 1.514-.876c.664-.661 1.026-1.597 1.022-2.604.01-1.047-.45-1.988-1.176-2.578-.723-.597-1.655-.874-2.625-.875h-1.709c-1.6047.0033-2.9047 1.3033-2.908 2.908v7.176h1.938v-2.036a.982.982 0 0 1 .97-.969h.772l2.085 2.554.146.18c.158.151.365.25.596.27v.001h.042a.282.282 0 0 0 .08 0h1.147l.003-1.567zM8.759 17.781c.797-.445 2.38-1.33 2.389-3.717V7.709H9.231l-.002 3.133c-.036 1.168-1.13 1.546-2.001 1.558-.995-.014-2.044-.566-2.044-2.083V7.709H3.293v2.608c0 1.184.409 2.195 1.184 2.925.701.66 1.662 1.031 2.712 1.049h.078c.705-.013 1.741-.473 1.942-.879v.863c0 1.144-1.455 1.89-1.847 2.086l.028.034a.4766.4766 0 0 0-.01.005l-.018.009 1.218 1.473.18-.101h-.001zm8.263-8.445c.605 0 1.09.177 1.39.428.295.257.464.558.474 1.085-.003.567-.184.96-.454 1.234-.275.271-.667.452-1.234.454h-1.885c-.292.001-.573.103-.839.2l-.13.047v-2.479a.982.982 0 0 1 .97-.969h1.708zM12 0C5.373 0 0 5.372 0 12c0 6.627 5.373 12 12 12 6.628 0 12-5.373 12-12 0-6.628-5.372-12-12-12z"/></svg>
```

2023-11-26 03:05 UTC, PratyushJayachandran commented on icons/yr.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Yr</title><path d="M20.185 15.914s-.473.132-.826-.246c-.415-.444-1.071-1.338-1.071-1.338a3.427 3.427 0 0 0 1.514-.876c.66
```suggestion
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Yr</title><path d="M18.412 9.764c.295.257.464.558.474 1.085-.003.567-.184.96-.454 1.234-.275.271-.667.452-1.234.454h-1.885c-.292.001-.573.103-.839.2l-.13.047v-2.479a.982.982 0 0 1 .97-.969h1.708c.605 0 1.09.177 1.39.428zM24 12c0 6.627-5.372 12-12 12-6.627 0-12-5.373-12-12C0 5.372 5.373 0 12 0c6.628 0 12 5.372 12 12zM11.148 7.709H9.231l-.002 3.133c-.036 1.168-1.13 1.546-2.001 1.558-.995-.014-2.044-.566-2.044-2.083V7.709H3.293v2.608c0 1.184.409 2.195 1.184 2.925.701.66 1.662 1.031 2.712 1.049h.078c.705-.013 1.741-.473 1.942-.879v.863c0 1.144-1.455 1.89-1.847 2.086l.028.034a.3059.3059 0 0 0-.01.005l-.018.009 1.218 1.473.18-.101h-.001c.797-.445 2.38-1.33 2.389-3.717V7.709zm7.14 6.621a3.427 3.427 0 0 0 1.514-.876c.664-.661 1.026-1.597 1.022-2.604.01-1.047-.45-1.988-1.176-2.578-.723-.597-1.655-.874-2.625-.875h-1.709c-1.6047.0033-2.9047 1.3033-2.908 2.908v7.176h1.938v-2.036a.982.982 0 0 1 .97-.969h.772l2.085 2.554.146.18c.158.151.365.25.596.27v.001h.042a.283.283 0 0 0 .08 0h1.147l.003-1.567s-.473.132-.826-.246c-.415-.444-1.071-1.338-1.071-1.338z"/></svg>
```

2023-12-01 20:31 UTC, merged