New Icon: SQL Developer
simple-icons/simple-icons pull request #8222
Opened 2023-01-04 22:15 UTC by chrimaho

![oraclesqldeveloper](https://user-images.githubusercontent.com/44449504/210659986-92dc514d-07a4-4175-a724-592f31dbb40f.png)

**Issue:** closes #8221

**Similarweb rank:** 1,603
https://www.similarweb.com/website/oracle.com

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
The Oracle icon <img src="https://raw.githubusercontent.com/simple-icons/simple-icons/develop/icons/oracle.svg" width="20"> refers to the Company, while the Oracle SQL Developer icon <img src="https://www.oracle.com/a/ocom/img/sql-dev3.svg" width="20"> refers to the IDE used to write SQL script for Oracle databases. The Oracle icon is already available, while but the Oracle SQL Developer icon is not; hence why raise this PR.

2023-07-16 11:16 UTC, adamrusted requested changes

2023-07-16 11:16 UTC, adamrusted commented on _data/simple-icons.json
> +            "source": "https://www.oracle.com/au/database/sqldeveloper",
```suggestion
            "source": "https://www.oracle.com/database/sqldeveloper",
```

2023-07-16 11:16 UTC, adamrusted commented on _data/simple-icons.json
> +            }
```suggestion
            "guidelines": "https://www.oracle.com/legal/logos.html"
```

2023-07-16 11:16 UTC, adamrusted commented on icons/oraclesqldeveloper.svg
I'm not 100% on the tiny gap at the top of the stack. Would you be able to expand that to 1px, instead of 0.5?

2023-07-28 05:23 UTC, chrimaho commented
Now fixed 👍 
Thanks!

2023-07-28 05:23 UTC, chrimaho commented
![image](https://github.com/simple-icons/simple-icons/assets/44449504/d2a33e25-fe05-4cd1-8964-9bf939a55456)

2023-11-21 11:19 UTC, adamrusted requested changes
Hey @chrimaho - I'm still seeing some differences in the icon SVG unfortunately.
Would you be up for giving this another go, or would you me to lend a hand?

2023-11-21 11:19 UTC, adamrusted commented on icons/oraclesqldeveloper.svg
![image](https://github.com/simple-icons/simple-icons/assets/1830867/f6c74366-4a2b-4965-a6c0-c96632b5191f)

2023-12-08 13:07 UTC, PeterShaggyNoble commented
Are you still working on this one, @chrimaho?

2023-12-15 22:46 UTC, chrimaho commented
Yes. Please give me some more time.

2024-01-11 15:12 UTC, PeterShaggyNoble commented
Closing due to inactivity. If you would like to continue working on this, @chrimaho then we can reopen it for you. If someone else would like to take it on then please open a new PR.

2024-01-11 15:12 UTC, closed without merging