New Icon: Session
simple-icons/simple-icons pull request #8246
Opened 2023-01-12 16:56 UTC by ripzerotwo

**Issue:** closes #8197 

**Similarweb rank:** 205,337 (https://www.similarweb.com/website/getsession.org/#overview)

### Checklist
  - [X] I updated the JSON data in `_data/simple-icons.json`
  - [X] I optimized the icon with SVGO or SVGOMG
  - [X] The SVG `viewbox` is `0 0 24 24`

### Description
![session](https://user-images.githubusercontent.com/64280645/212130900-3ad2c3eb-5e23-451f-810e-abfb953af700.png)

2023-07-12 12:19 UTC, service-paradis requested changes

2023-07-12 12:19 UTC, service-paradis commented on _data/simple-icons.json
> +            "source": "https://getsession.org/assets/downloads/Session-Brandmarks.zip"
Please use only `https://getsession.org` for the source since we can found the direct links in the footer.

2023-07-12 12:19 UTC, service-paradis commented on icons/session.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Session</title><path d="m19.4 12.2-4.5-2.5H18c2.7 0 4.8-2.2 4.8-4.8S20.6 0 18 0H7.3C3.9 0 1.2 2.7 1.2 6.1c0 2.4 1.3 4.6 3
You may need to use a higher precision while using SVGO. Right now, there are significant differences. Ex. 
![image](https://github.com/simple-icons/simple-icons/assets/12817388/ed89f458-e3d3-4f6a-b0a7-21424fc9e0c6)

Can you take another look at it?

2023-11-22 12:31 UTC, PeterShaggyNoble requested changes

2023-11-22 12:31 UTC, PeterShaggyNoble commented on _data/simple-icons.json
> +            "source": "https://getsession.org/assets/downloads/Session-Brandmarks.zip"
```suggestion
            "source": "https://getsession.org"
```

2023-11-22 12:31 UTC, PeterShaggyNoble commented on icons/session.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Session</title><path d="m19.4 12.2-4.5-2.5H18c2.7 0 4.8-2.2 4.8-4.8S20.6 0 18 0H7.3C3.9 0 1.2 2.7 1.2 6.1c0 2.4 1.3 4.6 3
```suggestion
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Session</title><path d="m19.431 12.193-4.53-2.51h3.071a4.847 4.847 0 0 0 4.842-4.841A4.848 4.848 0 0 0 17.972 0H7.252a6.073 6.073 0 0 0-6.066 6.066 6.566 6.566 0 0 0 3.383 5.741l4.53 2.51H6.028a4.847 4.847 0 0 0-4.842 4.841A4.848 4.848 0 0 0 6.028 24h10.72a6.073 6.073 0 0 0 6.066-6.066 6.568 6.568 0 0 0-3.383-5.741zm-14.136-1.7a5.065 5.065 0 0 1-2.607-4.309C2.627 3.61 4.79 1.5 7.367 1.5h10.508c1.797 0 3.345 1.378 3.434 3.173a3.345 3.345 0 0 1-3.337 3.51H11.92a.67.67 0 0 0-.67.67l-.001 4.94zM16.633 22.5H6.124c-1.797 0-3.345-1.378-3.434-3.173a3.345 3.345 0 0 1 3.337-3.51h6.053c.37 0 .67-.3.67-.67v-4.94l5.954 3.3a5.065 5.065 0 0 1 2.608 4.309c.06 2.575-2.103 4.684-4.679 4.684"/></svg>
```

2023-11-24 08:06 UTC, PratyushJayachandran approved these changes
Thank you for finishing up @PeterShaggyNoble and tahnk you for starting th issue @ripzerotwo :tada

2023-11-24 08:07 UTC, merged