New Icon: Ton
simple-icons/simple-icons pull request #8249
Opened 2023-01-12 19:46 UTC by ripzerotwo

**Issue:** closes #

**Similarweb rank:** 88,756 (https://www.similarweb.com/website/ton.org/#overview)

### Checklist
  - [X] I updated the JSON data in `_data/simple-icons.json`
  - [X]  I optimized the icon with SVGO or SVGOMG
  - [X] The SVG `viewbox` is `0 0 24 24`

### Description
![ton](https://user-images.githubusercontent.com/64280645/212165999-e0186a12-f9ec-408b-bcb7-e6c462615743.png)

2023-07-12 12:26 UTC, service-paradis requested changes

2023-07-12 12:26 UTC, service-paradis commented on icons/ton.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Ton</title><path d="M8.4 9c-.1 0-.2.1-.2.2s-.1.1 0 .2c0 0 0 .1.1.3l3.2 5.6V9H8.4zm7.3.1c0-.1 0-.1 0 0-.1-.1-.2-.1-.3-.1h-
I'm seeing major differences between your version and the SVG symbol found in their brand assets. Can you take another look at it?
![image](https://github.com/simple-icons/simple-icons/assets/12817388/2a652ff8-3027-44b9-87b5-7d4f1d04bf57)

2023-11-10 13:34 UTC, T8RIN commented
I can provide normal icon

2023-11-19 05:20 UTC, liketurbo commented
@ripzerotwo, Hi there! Sorry to bother you, but could you, please, update the code as per the requested changes? 
Alternatively, if you've lost interest, could you close the PR as only one PR can exist at a time?

2023-11-23 14:54 UTC, PeterShaggyNoble requested changes

2023-11-23 14:54 UTC, PeterShaggyNoble commented on _data/simple-icons.json
> +        },
```suggestion
        {
            "title": "TON",
            "hex": "0098EA",
            "source": "https://ton.org/en/brand-assets",
            "guidelines": "https://ton.org/en/brand-assets"
        },
```

2023-11-23 14:54 UTC, PeterShaggyNoble commented on icons/ton.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Ton</title><path d="M8.4 9c-.1 0-.2.1-.2.2s-.1.1 0 .2c0 0 0 .1.1.3l3.2 5.6V9H8.4zm7.3.1c0-.1 0-.1 0 0-.1-.1-.2-.1-.3-.1h-
```suggestion
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Ton</title><path d="M12 0C5.373 0 0 5.373 0 12s5.373 12 12 12 12-5.373 12-12S18.627 0 12 0zM7.902 6.697h8.196c1.505 0 2.462 1.628 1.705 2.94l-5.059 8.765a.86.86 0 0 1-1.488 0L6.199 9.637c-.758-1.314.197-2.94 1.703-2.94zm4.844 1.496v7.58l1.102-2.128 2.656-4.756a.465.465 0 0 0-.408-.696h-3.35zM7.9 8.195a.464.464 0 0 0-.408.694l2.658 4.754 1.102 2.13V8.195H7.9z"/></svg>
```

2023-11-24 08:09 UTC, PratyushJayachandran approved these changes
Thank you for finishing up @PeterShaggyNoble and thank you for starting PR @ripzerotwo  🎉

2023-11-24 08:21 UTC, merged