New Icon: Moq
simple-icons/simple-icons pull request #8274
Opened 2023-01-20 17:29 UTC by ripzerotwo

**Issue:** closes #8261 

**Similarweb rank:** N/A
**Github stars:** 5k stars

### Checklist
  - [X] I updated the JSON data in `_data/simple-icons.json`
  - [X] I optimized the icon with SVGO or SVGOMG
  - [X] The SVG `viewbox` is `0 0 24 24`

### Description
Manually vectorize png i.e. remade. Font was sourced from repo creator (https://www.myfonts.com/search?query=platelet).
Preview...
![moq](https://user-images.githubusercontent.com/64280645/213764893-c6159f6b-a4c3-478f-9ae9-85cc25f64d57.png)

2023-11-24 08:27 UTC, PratyushJayachandran requested changes

2023-11-24 08:27 UTC, PratyushJayachandran commented on icons/moq.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Moq</title><path d="M17.544 9.062a.855.855 0 0 0-.876.863V11.7c0 .42.312.863.876.863s.875-.443.875-.863V9.925a.854.854 0
Hello @ripzerotwo, on comparing with the original, it is not matching up.
![image](https://github.com/simple-icons/simple-icons/assets/35000807/26d91820-19ab-4e9c-98fd-915e942a8a04)

2023-12-08 13:06 UTC, PeterShaggyNoble commented
Are you still working on this one, @ripzerotwo?

2024-01-11 11:17 UTC, closed without merging

2024-01-11 11:17 UTC, PeterShaggyNoble commented
Closing due to inactivity. If you would like to continue working on this, @ripzerotwo then we can reopen it for you. If someone else would like to take it on then please open a new PR.