Kiwigrid logo
simple-icons/simple-icons pull request #8302
Opened 2023-02-02 11:47 UTC by jackalski

![kiwigrid](https://user-images.githubusercontent.com/7739107/216316215-f4d38687-bd34-403d-a6f5-7e04a36cc61f.png)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Official Kiwigrid logo in SVG

2023-07-16 11:54 UTC, adamrusted requested changes

2023-07-16 11:54 UTC, adamrusted commented on _data/simple-icons.json
> +            "source": "https://kiwigrid.com/"
```suggestion
            "source": "https://kiwigrid.com"
```

2023-07-16 11:54 UTC, adamrusted commented on icons/kiwigrid.svg
There seems to be [some differences](https://github.com/simple-icons/simple-icons/assets/1830867/e47295ae-d0a5-49a3-9c9d-328fd36ed7b3) between your PR in black, and the logo available on the site in red. Would you mind taking another look?

2023-08-08 17:40 UTC, service-paradis commented
It does not meet our popularity requirements:
https://www.similarweb.com/website/kiwigrid.com/#overview

Do you have more information we can use @jackalski ?

2023-08-14 20:37 UTC, service-paradis commented
Closing since it is out of scope.

2023-08-14 20:37 UTC, closed without merging