New Icon: Pico.CSS
simple-icons/simple-icons pull request #8308
Opened 2023-02-03 13:53 UTC by ripzerotwo

**Issue:** closes #8289 

**Similarweb rank:** [314,971](https://www.similarweb.com/website/picocss.com/#overview)

### Checklist
  - [X] I updated the JSON data in `_data/simple-icons.json`
  - [X] I optimized the icon with SVGO or SVGOMG
  - [X] The SVG `viewbox` is `0 0 24 24`

### Description
color grabbed from website using color pick eyedropper.
![picodotcss](https://user-images.githubusercontent.com/64280645/216620455-f9ee1821-4ca7-41e8-8cef-15e5f020df16.png)

2023-02-03 14:11 UTC, ripzerotwo commented
question if color should just be black.

2023-06-19 12:04 UTC, LitoMore commented
Hi @lucaslarroche, may I ask for approval from you on this PR? Thank you!

2023-07-16 11:57 UTC, adamrusted requested changes

2023-07-16 11:57 UTC, adamrusted commented on _data/simple-icons.json
> +            }
```suggestion
            "source": "https://picocss.com"
```

There's an SVG in the header of the site, and we don't need to worry about the alias.

2023-07-16 11:57 UTC, adamrusted commented on icons/picodotcss.svg
Not reviewed this icon yet. Will likely be different to the source once source updated.

2023-11-20 12:06 UTC, PeterShaggyNoble commented
Note that while [the ranking](https://www.similarweb.com/website/picocss.com/) of the website has dropped since this PR was opened, putting it below our 500k threshold, it's [GH stars](https://github.com/picocss/pico) still put it within our scope. However, development seems to have stalled with [no commits to their primary repo](https://github.com/picocss/pico/graphs/commit-activity) since April.

Should we label this as https://github.com/simple-icons/simple-icons/labels/out%20of%20scope for now, pending further monitoring?

This brings to light a possible issue with us using GH stars as a metric of popularity as they are not a reflection of current, real time popularity in the same way Similarweb is, rather they reflect a cumulative popularity over the lifetime of a project. Perhaps we need to revisit _how_ we use stars as a metric of popularity but that discussion should be had separately.

2023-11-24 09:17 UTC, PratyushJayachandran commented
> Note that while [the ranking](https://www.similarweb.com/website/picocss.com/) of the website has dropped since this PR was opened, putting it below our 500k threshold, it's [GH stars](https://github.com/picocss/pico) still put it within our scope. However, development seems to have stalled with [no commits to their primary repo](https://github.com/picocss/pico/graphs/commit-activity) since April.
> 
> Should we label this as [ out of scope](https://github.com/simple-icons/simple-icons/labels/out%20of%20scope) Issues or pull requests that are beyond the scope of the project for now, pending further monitoring?
> 
> This brings to light a possible issue with us using GH stars as a metric of popularity as they are not a reflection of current, real time popularity in the same way Similarweb is, rather they reflect a cumulative popularity over the lifetime of a project. Perhaps we need to revisit _how_ we use stars as a metric of popularity but that discussion should be had separately.

I agree with the rest of the reasoning, but how do we decide what the recent commit should be? Last commit being 6 months ago doesn't seem that bad to me. Maybe the maintainer took a break. Website is up and there doesn't seem to be any message about being discontinued.

2023-11-30 08:29 UTC, adamrusted commented
Let's use the 6mth threshold for GH updates for now then. Given the main package hasn't been updated since 22nd April, that would therefore put this out of scope for the time being. Thanks regardless for your work @ripzerotwo - and if the repository receives updates in the near future, please feel free to re-open this PR!

2023-11-30 08:29 UTC, closed without merging