Add Juejin icon
simple-icons/simple-icons pull request #8457
Opened 2023-03-23 19:07 UTC by LitoMore

<img width="725" alt="CleanShot 2023-03-24 at 03 01 50@2x" src="https://user-images.githubusercontent.com/8186898/227320996-1977c8fd-a08d-4ee7-b74e-fe3148ef8cd2.png">

**Similarweb rank:** [3,790](https://www.similarweb.com/website/juejin.cn/#overview)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Juejin is a UGC for global Chinese developers.

### Resources

See the bottom place of https://xitu.juejin.cn. You will find a link for `Press Kit`.

I used the `Press Kit/svg/logo_blue.svg` for processing this icon.

Its primary color is `#007FFF`. You can find the color inside the SVG file.

### Difference preview

<img width="785" alt="CleanShot 2023-03-24 at 02 58 49@2x" src="https://user-images.githubusercontent.com/8186898/227320536-09ed6f0c-433f-41ec-82f5-7958c7c69804.png">

2023-05-20 19:18 UTC, LitoMore commented
@simple-icons/icon-review Can I get an approval?

2023-07-12 12:35 UTC, service-paradis commented
Unfortunately, I'm not able to access https://xitu.juejin.cn. Got a 502 bad gateway response...

2023-07-12 12:50 UTC, LitoMore commented
@service-paradis See the description. I've uploaded their press kit ZIP file here.

2023-07-16 14:49 UTC, adamrusted requested changes

2023-07-16 14:49 UTC, adamrusted commented on _data/simple-icons.json
> +            "source": "https://xitu.juejin.cn"
```suggestion
            "source": "https://juejin.cn"
```

There's an SVG source in the header of the site now @LitoMore :)

2023-07-16 14:49 UTC, adamrusted commented on icons/juejin.svg
[Slight difference](https://github.com/simple-icons/simple-icons/assets/1830867/194203ef-499a-46d3-945d-927a3bd15688) between proposed new source in red, and this PR in black. Could you take another look?

2023-07-17 09:15 UTC, LitoMore commented
<img width="528" alt="image" src="https://github.com/simple-icons/simple-icons/assets/8186898/7589dc28-33f4-4481-975e-81259c2abd11">

Updated according to the new source.

2023-07-18 11:49 UTC, adamrusted approved these changes
LGTM, thanks @LitoMore 🎉

2023-07-18 11:50 UTC, merged