Add Inertia Icon
simple-icons/simple-icons pull request #8508
Opened 2023-04-04 15:35 UTC by mchev

![Inertia](https://i.imgur.com/CvMYPdj.png)

**Issue:** closes #8503

**Similarweb rank:** : 286,911

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

2023-04-05 04:36 UTC, LitoMore commented
Hi @mchev, the SVG one can be found at their homepage. Let's use that one as reference.

2023-04-05 07:30 UTC, LitoMore commented on _data/simple-icons.json
> +            "hex": "FFFFFF",
```suggestion
            "hex": "000000",
```

Let's use black as its primary color.

2023-04-05 07:39 UTC, LitoMore commented
I just leave a message on their Discord for asking the correct primary color. Let's wait for their response.

https://discord.com/channels/592327939920494592/592327939920494594/1093076623265370142

2023-04-05 08:42 UTC, mchev commented
> I just leave a message on their Discord for asking the correct primary color. Let's wait for their response.
> 
> https://discord.com/channels/592327939920494592/592327939920494594/1093076623265370142

It looks like the icon itself is white. But why not use the #9553e9 (from gradient) as primary color.

2023-04-05 12:00 UTC, LitoMore commented on _data/simple-icons.json
> +            "hex": "FFFFFF",
```suggestion
            "hex": "9553E9",
```

@mchev We just got their approve to use `#9553e9` as primary color.

2023-06-02 07:43 UTC, ConrDev commented
here i grabbed the official `>>` logo that is issued in their original logo:

https://github.com/simple-icons/simple-icons/issues/8300

2023-06-02 23:56 UTC, LitoMore commented
<img width="527" alt="2023-06-02 at 23 52 37@2x" src="https://github.com/simple-icons/simple-icons/assets/8186898/ba6cc716-41d8-4d26-810b-40a2ba493bd3">

The icon still has some differences. Could you point out which resource are you using as reference? BTW, you could use the resource in https://github.com/simple-icons/simple-icons/pull/8508#issuecomment-1573300245 as a reference.

2023-06-03 06:41 UTC, mchev commented
Sorry but i really don't understand what are the issues here. 

Linter check : `collinear-segments Collinear segment "l-6.668 6.668" found at index 174 (should be removed)`
I have no idea what that means.

Sizes : I tried 3 different versions from official sources. If you have time to just share the correct SVG code with correct viewBox in comments i'll push it.

There is also https://github.com/simple-icons/simple-icons/pull/7376 (where i copy/pasted the last attempt)

2023-06-03 07:18 UTC, ConrDev commented
> <img width="527" alt="2023-06-02 at 23 52 37@2x" src="https://github.com/simple-icons/simple-icons/assets/8186898/ba6cc716-41d8-4d26-810b-40a2ba493bd3">
> 
> 
> 
> The icon still has some differences. Could you point out which resource are you using as reference? BTW, you could use the resource in https://github.com/simple-icons/simple-icons/pull/8508#issuecomment-1573300245 as a reference.

i don't really get why mine was closed for duplicate tbh, when the icon svg i shared is different from the others :p

2023-07-06 05:46 UTC, PratyushJayachandran requested changes
The issue should be fixed now

2023-07-06 05:46 UTC, PratyushJayachandran commented on icons/inertia.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Inertia</title><path d="M0 5.332 6.668 12 0 18.668h6.902L13.57 12 6.902 5.332Zm10.43 0L17.098 12l-6.668 6.668h6.9L24 12l-
```suggestion
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Inertia</title><path d="M6.901 5.331H0L6.669 12 0 18.669h6.901L13.571 12 6.9 5.331zm10.43 0H10.43L17.099 12l-6.67 6.669h6.902L24 12l-6.669-6.669z"/></svg>
```

2023-07-18 17:50 UTC, adamrusted approved these changes
LGTM! Icon matches, and we've got the go-ahead to use this brand colour for now! Thanks folks!

2023-07-18 17:52 UTC, adamrusted commented
Darn co-linear segments. Hopefully @PratyushJayachandran has got it passing the linter with their improvements!

2023-07-18 17:53 UTC, merged