Adding new nextra icon
simple-icons/simple-icons pull request #8557
Opened 2023-04-23 08:34 UTC by officialrajdeepsingh

**Issue:** closes #

**Similarweb rank:** 1,093,997

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Nextra has 6.6k stars on the github repo and also fixed the icon color issue as well.

2023-04-24 16:44 UTC, LitoMore commented
<img width="492" alt="CleanShot 2023-04-25 at 00 41 26@2x" src="https://user-images.githubusercontent.com/8186898/234061765-2778e84d-1800-4d37-9187-399eb9a22020.png">


Hi @officialrajdeepsingh, I see some differences.

It looks like you deleted the stroke from the source resource. We should keep it and convert it to outline, then combine it into one path.

The expected visual should be like the bottom one.

2023-05-01 18:15 UTC, officialrajdeepsingh commented
Hii @LitoMore 
I found lots of errors related to width and size. I try to fix it using Figma, [Svg viewer](https://www.svgviewer.dev/), [Svg edit](https://aydos.com/svgedit/) and [svg path editor](https://yqnn.github.io/svg-path-editor/), etc. No one tools help me, i try many tools to fix my issue. Please help to recommend some tool which i used to fix dimension related error in my svg.

> x icons/nextra.svg
  x icon-size Size of <path> must be exactly 24 in one dimension; the size is currently 22.999 x 23
  x collinear-segments Collinear segment "-0.006 0.006" found in the chain "l-0.989 0.988 -0.006..." at index 482 (should be removed)
  x extraneous Unexpected newline character(s) detected in SVG markup
  x icon-centered <path> must be centered at (12, 12); the center is currently (11.996, 12.004)

2023-05-01 18:17 UTC, officialrajdeepsingh commented
Hii @LitoMore 
I found lots of errors related to width and size. I try to fix it using Figma, [Svg viewer](https://www.svgviewer.dev/), [Svg edit](https://aydos.com/svgedit/) and [svg path editor](https://yqnn.github.io/svg-path-editor/), etc. No one tools help me, i try many tools to fix my issue. Please help to recommend some tool which i used to fix dimension related error in my svg.

> x icons/nextra.svg
  x icon-size Size of <path> must be exactly 24 in one dimension; the size is currently 22.999 x 23
  x collinear-segments Collinear segment "-0.006 0.006" found in the chain "l-0.989 0.988 -0.006..." at index 482 (should be removed)
  x extraneous Unexpected newline character(s) detected in SVG markup
  x icon-centered <path> must be centered at (12, 12); the center is currently (11.996, 12.004)

2023-05-07 08:58 UTC, LitoMore commented
@officialrajdeepsingh Please follow this section and check your icon:

https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#4-annotate-the-icon

2023-07-07 08:48 UTC, PratyushJayachandran requested changes

2023-07-07 08:48 UTC, PratyushJayachandran commented on icons/nextra.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Nextra</title><path d="m22.226.29-.989.988c-5.089 5.09-13.342 5.09-18.43 0L1.816.29A1.05 1.05 0 0 0 .335 1.774l.988.988c5
```suggestion
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Nextra</title><path d="M23.677 22.111A1.109 1.109 0 0 1 22.894 24a1.1 1.1 0 0 1-.782-.324l-.983-.984A12.823 12.823 0 0 0 12 18.912a12.82 12.82 0 0 0-9.128 3.78l-.983.984a1.13 1.13 0 0 1-1.565 0 1.108 1.108 0 0 1 0-1.565l.983-.983c5.034-5.034 5.034-13.224 0-18.257l-.983-.983A1.099 1.099 0 0 1 0 1.106 1.107 1.107 0 0 1 1.888.324l.984.982c5.034 5.035 13.224 5.034 18.257 0l.983-.983a1.108 1.108 0 0 1 1.565 0 1.108 1.108 0 0 1 0 1.565l-.984.983c-5.033 5.033-5.033 13.223 0 18.257l.984.983z"/></svg>
```

This should fix the issues.

2023-07-07 08:50 UTC, PratyushJayachandran commented on icons/nextra.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Nextra</title><path d="m22.226.29-.989.988c-5.089 5.09-13.342 5.09-18.43 0L1.816.29A1.05 1.05 0 0 0 .335 1.774l.988.988c5
![Untitled](https://github.com/simple-icons/simple-icons/assets/35000807/a150178d-0d9f-4b0c-9178-388fd13b81e4)
With fixed logo^

2023-07-07 10:01 UTC, PratyushJayachandran requested changes
Remove unnecessary slash

2023-07-07 10:01 UTC, PratyushJayachandran commented on _data/simple-icons.json
> +            "source": "https://nextra.site/",
```suggestion
            "source": "https://nextra.site",
```

Remove redundant trailing slash

2023-07-11 07:56 UTC, PratyushJayachandran commented on icons/nextra.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Nextra</title><path d="M23.677 22.111A1.109 1.109 0 0 1 22.894 24a1.1 1.1 0 0 1-.782-.324l-.983-.984A12.823 12.823 0 0 0
```suggestion
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Nextra</title><path d="M22.604 20.422c-2.25-2.25-3.488-5.24-3.488-8.422s1.239-6.172 3.488-8.422l.945-.944a1.545 1.545 0 0 0 0-2.182 1.545 1.545 0 0 0-2.183 0l-.944.944c-4.644 4.644-12.2 4.644-16.843 0L2.635.452A1.533 1.533 0 0 0 1.543 0c-.412 0-.8.16-1.09.452A1.533 1.533 0 0 0 0 1.543c0 .412.16.8.452 1.091l.944.944c2.25 2.25 3.489 5.24 3.489 8.422s-1.24 6.172-3.489 8.422l-.944.944A1.534 1.534 0 0 0 0 22.456c0 .413.16.8.452 1.092.292.292.68.452 1.091.452.413 0 .8-.16 1.092-.452l.944-.944c4.644-4.643 12.2-4.643 16.843 0l.944.944c.602.602 1.58.601 2.183 0a1.545 1.545 0 0 0 0-2.182l-.945-.944z"/></svg>
```

I had to redo the SVG from source. But it should be fixed now.

2023-07-18 19:50 UTC, adamrusted requested changes
I'm still seeing [some differences](https://github.com/simple-icons/simple-icons/assets/1830867/658b3fae-0cef-42b7-838c-cb0db19e9688) when comparing the PR (in black) to the source icon (in red). Any chance you can have another look @officialrajdeepsingh?

2023-07-19 05:45 UTC, PratyushJayachandran requested changes

2023-07-19 05:45 UTC, PratyushJayachandran commented on icons/nextra.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Nextra</title><path d="M22.604 20.422c-2.25-2.25-3.488-5.24-3.488-8.422s1.239-6.172 3.488-8.422l.945-.944a1.545 1.545 0 0
```suggestion
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Nextra</title><path d="M22.68 21.031c-4.98-4.98-4.98-13.083 0-18.063l.978-.978c.22-.22.342-.513.342-.825 0-.311-.122-.604-.342-.824-.44-.441-1.207-.44-1.648 0l-.979.978c-4.98 4.98-13.084 4.98-18.063 0L1.99.34a1.17 1.17 0 0 0-1.649 0 1.168 1.168 0 0 0 0 1.649l.978.978c4.98 4.98 4.98 13.083 0 18.063l-.977.978c-.221.22-.342.513-.342.825 0 .31.121.604.341.824.442.443 1.21.441 1.65 0l.977-.977c4.98-4.983 13.083-4.98 18.064 0l.978.977c.22.22.513.342.824.342.312 0 .605-.122.824-.342.22-.22.342-.512.342-.824 0-.313-.122-.605-.342-.825l-.977-.978z"/></svg>
```

I outlined the stroke first before scaling it to 24px. Please merge this. I will explain the issue in a separate comment.
![nextra](https://github.com/simple-icons/simple-icons/assets/35000807/b6674c8d-f2e9-43b2-99f5-f7bc54c0f657)

2023-07-19 05:53 UTC, PratyushJayachandran commented
> I'm still seeing [some differences](https://github.com/simple-icons/simple-icons/assets/1830867/658b3fae-0cef-42b7-838c-cb0db19e9688) when comparing the PR (in black) to the source icon (in red). Any chance you can have another look @officialrajdeepsingh?

The issue is happening because the original icon has a stroke around it. It needs to be outlined and then combined together before scaling it up to 24px. I might have outlined it after scaling, making it go out of proportion with original. Please make sure to do the same when comparing with source.

CC: @LitoMore

2023-07-19 08:16 UTC, LitoMore approved these changes
<img width="342" alt="image" src="https://github.com/simple-icons/simple-icons/assets/8186898/6787f879-78a0-478f-8c49-a5fb8484188e">

Looks good. Thanks.

2023-07-19 08:16 UTC, merged