Update README.md
simple-icons/simple-icons pull request #8641
Opened 2023-05-15 07:22 UTC by Nivin389

### Checklist
  - [X] I Created A Toc In readme
  - [X] I  Created A Contributors Image and Hooked it on Readme.md

### Description
Updated Readme.md and Added Contribution Heading on the readme

2023-05-17 23:09 UTC, RyanLua requested changes
I've reviewed your changes and spotted some minor mistakes and suggestions.

- Lines 24 and 26 have spaces after the word "Usage".
- Line 31 is an extra line and should be deleted.
- Line 29 and 197 shouldn't have emojis to be consistent with the rest of the Readme.

These are just my suggestions; you don't have to follow all of them through.

2023-05-17 23:12 UTC, RyanLua requested changes

2023-05-17 23:12 UTC, RyanLua commented on README.md
> +  - [Node Usage ](#node-usage-)
Remove extra space.
```suggestion
  - [Node Usage](#node-usage-)
```

2023-05-17 23:12 UTC, RyanLua commented on README.md
> +  - [PHP Usage ](#php-usage-)
Remove extra space.
```suggestion
  - [PHP Usage](#php-usage-)
```

2023-05-17 23:12 UTC, RyanLua commented on README.md
> +- [Contributors 💕](#contributors-)
Remove emoji for consistency.
```suggestion
- [Contributors](#contributors-)
```

2023-05-17 23:12 UTC, RyanLua commented on README.md
> +
```suggestion
```

2023-05-17 23:12 UTC, RyanLua commented on README.md
> +## Contributors 💕
Remove emoji for consistency.
```suggestion
## Contributors
```

2023-05-19 05:57 UTC, LitoMore commented
Sorry, we don't want this. GitHub already has a ToC feature. See https://github.blog/changelog/2021-04-13-table-of-contents-support-in-markdown-files/.

On the other hand, those anchors you are trying to add won't work correctly on the description of https://npmjs.com/simple-icons.

2023-05-19 06:01 UTC, ilynivin commented
Ok . So I am closing this pull request

2023-05-19 06:01 UTC, closed without merging