Add Amazon SES Logo
simple-icons/simple-icons pull request #8731
Opened 2023-06-05 16:02 UTC by RiteshK-611

**Issue:** closes #8660 

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
This commit will resolve issue #8660 by adding Amazon SES (Simple Email Service) logo in amazonses.svg file and by updating simple-icons.json file

### Preview
![amazonses](https://github.com/simple-icons/simple-icons/assets/61982298/153ca6ea-4d23-4c9a-8fa5-cd8f1f45c5a6)

2023-07-18 18:23 UTC, adamrusted requested changes
Couple changes to be made to these please @RiteshK-611!

2023-07-18 18:23 UTC, adamrusted commented on icons/amazonses.svg
Spotting [some differences](https://github.com/simple-icons/simple-icons/assets/1830867/f9e3ce28-adaa-4c7d-bc30-0b48a82d828d) between your PR in black, and the official icon in red. Could you take a look at this please @RiteshK-611?

2023-07-18 18:23 UTC, adamrusted commented on _data/simple-icons.json
> +                ]
I'm not sure we need all/any of these aliases. Perhaps have AWS SES as the abbreviation, and Amazon Simple Email Service as the full title?

2023-07-23 11:35 UTC, adamrusted commented on _data/simple-icons.json
> +            }
```suggestion
            "title": "AWS SES",
            "hex": "DD344C",
            "source": "https://aws.amazon.com/architecture/icons/",
            "guidelines": "https://aws.amazon.com/architecture/icons/",
            "aliases": {
                "aka": [
                    "Amazon Simple Email Service"
                ]
            }
```

2023-07-23 11:41 UTC, adamrusted commented on icons/amazonses.svg
It looks like you're using a precision of 2 decimals here, and that's resulting in [minor differences](https://github.com/simple-icons/simple-icons/assets/1830867/cea4bb2a-5753-4026-b544-482133f58802) between the source and your final SVG. Could you try with 3 or 4 decimals of precision with SVGO?

2023-07-23 16:46 UTC, RiteshK-611 commented on icons/amazonses.svg
Done!

2023-07-23 17:05 UTC, adamrusted requested changes

2023-07-23 17:05 UTC, adamrusted commented on icons/amazonsimpleemailservice.svg
Your PR seems to be in 2 decimals of precision, leading to some [minor differences](https://github.com/simple-icons/simple-icons/assets/1830867/5e7642dd-a70a-4c52-b7ed-c073a82de506) like this. Please regenerate the icon from source using a precision of 3 decimals - that should fix this.

2023-07-23 19:19 UTC, RiteshK-611 commented on icons/amazonsimpleemailservice.svg
Check!

2023-07-23 19:25 UTC, adamrusted commented on icons/amazonsimpleemailservice.svg
Okay... 4 might be necessary...
![image](https://github.com/simple-icons/simple-icons/assets/1830867/e95bf9f4-45d7-4ca0-bf0f-97c311afc68f)

2023-07-23 20:19 UTC, adamrusted commented on icons/amazonsimpleemailservice.svg
Which version of the icon are you using @RiteshK-611? I'm comparing all of these against the 64*64 SVG icons - and the differences may just be down to the size of the source icon!

2023-07-25 16:33 UTC, adamrusted reviewed
I'm still seeing [some differences](https://github.com/simple-icons/simple-icons/assets/1830867/0ce482da-8e41-463c-bab6-454da843b31d) but at this point I can't tell if it's me! @LitoMore - could you lend a second pair of eyes on this one?

2023-09-11 07:13 UTC, PratyushJayachandran requested changes

2023-09-11 07:13 UTC, PratyushJayachandran commented on icons/amazonsimpleemailservice.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Amazon Simple Email Service</title><path d="M20.1429 21c0 1.1571-.9858 2.1429-2.1429 2.1429S15.8571 22.157 15.8571 21c0-1
```suggestion
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Amazon Simple Email Service</title><path d="M11.9996 0C5.3833 0 0 5.3834 0 11.9998c0 2.5316.7813 4.9544 2.2599 7.0051l.6955-.5014C1.5827 16.5993.8571 14.3505.8571 11.9998.8571 5.856 5.856.8572 12.0004.8572c6.144 0 11.1425 4.999 11.1425 11.1426 0 2.3508-.7256 4.5995-2.0983 6.5037l.6955.5014C23.2187 16.9542 24 14.5314 24 11.9998 24 5.3834 18.6163 0 11.9996 0z"/><path d="M6 16.7142a.4285.4285 0 0 0-.4286.4285v1.7598c-.9643.2048-1.7143 1.0822-1.7143 2.0974 0 1.1615.9815 2.143 2.1429 2.143s2.1429-.9815 2.1429-2.143c0-1.0152-.75-1.8926-1.7143-2.0974v-1.3312h5.1428v2.1883c-.9643.2049-1.7143 1.0822-1.7143 2.0975C9.8571 23.0186 10.8386 24 12 24s2.1429-.9814 2.1429-2.1429c0-1.0153-.75-1.8926-1.7143-2.0975v-2.1883h5.1428v1.3312c-.9643.2048-1.7143 1.0822-1.7143 2.0974 0 1.1615.9815 2.143 2.1429 2.143s2.1429-.9815 2.1429-2.143c0-1.0152-.75-1.8926-1.7143-2.0974v-1.7598A.4285.4285 0 0 0 18 16.7142h-5.5714v-2.5715H18c.237 0 .4286-.192.4286-.4286V5.9997A.4285.4285 0 0 0 18 5.571H6a.4285.4285 0 0 0-.4286.4286v7.7144c0 .2366.1916.4286.4286.4286h5.5714v2.5715H6zm1.2857 4.2857c0 .697-.5889 1.2858-1.2857 1.2858s-1.2857-.5889-1.2857-1.2858c0-.6968.5889-1.2857 1.2857-1.2857S7.2857 20.3031 7.2857 21zm12 0c0 .697-.5889 1.2858-1.2857 1.2858s-1.2857-.5889-1.2857-1.2858c0-.6968.5889-1.2857 1.2857-1.2857s1.2857.5889 1.2857 1.2857zm-1.7143-8.248L14.259 9.7703l3.3124-2.8389v5.8205zm-.7298-6.3236-4.842 4.1499-4.8412-4.15h9.6832zm-10.413.5031L9.741 9.7707 6.4286 12.752V6.9314zm.6878 6.3541 3.2807-2.9525 1.3239 1.135a.4253.4253 0 0 0 .2786.1032.4253.4253 0 0 0 .2785-.1033l1.3243-1.1349 3.2812 2.9525H7.1164zM12 20.5714c.6968 0 1.2857.5888 1.2857 1.2857 0 .6969-.5889 1.2857-1.2857 1.2857s-1.2857-.5888-1.2857-1.2857c0-.6969.5889-1.2857 1.2857-1.2857z"/></svg>
```
I am also seeing [differences in image](https://github.com/simple-icons/simple-icons/assets/35000807/8a8a3f7e-6d96-47c0-a372-819ea5eb34f2)


This should fix it.

2023-09-13 06:56 UTC, PratyushJayachandran approved these changes

2023-09-13 06:56 UTC, PratyushJayachandran commented on icons/amazonsimpleemailservice.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Amazon Simple Email Service</title><path d="M11.9996 0C5.3833 0 0 5.3834 0 11.9998c0 2.5316.7813 4.9544 2.2599 7.0051l.69
```suggestion
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Amazon Simple Email Service</title><path d="M11.9996 0C5.3833 0 0 5.3834 0 11.9998c0 2.5316.7813 4.9544 2.2599 7.0051l.6955-.5014C1.5827 16.5993.8571 14.3505.8571 11.9998.8571 5.856 5.856.8572 12.0004.8572c6.144 0 11.1425 4.999 11.1425 11.1426 0 2.3508-.7256 4.5995-2.0983 6.5037l.6955.5014C23.2187 16.9542 24 14.5314 24 11.9998 24 5.3834 18.6163 0 11.9996 0zM6 16.7142a.4285.4285 0 0 0-.4286.4285v1.7598c-.9643.2048-1.7143 1.0822-1.7143 2.0974 0 1.1615.9815 2.143 2.1429 2.143s2.1429-.9815 2.1429-2.143c0-1.0152-.75-1.8926-1.7143-2.0974v-1.3312h5.1428v2.1883c-.9643.2049-1.7143 1.0822-1.7143 2.0975C9.8571 23.0186 10.8386 24 12 24s2.1429-.9814 2.1429-2.1429c0-1.0153-.75-1.8926-1.7143-2.0975v-2.1883h5.1428v1.3312c-.9643.2048-1.7143 1.0822-1.7143 2.0974 0 1.1615.9815 2.143 2.1429 2.143s2.1429-.9815 2.1429-2.143c0-1.0152-.75-1.8926-1.7143-2.0974v-1.7598A.4285.4285 0 0 0 18 16.7142h-5.5714v-2.5715H18c.237 0 .4286-.192.4286-.4286V5.9997A.4285.4285 0 0 0 18 5.571H6a.4285.4285 0 0 0-.4286.4286v7.7144c0 .2366.1916.4286.4286.4286h5.5714v2.5715H6zm1.2857 4.2857c0 .697-.5889 1.2858-1.2857 1.2858s-1.2857-.5889-1.2857-1.2858c0-.6968.5889-1.2857 1.2857-1.2857S7.2857 20.3031 7.2857 21zm12 0c0 .697-.5889 1.2858-1.2857 1.2858s-1.2857-.5889-1.2857-1.2858c0-.6968.5889-1.2857 1.2857-1.2857s1.2857.5889 1.2857 1.2857zm-1.7143-8.248L14.259 9.7703l3.3124-2.8389v5.8205zm-.7298-6.3236-4.842 4.1499-4.8412-4.15h9.6832zm-10.413.5031L9.741 9.7707 6.4286 12.752V6.9314zm.6878 6.3541 3.2807-2.9525 1.3239 1.135a.4253.4253 0 0 0 .2786.1032.4253.4253 0 0 0 .2785-.1033l1.3243-1.1349 3.2812 2.9525H7.1164zM12 20.5714c.6968 0 1.2857.5888 1.2857 1.2857 0 .6969-.5889 1.2857-1.2857 1.2857s-1.2857-.5888-1.2857-1.2857c0-.6969.5889-1.2857 1.2857-1.2857z"/></svg>
```
The linter error should be fixed now

2023-09-13 07:05 UTC, merged