Add Amazon DocumentDB Icon
simple-icons/simple-icons pull request #8732
Opened 2023-06-05 17:58 UTC by RiteshK-611

**Issue:** closes #7726

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
This commit will resolve issue #7726 by adding Amazon DocumentDB Logo in amazondocumentdb.svg and by updating simple-icons.json file

### Preview
![amazondocumentdb](https://github.com/simple-icons/simple-icons/assets/61982298/a22b36a2-454c-45d3-811d-b45ce2fe79a9)

2023-07-18 18:24 UTC, adamrusted requested changes
I'm seeing [quite a difference](https://github.com/simple-icons/simple-icons/assets/1830867/69f98d8e-0c1c-4e96-ae5b-a6442eb401c5) between your PR in black, and the source icon in red. Could you take another look please @RiteshK-611?

2023-07-23 11:43 UTC, adamrusted requested changes

2023-07-23 11:43 UTC, adamrusted commented on _data/simple-icons.json
> +            "guidelines": "https://aws.amazon.com/architecture/icons/",
```suggestion
            "source": "https://aws.amazon.com/architecture/icons",
            "guidelines": "https://aws.amazon.com/architecture/icons",
```

2023-07-23 11:43 UTC, adamrusted commented on icons/amazondocumentdb.svg
I'm seeing some [minor differences](https://github.com/simple-icons/simple-icons/assets/1830867/dbfacbdc-217b-4307-8512-9975dc6572ad) in the more complex shapes. Could you re-export with a precision of 4 decimals please? 🙏

2023-07-23 16:55 UTC, RiteshK-611 commented on icons/amazondocumentdb.svg
Done!

2023-07-23 17:08 UTC, adamrusted requested changes

2023-07-23 17:08 UTC, adamrusted commented on icons/amazondocumentdb.svg
Icon still appears to be in 3 decimals of precision, and I'm still seeing [some differences](https://github.com/simple-icons/simple-icons/assets/1830867/bd7906f5-4929-4b77-a12a-9832f38d3824). Could you please regenerate from source (I'm using the 64*64 icons when comparing) with 4 decimals of precision? 🙏

2023-07-24 17:16 UTC, adamrusted requested changes
Seems you've overridden DynamoDB...

2023-07-24 19:18 UTC, RiteshK-611 commented
> Seems you've overridden DynamoDB...

oh.. yes... I fixed it
Thanks @adamrusted for being supportive

2023-09-03 19:46 UTC, adamrusted approved these changes
Happy with this, thanks @RiteshK-611 🎉

2023-09-03 19:50 UTC, merged