Add nxp semiconductors icon #8747
simple-icons/simple-icons pull request #8748
Opened 2023-06-07 08:46 UTC by PratyushJayachandran

![nxpsemiconductors](https://github.com/simple-icons/simple-icons/assets/35000807/c13ae7f9-7fde-4f94-8f65-8373200e6eaa)

**Issue:** closes #8747 

**Similarweb rank:** 33,570. See https://www.similarweb.com/website/nxp.com/

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Hex Value picked from logo based on the most dominant color: F9B500
Brand mentions not to use company colors on solid logo. Mentions to only use black or white.

Logo extracted from PDF found on brand website that specifically mentions a different logo for monochromatic use: https://www.nxp.com/docs/en/supporting-information/NXPLOGOGD.pdf

```
PS X:\~~~> npm test    

 22284 passing (1s)

PS X:\~~~> npm run lint
--------------------- Summary ---------------------
✓ 2472 valid files.
```

2023-06-21 15:05 UTC, LitoMore commented
![image](https://github.com/simple-icons/simple-icons/assets/8186898/5946a57c-a019-4ca9-838e-6b34839a35bf)

Please follow their [logo use guideline](https://www.nxp.com/docs/en/supporting-information/NXPLOGOGD.pdf).

2023-06-21 15:20 UTC, PratyushJayachandran commented
I had this doubt beforehand.
So should the logo be black or white?

2023-06-21 15:26 UTC, LitoMore commented
Black.

2023-06-22 07:18 UTC, PratyushJayachandran commented
> Black.

I have changed the color to black and updated PR details to match.

2023-06-22 07:59 UTC, LitoMore requested changes

2023-06-22 08:34 UTC, PratyushJayachandran commented on _data/simple-icons.json
> +            },
Fixed and pushed commit.

2023-06-22 09:11 UTC, LitoMore requested changes

2023-06-22 09:11 UTC, LitoMore commented on _data/simple-icons.json
> +            "title": "NXP Semiconductors",
```suggestion
            "title": "NXP",
```

2023-06-22 13:27 UTC, LitoMore approved these changes

2023-06-22 13:27 UTC, merged