Add Akkoma icon
simple-icons/simple-icons pull request #8752
Opened 2023-06-08 05:27 UTC by Sevichecc

[Akkoma](https://akkoma.social/) is a new fediverse social software based on Pleroma. An increasing number of instance are using Akkoma. Here is some data on Akkoma: [Fediverse Observer](https://akkoma.fediverse.observer/stats). Currently it has 10,526 active montly users.

<img width="724" alt="image" src="https://github.com/simple-icons/simple-icons/assets/91365763/270a34cf-cd52-45ae-bfbc-abc187386470">

**Similarweb rank:** 8,945,151
### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Since Akkoma has not provided official branding materials, I picked the hex color from their favicon: https://akkoma.dev/AkkomaGang/akkoma/src/branch/develop/docs/docs/images/favicon.png

2023-07-16 16:02 UTC, adamrusted requested changes
Slight nit-pick on the source URL. It would also appear that neither website currently meets our inclusion criteria. Have we included other fediverse instances with similar performance?

2023-07-16 16:02 UTC, adamrusted commented on _data/simple-icons.json
> +            "source": "https://akkoma.dev/assets/img/logo.svg"
```suggestion
            "source": "https://akkoma.dev"
```

We can shorten this down to just the homepage, given the SVG is embedded there.

2023-08-08 17:29 UTC, service-paradis commented
I'm not sure it meets our popularity requirements. Do you have more information that we can use?

2023-08-14 20:37 UTC, service-paradis commented
Closing since it is out of scope.

2023-08-14 20:37 UTC, closed without merging