Add JetBrains Space Icon
simple-icons/simple-icons pull request #8799
Opened 2023-06-13 18:01 UTC by RiteshK-611

**Issue:** closes #8795

**Similarweb rank:**
  
The similarweb rank is 4,941. See https://www.similarweb.com/website/jetbrains.com/

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
This change resolves issue #8795 by adding JetBrains Space logo in jetbrainsspace.svg file and by updating simple-icons.json file with icon's info

### Preview
![jetbrainsspace](https://github.com/simple-icons/simple-icons/assets/61982298/9109846b-6034-4f43-8cf3-c2219505b5e6)

2023-06-14 05:35 UTC, PratyushJayachandran commented
Did you pick this SVG from their website?
Just asking because I see a different one on their website. An invert of what you added.

2023-06-14 16:29 UTC, LitoMore commented
Could you two @RiteshK-611 @PratyushJayachandran point out where did you find your icons? I can't find the flat version of icon on their website. Thanks.

2023-06-14 16:40 UTC, PratyushJayachandran commented
> Could you two @RiteshK-611 @PratyushJayachandran point out where did you find your icons? I can't find the flat version of icon on their website. Thanks.

https://www.jetbrains.com/fleet/
Keep scrolling down and you will see them mentioning space. They also have a branding page with all icons in color as svg and png: https://www.jetbrains.com/company/brand/#logos-and-icons

2023-06-14 16:51 UTC, LitoMore commented
We should always pick resource from their [Brand Assets](https://www.jetbrains.com/company/brand/) page. Or asking them for an approval to use the informal flat icon.

<img width="416" alt="image" src="https://github.com/simple-icons/simple-icons/assets/8186898/510fe1da-bb77-4d0e-89de-a311b5158a8f">

2023-06-14 17:06 UTC, PratyushJayachandran commented
> We should always pick resource from their [Brand Assets](https://www.jetbrains.com/company/brand/) page. Or asking them for an approval to use the informal flat icon.

I see this problem with almost all brands. They always say don't alter colors and it makes sense too. But at really small sizes like the badge, we would like it to be flat.

Is providing logos in original design something that is planned for future?

2023-06-14 17:25 UTC, LitoMore commented
> Is providing logos in original design something that is planned for future?

I don't think so.

We can suggest JetBrains team make a new flat icon for badges.

2023-06-14 18:10 UTC, RiteshK-611 commented
> Did you pick this SVG from their website? Just asking because I see a different one on their website. An invert of what you added. ![image](https://user-images.githubusercontent.com/35000807/245686067-99aa5ceb-2c47-4316-b60e-a88d7a206aea.png)

Actually I alter the original SVG to make it flat, but now I updated it with the above one which looks better
Thanks @PratyushJayachandran for this

2023-06-14 19:55 UTC, PratyushJayachandran commented
> We can suggest JetBrains team make a new flat icon for badges.
They might actually agree too but for other companies who don't know what this project is for and how it is used, do we have some template that we can use to ask the brands? 

From what I see saying yes to an exception means exception for everyone else too. Like some companies explicitly mention how to use logo when you want it flat. Some companies say that you may use it freely for editorial work and things like that. If someone can chime in and tell what is the language one should use, that would be great. We can include it in our contribution guides.

2023-07-18 20:26 UTC, adamrusted commented
We have set a precedent with other JetBrains products to use the full icon (minus the background squiggles) as our icon. We should probably continue that here.

2023-12-01 16:03 UTC, adamrusted commented
In an interesting turn of events - JetBrains have kept the Space logo previously contributed!

![image](https://github.com/simple-icons/simple-icons/assets/1830867/76f9a9b3-06ee-4cb5-ade2-4f19d30fade8)

I'll review this one shortly.

2023-12-01 16:08 UTC, adamrusted requested changes
Spotting a slight difference between your icon and my re-rendered version with a 1px gap between each section. Could you have another look please @RiteshK-611?

2023-12-01 16:08 UTC, adamrusted commented on icons/jetbrainsspace.svg
![image](https://github.com/simple-icons/simple-icons/assets/1830867/0857e001-fc4e-4c07-9588-50984ea1b42e)

2024-01-11 12:33 UTC, PeterShaggyNoble commented
Closing due to inactivity. If you would like to continue working on this, @RiteshK-611 then we can reopen it for you. If someone else would like to take it on then please open a new PR.

2024-01-11 12:33 UTC, closed without merging