Add tradingview icon
simple-icons/simple-icons pull request #8809
Opened 2023-06-15 21:08 UTC by bneeland

**Issue:** closes #8805

**Similarweb rank:**
284
https://www.similarweb.com/website/tradingview.com/#overview

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Adds TradingView icon.

2023-06-20 01:28 UTC, LitoMore requested changes
<img width="590" alt="image" src="https://github.com/simple-icons/simple-icons/assets/8186898/aa3f3341-9966-4e27-9ecf-cb5c54d1402c">

@bneeland I used https://tradingview.com/static/images/svg/tradingview-with-text-logo.svg as reference but found some differences.

Please make sure you're using the correct resource as reference.

2023-06-20 06:38 UTC, PratyushJayachandran requested changes
Fixed the SVG by taking it directly from the brand website

2023-06-20 06:38 UTC, PratyushJayachandran commented on icons/tradingview.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>TradingView</title><path d="M9.465 18.193H4.732v-7.57H0V5.808h9.465v12.386Zm9.465 0h-5.41l5.07-12.386H24l-5.07 12.386Zm-5
```suggestion
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>TradingView</title><path d="M9 6H0v4.5h4.5V18H9V6zm10.5 12h-6L18 6h6l-4.5 12zm-6.75-7.5c1.2426 0 2.25-1.0074 2.25-2.25S13.9926 6 12.75 6 10.5 7.0074 10.5 8.25s1.0074 2.25 2.25 2.25z"/></svg>
```
Took SVG from their website header and resized it to project specifications.

2023-06-29 22:45 UTC, LitoMore submitted a review, later dismissed
I use this one below as a reference:

```svg
<svg width="36" height="28" viewBox="0 0 36 28" xmlns="http://www.w3.org/2000/svg">
	<path d="M14 22H7V11H0V4h14v18zM28 22h-8l7.5-18h8L28 22z" fill="currentColor"/>
	<circle cx="20" cy="8" r="4" fill="currentColor"/>
</svg>
```

But still found some differences:

<img width="631" alt="image" src="https://github.com/simple-icons/simple-icons/assets/8186898/51ba4759-5131-420f-aa26-7e85774dc345">

2023-07-01 03:00 UTC, PratyushJayachandran submitted a review, later dismissed
Please merge my suggestion.

2023-07-01 03:00 UTC, PratyushJayachandran commented on icons/tradingview.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>TradingView</title><path d="M9 6H0v4.5h4.5V18H9V6zm10.5 12h-6L18 6h6l-4.5 12zm-6.75-7.5c1.2426 0 2.25-1.0074 2.25-2.25S13
```suggestion
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>TradingView</title><path d="M9.465 18.085H4.732v-7.437H0V5.915h9.465v12.17zm9.465 0h-5.41l5.07-12.17H24l-5.07 12.17zm-5.41-12.17a2.704 2.704 0 1 1 0 5.409 2.704 2.704 0 0 1 0-5.409z"/></svg>
```
This should fix the differences. Perplexed as to why the previous suggestion didn't work

2023-07-18 19:37 UTC, adamrusted requested changes
Even with @PratyushJayachandran's changes - I'm seeing [major differences](https://github.com/simple-icons/simple-icons/assets/1830867/f7bcf3b2-e905-4b19-88b2-52182219bacd) when compared to the SVG linked by @LitoMore. This'll still need some work I'm afraid!

2023-11-20 15:32 UTC, PeterShaggyNoble submitted a review, later dismissed

2023-11-20 15:32 UTC, PeterShaggyNoble commented on _data/simple-icons.json
> +            "source": "https://tradingview.com"
```suggestion
            "source": "https://www.tradingview.com/media-kit"
```

2023-11-20 15:32 UTC, PeterShaggyNoble commented on icons/tradingview.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>TradingView</title><path d="M9.465 18.085H4.732v-7.437H0V5.915h9.465v12.17zm9.465 0h-5.41l5.07-12.17H24l-5.07 12.17zm-5.4
```suggestion
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>TradingView</title><path d="M15.8654 8.2789c0 1.3541-1.0978 2.4519-2.452 2.4519-1.354 0-2.4519-1.0978-2.4519-2.452 0-1.354 1.0978-2.4518 2.452-2.4518 1.3541 0 2.4519 1.0977 2.4519 2.4519zM9.75 6H0v4.9038h4.8462v7.2692H9.75Zm8.5962 0H24l-5.1058 12.173h-5.6538z"/></svg>
```

2023-11-20 15:35 UTC, PeterShaggyNoble commented
In the interests of getting this merged in, I've taken another pass at this. This latest version is based on `TradingView.zip\TradingView-media-kit\logo\svg\black\icon-logo.svg` from the media kit available at https://www.tradingview.com/media-kit/ - from their own usage I think we're OK to leave the background off and just use the icon.

2023-11-21 11:52 UTC, adamrusted approved these changes

2023-11-21 11:57 UTC, merged