Add wells fargo icon
simple-icons/simple-icons pull request #8867
Opened 2023-06-24 19:52 UTC by PratyushJayachandran

![simpleicons](https://github.com/simple-icons/simple-icons/assets/35000807/6df45c2d-4a82-4642-9e75-ac14d711d252)

**Issue:** closes #8099 

**Similarweb rank:**
The similarweb rank is 183. See https://www.similarweb.com/website/wellsfargo.com

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
SVG: Taken from newsletter PDFs from their website https://www.wellsfargo.com/about/
Color: `#d71e28` Taken from website header.

2023-07-23 14:04 UTC, adamrusted commented
@PratyushJayachandran - could you link to a particular document that uses an SVG? All the ones I'm seeing are PNGs!

2023-09-03 08:10 UTC, adamrusted requested changes
I'm seeing [some differences](https://github.com/simple-icons/simple-icons/assets/1830867/8059d936-8934-483a-a9b8-58bd996a919f) when comparing to the SVG on the front page of that report. Could you re-generate this one please @PratyushJayachandran? 🙏

2023-09-06 06:47 UTC, PratyushJayachandran commented
> I'm seeing [some differences](https://github.com/simple-icons/simple-icons/assets/1830867/8059d936-8934-483a-a9b8-58bd996a919f) when comparing to the SVG on the front page of that report. Could you re-generate this one please @PratyushJayachandran? 🙏

Fixed

2023-11-15 11:40 UTC, adamrusted approved these changes

2023-11-15 11:45 UTC, merged