Add Boosty icon
simple-icons/simple-icons pull request #8897
Opened 2023-06-28 19:02 UTC by Gautam25Raj

![boosty](https://github.com/simple-icons/simple-icons/assets/63155224/770c2d24-886b-405e-90cd-6ad8dec79cea)

**Issue:** closes #8894

**Similarweb rank:**
The Similarweb rank is 4,523. See https://www.similarweb.com/website/boosty.to

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
SVG: Taken from boosty website which was provided as SVG https://boosty.to/app/brand?locale=en_US
Color: `#F15F2C` Mentioned in the boosty website.

2023-06-28 22:43 UTC, LitoMore requested changes

2023-06-28 22:43 UTC, LitoMore commented on _data/simple-icons.json
> +        },
```suggestion
        {
            "title": "Boosty",
            "hex": "F15F2C",
            "source": "https://boosty.to/app/brand",
            "guidelines": "https://boosty.to/app/brand"
        },
```

Those queries need to be removed.

2023-07-20 09:12 UTC, adamrusted requested changes
Thanks for the contribution @Gautam25Raj!
There's a couple tweaks to this that'll need making before we can accept it. I've removed the locale string on the URLs, and there appears to be a difference in the SVG source (red) and your PR (black). Probably just down to the precision of SVGO, would be worth trying a precision of 4 instead of 3!

2023-07-20 09:12 UTC, adamrusted commented on _data/simple-icons.json
> +            "guidelines": "https://boosty.to/app/brand?locale=en_US"
```suggestion
            "source": "https://boosty.to/app/brand",
            "guidelines": "https://boosty.to/app/brand"
```

2023-07-20 09:12 UTC, adamrusted commented on icons/boosty.svg
![image](https://github.com/simple-icons/simple-icons/assets/1830867/9e54a8af-a100-470b-a368-283253a742e7)

2023-11-22 12:23 UTC, PeterShaggyNoble commented on icons/boosty.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Boosty</title><path d="M2.638 14.336 6.788 0h6.377L11.88 4.444l-.039.077-3.386 11.733h3.157a1461.06 1461.06 0 0 0-3.093 7
```suggestion
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Boosty</title><path d="M2.661 14.337 6.801 0h6.362L11.88 4.444l-.038.077-3.378 11.733h3.15c-1.321 3.289-2.35 5.867-3.086 7.733-5.816-.063-7.442-4.228-6.02-9.155M8.554 24l7.67-11.035h-3.25l2.83-7.073c4.852.508 7.137 4.33 5.791 8.952C20.16 19.81 14.344 24 8.68 24h-.127z"/></svg>
```

2023-11-22 15:20 UTC, adamrusted approved these changes

2023-11-22 15:22 UTC, merged