Add Roadmap.sh Icon
simple-icons/simple-icons pull request #8921
Opened 2023-07-01 16:45 UTC by RiteshK-611

**Issue:** closes #8918

**Similarweb rank:**
Global Rank: 22,331
https://www.similarweb.com/website/roadmap.sh/

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
This commit resolves issue #8918 by adding Roadmap.sh logo in roadmapdotsh.svg file and by updating simple-icons.svg file with icon's data

### Preview
![roadmapdotsh](https://github.com/simple-icons/simple-icons/assets/61982298/0f6126dd-0fa6-487c-b233-02cf499aff3e)

2023-07-03 13:40 UTC, adamrusted commented
Thanks for the submission @RiteshK-611!
Looks like there's a usable SVG on their homepage, which would require the `r.` to be inside a rounded square. We would probably be better using that one, and updating the source to the same.

2023-07-04 22:10 UTC, PratyushJayachandran requested changes
Please update to logo from website header

2023-07-04 22:10 UTC, PratyushJayachandran commented on _data/simple-icons.json
> +            "source": "https://github.com/kamranahmedse/developer-roadmap/blob/0fa6ecd3cec96577c1fde203934033700d413eb9/src/icons/logo.svg"
```suggestion
            "source": "https://roadmap.sh"
```

2023-07-04 22:10 UTC, PratyushJayachandran commented on icons/roadmapdotsh.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Roadmap.sh</title><path d="M7.7666 22.9874c-.3047.0914-.792.1828-1.462.2741-.6396.0914-1.3097.137-2.0101.137-.6702 0-1.27
```suggestion
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Roadmap.sh</title><path d="M20.693 0H3.307A3.307 3.307 0 0 0 0 3.307v17.386A3.307 3.307 0 0 0 3.307 24h17.386A3.307 3.307 0 0 0 24 20.693V3.307A3.307 3.307 0 0 0 20.693 0zm-7.706 9.18c-.349.031-.689.078-1.021.142-.333.063-.65.134-.95.214a3.64 3.64 0 0 0-.736.237v8.097a5.522 5.522 0 0 1-.76.143c-.333.047-.68.07-1.045.07a5.87 5.87 0 0 1-.95-.07 1.588 1.588 0 0 1-.688-.285 1.476 1.476 0 0 1-.452-.57c-.095-.253-.142-.578-.142-.974V9.061c0-.364.063-.673.19-.926.142-.27.34-.507.594-.713a3.93 3.93 0 0 1 .926-.546 9.133 9.133 0 0 1 2.54-.736 8.093 8.093 0 0 1 1.378-.119c.76 0 1.361.15 1.804.451.444.285.665.76.665 1.425 0 .222-.032.443-.095.665a3.075 3.075 0 0 1-.237.57c-.341 0-.682.016-1.021.047zm5.113 8.453c-.412.443-.974.665-1.686.665s-1.274-.222-1.686-.665c-.412-.443-.617-.998-.617-1.662 0-.665.205-1.22.617-1.663.412-.443.974-.664 1.686-.664s1.274.221 1.686.664c.411.444.617.998.617 1.663 0 .664-.206 1.219-.617 1.662z"/></svg>
```

2023-07-04 22:10 UTC, PratyushJayachandran commented on icons/roadmapdotsh.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Roadmap.sh</title><path d="M7.7666 22.9874c-.3047.0914-.792.1828-1.462.2741-.6396.0914-1.3097.137-2.0101.137-.6702 0-1.27
Updated to logo from website header

2023-07-04 22:11 UTC, PratyushJayachandran commented on icons/roadmapdotsh.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Roadmap.sh</title><path d="M7.7666 22.9874c-.3047.0914-.792.1828-1.462.2741-.6396.0914-1.3097.137-2.0101.137-.6702 0-1.27
As mentioned in contributing guidelines, the precision could be set to 3 decimal points to be consistent with other SVGs in the project

2023-07-04 22:13 UTC, PratyushJayachandran commented on icons/roadmapdotsh.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Roadmap.sh</title><path d="M7.7666 22.9874c-.3047.0914-.792.1828-1.462.2741-.6396.0914-1.3097.137-2.0101.137-.6702 0-1.27
![roadmapdotsh](https://github.com/simple-icons/simple-icons/assets/35000807/ae831bce-4115-46c2-b010-2d9332011233)

2023-07-05 18:30 UTC, RiteshK-611 commented
Thanks @PratyushJayachandran 😊

2023-07-20 12:13 UTC, adamrusted approved these changes
LGTM! Thanks @RiteshK-611 and @PratyushJayachandran 🎉

2023-07-20 12:21 UTC, merged