Update Ubiquiti Icon
simple-icons/simple-icons pull request #8927
Opened 2023-07-03 18:00 UTC by RiteshK-611

**Issue:** closes #5667 

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
This change resolves issue #5667 by updating Ubiquiti logo in ubiquiti.svg file 

### Preview
![ubiquiti](https://github.com/simple-icons/simple-icons/assets/61982298/59581206-85ee-460a-be01-732fe9c78398)

2023-07-05 13:58 UTC, service-paradis requested changes
Thanks @RiteshK-611 for your contribution!

I'm seeing some differences that might be due to SVGO precision. Which logo did you use? I compared it using the one found in their Website homepage header.

Also, we'll need to update `source` in `simple-icons.json` since https://www.ui.com/marketing/#logos does not exists anymore.

2023-07-05 18:38 UTC, RiteshK-611 commented
Thanks @service-paradis for pointing out my mistake. I updated the source link 👍

2023-07-07 07:51 UTC, adamrusted commented on _data/simple-icons.json
> +            "source": "https://commons.wikimedia.org/wiki/File:Ubiquiti_Logo_2023.svg"
There is an [SVG](https://www.ui.com/microsite/static/media/logo.47175193.svg) available (albeit hidden as a `-webkit-mask` in the source code) on their homepage. IMHO that'd be a better source link than Wikimedia.

```suggestion
            "source": "https://www.ui.com"
```

2023-07-08 13:34 UTC, adamrusted requested changes

2023-07-08 13:34 UTC, adamrusted commented on icons/ubiquiti.svg
I'm seeing a little bit of a [difference](https://github.com/simple-icons/simple-icons/assets/1830867/2fbb86b2-f324-4a64-8423-7ed3dde3c69e) between the source file (red) and your icon (black). This could be down to the difference in source, so could you recreate using the SVG found in the homepage header? 🙏

2023-07-08 14:23 UTC, RiteshK-611 commented on icons/ubiquiti.svg
Can you share the link for the svg source file

2023-07-08 14:24 UTC, adamrusted commented on icons/ubiquiti.svg
https://www.ui.com/microsite/static/media/logo.47175193.svg

2023-07-08 14:27 UTC, RiteshK-611 commented on icons/ubiquiti.svg
Thanks @adamrusted 👍... I'll update ASAP!!

2023-07-10 16:02 UTC, service-paradis approved these changes
LGTM now, Thank you @RiteshK-611 💯

2023-07-10 16:05 UTC, merged