Update fujifilm
simple-icons/simple-icons pull request #8939
Opened 2023-07-04 21:40 UTC by PratyushJayachandran

![fujifilm](https://github.com/simple-icons/simple-icons/assets/35000807/dda3bdd3-1a8e-475d-879e-fcc3cb263d2f)

**Issue:** closes #

**Similarweb rank:**
  

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json`
  - [ ] I optimized the icon with SVGO or SVGOMG
  - [ ] The SVG `viewbox` is `0 0 24 24`

### Description
SVG: Taken from website header https://www.fujifilm.com/us/themes/custom/fujifilm_com_g2/common/img/fujifilm_corporate_logo.svg
Color: `#FB0020` Taken from the same SVG. Although it can also be green based on Fujifilm packaging since a long time. https://www.fujifilm.com/us/en/social-media/apps

2023-07-04 21:41 UTC, PratyushJayachandran commented
The icon is already in the project but I am not sure if we can add their logo after reading the terms
https://www.fujifilm.com/us/en/terms

2023-07-07 11:56 UTC, adamrusted requested changes
Icon itself looks perfect, just one nit-pick regarding the source. Otherwise, great job @PratyushJayachandran!

2023-07-07 11:56 UTC, adamrusted commented on _data/simple-icons.json
> +            "source": "https://www.fujifilm.com/us/themes/custom/fujifilm_com_g2/common/img/fujifilm_corporate_logo.svg",
```suggestion
            "source": "https://www.fujifilm.com",
```
I'd suggest we just link to the website, if it's available in the header - saves us getting a 404 if/when they change the filename! 🙃

2023-07-07 15:13 UTC, PratyushJayachandran commented
> Icon itself looks perfect, just one nit-pick regarding the source. Otherwise, great job @PratyushJayachandran!

I usually only add the website but I saw other icons with absolute address so I thought I'll do the same🙈

Will stick to just the website unless they have a branding page.

2023-07-09 08:56 UTC, adamrusted approved these changes
LGTM! Thanks @PratyushJayachandran 🎉

2023-07-09 08:56 UTC, merged