Add Threads icon
simple-icons/simple-icons pull request #8943
Opened 2023-07-06 01:14 UTC by Saeris

**Issue:** closes #8930

**Similarweb rank:**
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Threads is a new social media app by Instagram, made publicly available on July 5th, 2023. There appears to be no official brand guidelines page yet, so this SVG was pulled from the Wikipedia article for the app.

2023-07-07 11:20 UTC, adamrusted requested changes
Please see comments regarding this PR.
Important to note that the `threads.net` site, which is the main domain for the app is currently sitting at a SimilarWeb rank of [2,875,528](https://www.similarweb.com/website/threads.net/) which would put it [squarely out of scope](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon) of this project at the moment. How do other @simple-icons/maintainers feel about this one?

2023-07-07 11:20 UTC, adamrusted commented on _data/simple-icons.json
> +            "source": "https://en.wikipedia.org/wiki/Threads_(app)#/media/File:Threads_(app)_logo.svg"
```suggestion
            "source": "https://commons.wikimedia.org/wiki/File:Threads_(app)_logo.svg"
```

Please update the source to the Wikimedia Commons location 😄

2023-07-07 11:20 UTC, adamrusted commented on icons/threads.svg
Icon itself is a perfect match. If you can update the source as above, this'll be good to go.

2023-07-07 23:03 UTC, Saeris commented
Yeah it's a brand new app so I'm not surprised that it has a low ranking at the time I filed this PR.

According to reports from Meta employees, Threads is already at 70m+ users as if this morning, so I expect that rank will change quickly.

I filed this PR because I want to use this icon in my social link sharing site, and figured it would be worth sharing in case others wanted to add links to their own sites. Can imagine that fairly soon many brands will be updating their social contacts to include their official account on Threads.

I'm not in a particular rush to get this merged, just thought I'd add some context as to why I submitted this in the first place.

2023-07-07 23:48 UTC, LitoMore commented
The popular metric looks good to me. This product is well-known enough.

2023-07-07 23:49 UTC, LitoMore approved these changes

2023-07-08 13:39 UTC, adamrusted commented
Alrighty, I'm happy to merge this one in, given I can see it's got over 10m downloads on android alone since it's launch!

2023-07-08 13:40 UTC, merged