Add Pansonic icon
simple-icons/simple-icons pull request #8975
Opened 2023-07-09 10:47 UTC by PratyushJayachandran

![panasonic](https://github.com/simple-icons/simple-icons/assets/35000807/bb78a85e-9e6b-4a5f-88dc-c6a99298fcda)

**Issue:** closes #5233 

**Similarweb rank:** 4,502. See https://www.similarweb.com/website/panasonic.com

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
SVG: Taken from website header at https://www.panasonic.com
Color: `#0049ab` Taken from website header and footer.

2023-07-21 14:02 UTC, adamrusted requested changes
I'm seeing some [slight differences](https://github.com/simple-icons/simple-icons/assets/1830867/63960a20-26d3-42fc-a70e-27c73198380d) (ignoring where their own SVG is broken!) between your PR in black and the source icon in red. I'd also steer away from having `www.na.` in the URL, and instead default it to just `www.`.

2023-07-22 08:10 UTC, PratyushJayachandran commented
> I'm seeing some [slight differences](https://github.com/simple-icons/simple-icons/assets/1830867/63960a20-26d3-42fc-a70e-27c73198380d) (ignoring where their own SVG is broken!) between your PR in black and the source icon in red. I'd also steer away from having `www.na.` in the URL, and instead default it to just `www.`.

This is one of the more you look at it cases. Anyway I tried to fix it. Please review.

2023-07-22 10:14 UTC, adamrusted requested changes
I'm still spotting a [slight difference](https://github.com/simple-icons/simple-icons/assets/1830867/5ed2c4e0-090e-4fd7-a558-1fb221182c7d) I'm afraid @PratyushJayachandran - might need to up the precision to 4 to fix it.

2023-07-22 21:34 UTC, PratyushJayachandran commented
> I'm still spotting a [slight difference](https://github.com/simple-icons/simple-icons/assets/1830867/5ed2c4e0-090e-4fd7-a558-1fb221182c7d) I'm afraid @PratyushJayachandran - might need to up the precision to 4 to fix it.

[It is not perfect](https://github.com/simple-icons/simple-icons/assets/35000807/6fea91d0-efe5-443d-89bc-19b0c06af191) but it is better than before.

2023-07-25 16:50 UTC, adamrusted requested changes
Unfortunately still seeing [quite a difference](https://github.com/simple-icons/simple-icons/assets/1830867/ce8826d7-276a-4ced-b9b8-6e05b2968144) between your PR and [this file](https://www.panasonic.com/content/dam/Panasonic/plogo.svg) from the header.

2023-07-28 03:55 UTC, PratyushJayachandran commented
> Unfortunately still seeing [quite a difference](https://github.com/simple-icons/simple-icons/assets/1830867/ce8826d7-276a-4ced-b9b8-6e05b2968144) between your PR and [this file](https://www.panasonic.com/content/dam/Panasonic/plogo.svg) from the header.

I hope it is fixed now. I might have been using the wrong source. I took your source, updated JSON with it and re-did all the process with precision 4. I didn't touch any point or try clean-ups
![panasonic](https://github.com/simple-icons/simple-icons/assets/35000807/6da36246-469d-4e40-98c9-219fcfa6861e)

2023-07-28 06:22 UTC, Wissididom commented
I don't know it it is important but I think there is a typo in the PR title
```diff
- Add Pansonic icon
+ Add Panasonic icon
```

2023-07-28 06:56 UTC, PratyushJayachandran commented
> I don't know if it is important but I think there is a typo in the PR title
> 
> ```diff
> - Add Pansonic icon
> + Add Panasonic icon
> ```

Thanks for pointing it out

2023-08-10 15:14 UTC, adamrusted requested changes

2023-08-10 15:14 UTC, adamrusted commented on _data/simple-icons.json
> +            "source": "https://www.panasonic.com/content/dam/Panasonic/plogo.svg",
```suggestion
            "source": "https://www.panasonic.com",
```
Although we're using a specific SVG, it's available in the website header. No need to link directly to the file.

2023-08-10 15:14 UTC, adamrusted commented on icons/panasonic.svg
Path itself now matches up perfectly. If you're able to resolve the imperfections without altering the shape, then please do. Otherwise, I'm happy to merge this in - unless another @simple-icons/icon-review maintainer is willing to take a look?

2023-08-10 15:22 UTC, adamrusted commented on icons/panasonic.svg
If you can remove the discrepencies (like the weird chunks missing from letters) then go for it. I'm only anti-edit in as much as the main shape needs to remain the same. SVG optimisations are fine.

2023-08-11 06:29 UTC, PratyushJayachandran commented on icons/panasonic.svg
I have cleaned up `P a o`
Precision 4 and checked from my side.

2023-09-03 08:43 UTC, adamrusted approved these changes
LGTM! Thanks @PratyushJayachandran 🎉

2023-09-03 08:45 UTC, merged