Add Raycast Icon
simple-icons/simple-icons pull request #8987
Opened 2023-07-10 18:58 UTC by RiteshK-611

**Issue:** closes #8977

**Similarweb rank:**
Raycast's Similarweb rank is: [125,433](https://www.similarweb.com/website/raycast.com/#overview)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
This change resolves issue #8977 by adding Raycast logo in raycast.svg file and by updating simple-icons.json file with icon's data

### Preview
![raycast](https://github.com/simple-icons/simple-icons/assets/61982298/7a60cdff-30d3-41af-85d0-5dacfb8da0af)

2023-07-22 16:20 UTC, RiteshK-611 commented
> ping @thomaspaulmann @itsnwa to double check the brand guidelines

Hey @fmerian I think its no required as I took svg from their official asset https://raycastapp.notion.site/Raycast-Press-Kit-ce1ccf8306b14ac8b8d47b3276bf34e0

2023-07-23 12:20 UTC, adamrusted requested changes

2023-07-23 12:20 UTC, adamrusted commented on _data/simple-icons.json
> +            "guidelines": "https://raycastapp.notion.site/Raycast-Press-Kit-ce1ccf8306b14ac8b8d47b3276bf34e0"
```suggestion
            "source": "https://www.raycast.com",
            "guidelines": "https://www.raycast.com/press"
```

2023-07-23 12:20 UTC, adamrusted commented on icons/raycast.svg
There's a couple of [tiny differences](https://github.com/simple-icons/simple-icons/assets/1830867/7748ad2e-70e1-4690-9f3a-99650c2f61fe) between your icon and the one found on the website homepage. If you don't fancy re-doing this with the website header SVG, I'm happy to let this one through - else you'll be going up to 5 decimals of precision! Could you update the source and guidelines link though?

2023-08-15 17:55 UTC, adamrusted commented on icons/raycast.svg
Im still seeing [minor differences](https://github.com/simple-icons/simple-icons/assets/1830867/4ff4edc8-33ba-4d11-b03b-aadcaf71e080) throughout this icon. @LitoMore - would you mind pitching in on this one?

2023-11-21 10:29 UTC, PeterShaggyNoble submitted a review, later dismissed

2023-11-21 11:21 UTC, adamrusted approved these changes

2023-11-21 11:22 UTC, adamrusted commented on _data/simple-icons.json
> +            "guidelines": "https://raycastapp.notion.site/Raycast-Press-Kit-ce1ccf8306b14ac8b8d47b3276bf34e0"
```suggestion
            "source": "https://www.raycast.com/press",
            "guidelines": "https://www.raycast.com/press"
```

2023-11-21 11:23 UTC, merged