Add TCS icon
simple-icons/simple-icons pull request #9026
Opened 2023-07-15 22:25 UTC by PratyushJayachandran

![tcs](https://github.com/simple-icons/simple-icons/assets/35000807/77d4d8c7-8d82-461a-8db4-45eaed5853ff)

**Issue:** closes #5323 

**Similarweb rank:** 18,811. See https://www.similarweb.com/website/tcs.com

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
SVG: Taken from website footer https://www.tcs.com/. Header is PNG.
COlor: `#ee3984` Taken from one of the logo colors. I am not sure. Maybe `#000000` would be more suitable.

2023-07-23 14:33 UTC, adamrusted requested changes
I would, in this instance, suggest we display the full title - but use the shorter slug. Purely because the 'aka' tag isn't used on the website at the minute. Otherwise, icon is spot on!

2023-07-23 14:33 UTC, adamrusted commented on _data/simple-icons.json
> +            }
```suggestion
            "title": "Tata Consultancy Services",
            "slug": "tcs",
            "hex": "EE3984",
            "source": "https://www.tcs.com",
            "aliases": {
                "aka": [
                    "TCS"
                ]
            }
```

2023-07-30 03:38 UTC, PratyushJayachandran commented
> I would, in this instance, suggest we display the full title - but use the shorter slug. Purely because the 'aka' tag isn't used on the website at the minute. Otherwise, icon is spot on!

Applied your suggestion

2023-07-30 03:50 UTC, PratyushJayachandran commented
> I would, in this instance, suggest we display the full title - but use the shorter slug. Purely because the 'aka' tag isn't used on the website at the minute. Otherwise, icon is spot on!

Applied your suggestion

2023-08-13 18:46 UTC, adamrusted approved these changes
LGTM! Thanks @PratyushJayachandran 🎉

2023-08-13 18:48 UTC, merged