Add Pearson icon
simple-icons/simple-icons pull request #9030
Opened 2023-07-16 06:51 UTC by PratyushJayachandran

![pearson](https://github.com/simple-icons/simple-icons/assets/35000807/dcd0583d-618c-41af-b52a-c627d17a1909)
**Issue:** closes #5865 

**Similarweb rank:** 1,504. See https://www.similarweb.com/website/pearson.com

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
SVG: Taken from website https://www.pearson.com
Color: Taken from logo `#000000`. Also mentioned in the [branding guidelines](https://www.pearson.com/content/dam/corporate/global/pearson-dot-com/files/logos/Pearson_Guidelines_Logo.pdf) which I cannot find a landing page for.

2023-07-18 15:04 UTC, adamrusted commented
Also worth noting the exact same logo is used for Pearson VUE, the online testing platform. We might want to add this in as an AKA alias.

2023-07-19 06:20 UTC, PratyushJayachandran commented
> Also worth noting the exact same logo is used for Pearson VUE, the online testing platform. We might want to add this in as an AKA alias.

Added and pushed commit. Thanks for the suggestion 💯

2023-07-20 15:07 UTC, LitoMore commented
<img width="484" alt="image" src="https://github.com/simple-icons/simple-icons/assets/8186898/5d1182a1-ba3e-4212-9a9b-dd961da93900">


@PratyushJayachandran I picked the resource from their homepage, but I found some difference

2023-07-21 05:15 UTC, PratyushJayachandran commented
> <img alt="image" width="484" src="https://user-images.githubusercontent.com/8186898/254925832-5d1182a1-ba3e-4212-9a9b-dd961da93900.png">
> 
> @PratyushJayachandran I picked the resource from their homepage, but I found some differences.

I have tried to fix it. Hope the new commit resolves it. Thanks for the review.

2023-07-21 12:46 UTC, LitoMore requested changes
<img width="323" alt="image" src="https://github.com/simple-icons/simple-icons/assets/8186898/d487e9c3-0131-4aa7-b840-bf77e4e7b547">

Hey @PratyushJayachandran, please review your changes before committing. Thank you.

2023-07-21 18:59 UTC, PratyushJayachandran commented
> <img alt="image" width="323" src="https://user-images.githubusercontent.com/8186898/255175838-d487e9c3-0131-4aa7-b840-bf77e4e7b547.png">
> 
> Hey @PratyushJayachandran, please review your changes before committing. Thank you.

Oops my bad. It was looking fine in my editing app but then after optimization it becomes this. Forgot to recheck this time.

I'll fix it.

2023-07-22 08:21 UTC, PratyushJayachandran commented
> Hey @PratyushJayachandran, please review your changes before committing. Thank you.

I fixed it.

2023-07-23 14:45 UTC, adamrusted approved these changes
Icon itself is a perfect match, just an amendment to the JSON, which I should've proposed instead of the 'aka' entry and then we're good to go. I'll merge this in myself - save you doing it and re-requesting a review @PratyushJayachandran 🎉

2023-07-23 14:45 UTC, adamrusted commented on _data/simple-icons.json
> +                ]
I know I suggested the `aka` of Pearson VUE, but this is probably a better way to handle it, given their hex codes are different...

```suggestion
                "dup": [
                    {
                        "title": "Pearson VUE",
                        "hex": "008FB4"
                    }
                ]
```

2023-07-23 14:46 UTC, merged