Add Mediawiki icon
simple-icons/simple-icons pull request #9052
Opened 2023-07-19 11:41 UTC by pisceskaze

![mediawiki](https://github.com/simple-icons/simple-icons/assets/57829841/b20eebbf-70bb-49de-9475-057bde67d1a9)
**Issue:** closes #9041 

**Similarweb rank:**
https://www.similarweb.com/website/mediawiki.org - `#37,518`

### Checklist
  - [X] I updated the JSON data in `_data/simple-icons.json`
  - [X] I optimized the icon with SVGO or SVGOMG
  - [X] The SVG `viewbox` is `0 0 24 24`

### Description
SVG: Taken from https://upload.wikimedia.org/wikipedia/commons/a/a6/MediaWiki-2020-icon.svg
Color: There don't seem to be any mentions of primary colors.

2023-07-19 11:45 UTC, pisceskaze commented
Please hold on, I know why the linter test failed. But what about the "Verify Source / Test package"?

2023-07-19 11:48 UTC, pisceskaze commented
LET'S GOOOOOOOOOOOOO

2023-07-19 17:43 UTC, alistair3149 commented
Brand guideline: https://mediawiki.org/wiki/Manual:MediaWiki_logo_guidelines

2023-07-19 17:46 UTC, pisceskaze commented
> Brand guideline: https://mediawiki.org/wiki/Manual:MediaWiki_logo_guidelines

I already attached it to the metadata. However the simpler you want the icons, the harder for us to compile with these policies. The policies mention that I should still attach the "gradient" effect, like in the install screen's icon.

2023-07-19 17:54 UTC, alistair3149 commented
It is a bit tough with the MediaWiki icon since it has several incompatibility with SimpleIcons, the official icon has:
- Different variations (pedals) depending on the icon size
- Use of gradient instead of solid color
- Use of opacity for the overlapped pedals

Perhaps someone who's more experienced with converting this kind of icons can give some tips.

2023-07-19 18:07 UTC, pisceskaze commented
![mediawiki (5)](https://github.com/simple-icons/simple-icons/assets/57829841/82084313-cee7-437a-98a5-64eb0686e75d)
I got another version, what do you think?

2023-07-21 16:49 UTC, adamrusted commented
Would it be worth [reaching out](https://www.mediawiki.org/wiki/Communication) to the MediaWiki team, to see if they have any preference? Given the complexity of the logo, it might just not translate well to our package. I'd rather we asked them directly than tried our own interpretations.

2023-07-22 06:28 UTC, pisceskaze commented
> Would it be worth [reaching out](https://www.mediawiki.org/wiki/Communication) to the MediaWiki team, to see if they have any preference? Given the complexity of the logo, it might just not translate well to our package. I'd rather we asked them directly than tried our own interpretations.

I just noticed that MediaWiki was a project by Wikimedia Foundation, and so they are the commissioner for the icon. I think we should reach out to the foundation, not the developer team.

2023-07-23 15:33 UTC, pisceskaze commented
Oh and FYI, I have sent a notice to Serhio's at their Commons's profile talk page, but if I can't get a response, I would likely go and contact the foundation.

2023-07-23 15:36 UTC, adamrusted commented
> Oh and FYI, I have sent a notice to Serhio's at their Commons's profile talk page, but if I can't get a response, I would likely go and contact the foundation.

Amazing, thank you @pisceskaze! I'll mark this as 'awaiting reply' for now, let us know if/when you hear back!

2023-08-04 08:09 UTC, pisceskaze commented
> > Oh and FYI, I have sent a notice to Serhio's at their Commons's profile talk page, but if I can't get a response, I would likely go and contact the foundation.
> 
> Amazing, thank you @pisceskaze! I'll mark this as 'awaiting reply' for now, let us know if/when you hear back!

I got the reply from the trademark department and I would like to share this to you!

<img width="550" alt="image" src="https://github.com/simple-icons/simple-icons/assets/57829841/2cbd8612-8d3d-43fb-ae35-9f2eb9c77116">

2023-08-04 08:23 UTC, adamrusted requested changes

2023-08-04 08:37 UTC, pisceskaze commented on icons/mediawiki.svg
By my contact you mean respond to them?

2023-09-03 08:41 UTC, adamrusted commented on icons/mediawiki.svg
Any joy, @pisceskaze?

2023-09-17 03:22 UTC, PratyushJayachandran commented
@pisceskaze The contributed SVG is not matching with the provided source. See [differences here!](https://github.com/simple-icons/simple-icons/assets/35000807/0458ea5d-70a5-469c-9d68-713404fe0c7f)

2023-09-17 08:49 UTC, pisceskaze commented
> @pisceskaze The contributed SVG is not matching with the provided source. See [differences here!](https://github.com/simple-icons/simple-icons/assets/35000807/0458ea5d-70a5-469c-9d68-713404fe0c7f)

Oops!

2023-09-17 08:50 UTC, pisceskaze commented on icons/mediawiki.svg
Not really, neither the legal department or the author reply.

2023-09-17 09:16 UTC, pisceskaze commented on icons/mediawiki.svg
But based on the last reply, as long as we share it under the same license, all will be okay.

2023-10-04 03:52 UTC, PratyushJayachandran commented
> Update in the situation: For now, I have upload my new version of the logo that follows the rule, but I still might have to suggests that MediaWiki should have it's exception in [.svglint-ignored.json](https://github.com/simple-icons/simple-icons/blob/develop/.svglint-ignored.json).

It is still different from the source. [See Here!](https://github.com/simple-icons/simple-icons/assets/35000807/bf8c6d4b-9024-4733-8ba0-f65c105f6f85)
Are we looking at the same source file? This is the source I am comparing against: 
![MediaWiki-2020-logo](https://github.com/simple-icons/simple-icons/assets/35000807/a7b82f31-51eb-4720-b0d8-56e58e2fcdb5)

I tried to create one to check linting issues. It passes fine. The version I created has 325 points vs yours which has 528 points. The redundant points are causing linting issues.

I followed these steps:
1. Scaled original and centered it.
2. Set opacity to 100%
3. Put stroke aligned to inside of shape and the converted to outline
4. Merged the resulting shape
5. SVGO optimized to precision 3

2023-10-04 04:11 UTC, pisceskaze commented
> > Update in the situation: For now, I have upload my new version of the logo that follows the rule, but I still might have to suggests that MediaWiki should have it's exception in [.svglint-ignored.json](https://github.com/simple-icons/simple-icons/blob/develop/.svglint-ignored.json).
> 
> It is still different from the source. [See Here!](https://github.com/simple-icons/simple-icons/assets/35000807/bf8c6d4b-9024-4733-8ba0-f65c105f6f85) Are we looking at the same source file? This is the source I am comparing against: ![MediaWiki-2020-logo](https://user-images.githubusercontent.com/35000807/272455807-a7b82f31-51eb-4720-b0d8-56e58e2fcdb5.svg)
> 
> I tried to create one to check linting issues. It passes fine. The version I created has 325 points vs yours which has 528 points. The redundant points are causing linting issues.
> 
> I followed these steps:
> 
>     1. Scaled original and centered it.
> 
>     2. Set opacity to 100%
> 
>     3. Put stroke aligned to inside of shape and the converted to outline
> 
>     4. Merged the resulting shape
> 
>     5. SVGO optimized to precision 3

Ohhh. I thought you say about the "MediaWiki_2020_icon.svg".
I will look into it. Or you can just suggest the changes and I will commit.

2023-10-04 04:40 UTC, PratyushJayachandran commented
> Ohhh. I thought you say about the "MediaWiki_2020_icon.svg". I will look into it. Or you can just suggest the changes and I will commit.

Give it another try :)
I'll suggest if it doesn't work out

2023-10-04 05:10 UTC, pisceskaze commented
> > Ohhh. I thought you say about the "MediaWiki_2020_icon.svg". I will look into it. Or you can just suggest the changes and I will commit.
> 
> Give it another try :) I'll suggest if it doesn't work out

nah, it ain't work lol
I actually done the same as you do, but don't seems to work out for me.

2023-10-05 07:08 UTC, PratyushJayachandran commented on icons/mediawiki.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>MediaWiki</title><path d="M9.023.497c.648.49 1.224.977 1.686 1.538a7.303 7.303 0 0 1 1.204-1.92L12.01 0l.092.119c.499.641
```suggestion
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>MediaWiki</title><path d="M22.368 12.006c.546-.341 1.06-.767 1.568-1.246a8.123 8.123 0 0 0-1.793-.91c.463-.447.877-.97 1.274-1.544a8.133 8.133 0 0 0-1.94-.52c.359-.534.654-1.13.923-1.773a8.838 8.838 0 0 0-1.468-.132c-.182 0-.36.016-.54.03.24-.598.406-1.244.536-1.93a8.129 8.129 0 0 0-1.986.318c.112-.634.14-1.301.123-1.998a8.116 8.116 0 0 0-1.874.723c-.023-.644-.135-1.302-.296-1.98a8.107 8.107 0 0 0-1.684 1.097c-.157-.625-.403-1.245-.701-1.876a8.119 8.119 0 0 0-1.42 1.424C12.807 1.11 12.438.555 12.015 0a8.124 8.124 0 0 0-1.093 1.688C10.525 1.181 10.048.714 9.52.26a8.12 8.12 0 0 0-.717 1.877c-.494-.414-1.057-.77-1.67-1.105a8.115 8.115 0 0 0-.31 1.986c-.57-.303-1.195-.535-1.864-.735-.043.712-.01 1.37.11 2.007-.62-.177-1.28-.274-1.976-.33.105.707.276 1.346.526 1.946-.168-.012-.335-.028-.506-.028-.486 0-.984.043-1.497.11.25.667.548 1.255.916 1.789-.638.09-1.28.27-1.94.501a8.14 8.14 0 0 0 1.267 1.558c-.605.22-1.195.532-1.79.895.499.509 1.01.924 1.564 1.263-.546.341-1.06.767-1.568 1.246a8.124 8.124 0 0 0 1.793.91c-.464.447-.878.97-1.274 1.544a8.151 8.151 0 0 0 1.94.52c-.359.534-.654 1.131-.923 1.773.508.086.993.132 1.467.132.182 0 .362-.015.541-.03-.24.598-.406 1.244-.536 1.93a8.125 8.125 0 0 0 1.985-.318c-.111.634-.139 1.301-.122 1.999a8.12 8.12 0 0 0 1.874-.724c.023.644.135 1.302.296 1.98a8.117 8.117 0 0 0 1.684-1.097c.157.625.403 1.245.701 1.876a8.115 8.115 0 0 0 1.42-1.424c.283.579.652 1.134 1.075 1.689a8.123 8.123 0 0 0 1.092-1.688c.397.507.874.974 1.404 1.428.33-.632.566-1.247.717-1.877.494.414 1.057.77 1.67 1.106.19-.688.294-1.338.31-1.986.57.302 1.195.534 1.863.735.044-.713.01-1.371-.108-2.008.62.177 1.28.274 1.975.33a8.117 8.117 0 0 0-.526-1.946c.168.012.335.028.506.028.486 0 .984-.043 1.497-.11a8.12 8.12 0 0 0-.916-1.789c.638-.09 1.28-.27 1.94-.5a8.124 8.124 0 0 0-1.267-1.56c.605-.22 1.195-.531 1.79-.893a8.116 8.116 0 0 0-1.564-1.264zm1.161-1.21a8.655 8.655 0 0 1-1.402 1.062 6.235 6.235 0 0 0-.63-.306c-.544-.225-1.096-.357-1.658-.357-.296 0-.595.036-.898.115-.358.096-.68.277-.96.512-.08-.084-.166-.159-.241-.257a.36.36 0 0 1-.049-.292 2.25 2.25 0 0 1 .182-.357c.386.214.799.336 1.248.336.209 0 .426-.025.65-.075.867-.196 1.562-.6 2.167-1.134a7.39 7.39 0 0 1 1.591.753zm-1.659 1.21a4.653 4.653 0 0 1-2.14.554c-.616 0-1.138-.185-1.577-.558.249-.206.535-.365.851-.45.273-.071.554-.107.835-.107.5 0 1.012.11 1.562.338.16.066.315.143.47.223zm-4.35-2.288c.25.077.504.126.76.126.253 0 .51-.054.767-.133a3.56 3.56 0 0 0-.4.171 2.49 2.49 0 0 0-.838.707 2.969 2.969 0 0 1-.285-.208.36.36 0 0 1-.108-.276 2.25 2.25 0 0 1 .104-.387zm.105-.225c.143-.287.339-.547.592-.75.612-.49 1.359-.74 2.283-.765l.158-.002c.121 0 .242.01.364.018a4.554 4.554 0 0 1-1.697 1.358c-.349.16-.7.242-1.044.242-.218 0-.437-.038-.656-.101zm1.133.613c.476-.239.98-.355 1.542-.355.268 0 .555.028.85.082.172.032.34.075.51.122-.54.45-1.172.803-1.944.978-.203.046-.404.069-.595.069-.39 0-.752-.101-1.097-.286.2-.25.445-.463.734-.61zm4.269-1.68a8.772 8.772 0 0 1-1.148 1.33 6.226 6.226 0 0 0-.683-.168A4.923 4.923 0 0 0 20.3 9.5c-.424 0-.84.064-1.247.208.125-.039.25-.072.377-.13.809-.372 1.405-.912 1.886-1.563.547.06 1.106.192 1.711.41zM20.932 6.13c.352 0 .718.026 1.11.08a8.755 8.755 0 0 1-.849 1.545 6.226 6.226 0 0 0-.7-.028c-.896.024-1.724.252-2.432.819a2.49 2.49 0 0 0-.667.853c-.11-.043-.22-.074-.327-.132a.36.36 0 0 1-.163-.247 2.25 2.25 0 0 1 .02-.4c.081.007.163.02.243.02.557 0 1.09-.176 1.597-.554.713-.532 1.184-1.184 1.52-1.92.212-.021.426-.036.648-.036zm-3.95 2.245c.08-.31.217-.603.421-.855.498-.606 1.176-1.006 2.075-1.222.169-.04.34-.065.512-.09a4.553 4.553 0 0 1-1.375 1.678c-.455.338-.928.503-1.448.503-.06 0-.124-.01-.185-.014zM20.62 4.25a8.764 8.764 0 0 1-.509 1.684 6.237 6.237 0 0 0-.691.122c-.873.21-1.634.604-2.21 1.306a2.49 2.49 0 0 0-.478.988 2.984 2.984 0 0 1-.344-.075.36.36 0 0 1-.211-.209 2.248 2.248 0 0 1-.063-.4 2.594 2.594 0 0 0 1.689-.9c.586-.667.911-1.402 1.086-2.19a7.39 7.39 0 0 1 1.73-.326zm-4.5 3.165c.014-.318.087-.632.234-.92.36-.696.941-1.228 1.775-1.626a5.99 5.99 0 0 1 .483-.201 4.553 4.553 0 0 1-.997 1.933c-.416.473-.911.734-1.496.814zm2.7-4.788a8.78 8.78 0 0 1-.147 1.751c-.22.076-.437.163-.651.265-.81.386-1.473.931-1.89 1.737a2.49 2.49 0 0 0-.262 1.06c-.042.001-.08.011-.124.011a3.65 3.65 0 0 1-.228-.007.36.36 0 0 1-.25-.16 2.25 2.25 0 0 1-.141-.368c.613-.21 1.108-.61 1.462-1.242.434-.775.6-1.562.607-2.37a7.386 7.386 0 0 1 1.624-.677zM15.114 5.71c.207-.755.665-1.396 1.399-1.96.138-.106.284-.203.432-.298a4.556 4.556 0 0 1-.574 2.1c-.309.55-.734.92-1.293 1.118a2.238 2.238 0 0 1 .036-.96zm1.61-4.296c.124.57.212 1.155.22 1.742-.2.121-.395.251-.583.396-.712.546-1.248 1.217-1.488 2.092a2.49 2.49 0 0 0-.037 1.083c-.119.03-.232.068-.362.085a.362.362 0 0 1-.258-.105 2.251 2.251 0 0 1-.214-.33c.555-.333.956-.828 1.17-1.519.265-.848.263-1.652.102-2.443a7.375 7.375 0 0 1 1.45-1.001zM13.738 5.2c.046-.783.36-1.505.96-2.208.113-.132.235-.257.36-.38.12.693.11 1.416-.125 2.172-.188.605-.53 1.056-1.03 1.364-.12-.3-.182-.621-.165-.948zm.68-4.537c.24.533.448 1.087.577 1.66-.17.159-.333.327-.487.507-.582.682-.966 1.45-1.02 2.355-.019.37.053.733.19 1.07-.104.052-.202.11-.318.152a.364.364 0 0 1-.293-.045 2.246 2.246 0 0 1-.28-.279c.475-.44.764-1.008.83-1.728.082-.885-.087-1.67-.409-2.411a7.385 7.385 0 0 1 1.21-1.28zM12.644 5.88a2.236 2.236 0 0 1-.358-.893c-.118-.775.039-1.546.48-2.36.083-.152.176-.3.273-.446.261.653.402 1.362.33 2.151-.06.63-.3 1.142-.725 1.548zM12.008.408c.346.472.664.97.91 1.503a6.234 6.234 0 0 0-.37.598c-.429.788-.645 1.618-.508 2.516.057.365.203.705.408 1.007-.092.072-.175.15-.28.214a.366.366 0 0 1-.296.018 2.252 2.252 0 0 1-.33-.215c.371-.53.536-1.145.451-1.863-.104-.882-.432-1.616-.901-2.274.226-.502.522-.996.916-1.504zm-1.185 4.673c-.277-.734-.284-1.521-.021-2.408.05-.167.11-.33.173-.493.392.584.677 1.249.77 2.035.074.63-.055 1.18-.386 1.665a2.238 2.238 0 0 1-.536-.8zM9.598.66c.436.388.851.81 1.203 1.28-.091.215-.172.434-.239.661-.255.86-.294 1.718.027 2.567.132.346.345.648.608.9-.074.09-.14.183-.23.268a.366.366 0 0 1-.23.082c-.024 0-.049-.002-.055-.003a2.253 2.253 0 0 1-.368-.141c.253-.596.287-1.232.055-1.917-.285-.842-.76-1.49-1.354-2.037a7.387 7.387 0 0 1 .583-1.66zm-.71 2.465c.014-.173.04-.346.068-.519.505.49.922 1.081 1.176 1.831.203.6.191 1.166-.032 1.71a2.236 2.236 0 0 1-.69-.67c-.423-.661-.594-1.43-.521-2.352zM7.294 1.407c.508.29 1 .616 1.443 1.003-.044.229-.078.46-.096.697-.07.894.07 1.74.56 2.505.2.31.472.562.781.754-.054.103-.098.208-.168.31a.36.36 0 0 1-.263.136 2.25 2.25 0 0 1-.39-.062c.124-.635.025-1.264-.345-1.886-.453-.764-1.052-1.3-1.748-1.71a7.387 7.387 0 0 1 .226-1.747zM8.925 6.67a2.236 2.236 0 0 1-.815-.512c-.55-.558-.877-1.274-.998-2.191a5.974 5.974 0 0 1-.042-.522A4.555 4.555 0 0 1 8.6 4.992c.324.544.43 1.1.325 1.678zM5.193 2.617a8.768 8.768 0 0 1 1.62.681c.005.233.02.467.051.702.117.889.43 1.688 1.068 2.334.262.262.58.45.922.575-.031.112-.053.223-.1.337a.36.36 0 0 1-.23.189 2.25 2.25 0 0 1-.318.022c-.026 0-.05-.01-.075-.01-.012-.645-.241-1.236-.73-1.765-.603-.653-1.3-1.053-2.065-1.31a7.385 7.385 0 0 1-.143-1.755zm2.69 4.794a2.224 2.224 0 0 1-.903-.317c-.655-.43-1.123-1.064-1.432-1.935a5.975 5.975 0 0 1-.149-.502c.66.243 1.281.613 1.818 1.194.426.462.645.979.666 1.56zM3.39 4.237a8.774 8.774 0 0 1 1.726.33c.053.227.117.452.196.675.3.846.772 1.562 1.53 2.061.31.202.662.305 1.022.355-.007.121-.006.24-.03.367a.36.36 0 0 1-.184.232c-.124.046-.251.08-.38.103-.145-.632-.492-1.166-1.083-1.584-.726-.514-1.49-.763-2.294-.854a7.41 7.41 0 0 1-.503-1.685zm3.632 4.145c-.05.003-.098.013-.147.013a2.24 2.24 0 0 1-.806-.15c-.73-.285-1.32-.807-1.803-1.595-.09-.148-.171-.301-.25-.457.769.11 1.429.364 2.027.787.517.366.84.83.979 1.402zM1.965 6.197c.43-.047.8-.07 1.147-.07.215 0 .413.02.613.038.098.21.206.415.328.615.47.765 1.08 1.367 1.926 1.698a2.5 2.5 0 0 0 .897.167c.06 0 .12-.012.18-.016.016.115.041.226.045.349a.36.36 0 0 1-.133.265c-.112.07-.237.111-.358.16-.274-.578-.723-1.021-1.381 [...]

2023-10-05 08:34 UTC, pisceskaze commented on icons/mediawiki.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>MediaWiki</title><path d="M9.023.497c.648.49 1.224.977 1.686 1.538a7.303 7.303 0 0 1 1.204-1.92L12.01 0l.092.119c.499.641
Committed.

2023-10-05 18:34 UTC, adamrusted requested changes
This looks a little _sad_ at the smallest of sizes, perhaps it's worth upping the stroke width to 0.5pt while the icon is at correct scale?

![mediawiki](https://github.com/simple-icons/simple-icons/assets/1830867/5942df2a-b16e-408a-a791-2955f6ef3bd3)

2023-10-06 04:09 UTC, pisceskaze commented
> ![mediawiki (5)](https://user-images.githubusercontent.com/57829841/254670472-82084313-cee7-437a-98a5-64eb0686e75d.png) I got another version, what do you think?

You mean this one.
I will try to replicate it, and also, sinces we have alternative versions for large, normal and smol (for the Powered by `MediaWiki` button), I might prefer to have 2/3 versions for this

2023-10-06 04:21 UTC, pisceskaze commented
![mediawiki](https://github.com/simple-icons/simple-icons/assets/57829841/22a082da-5082-40dd-ad63-6ffe9419f73c)
Is this good?

2023-10-06 04:25 UTC, pisceskaze commented
Shall be good to go.

2023-10-06 04:58 UTC, pisceskaze reviewed
I personally think it's good to go.

2023-12-01 19:18 UTC, adamrusted requested changes
The source needs updating, currently 404'ing for me. Also seeing some inconsistencies with the icon itself. Could you re-work please @pisceskaze?

2023-12-01 19:18 UTC, adamrusted commented on _data/simple-icons.json
> +            "source": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/MediaWiki-2020-icon.svg",
```suggestion
            "source": "https://commons.wikimedia.org/wiki/File:MediaWiki-2020-icon.svg",
```

2023-12-01 19:41 UTC, pisceskaze commented
After a long times to considers, unless we can actually have a perfect way to execute this, like a change/exemption of the policy, and/or the foundation does something to the logo, I prefer to make this cold for now. I'm sorry for letting you all down, but I still have other things to do and I didn't have much times to work with this.

2023-12-01 19:41 UTC, pisceskaze commented
Forgot to close this.

2023-12-01 19:41 UTC, closed without merging

2023-12-01 19:48 UTC, adamrusted commented
No worries @pisceskaze - thanks for your work on this regardless!