[closes #9139] Updating Pets at home logo
simple-icons/simple-icons pull request #9140
Opened 2023-07-29 00:56 UTC by userbradley

**Issue:** closes #9139

**Similarweb rank:**
Global: 11,009

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

Updated the Pets at Home logo using the latest icon from the site

2023-07-29 08:25 UTC, PratyushJayachandran requested changes
Please read [Contribution Guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md). I have suggested changes which you may apply or redo from source for the tests to pass and be considered for addition to this project.

2023-07-29 08:25 UTC, PratyushJayachandran commented on _data/simple-icons.json
> +            "hex": "04A928",
```suggestion
            "hex": "00AA28",
```
Color picked from wordmark was different

2023-07-29 08:25 UTC, PratyushJayachandran commented on icons/petsathome.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 740 420"><path d="M132 382c0-23.3 12.6-38 31.8-38 8.9 0 15.6 4.8 18.9 12v-7.4c0-2.1 1.2-3.3 3.3-3.3h15.4c2.1 0 3.3 1.2 3.3 3.3v66.7c0 2.1-1.2 3.3-
```suggestion
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Pets at Home</title><path d="M4.283 17.577c0-.756.409-1.232 1.031-1.232a.65.65 0 0 1 .613.389v-.24c0-.068.039-.107.107-.107h.5c.067 0 .106.039.106.107v2.163c0 .068-.039.107-.107.107h-.499c-.068 0-.107-.04-.107-.107v-.237a.65.65 0 0 1-.613.389c-.622 0-1.03-.477-1.03-1.232zm1.19.7c.302 0 .46-.236.46-.7s-.158-.7-.46-.7-.46.236-.46.7.159.7.46.7zm2.305-2.211v.32h.383c.068 0 .107.04.107.108v.337c0 .068-.039.107-.107.107h-.383v1.025c0 .25.094.36.237.36a.49.49 0 0 0 .175-.043c.1-.042.16.01.16.104 0 .237-.27.425-.598.425-.505 0-.687-.318-.687-.756v-1.776c0-.042.023-.072.062-.091l.502-.21c.088-.04.15-.004.15.09zm2.157 2.7h-.532c-.068 0-.107-.038-.107-.106v-2.792c0-.068.039-.107.107-.107h.532c.068 0 .107.04.107.107v1.038h1.047v-1.038c0-.068.039-.107.107-.107h.532c.068 0 .107.04.107.107v2.792c0 .068-.04.107-.107.107h-.532c-.068 0-.107-.04-.107-.107v-1.184h-1.047v1.184c0 .068-.04.107-.107.107zm2.273-1.19c0-.755.46-1.231 1.19-1.231.729 0 1.19.476 1.19 1.232 0 .755-.461 1.232-1.19 1.232-.73 0-1.19-.477-1.19-1.232zm1.186.701c.302 0 .46-.236.46-.7s-.158-.7-.46-.7c-.301 0-.46.236-.46.7s.162.7.46.7zm3.463.49h-.5c-.067 0-.106-.04-.106-.107v-1.453c0-.243-.072-.288-.201-.288a.518.518 0 0 0-.383.172v1.566c0 .068-.039.107-.107.107h-.5c-.067 0-.106-.04-.106-.107v-1.998c0-.042.022-.071.061-.09l.503-.211c.09-.04.15-.004.15.09v.344c.129-.318.359-.45.677-.45.282 0 .49.132.587.428a.646.646 0 0 1 .638-.428c.38 0 .688.207.688.732v1.58c0 .067-.04.106-.107.106h-.5c-.068 0-.107-.039-.107-.107v-1.452c0-.243-.07-.289-.2-.289a.518.518 0 0 0-.383.172v1.566c.003.078-.036.117-.104.117zm1.77-1.213c0-.7.4-1.21 1.19-1.21s1.138.575 1.138 1.204v.065c0 .068-.038.107-.107.107h-1.507c0 .282.227.57.72.57.204 0 .356-.052.55-.12.111-.039.199-.016.199.104 0 .23-.34.535-.928.535-.797 0-1.255-.493-1.255-1.255zm1.65-.272c-.028-.289-.194-.448-.46-.448s-.428.16-.46.448h.92zm1.735-6.598-.661-.16c-.726-.171-.992-.362-.992-.713 0-.353.353-.586.895-.586.619 0 1.076.214 1.835.726.084.052.159.097.214.097.107 0 .181-.042.2-.2.024-.173.033-.332.033-.546 0-.32-.01-.535-.032-.651-.033-.182-.097-.276-.214-.354-.63-.395-1.333-.564-2.11-.564-1.752 0-2.893.853-2.893 2.166 0 .982.713 1.718 1.952 2.026l.694.172c.885.214.992.415.992.727 0 .363-.308.61-.82.61-.811 0-1.408-.3-2.07-.96-.096-.098-.158-.16-.275-.16a.279.279 0 0 0-.256.15c-.405.67-.713.917-1.141.917-.457 0-.778-.32-.778-.908V9.39h1.005c.133 0 .243-.11.243-.243V8.08a.245.245 0 0 0-.243-.243h-1.005V6.579c0-.276-.182-.383-.457-.266l-1.537.642a.288.288 0 0 0-.182.275v2.983c0 1.868-1.248 3.136-2.837 3.136-.833 0-1.589-.321-1.868-1.132.192.075.513.107.97.107 1.835 0 3.113-1.002 3.113-2.454 0-1.29-1.067-2.143-2.656-2.143a4.25 4.25 0 0 0-1.647.32C9.092 6.324 7.415 5.192 5.1 5.192c-1.057 0-2.017.13-2.902.396-.246.074-.395.233-.395.48v4.211a2.963 2.963 0 0 1-1.281-.97C.447 9.213.392 9.15.276 9.15c-.172 0-.276.13-.276.298 0 .727.853 1.686 1.803 2.156v2.902c0 .133.11.244.243.244h1.903c.133 0 .243-.11.243-.244v-2.198c.14.01.276.023.428.023 1.258 0 2.205-.198 2.896-.646.14 1.904 1.563 3.233 3.735 3.233 1.119 0 2.442-.395 3.178-1.397.353.852 1.183 1.397 2.198 1.397s1.621-.256 2.133-.843c.662.555 1.398.843 2.38.843 1.751 0 2.86-.875 2.86-2.25-.003-.983-.538-1.631-1.988-1.984zm-17.816-.065V7.325c0-.202.084-.321.275-.35.289-.053.48-.053.639-.053 1.29 0 2.059.681 2.059 1.813.003 1.193-.914 1.855-2.973 1.884zm6.734-1.514c.512 0 .788.308.788.736 0 .713-.639 1.193-1.589 1.193-.33 0-.522-.023-.652-.075.004-1.105.568-1.854 1.453-1.854z"/></svg>
```
Please apply suggestion or redo using source.

2023-07-29 15:26 UTC, userbradley commented on icons/petsathome.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 740 420"><path d="M132 382c0-23.3 12.6-38 31.8-38 8.9 0 15.6 4.8 18.9 12v-7.4c0-2.1 1.2-3.3 3.3-3.3h15.4c2.1 0 3.3 1.2 3.3 3.3v66.7c0 2.1-1.2 3.3-
Applied suggesition

2023-07-29 15:27 UTC, userbradley commented on _data/simple-icons.json
> +            "hex": "04A928",
Applied suggestion

2023-07-29 17:29 UTC, adamrusted requested changes
Thanks for this change, @userbradley. As suggested by @PratyushJayachandran, it looks like the icon is failing the linter, as you've not followed the [contribution guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) correctly. Could you please review and give this another go? If the source or colour is different from when we included the previous version, the JSON file will also need updating. Feel free to leave a comment if you need some more support.

2023-07-30 11:09 UTC, userbradley commented
Hey @adamrusted - I'm struggling here. Are you able to give me a hint where I've gone wrong?

2023-08-24 15:26 UTC, adamrusted commented
Apologies for the delay @userbradley - please see feedback below:

It would appear the icon you've submitted is still two paths, these should be merged in your graphics software (Inkscape is a great free one if you're unsure) - you'll also need to resize the **canvas** to 24*24px - and adjust the size of the icon so that the longest side (in this case, the width) is equal to 24px. Be careful to maintain the aspect ratio of the icon, so we don't break it! If you then save that, and run `npx svgo icons/petsathome.svg` it should do most of the work for you.

If you could also review `_data/simple-icons.json` to ensure it's all up to date, including the source URL and the hex code, and run `npm run lint` on your local machine to check for any errors.

2023-09-03 07:47 UTC, adamrusted commented
Did you want a hand on this one @userbradley?

2023-09-03 11:40 UTC, userbradley commented
Hey @adamrusted I'll most likely take a look on Monday at work at this one

(I work for Pets At Home)

2023-09-24 20:21 UTC, PratyushJayachandran approved these changes
Perfect match @adamrusted! Thank you for starting the PR @userbradley 🎉

2023-09-24 20:22 UTC, merged