Adding IndiGo icon
simple-icons/simple-icons pull request #9147
Opened 2023-07-29 10:37 UTC by CodeWithShipraJain

**Issue:** closes #9141

**Similarweb rank:**3,771. See https://www.similarweb.com/website/goindigo.in/#overview
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

2023-08-10 15:41 UTC, adamrusted requested changes

2023-08-10 15:41 UTC, adamrusted commented on _data/simple-icons.json
> +            "hex": "FFFFFF",
```suggestion
            "hex": "09009B",
```

2023-08-12 06:25 UTC, CodeWithShipraJain commented on icons/indigo.svg
@adamrusted yes it is caused due to SVGO precision, I have updated the image with precision value 4.

2023-09-03 09:02 UTC, adamrusted commented on _data/simple-icons.json
> +            "hex": "FFFFFF",
Happy with the SVG now, but I'd still go with the hex change suggested here. Once that's done - we can get this merged!

2023-09-09 08:08 UTC, adamrusted approved these changes
LGTM! Thanks @CodeWithShipraJain 🎉

2023-09-09 08:16 UTC, merged