Add ericsson
simple-icons/simple-icons pull request #9173
Opened 2023-07-31 06:19 UTC by PratyushJayachandran

![ericsson](https://github.com/simple-icons/simple-icons/assets/35000807/08856075-1afc-4655-9812-e4daddd3b4ce)

**Issue:** closes #5915 

**Similarweb rank:** 41,230. See https://www.similarweb.com/website/ericsson.com

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
SVG: Taken from brand resource kit available [here](https://mediabank.ericsson.net/admin/mb/?h=dbeb87a1bcb16fa379c0020bdf713872) in the section Ericsson Logotype and Econ. I took this file `171115_ericsson_logo\_Digital\Econ\Black\SVG\ECON_RGB.svg`
Color: Taken from logo which is also mentioned in [Ericsson Brand Guidelines - Extract from Ericsson Brand House v.2.0](https://mediabank.ericsson.net/admin/mb/?h=dbeb87a1bcb16fa379c0020bdf713872) as to be `#000000`

2023-08-15 19:47 UTC, adamrusted requested changes
Just the change to the hex (guidelines state the icon should only be shown in black on a light background, or white on a darker background, but this is the brand colour) and this is good to go. Icon is a perfect match.

2023-08-15 19:47 UTC, adamrusted commented on _data/simple-icons.json
> +            "hex": "000000",
The below is described as 'Ericsson Blue'.

```suggestion
            "hex": "0082F00",
```

2023-08-16 00:09 UTC, PratyushJayachandran commented
> Just the change to the hex (guidelines state the icon should only be shown in black on a light background, or white on a darker background, but this is the brand colour) and this is good to go. Icon is a perfect match.

Ya I was confused about this. I committed your suggestion.

2023-08-16 09:12 UTC, adamrusted commented on _data/simple-icons.json
> +            "hex": "0082f0",
```suggestion
            "hex": "0082F0",
```

Needs to be uppercase to keep the linter happy, apologies for the additional 0 in my original review...

2023-08-16 09:17 UTC, merged