Added Scribus icon #8722
simple-icons/simple-icons pull request #9184
Opened 2023-07-31 20:16 UTC by PixelWelt

2023-07-31 20:24 UTC, PixelWelt reviewed
really fixed alphabetical order

2023-08-01 07:52 UTC, PratyushJayachandran requested changes
The project only accepts single line SVG optimized to follow a uniform format. The icons should also be monochromatic. Please have a look at https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md and give it another go. Since the source icon has a lot of details and colors, some modification will need to be done to make it look good in monochromatic use.

2023-08-15 18:17 UTC, adamrusted requested changes
I've found an official source through that original Wikipedia source. Would you be able to regenerate following [contribution guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and using the SVG found there?

2023-08-15 18:17 UTC, adamrusted commented on _data/simple-icons.json
> +            "source": "https://commons.wikimedia.org/wiki/File:Scribus_logo.svg"
```suggestion
            "source": "https://wiki.scribus.net/canvas/Promotion_material"
```

2023-11-21 10:55 UTC, PeterShaggyNoble commented
There's now an [SVG](http://linux.hanski.info/static/scribus_promotion/scribus-icon2.svg) provided at [the original source](https://wiki.scribus.net/canvas/Promotion_material) so we should use that. We'll need to decide on a monochrome treatment first, though. One possible, and _very_ rough, option would be:

![Scribus](https://github.com/simple-icons/simple-icons/assets/15157491/974bef9f-4f23-4e1e-9933-7cfef8ead2f4)

2023-12-08 12:49 UTC, PeterShaggyNoble commented
Closing due to lack of activity. @PixelWelt, if you would like to continue working on this then we can re-open this PR for you. If anyone else would like to take it on then please open a new PR.

2023-12-08 12:49 UTC, closed without merging