Astro
simple-icons/simple-icons pull request #9201
Opened 2023-08-02 20:28 UTC by natemoo-re

![Preview of updated Astro logo](https://github.com/simple-icons/simple-icons/assets/7118177/de551033-9d28-4048-adb0-bb49909e8b3a)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

- Astro rebranded and launched a new version of https://astro.build featuring an updated logo and brand color.
- Hex value is Astro's official accent color

2023-08-02 20:42 UTC, natemoo-re commented
I will get those lint errors fixed as soon as I can 👍🏻

2023-08-05 06:39 UTC, PratyushJayachandran requested changes

2023-08-05 06:39 UTC, PratyushJayachandran commented on icons/astro.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Astro</title><path d="M8.352 20.029c-1.178-1.062-1.521-3.294-1.03-4.91.85 1.018 2.029 1.341 3.25 1.524 1.884.281 3.735.17
```suggestion
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Astro</title><path d="M8.358 20.162c-1.186-1.07-1.532-3.316-1.038-4.944.856 1.026 2.043 1.352 3.272 1.535 1.897.283 3.76.177 5.522-.678.202-.098.388-.229.608-.36.166.473.209.95.151 1.437-.14 1.185-.738 2.1-1.688 2.794-.38.277-.782.525-1.175.787-1.205.804-1.531 1.747-1.078 3.119l.044.148a3.158 3.158 0 0 1-1.407-1.188 3.31 3.31 0 0 1-.544-1.815c-.004-.32-.004-.642-.048-.958-.106-.769-.472-1.113-1.161-1.133-.707-.02-1.267.411-1.415 1.09-.012.053-.028.104-.045.165h.002zm-5.961-4.445s3.24-1.575 6.49-1.575l2.451-7.565c.092-.366.36-.614.662-.614.302 0 .57.248.662.614l2.45 7.565c3.85 0 6.491 1.575 6.491 1.575L16.088.727C15.93.285 15.663 0 15.303 0H8.697c-.36 0-.615.285-.784.727l-5.516 14.99z"/></svg>
```
Linting issues should be fixed now.

2023-08-10 14:55 UTC, adamrusted approved these changes
LGTM! Thanks @natemoo-re and @PratyushJayachandran 🎉🎉

2023-08-10 14:56 UTC, merged