Malt
simple-icons/simple-icons pull request #9213
Opened 2023-08-04 22:07 UTC by Ash-Crow

![malt](https://github.com/simple-icons/simple-icons/assets/765956/1cac3a38-16ff-4eff-ac0c-6b4e42f1fe5e)

**Issue:** closes #6361

**Similarweb rank:** 43,313

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
- Icon taken from the previous PR (#6362 ), I just removed the wordmark, adapted the viewport and made the changes asked in the contribution guidelines.
- Color taken directly from the official logo.

2023-08-07 10:32 UTC, Ash-Crow commented
I see that some tests have failed but I don't know how to fix the svg file so that they pass.

2023-08-09 07:16 UTC, PratyushJayachandran requested changes
You may apply the suggestion to fix the issues.

2023-08-09 07:16 UTC, PratyushJayachandran commented on icons/malt.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Malt</title><path d="M12.03 0c-1.978 0-2.72 1.18-2.975 2.488.184.16.367.32.555.507l2.424 2.42 2.464-2.464c.164-.164.335-.
```suggestion
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Malt</title><path d="M20.538 3.463c-1.811-1.812-3.747-.64-4.958.572L4.14 15.476c-1.211 1.211-2.479 3.051-.572 4.957 1.906 1.908 3.746.64 4.957-.571L19.966 8.42c1.211-1.211 2.384-3.147.572-4.958zm-10.93-.469 2.423 2.423 2.465-2.466c.168-.168.338-.324.509-.47C14.747 1.178 14.003 0 12.029 0c-1.977 0-2.72 1.182-2.976 2.488.184.16.368.32.555.506zm4.887 17.995-2.464-2.465-2.422 2.421a9.462 9.462 0 0 1-.549.51C9.338 22.783 10.124 24 12.03 24c1.91 0 2.695-1.223 2.971-2.555-.17-.146-.339-.29-.506-.456zM8.58 8.867H3.91c-1.712 0-3.91.54-3.91 3.101 0 1.912 1.223 2.697 2.556 2.972.158-.182 6.024-6.073 6.024-6.073zm12.933.124c-.148.172-6.027 6.078-6.027 6.078h4.604c1.712 0 3.91-.404 3.91-3.1 0-1.978-1.182-2.72-2.487-2.978zM10.11 7.334l.834-.834-2.42-2.422C7.312 2.868 5.472 1.6 3.565 3.506 2.168 4.904 2.48 6.266 3.22 7.37c.226-.017 6.89-.036 6.89-.036zm3.839 9.268-.837.837 2.466 2.466c1.211 1.211 3.146 2.383 4.958.572 1.351-1.352 1.041-2.772.294-3.909-.24.017-6.881.034-6.881.034z"/></svg>
```
This should fix the issues.

2023-08-09 09:05 UTC, Ash-Crow commented
> You may apply the suggestion to fix the issues.

Thanks! It seems like it worked. Can you please explain what was the problem and how you fixed it?

2023-09-03 09:03 UTC, adamrusted commented
Given no feedback, happy for you to make a call on this, @Ash-Crow.
We can either add the full logo with the wordmark, contact them directly and ask for permission to just user the icon, or shut this PR down and I'll mark the issue as `won't add`.

2023-11-21 12:18 UTC, PeterShaggyNoble commented
I agree with @adamrusted's interpretation of their guidelines; that we _can't_ use the icon on its own. This is backed up by the fact that they only make the full logo available for download in their media kit. I've always been of the opinion that, as an _icon_ library, we shouldn't have any logos in our collection. But I'm in the minority on that and the precedent has long since been set! 😆

@Ash-Crow, could you update this PR to use the full logo, please?

2023-12-08 12:39 UTC, PeterShaggyNoble commented
Are you still working on this one, @Ash-Crow?

2023-12-11 08:46 UTC, Ash-Crow commented
The previous task had been closed because the contributor used the full wordmark and was asked to just put the logo...

I'll try to contact Malt first, if that's ok with you.

2024-01-11 11:59 UTC, PeterShaggyNoble commented
Have you has a response from them, @Ash-Crow?

2024-03-15 12:32 UTC, service-paradis approved these changes

2024-03-15 12:32 UTC, merged