Add Rumble Icon
simple-icons/simple-icons pull request #9216
Opened 2023-08-05 18:28 UTC by RiteshK-611

**Issue:** closes #9214

**Similarweb rank:**
The Similarweb site for Rumble is https://www.similarweb.com/website/rumble.com/

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

### Preview
![rumble](https://github.com/simple-icons/simple-icons/assets/61982298/562782d2-a684-46e1-b85c-df12f06cdd15)

2023-08-09 07:24 UTC, PratyushJayachandran requested changes

2023-08-12 17:21 UTC, PratyushJayachandran approved these changes
Seems good 😊

2023-08-12 17:30 UTC, RiteshK-611 commented
> Seems good 😊

Then who is gonna Merge it?

2023-08-12 17:55 UTC, PratyushJayachandran commented
> Then who is gonna Merge it?

I cannot. I don't have permissions😅

2023-08-15 15:07 UTC, RiteshK-611 commented
> > Then who is gonna Merge it?
> 
> I cannot. I don't have permissions😅

No problem 🙂
Can you add reviewer who can merge it?

2023-08-15 19:23 UTC, adamrusted requested changes
Icon itself is spot on, just the one change needed to the hex code to match the one found in the SVG.

2023-08-15 19:23 UTC, adamrusted commented on _data/simple-icons.json
> +            "hex": "74CC1D",
```suggestion
            "hex": "85C742",
```

2023-08-17 18:28 UTC, adamrusted approved these changes
LGTM! Thanks @RiteshK-611 🎉

2023-08-17 18:29 UTC, merged