Add Frappe and ERPNext icons
simple-icons/simple-icons pull request #9245
Opened 2023-08-09 08:12 UTC by walstanb

![erpnext](https://github.com/simple-icons/simple-icons/assets/38958184/ba3128bb-7527-4a3a-89ed-7136641202b7)

![frappe](https://github.com/simple-icons/simple-icons/assets/38958184/6ae64631-def6-434e-86e9-edc4833ab9ee)

**Issue:** closes #9242 and #9243 

**Similarweb rank:**
ERPNext: **93,718** See: https://www.similarweb.com/website/erpnext.com/#overview
Frappe: **480,000** See: https://www.similarweb.com/website/frappe.io/#overview

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
 * Extracted the logo from[ Frappe](https://raw.githubusercontent.com/frappe/frappe/59e1db7bb58e155744f9a2e7912fd233f9fac981/frappe/public/images/frappe-framework-logo.svg) & [ERPNext](https://raw.githubusercontent.com/frappe/erpnext/c1dd06065b6d1aad97d909362a7d71a39fd99608/erpnext/public/images/erpnext-logo.svg) Github Repos
 * Color: Taken from logo `#0089FF`

2023-08-15 19:54 UTC, adamrusted requested changes

2023-08-15 19:54 UTC, adamrusted commented on _data/simple-icons.json
> +            "source": "https://raw.githubusercontent.com/frappe/erpnext/c1dd06065b6d1aad97d909362a7d71a39fd99608/erpnext/public/images/erpnext-logo.svg"
```suggestion
            "source": "https://github.com/frappe/erpnext/blob/924911e74317f95a59f29e9410d4f141020a0411/erpnext/public/images/erpnext-logo.svg"
```

2023-08-15 19:54 UTC, adamrusted commented on _data/simple-icons.json
> +            "source": "https://raw.githubusercontent.com/frappe/frappe/59e1db7bb58e155744f9a2e7912fd233f9fac981/frappe/public/images/frappe-framework-logo.svg"
```suggestion
            "source": "https://github.com/frappe/frappe/blob/1331fa6f721122805d15894fa3bd9eb90dccdca2/frappe/public/images/frappe-framework-logo.svg"
```

2023-08-15 19:54 UTC, adamrusted commented on icons/erpnext.svg
Spotting [some slight differences](https://github.com/simple-icons/simple-icons/assets/1830867/2eaed456-84bf-4e33-8a25-9009812e9f8e) with the source in blue, and the PR in black. Looks like you've optimised this to 1 decimal of precision. Could you regenerate to 3 please? 🙏

2023-08-15 19:54 UTC, adamrusted commented on icons/frappe.svg
Same as with ERPNext, I'm seeing [minor differences](https://github.com/simple-icons/simple-icons/assets/1830867/f10710d2-e3c0-4d9e-b0ac-a377e9cf31c9). Again, seems to be down to the icon being saved with only one decimal of precision.

2023-11-21 11:42 UTC, PeterShaggyNoble commented
Any update on these, @walstanb?

2023-12-08 12:34 UTC, PeterShaggyNoble submitted a review, later dismissed

2023-12-08 12:34 UTC, PeterShaggyNoble commented on icons/erpnext.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>ERPNext</title><path d="M0 2.9C0 1.3 1.3 0 2.9 0h18.2C22.7 0 24 1.3 24 2.9v18.2c0 1.6-1.3 2.9-2.9 2.9H2.9C1.3 24 0 22.7 0
```suggestion
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>ERPNext</title><path d="M2.88 0C1.29 0 0 1.29 0 2.88v18.24C0 22.71 1.29 24 2.88 24h18.24c1.59 0 2.88-1.29 2.88-2.88V2.88C24 1.29 22.71 0 21.12 0Zm5.04 5.76h8.254v2.146H7.92Zm0 5.033h7.85v2.146h-5.233v2.954h5.703v2.146H7.92Z"/></svg>
```

2023-12-08 12:34 UTC, PeterShaggyNoble commented on icons/frappe.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Frappe</title><path d="M0 2.9C0 1.3 1.3 0 2.9 0h18.2C22.7 0 24 1.3 24 2.9v18.2c0 1.6-1.3 2.9-2.9 2.9H2.9C1.3 24 0 22.7 0
```suggestion
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Frappe</title><path d="M2.88 0C1.29 0 0 1.29 0 2.88v18.24C0 22.71 1.29 24 2.88 24h18.24c1.59 0 2.88-1.29 2.88-2.88V2.88C24 1.29 22.71 0 21.12 0H2.88zM8.4 6h8.024v2.111H8.4V6zm0 5.385h7.49v2.113h-4.93V18H8.4v-6.615z"/></svg>
```

2023-12-12 12:51 UTC, adamrusted approved these changes

2023-12-12 12:53 UTC, merged

2023-12-12 14:14 UTC, walstanb commented
Thanks @PeterShaggyNoble I wasn't getting a chance to make changes.