Add Hugging Face
simple-icons/simple-icons pull request #9259
Opened 2023-08-11 07:59 UTC by PratyushJayachandran

![huggingface](https://github.com/simple-icons/simple-icons/assets/35000807/3eb9f5f1-4338-41a2-8c22-7cb85bb443a2)

**Issue:** closes #9256 

**Similarweb rank:** 2,302. See https://www.similarweb.com/website/huggingface.co

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
SVG: Taken from https://huggingface.co/brand
Color Taken from major color in logo `#FFD21E`

2023-08-11 10:12 UTC, TheProjectsGuy commented
Had opened https://github.com/simple-icons/simple-icons/issues/9256 and just noticed this 😅

2023-08-11 14:53 UTC, PratyushJayachandran commented
> Had opened #9256 and just noticed this 😅

Whoops. Sorry for jumping the gun. I read "I request the square icon" and thought you want someone to contribute

2023-09-03 09:05 UTC, adamrusted requested changes
Happy with this treatment, though the SVG path should fill the 24x24 viewbox. Could you update this one please @PratyushJayachandran? 🙏

2023-09-06 07:11 UTC, adamrusted reviewed
I'm happy with this interpretation, though there are a _lot_ of excess points to the paths.
Not our responsibility to fix, but might save us some file size if you're able to remove some of them.
Thoughts, @simple-icons/icon-review?

2023-09-06 08:39 UTC, PratyushJayachandran commented
> I'm happy with this interpretation, though there are a _lot_ of excess points to the paths. ![image](https://user-
> Not our responsibility to fix, but might save us some file size if you're able to remove some of them. Thoughts, @simple-icons/icon-review?

Finding it difficult to auto simplify without losing shape

2023-11-24 12:29 UTC, PeterShaggyNoble commented
Ew! Far too many points! 😆

@PratyushJayachandran, could you give it another go with the [SVG](https://huggingface.co/front/assets/huggingface_logo-noborder.svg) in the website header? It's a little bit cleaner.

2023-11-25 07:15 UTC, PratyushJayachandran commented
> Ew! Far too many points! 😆
> 
> @PratyushJayachandran, could you give it another go with the [SVG](https://huggingface.co/front/assets/huggingface_logo-noborder.svg) in the website header? It's a little bit cleaner.

I redid it from the source you attached and changed the source in JSON

2023-11-25 11:14 UTC, adamrusted requested changes
Hey @PratyushJayachandran - I'm seeing some differences between the header icon and your PR, potentially just a precision thing?

![image](https://github.com/simple-icons/simple-icons/assets/1830867/9f5cea57-7d23-46b0-9cd7-af96d4716c1b)

2023-11-26 02:33 UTC, PratyushJayachandran commented
> Hey @PratyushJayachandran - I'm seeing some differences between the header icon and your PR, potentially just a precision thing?

I upped the precision, please take another look

2023-12-18 09:53 UTC, PratyushJayachandran commented
I redid the icon but I am somehow ending up with a lot of points on the mouth part. I tried to do it in different ways but my program always produces those excess points.
@adamrusted @PeterShaggyNoble

2024-01-08 16:44 UTC, PeterShaggyNoble commented
Your current version lines up perfectly with the source, @PratyushJayachandran; nice work.

Had a go at cleaning up some of the excess points and cam up with the below. Damn near drove me blind so it'll need to be optimised and compared with the original again.

```
M 11.931641,0.91601562C 6.0950521,0.91601563 1.3632812,5.6477866 1.3632812,11.484375a 10.5596,10.5596 0 0 0 0.4824219,3.158203c -0.004,0 -0.00967,10e-5 -0.013672,0 -0.422699,0 -0.8042192,0.161325 -1.0742187,0.453125a 1.5818,1.5818 0 0 0 -0.21679688,1.908203 1.4458,1.4458 0 0 0 -0.48828125,0.769532 1.5949,1.5949 0 0 0 0.21679688,1.292968 1.4235,1.4235 0 0 0 -0.0996094,1.369141c 0.27809944,0.632598 0.97226822,1.129564 2.32226562,1.664062 0.8371984,0.3327 1.6077813,0.544075 1.6132813,0.546875a 12.0915,12.0915 0 0 0 2.9804687,0.4375c 1.4278972,0 2.4906239,-0.394017 3.1699215,-1.166015 0.546,0.0872 1.105282,0.134765 1.675782,0.134765 0.612298,0 1.211223,-0.0543 1.794921,-0.154296 0.6785,0.785098 1.747504,1.185546 3.1875,1.185546a 12.0915,12.0915 0 0 0 2.980469,-0.4375c 0.0055,-0.0028 0.775235,-0.214175 1.615235,-0.546875 1.347296,-0.534598 2.042212,-1.031364 2.320312,-1.664062 0.2031,-0.4435 0.166389,-0.960141 -0.09961,-1.369141 0.349198,-0.528998 0.282197,-1.04747 0.216797,-1.292968 -0.0749,-0.3019 -0.243977,-0.572032 -0.484375,-0.769532a 1.5818,1.5818 0 0 0 -0.21875,-1.908203c -0.27,-0.2918 -0.651521,-0.453125 -1.074219,-0.453125a 1.9273,1.9273 0 0 0 -0.154297,0.0098C 22.329525,13.652546 22.5,12.587773 22.5,11.484375 22.5,5.6477866 17.768229,0.91601562 11.931641,0.91601562Zm 0,1.09179688c 5.233994,0 9.476562,4.2425677 9.476562,9.4765625a 9.4964,9.4964 0 0 1 -0.236328,2.103516c -0.265,-0.2585 -0.61686,-0.398438 -1.005859,-0.398438a 2.0187,2.0187 0 0 0 -1.080078,0.345703c -0.2427,0.1555 -0.510504,0.425932 -0.783204,0.769532 -0.285299,-0.4131 -0.751906,-0.663876 -1.253906,-0.671876 -0.929999,1e-6 -1.490425,0.807804 -1.703125,1.533204 -0.1036,0.245399 -0.607035,1.361041 -1.365234,2.11914 -1.151699,1.149499 -1.441506,2.33627 -0.878907,3.605469 -0.382999,0.0473 -0.774122,0.07031 -1.169921,0.07031 -0.3511,0 -0.697863,-0.01934 -1.039063,-0.05664 0.5714,-1.274799 0.283052,-2.465342 -0.873047,-3.619141C 9.2641322,16.527057 8.7599499,15.411415 8.65625,15.166016 8.4435502,14.440616 7.8811709,13.632812 6.9511719,13.632812A 1.5545,1.5545 0 0 0 5.6972656,14.304688C 5.4245659,13.961088 5.1579685,13.690656 4.9179688,13.535156A 2.0186,2.0186 0 0 0 3.8339844,13.189453c -0.4417996,0 -0.8339753,0.179766 -1.109375,0.509766 -0.002,0.0025 -0.00386,0.0053 -0.00586,0.0078 -0.1713998,-0.712999 -0.2636719,-1.457057 -0.2636719,-2.222656 0,-5.2339948 4.242568,-9.4765625 9.4765629,-9.4765625zM 3.8339844,14.279297c 0.1390996,0 0.3125472,0.06053 0.4980468,0.177734 0.583599,0.371 1.7034352,2.29883 2.1152344,3.048828 0.1362998,0.2509 0.3739848,0.357422 0.5839844,0.357422 0.4226992,0 0.7501142,-0.417419 0.041016,-0.949219 -1.0690978,-0.798998 -0.6955458,-2.104493 -0.1855468,-2.183593 0.0218,-0.0054 0.045353,-0.0059 0.064453,-0.0059 0.4635989,0 0.6679687,0.798828 0.6679687,0.798829 0,0 0.6018147,1.506111 1.6328125,2.537109 0.9322979,0.932298 1.0604779,1.698046 0.5175781,2.652344 -0.037663,0.06633 -0.1561173,0.274817 -0.2753906,0.419921 -0.5500127,0.672458 -1.5159813,0.857422 -2.4082031,0.857422 -1.0390978,0 -2.1077793,-0.245637 -2.7050781,-0.398437 -0.03,-0.0082 -3.66793037,-1.037458 -3.2070313,-1.910156 0.0764,-0.1473 0.2043348,-0.207032 0.3652344,-0.207032 0.6490988,0 1.8259385,0.966797 2.3359375,0.966797 0.1117998,0 0.1911625,-0.04676 0.2265625,-0.164062 0.2154996,-0.777198 -3.28874011,-1.104818 -2.9941406,-2.228516 0.0545,-0.199 0.1934785,-0.277344 0.3925781,-0.277344 0.8562981,0 2.7819477,1.507813 3.1855469,1.507813 0.047367,0 0.060785,-0.01386 0.087891,-0.06641 0.1203242,-0.219968 0.065286,-0.400229 -0.4140625,-0.761719 -0.1318147,-0.09907 -0.3067954,-0.21711 -0.3183594,-0.22461 -0.2228675,-0.147872 -0.4525113,-0.28712 -0.6269531,-0.392578 -1.4208972,-0.861798 -2.42081457,-1.381 -1.8535156,-2 0.1637084,-0.177725 0.4803819,-0.09538 0.7441406,0.01563v 0.002c 0.9037164,0.380891 2.1643585,1.493232 2.4355469,1.738282 0,0 0.5512196,0.574218 0.8867187,0.574218 0.0763,0 0.1418469,-0.02722 0.1855469,-0.103515 0.2343996,-0.3982 -2.1995377,-2.242908 -2.3359375,-3.003906 -0.0927,-0.5182 0.065523,-0.777344 0.3574219,-0.777344zm 16.3320316,0c 0.291898,0 0.45012,0.259144 0.357422,0.777344 -0.1364,0.760898 -2.569232,2.605706 -2.332032,3.003906 0.03721,0.06689 0.109077,0.106915 0.185547,0.103515 0.1503,10e-7 0.343419,-0.118093 0.511719,-0.246093l 0.0039,-0.002c 0.128597,-0.113961 0.267164,-0.215817 0.384766,-0.341797 0.705972,-0.601607 1.417423,-1.210875 2.24414,-1.642578 0.247,-0.1228 0.471838,-0.201172 0.648438,-0.201172 0.1118,0 0.204878,0.03252 0.267578,0.103515 0.572698,0.619 -0.429171,1.138202 -1.855469,2 -0.778198,0.4711 -1.161759,0.752544 -1.318359,0.964844 -0.02865,0.06343 -0.08527,0.117426 -0.08594,0.191406 -0.01304,0.09338 0.02174,0.165563 0.02344,0.164063 0.01411,0.03366 0.03135,0.06676 0.05078,0.09766 0.0109,0.0191 0.0353,0.02734 0.0625,0.02734 0.4037,0 2.329249,-1.507813 3.185547,-1.507813 0.2019,0 0.340778,0.07824 0.392578,0.277344 0.2946,1.123598 -3.210387,1.451318 -2.992187,2.228516 0.0327,0.1173 0.112062,0.164062 0.226562,0.164062 0.5073,0 1.688891,-0.966797 2.337891,-0.966797 0.1609,0 0.286234,0.05973 0.365234,0.207032 0.4609,0.872698 -3.179831,1.901956 -3.207031,1.910156 -0.6001,0.1528 -1.667287,0.398437 -2.708985,0.398437 -0.715429,0 -1.609664,-0.121609 -2.193359,-0.636718 -0.06017,-0.06077 -0.125347,-0.117124 -0.179687,-0.183594 -0.184798,-0.21596 -0.321372,-0.487728 -0.326172,-0.486328 -0.5253,-0.940598 -0.388089,-1.700349 0.537109,-2.623047 1.028098,-1.030898 1.628906,-2.53711 1.628906,-2.537109 0,0 0.204371,-0.798829 0.667969,-0.798829 0.02191,1e-4 0.04282,0.0024 0.06445,0.0059 0.51,0.0791 0.884758,1.384495 -0.18164,2.183593 -0.7118,0.5317 -0.382891,0.949219 0.03711,0.949219 0.245733,-0.0017 0.470743,-0.13933 0.583984,-0.357422 0.4118,-0.749998 1.536388,-2.677828 2.117188,-3.048828 0.1882,-0.1172 0.357094,-0.177734 0.496094,-0.177734zM 8.3789062,6.9882812C 7.8952043,6.9929307 7.4283717,7.2556348 7.1855469,7.7128906 6.8324473,8.37809 7.0867537,9.203441 7.7519531,9.5566406 8.1009527,9.7420404 8.2386911,9.028203 8.5878906,8.9082031l -0.00195,-0.00391C 8.8969372,8.795197 9.4273502,9.3058872 9.59375,8.9921875H 9.5957C 9.9488028,8.3268882 9.6944962,7.5016371 9.0292969,7.1484375 8.8214221,7.0380626 8.5987708,6.9861678 8.3789062,6.9882812Zm 6.7753908,0c -0.198359,0.00774 -0.396925,0.060875 -0.583985,0.1601563 -0.665199,0.3531996 -0.919605,1.1784507 -0.566406,1.84375 0.1663,0.3136997 0.696166,-0.1969905 1.009766,-0.087891l -0.002,0.00391c 0.348999,0.1199999 0.484138,0.8338373 0.835937,0.6484375 0.6652,-0.3531996 0.919506,-1.1785506 0.566406,-1.84375C 16.1602,7.2348505 15.661215,6.9685133 15.154297,6.9882812ZM 18.340854,10.1891a 0.8864,0.8864 0 1 0 0,-1.7727 0.8864,0.8864 0 0 0 0,1.7727zM 5.6592542,8.4164a 0.8864,0.8864 0 1 0 0,1.7727 0.8864,0.8864 0 0 0 0,-1.7727zm 8.0772998,5.922a 2.346,2.346 0 0 0 -1.082,-0.7239c -0.1172,-0.0355 -0.2373,0.15 -0.36,0.3409 -0.1173,0.1827 -0.24,0.3682 -0.3627,0.3682 -0.1145,0 -0.229,-0.1882 -0.3382,-0.3736 -0.1172,-0.1937 -0.229,-0.3819 -0.3381,-0.3491a 2.3722,2.3722 0 0 0 -1.1783,0.8016c 0.44,0.3271 1.022,0.5472 1.788,0.5475 0.815,-4e-4 1.4223,-0.2493 1.8713,-0.6116zm -1.8715,1.1116c -0.8631,-4e-4 -1.5368,-0.2485 -2.0547998,-0.625 -0.5492865,-0.379527 -0.8947936,-0.963314 -1.0180001,-1.1971 -0.335,-0.633 -0.474,-1.3057 -0.474,-1.7943 0,-0.140186 0.012056,-0.4162 0.2717,-0.4162l 0.0017,-2e-4 0.0033,2e-4c 0.4349357,0.0054 1.2588687,0.643209 2.3317999,0.9329 0.09412,0.02868 0.456497,0.112538 0.7833,0.1281 0.09574,0.0082 0.313113,0.0036 0.4968,-0.0142 0.153973,-0.01309 0.452008,-0.0757 0.5185,-0.0939 1.0177,-0.249608 1.833679,-0.854978 2.3205,-0.9432 0.286876,-0.053 0.337318,0.147408 0.3542,0.2713 0.01896,0.09064 0.0223,0.57192 -0.1513,1.1609 -0.04264,0.1609 -0.168714,0.507656 -0.3348,0.8129 [...]

2024-01-10 07:17 UTC, PratyushJayachandran commented
> Your current version lines up perfectly with the source, @PratyushJayachandran; nice work.
> 
> Had a go at cleaning up some of the excess points and cam up with the below. Damn near drove me blind so it'll need to be optimised and compared with the original again.
> 
> ```
> M 11.931641,0.91601562C 6.0950521,0.91601563 1.3632812,5.6477866 1.3632812,11.484375a 10.5596,10.5596 0 0 0 0.4824219,3.158203c -0.004,0 -0.00967,10e-5 -0.013672,0 -0.422699,0 -0.8042192,0.161325 -1.0742187,0.453125a 1.5818,1.5818 0 0 0 -0.21679688,1.908203 1.4458,1.4458 0 0 0 -0.48828125,0.769532 1.5949,1.5949 0 0 0 0.21679688,1.292968 1.4235,1.4235 0 0 0 -0.0996094,1.369141c 0.27809944,0.632598 0.97226822,1.129564 2.32226562,1.664062 0.8371984,0.3327 1.6077813,0.544075 1.6132813,0.546875a 12.0915,12.0915 0 0 0 2.9804687,0.4375c 1.4278972,0 2.4906239,-0.394017 3.1699215,-1.166015 0.546,0.0872 1.105282,0.134765 1.675782,0.134765 0.612298,0 1.211223,-0.0543 1.794921,-0.154296 0.6785,0.785098 1.747504,1.185546 3.1875,1.185546a 12.0915,12.0915 0 0 0 2.980469,-0.4375c 0.0055,-0.0028 0.775235,-0.214175 1.615235,-0.546875 1.347296,-0.534598 2.042212,-1.031364 2.320312,-1.664062 0.2031,-0.4435 0.166389,-0.960141 -0.09961,-1.369141 0.349198,-0.528998 0.282197,-1.04747 0.216797,-1.292968 -0.0749,-0.3019 -0.243977,-0.572032 -0.484375,-0.769532a 1.5818,1.5818 0 0 0 -0.21875,-1.908203c -0.27,-0.2918 -0.651521,-0.453125 -1.074219,-0.453125a 1.9273,1.9273 0 0 0 -0.154297,0.0098C 22.329525,13.652546 22.5,12.587773 22.5,11.484375 22.5,5.6477866 17.768229,0.91601562 11.931641,0.91601562Zm 0,1.09179688c 5.233994,0 9.476562,4.2425677 9.476562,9.4765625a 9.4964,9.4964 0 0 1 -0.236328,2.103516c -0.265,-0.2585 -0.61686,-0.398438 -1.005859,-0.398438a 2.0187,2.0187 0 0 0 -1.080078,0.345703c -0.2427,0.1555 -0.510504,0.425932 -0.783204,0.769532 -0.285299,-0.4131 -0.751906,-0.663876 -1.253906,-0.671876 -0.929999,1e-6 -1.490425,0.807804 -1.703125,1.533204 -0.1036,0.245399 -0.607035,1.361041 -1.365234,2.11914 -1.151699,1.149499 -1.441506,2.33627 -0.878907,3.605469 -0.382999,0.0473 -0.774122,0.07031 -1.169921,0.07031 -0.3511,0 -0.697863,-0.01934 -1.039063,-0.05664 0.5714,-1.274799 0.283052,-2.465342 -0.873047,-3.619141C 9.2641322,16.527057 8.7599499,15.411415 8.65625,15.166016 8.4435502,14.440616 7.8811709,13.632812 6.9511719,13.632812A 1.5545,1.5545 0 0 0 5.6972656,14.304688C 5.4245659,13.961088 5.1579685,13.690656 4.9179688,13.535156A 2.0186,2.0186 0 0 0 3.8339844,13.189453c -0.4417996,0 -0.8339753,0.179766 -1.109375,0.509766 -0.002,0.0025 -0.00386,0.0053 -0.00586,0.0078 -0.1713998,-0.712999 -0.2636719,-1.457057 -0.2636719,-2.222656 0,-5.2339948 4.242568,-9.4765625 9.4765629,-9.4765625zM 3.8339844,14.279297c 0.1390996,0 0.3125472,0.06053 0.4980468,0.177734 0.583599,0.371 1.7034352,2.29883 2.1152344,3.048828 0.1362998,0.2509 0.3739848,0.357422 0.5839844,0.357422 0.4226992,0 0.7501142,-0.417419 0.041016,-0.949219 -1.0690978,-0.798998 -0.6955458,-2.104493 -0.1855468,-2.183593 0.0218,-0.0054 0.045353,-0.0059 0.064453,-0.0059 0.4635989,0 0.6679687,0.798828 0.6679687,0.798829 0,0 0.6018147,1.506111 1.6328125,2.537109 0.9322979,0.932298 1.0604779,1.698046 0.5175781,2.652344 -0.037663,0.06633 -0.1561173,0.274817 -0.2753906,0.419921 -0.5500127,0.672458 -1.5159813,0.857422 -2.4082031,0.857422 -1.0390978,0 -2.1077793,-0.245637 -2.7050781,-0.398437 -0.03,-0.0082 -3.66793037,-1.037458 -3.2070313,-1.910156 0.0764,-0.1473 0.2043348,-0.207032 0.3652344,-0.207032 0.6490988,0 1.8259385,0.966797 2.3359375,0.966797 0.1117998,0 0.1911625,-0.04676 0.2265625,-0.164062 0.2154996,-0.777198 -3.28874011,-1.104818 -2.9941406,-2.228516 0.0545,-0.199 0.1934785,-0.277344 0.3925781,-0.277344 0.8562981,0 2.7819477,1.507813 3.1855469,1.507813 0.047367,0 0.060785,-0.01386 0.087891,-0.06641 0.1203242,-0.219968 0.065286,-0.400229 -0.4140625,-0.761719 -0.1318147,-0.09907 -0.3067954,-0.21711 -0.3183594,-0.22461 -0.2228675,-0.147872 -0.4525113,-0.28712 -0.6269531,-0.392578 -1.4208972,-0.861798 -2.42081457,-1.381 -1.8535156,-2 0.1637084,-0.177725 0.4803819,-0.09538 0.7441406,0.01563v 0.002c 0.9037164,0.380891 2.1643585,1.493232 2.4355469,1.738282 0,0 0.5512196,0.574218 0.8867187,0.574218 0.0763,0 0.1418469,-0.02722 0.1855469,-0.103515 0.2343996,-0.3982 -2.1995377,-2.242908 -2.3359375,-3.003906 -0.0927,-0.5182 0.065523,-0.777344 0.3574219,-0.777344zm 16.3320316,0c 0.291898,0 0.45012,0.259144 0.357422,0.777344 -0.1364,0.760898 -2.569232,2.605706 -2.332032,3.003906 0.03721,0.06689 0.109077,0.106915 0.185547,0.103515 0.1503,10e-7 0.343419,-0.118093 0.511719,-0.246093l 0.0039,-0.002c 0.128597,-0.113961 0.267164,-0.215817 0.384766,-0.341797 0.705972,-0.601607 1.417423,-1.210875 2.24414,-1.642578 0.247,-0.1228 0.471838,-0.201172 0.648438,-0.201172 0.1118,0 0.204878,0.03252 0.267578,0.103515 0.572698,0.619 -0.429171,1.138202 -1.855469,2 -0.778198,0.4711 -1.161759,0.752544 -1.318359,0.964844 -0.02865,0.06343 -0.08527,0.117426 -0.08594,0.191406 -0.01304,0.09338 0.02174,0.165563 0.02344,0.164063 0.01411,0.03366 0.03135,0.06676 0.05078,0.09766 0.0109,0.0191 0.0353,0.02734 0.0625,0.02734 0.4037,0 2.329249,-1.507813 3.185547,-1.507813 0.2019,0 0.340778,0.07824 0.392578,0.277344 0.2946,1.123598 -3.210387,1.451318 -2.992187,2.228516 0.0327,0.1173 0.112062,0.164062 0.226562,0.164062 0.5073,0 1.688891,-0.966797 2.337891,-0.966797 0.1609,0 0.286234,0.05973 0.365234,0.207032 0.4609,0.872698 -3.179831,1.901956 -3.207031,1.910156 -0.6001,0.1528 -1.667287,0.398437 -2.708985,0.398437 -0.715429,0 -1.609664,-0.121609 -2.193359,-0.636718 -0.06017,-0.06077 -0.125347,-0.117124 -0.179687,-0.183594 -0.184798,-0.21596 -0.321372,-0.487728 -0.326172,-0.486328 -0.5253,-0.940598 -0.388089,-1.700349 0.537109,-2.623047 1.028098,-1.030898 1.628906,-2.53711 1.628906,-2.537109 0,0 0.204371,-0.798829 0.667969,-0.798829 0.02191,1e-4 0.04282,0.0024 0.06445,0.0059 0.51,0.0791 0.884758,1.384495 -0.18164,2.183593 -0.7118,0.5317 -0.382891,0.949219 0.03711,0.949219 0.245733,-0.0017 0.470743,-0.13933 0.583984,-0.357422 0.4118,-0.749998 1.536388,-2.677828 2.117188,-3.048828 0.1882,-0.1172 0.357094,-0.177734 0.496094,-0.177734zM 8.3789062,6.9882812C 7.8952043,6.9929307 7.4283717,7.2556348 7.1855469,7.7128906 6.8324473,8.37809 7.0867537,9.203441 7.7519531,9.5566406 8.1009527,9.7420404 8.2386911,9.028203 8.5878906,8.9082031l -0.00195,-0.00391C 8.8969372,8.795197 9.4273502,9.3058872 9.59375,8.9921875H 9.5957C 9.9488028,8.3268882 9.6944962,7.5016371 9.0292969,7.1484375 8.8214221,7.0380626 8.5987708,6.9861678 8.3789062,6.9882812Zm 6.7753908,0c -0.198359,0.00774 -0.396925,0.060875 -0.583985,0.1601563 -0.665199,0.3531996 -0.919605,1.1784507 -0.566406,1.84375 0.1663,0.3136997 0.696166,-0.1969905 1.009766,-0.087891l -0.002,0.00391c 0.348999,0.1199999 0.484138,0.8338373 0.835937,0.6484375 0.6652,-0.3531996 0.919506,-1.1785506 0.566406,-1.84375C 16.1602,7.2348505 15.661215,6.9685133 15.154297,6.9882812ZM 18.340854,10.1891a 0.8864,0.8864 0 1 0 0,-1.7727 0.8864,0.8864 0 0 0 0,1.7727zM 5.6592542,8.4164a 0.8864,0.8864 0 1 0 0,1.7727 0.8864,0.8864 0 0 0 0,-1.7727zm 8.0772998,5.922a 2.346,2.346 0 0 0 -1.082,-0.7239c -0.1172,-0.0355 -0.2373,0.15 -0.36,0.3409 -0.1173,0.1827 -0.24,0.3682 -0.3627,0.3682 -0.1145,0 -0.229,-0.1882 -0.3382,-0.3736 -0.1172,-0.1937 -0.229,-0.3819 -0.3381,-0.3491a 2.3722,2.3722 0 0 0 -1.1783,0.8016c 0.44,0.3271 1.022,0.5472 1.788,0.5475 0.815,-4e-4 1.4223,-0.2493 1.8713,-0.6116zm -1.8715,1.1116c -0.8631,-4e-4 -1.5368,-0.2485 -2.0547998,-0.625 -0.5492865,-0.379527 -0.8947936,-0.963314 -1.0180001,-1.1971 -0.335,-0.633 -0.474,-1.3057 -0.474,-1.7943 0,-0.140186 0.012056,-0.4162 0.2717,-0.4162l 0.0017,-2e-4 0.0033,2e-4c 0.4349357,0.0054 1.2588687,0.643209 2.3317999,0.9329 0.09412,0.02868 0.456497,0.112538 0.7833,0.1281 0.09574,0.0082 0.313113,0.0036 0.4968,-0.0142 0.153973,-0.01309 0.452008,-0.0757 0.5185,-0.0939 1.0177,-0.249608 1.833679,-0.854978 2.3205,-0.9432 0.286876,-0.053 0.337318,0.147408 0.3542,0.2713 0.01896,0.09064 0.0223,0.57192 -0.1513,1.1609 -0.04264,0.1609 -0.168714,0.507656 -0 [...]

2024-03-21 10:01 UTC, adamjstewart commented
Any updates on this? Would love to see this merged.

2024-03-21 12:21 UTC, PeterShaggyNoble commented
Updated the icon based on the new (almost) monochrome icon @adamjstewart pointed out is now available on [their brand page](https://huggingface.co/brand). It's much cleaner than anything we've tried to work off before but still has quite a few excess points and is very fiddly to work with. I did my best to strike a happy medium between removing points and staying as faithful as I could to the source, but there will likely be a few tiny differences as a result, but I'd be happy with that trade-off.

![](https://github.com/simple-icons/simple-icons/assets/15157491/d96f7a0a-ced4-4d3b-af8e-ec3ca603af5e)

2024-03-21 15:58 UTC, PratyushJayachandran commented
@PeterShaggyNoble we should put a stroke on the bottom part of the face like the original preview image on this PR.

2024-03-21 16:40 UTC, PeterShaggyNoble commented
Having now seen their own (almost) monochrome treatment, I no longer think it's necessary. But, if anyone else feels differently then here's an unoptimised path with it included:
```
m13.980469,14.433594c-0.499814,0.328615 -1.132812,0.542636 -1.923828,0.548828 -0.442247,0 -1.214602,-0.07945 -1.925829,-0.546875 -0.2297813,0.100481 -0.2306809,0.100481 -0.1894528,0.365234 0.7594528,0.583186 1.6201798,0.681641 2.1152818,0.681641 0.894269,-0.007 1.587251,-0.277701 2.113281,-0.681641 5.48e-4,-0.358175 5.48e-4,-0.349191 -0.189453,-0.367187zM1.4445855,11.50585c0,1.1021 0.1673,2.1585 0.4847,3.1563 -0.0378,-0.0028 -0.0691,-0.0058 -0.1058,-0.0058 -0.4209,0 -0.8015,0.16 -1.07039997,0.4512 -0.3454,0.3737 -0.4984,0.8335 -0.4316,1.293 0.0302836,0.21178 0.10336788,0.415178 0.2148,0.5978 -0.2319,0.1864 -0.4018,0.4456 -0.4844,0.7578 -0.0646,0.2448 -0.131,0.7543 0.2149,1.2794 -0.0223064,0.03427 -0.0431582,0.06947 -0.0625,0.1055 -0.208,0.3923 -0.2207,0.8372 -0.0371,1.25 0.2783,0.6258 0.96959997,1.1175 2.31259997,1.6467 0.8356,0.3292 1.5988,0.5411 1.6056,0.543 1.1046,0.2847 2.104,0.4277 2.969,0.4277 1.4173,0 2.4754,-0.3849 3.1525005,-1.1446 1.538,0.2651 2.791,0.1403 3.592,0.006 0.6773,0.7555 1.7332,1.1387 3.1467,1.1387 0.8649,0 1.8643,-0.143 2.969,-0.4278 0.0068,-0.0019 0.77,-0.2138 1.6056,-0.543 1.343,-0.5292 2.0343,-1.0208 2.3126,-1.6466 0.1836,-0.4129 0.171,-0.8577 -0.037,-1.25 -0.01939,-0.03606 -0.04027,-0.07129 -0.0626,-0.1056 0.346,-0.525 0.2795,-1.0346 0.2149,-1.2793 -0.0826,-0.3122 -0.2525,-0.5714 -0.4844,-0.7579 0.11,-0.1816 0.1831,-0.3788 0.2148,-0.5977 0.0669,-0.4595 -0.0862,-0.9193 -0.4316,-1.293 -0.2688,-0.2913 -0.6495,-0.4513 -1.0704,-0.4513 -0.0209,0 -0.0376,8e-4 -0.0588,0.0018 0.3162,-0.9966 0.4846,-2.0518 0.4846,-3.1523 0,-5.807 -4.7362,-10.5144 -10.5789,-10.5144 -5.8426005,0 -10.5788005,4.7073 -10.5788005,10.5144zM12.023386,2.02275c5.2727,0 9.5476,4.246 9.5476,9.483 -8.4e-5,0.7536 -0.0906,1.504468 -0.2696,2.2365 -0.184703,-0.22259 -0.54049,-0.5215 -1.1192,-0.5215 -0.352,0 -0.714,0.1155 -1.0763,0.3438 -0.2403,0.1517 -0.5058,0.422 -0.7793,0.7598 -0.2534,-0.3492 -0.608,-0.5832 -1.0137,-0.6465 -0.07756,-0.01192 -0.155929,-0.0178 -0.2344,-0.0176 -0.9263,0 -1.4828,0.7993 -1.6935,1.5177 -0.1046,0.2426 -0.6065,1.3482 -1.3614,2.0978 -1.1681,1.1601 -1.4458,2.3534 -0.8396,3.6382 -0.843,0.1029 -1.5836,0.0927 -2.365,-0.006 0.5906,-1.212 0.3626,-2.4388 -0.8426005,-3.6322 -0.755,-0.7496 -1.2568,-1.8552 -1.3614,-2.0978 -0.2107,-0.7184 -0.7673,-1.5177 -1.6935,-1.5177 -0.078,0 -0.1568,0.0054 -0.2344,0.0176 -0.4057,0.0633 -0.7604,0.2973 -1.0137,0.6465 -0.2735,-0.3379 -0.539,-0.6081 -0.7794,-0.7598 -0.3622,-0.2283 -0.7243,-0.3438 -1.0762,-0.3438 -0.4266,0 -0.8094,0.171 -1.0821,0.4786 -0.1723206,-0.718482 -0.2595199,-1.454742 -0.2598,-2.1936 0,-5.237 4.2749,-9.483 9.5475005,-9.483zm-3.3791005,4.9808c-0.4838,0.0043 -0.9503,0.2667 -1.1934,0.7227 -0.3536,0.6633 -0.1006,1.4873 0.5645,1.84 0.351,0.1862 0.4883,-0.5261 0.836,-0.6485 0.3107,-0.1095 0.841,0.399 1.0078,0.086 0.3536005,-0.6634 0.1025,-1.4874 -0.5625,-1.84 -0.2007392,-0.1068788 -0.4249879,-0.1619441 -0.6524,-0.1602zm6.8403005,0c-0.2199,-0.002 -0.4426,0.05 -0.6504,0.1602 -0.665,0.3526 -0.9181,1.1766 -0.5645,1.84 0.1669,0.313 0.6971,-0.1955 1.0079,-0.086 0.3476,0.1224 0.4867,0.8347 0.838,0.6485 0.6649,-0.3527 0.916,-1.1767 0.5624,-1.84 -0.243,-0.456 -0.7096,-0.7184 -1.1934,-0.7227zm-9.7565005,1.418c-0.4843995,-1.105e-4 -0.8771105,0.3926005 -0.877,0.877 0,0.4846 0.3925,0.877 0.877,0.877 0.4843995,1.11e-4 0.8771105,-0.3926005 0.877,-0.877 1.105e-4,-0.4843995 -0.3926005,-0.8771105 -0.877,-0.877zm12.6434005,0c-0.4845,0 -0.879,0.3925 -0.879,0.877 0,0.4846 0.3945,0.877 0.879,0.877 0.484399,1.11e-4 0.877111,-0.3926005 0.877,-0.877 1.11e-4,-0.4843995 -0.392601,-0.8771105 -0.877,-0.877zm-9.5788005,3.0374c-0.179,-0.003 -0.2793,0.1107 -0.2793,0.416l2.9358005,1.7228c0.2315,0.1167 0.2191,0.4417 0.6074,0.7266 0.3884,-0.285 0.374,-0.6098 0.6056,-0.7266l2.9357,-1.7228c0,-1.2212 -1.583,0.6402 -3.5413,0.6485 -1.4686,-0.0061 -2.7266005,-1.0558 -3.2639005,-1.0645zm-4.4807,3.0178c0.5792,0.365 1.6964,2.2751 2.1056,3.0177 0.1371,0.2488 0.371,0.3536 0.582,0.3536 0.4188,0 0.7465,-0.4138 0.0391,-0.9395 -1.0636,-0.791 -0.6914,-2.0846 -0.1836,-2.1642 0.021997,-0.003 0.044197,-0.0044 0.0664,-0.004 0.4616,0 0.666,0.7892 0.666,0.7892 0,0 0.5959,1.4898 1.6213,2.508 0.9420005,0.9356 1.0620005,1.703 0.4961,2.6661 -0.0164,-0.004 -0.0159,0.0236 -0.1484,0.2149 -0.1853,0.2673 -0.4322,0.4688 -0.7188,0.6152 -0.5062,0.2269 -1.1397,0.2696 -1.7833,0.2696 -1.037,0 -2.1017,-0.1824 -2.6975,-0.336 -0.0293,-0.0075 -3.65049997,-0.9567 -3.1916,-1.8224 0.0771,-0.1454 0.2033,-0.2031 0.3633,-0.2031 0.6463,0 1.823,0.9551 2.3283,0.9551 0.113,0 0.196,-0.0865 0.2285,-0.2031 0.2249,-0.8045 -3.27869997,-1.0522 -2.9846,-2.1642 0.0519,-0.1967 0.193,-0.2757 0.3907,-0.2754 0.854,0 2.7704,1.4923 3.172,1.4923 0.0307,0 0.0525,-0.0085 0.0645,-0.0274 0.2012,-0.3227 0.1096,-0.5865 -1.3087,-1.4395 -1.4182,-0.8533 -2.43149997,-1.329 -1.8653,-1.9416 0.0651,-0.0707 0.1574,-0.1015 0.2695,-0.1015 0.8611,2e-4 2.8948,1.84 2.8948,1.84 0,0 0.5487,0.5683 0.8809,0.5683 0.0762,0 0.1416,-0.0315 0.1855,-0.1054 0.2355,-0.3946 -2.1858,-2.2183 -2.3224,-2.971 -0.0926,-0.51 0.0641,-0.7676 0.3555,-0.7676 -6e-4,0.008 0.1701,-0.0285 0.4942,0.1759zm16.2257005,0.5918c-0.1366,0.7526 -2.5579,2.5764 -2.3224,2.9709 0.044,0.074 0.1092,0.1055 0.1855,0.1055 0.3321,0 0.881,-0.5684 0.881,-0.5684 0,0 2.0336,-1.8397 2.8947,-1.84 0.1121,0 0.2044,0.0308 0.2695,0.1016 0.5662,0.6125 -0.447,1.0882 -1.8653,1.9415 -1.4183,0.853 -1.51,1.1168 -1.3087,1.4396 0.012,0.0188 0.0337,0.0273 0.0644,0.0273 0.4016,0 2.3181,-1.4923 3.1721,-1.4923 0.1977,-2e-4 0.3388,0.0787 0.3907,0.2754 0.294,1.112 -3.2095,1.3597 -2.9846,2.1642 0.0325,0.1166 0.1156,0.2032 0.2285,0.2032 0.5054,0 1.682,-0.9552 2.3283,-0.9552 0.16,0 0.2862,0.0577 0.3633,0.2032 0.459,0.8656 -3.1623,1.8149 -3.1916,1.8224 -0.5958,0.1535 -1.6605,0.336 -2.6975,0.336 -0.6351,0 -1.261,-0.0409 -1.7638,-0.2599 -0.2949,-0.1472 -0.5488,-0.3516 -0.7383,-0.625 -0.0411,-0.0682 -0.1026,-0.1476 -0.1426,-0.205 -0.5726,-0.9679 -0.455,-1.7371 0.4903,-2.676 1.0254,-1.0182 1.6212,-2.508 1.6212,-2.508 0,0 0.2044,-0.7891 0.666,-0.7891 0.02223,-4.14e-4 0.04447,8.9e-4 0.0665,0.0039 0.5078,0.0796 0.88,1.3732 -0.1836,2.1642 -0.7074,0.5257 -0.3797,0.9395 0.039,0.9395 0.211,0 0.445,-0.1047 0.5821,-0.3535 0.4092,-0.7426 1.5264,-2.6527 2.1056,-3.0178 0.5588,-0.3524 0.99,-0.1816 0.8497,0.5918z
```

2024-05-11 16:04 UTC, adamjstewart commented
FWIW, I like it better with the line under the mouth.

2024-05-20 20:07 UTC, adamrusted approved these changes
Happy with this treatment for now, hopefully they release a _truly_ monochrome version of their icon in the near future... Thanks @PratyushJayachandran and @PeterShaggyNoble 🎉

2024-05-20 20:07 UTC, merged

2024-09-17 21:03 UTC, PratyushJayachandran commented
Thank you @julien-c 💯

2024-12-04 16:21 UTC, d-kleine commented
I wanted to express my gratitude for your efforts in implementing the Hugging Face icon! However, I have a small suggestion regarding the current design. While the contours are nicely drawn and colored yellow, I believe it might enhance the visual appeal if we could fill the inside with yellow instead. Additionally, making the eyes, mouth, palms, and cheeks transparent could provide a cleaner look. This is the current implementation:
[![HuggingFace Badge](https://img.shields.io/badge/HuggingFace-grey?style=for-the-badge&logo=huggingface)](https://github.com/huggingface)

Would it be possible to consider these adjustments? I believe they could improve the overall aesthetic of the icon.