Add October CMS
simple-icons/simple-icons pull request #9282
Opened 2023-08-13 21:57 UTC by PratyushJayachandran

![octobercms](https://github.com/simple-icons/simple-icons/assets/35000807/43c43f94-331e-4077-9c13-0673c32aa447)

**Issue:** closes #9279 

**GitHub Stars:** 10.9K. See https://github.com/octobercms/october

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
SVG: Taken from https://github.com/octobercms/october/blob/e3b455ad587282f0fbcb7763c6d9c3d000ca1e6a/modules/backend/assets/images/october-leaf.svg
Color: Taken from logo `#db6a26`

2023-08-15 20:32 UTC, adamrusted requested changes

2023-08-15 20:32 UTC, adamrusted commented on _data/simple-icons.json
> +            "source": "https://github.com/octobercms/october/blob/e3b455ad587282f0fbcb7763c6d9c3d000ca1e6a/modules/backend/assets/images/october-leaf.svg"
SVG icon available in the header of the website.

```suggestion
            "source": "https://octobercms.com"
```

2023-08-15 20:32 UTC, adamrusted commented on icons/octobercms.svg
[Minor difference](https://github.com/simple-icons/simple-icons/assets/1830867/298ba92a-c71a-4c77-8000-56c8e0226e2f) between this new source in orange, and your PR. Could you take another look please?

2023-08-16 01:07 UTC, PratyushJayachandran commented on icons/octobercms.svg
I'll take from website for this PR but this brings back the discussion of which source should prevail. Maybe we should jot down this in the Contributing guidelines.

2023-08-16 06:24 UTC, adamrusted commented on icons/octobercms.svg
Yeah, again it's another odd one. Given the leaf SVG isn't in newer versions of the repo, I'm reluctant to have that as our source, so we won't be able to track if it updates from that location. Homepage of the site would (you'd hope!) get updated relatively swiftly.

2023-08-16 07:03 UTC, PratyushJayachandran commented on icons/octobercms.svg
I agree with your reasoning. I have updated the icon. This issue seems like a case by case thing in general. Since we have no way to know whether the website logo was made first or the GitHub logo, we will have to go based off of assumptions.

2023-08-16 09:10 UTC, merged