Adding League of Legends Logo
simple-icons/simple-icons pull request #9297
Opened 2023-08-16 13:02 UTC by CodeWithShipraJain

**Issue:** closes #9262

**Similarweb rank:** 3,459. See https://www.similarweb.com/website/leagueoflegends.com/
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

2023-08-16 13:21 UTC, adamrusted requested changes

2023-08-16 13:21 UTC, adamrusted commented on _data/simple-icons.json
> +            "hex": "BF913B",
```suggestion
            "hex": "C28F2C",
```

Taken from the source icon on the homepage.

2023-08-16 13:21 UTC, adamrusted commented on icons/leagueoflegends.svg
The monochrome icon on the homepage contains an inner circle too. We should follow their precedent.
![image](https://github.com/simple-icons/simple-icons/assets/1830867/eda6cb0d-99fa-429b-94d0-c938b8beab97)

2023-08-17 08:07 UTC, adamrusted approved these changes
Looks perfect, thanks @CodeWithShipraJain 🎉

2023-08-17 08:08 UTC, merged

2023-08-17 10:37 UTC, LitoMore commented
Great job @CodeWithShipraJain! I love this one!