A Review - Part 1
simple-icons/simple-icons pull request #9300
Opened 2023-08-16 19:23 UTC by adamrusted

2023-08-22 15:16 UTC, service-paradis requested changes
Only 2 small comments and it should be good to go!

2023-08-22 15:16 UTC, service-paradis commented on _data/simple-icons.json
>              "source": "https://about.me/assets"
I think it could be added as guidelines too

2023-08-22 15:16 UTC, service-paradis commented on _data/simple-icons.json
> +            "source": "https://www.adobe.com/creativecloud.html"
We can add https://developer.adobe.com/developer-distribution/creative-cloud/docs/guides/branding_guidelines/ for every Adobe icon as guidelines.

Maybe https://developer.adobe.com/distribute/cc-brand-assets should be used as source for some icons too.

2023-08-22 15:43 UTC, LitoMore commented
Can we move `aboutdotme` icon change to another PR? I want to ignore these changes to our release note.

See https://github.com/simple-icons/simple-icons/pull/8776. PRs with `[skip]` prefixes will not be recorded.

In the meantime, I will change `[skip]` trick to a `skip release action` label in the future.

2023-08-22 15:46 UTC, service-paradis requested changes

2023-08-22 15:46 UTC, service-paradis commented on _data/simple-icons.json
> +            "guidelines": "https://developer.adobe.com/developer-distribution/creative-cloud/docs/guides/branding_guidelines/"
```suggestion
            "guidelines": "https://developer.adobe.com/developer-distribution/creative-cloud/docs/guides/branding_guidelines"
```

2023-08-22 15:46 UTC, service-paradis commented on _data/simple-icons.json
> +            "guidelines": "https://developer.adobe.com/developer-distribution/creative-cloud/docs/guides/branding_guidelines/"
```suggestion
            "guidelines": "https://developer.adobe.com/developer-distribution/creative-cloud/docs/guides/branding_guidelines"
```

2023-08-22 15:46 UTC, service-paradis commented on _data/simple-icons.json
> +            "guidelines": "https://developer.adobe.com/developer-distribution/creative-cloud/docs/guides/branding_guidelines/"
```suggestion
            "guidelines": "https://developer.adobe.com/developer-distribution/creative-cloud/docs/guides/branding_guidelines"
```

2023-08-22 15:46 UTC, service-paradis commented on _data/simple-icons.json
> +            "guidelines": "https://developer.adobe.com/developer-distribution/creative-cloud/docs/guides/branding_guidelines/"
```suggestion
            "guidelines": "https://developer.adobe.com/developer-distribution/creative-cloud/docs/guides/branding_guidelines"
```

2023-08-22 15:46 UTC, service-paradis commented on _data/simple-icons.json
> +            "guidelines": "https://developer.adobe.com/developer-distribution/creative-cloud/docs/guides/branding_guidelines/"
```suggestion
            "guidelines": "https://developer.adobe.com/developer-distribution/creative-cloud/docs/guides/branding_guidelines"
```

2023-08-22 15:46 UTC, service-paradis commented on _data/simple-icons.json
> +            "guidelines": "https://developer.adobe.com/developer-distribution/creative-cloud/docs/guides/branding_guidelines/"
```suggestion
            "guidelines": "https://developer.adobe.com/developer-distribution/creative-cloud/docs/guides/branding_guidelines"
```

2023-08-22 15:48 UTC, adamrusted commented
@LitoMore - do we still need the `[skip]` prefix if I'm moving the about.me update to another PR?

2023-08-22 15:52 UTC, LitoMore commented
> Do we still need the `[skip]` prefix if I'm moving the about.me update to another PR?

We do. Icons will be listed under the `Updated icons` if you don't add the `[skip]` prefix.

But for the PR of `about.me` icon change, we should not add the `[skip]` prefix.

2023-08-22 15:54 UTC, adamrusted commented
Ah, I've not been using the `[skip]` prefix for any of the other Great Icon Review PRs - and have already merged some.

2023-08-22 15:57 UTC, LitoMore commented
@adamrusted No worries. Adding the `[skip]` prefix to the title before the weekly release then will be fine.

2023-08-22 15:58 UTC, adamrusted commented
@LitoMore 
To the title of the PR, even if it's merged without it?

2023-08-22 15:59 UTC, LitoMore commented
> @LitoMore To the title of the PR, even if it's merged without it?

Yes. Even if it's merged without it.

2023-08-22 16:15 UTC, LitoMore commented
Remember to trim the `[skip]` prefix when merging it.

<img width="913" alt="image" src="https://github.com/simple-icons/simple-icons/assets/8186898/8c774ffb-40d8-4876-a6b2-efef8ee7a6a6">

This field only specifies the commit message that merged to develop branch.

2023-08-23 17:44 UTC, service-paradis approved these changes

2023-08-23 18:36 UTC, merged