Add Amazon Music
simple-icons/simple-icons pull request #9312
Opened 2023-08-17 11:57 UTC by adamrusted

![amazonmusic](https://github.com/simple-icons/simple-icons/assets/1830867/c3b574dc-7a16-4679-bc30-429930113b9d)

**Issue:** closes #3163

**Similarweb rank:** N/A (Amazon Brand)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
SVG pulled from homepage (behind login).
Hex is used extensively as the CTA color on the site.

2023-09-17 21:29 UTC, PratyushJayachandran requested changes
The icon is a perfect match @adamrusted!
Let us add the guidelines too :)

2023-09-17 21:29 UTC, PratyushJayachandran commented on _data/simple-icons.json
> +            "source": "https://music.amazon.com"
```suggestion
            "source": "https://music.amazon.com",
            "guidelines": "https://artists.amazonmusic.com/tools"
```
We should add the guidelines entry

2023-09-18 10:11 UTC, adamrusted commented
> Should we use the indigo color instead `#4512ff`? Perhaps stack the word mark too as shown in guidelines?

I used the brand colour available when visiting Amazon Music - and the wordmark used there too. A lot of our Amazon brands use the horizontal wordmark, so I don't think we need to worry there necessarily.

2023-09-18 15:39 UTC, PratyushJayachandran commented
> > Should we use the indigo color instead `#4512ff`? Perhaps stack the word mark too as shown in guidelines?
> 
> I used the brand colour available when visiting Amazon Music - and the wordmark used there too. A lot of our Amazon brands use the horizontal wordmark, so I don't think we need to worry there necessarily.

Okay then, should we add the guidelines entry to JSON?

2023-09-21 05:35 UTC, PratyushJayachandran requested changes
It seems like the linter has started to fail even though the change was unrelated ti failure. @adamrusted can you re-do it?

2023-09-24 19:58 UTC, PratyushJayachandran requested changes

2023-09-24 19:58 UTC, PratyushJayachandran commented on icons/amazonmusic.svg
When compared with their PNG I see [some differences in positioning.](https://github.com/simple-icons/simple-icons/assets/35000807/4e0d8ec3-0684-4f84-8a4b-4bce1dde3cf2)

2023-11-24 21:53 UTC, closed without merging