Add EJS icon
simple-icons/simple-icons pull request #9325
Opened 2023-08-19 19:57 UTC by PratyushJayachandran

![ejs](https://github.com/simple-icons/simple-icons/assets/35000807/aec5e004-51fc-4aad-9dfb-5f7080b24f0e)

**Issue:** closes #6132 

**GitHub Stars:** 7.2k. See https://github.com/mde/ejs

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
SVG: Taken from https://ejs.co/favicon.svg
Color: Taken from logo `#a91e50`

2023-08-20 16:16 UTC, adamrusted requested changes

2023-08-20 16:16 UTC, adamrusted commented on _data/simple-icons.json
> +            "source": "https://ejs.co/favicon.svg"
```suggestion
            "source": "https://github.com/mde/ejs-site/blob/dd845093a46b373df42108b888a0ad80085a5c94/ejs.svg"
```

There's a higher resolution version of the logo on GitHub that we can use here - could you update using that as your source?

2023-11-21 11:34 UTC, PeterShaggyNoble commented
Don't forget about this one, @PratyushJayachandran 😉 

Although it looks like [development might have stalled](https://github.com/mde/ejs/graphs/commit-activity) on the project.

2023-11-22 07:02 UTC, PratyushJayachandran commented
> Don't forget about this one, @PratyushJayachandran 😉
> 
> Although it looks like [development might have stalled](https://github.com/mde/ejs/graphs/commit-activity) on the project.

Oops... missed this. I have updated the icon based on SVG from GitHub repository

2023-11-29 11:10 UTC, PeterShaggyNoble requested changes
SVG looks good to me, @PratyushJayachandran 👍🏻 But, from [their website](https://ejs.co/), it looks to me like their primary colour is the green and that the pink is the secondary.

Also, my concerns about stalled development above aside, I think we name definitely say [12.5m weekly downloads](https://www.npmjs.com/package/ejs) on npm makes it popular enough for us to include! 😆

2023-11-29 15:29 UTC, PeterShaggyNoble approved these changes

2023-11-29 15:30 UTC, merged