Add netcup
simple-icons/simple-icons pull request #9352
Opened 2023-08-21 06:50 UTC by PratyushJayachandran

![netcup](https://github.com/simple-icons/simple-icons/assets/35000807/7b6e7d4c-2c01-4526-8ce8-26640ecf21d0)

**Issue:** closes #6151 

**Similarweb rank:** 279,478. See https://www.similarweb.com/website/netcup.de

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
SVG: Taken from favicon https://www.netcup.de/static/assets/images/favicons/favicon.svg
Color: Taken from logo `#056473`

2023-08-22 17:45 UTC, adamrusted commented
Looks like we'll need permission @PratyushJayachandran:
https://www.netcup-wiki.de/wiki/Werbemittel#rechtliche_Hinweise

2023-08-24 06:57 UTC, PratyushJayachandran commented
> Looks like we'll need permission @PratyushJayachandran: https://www.netcup-wiki.de/wiki/Werbemittel#rechtliche_Hinweise ![image](https://user-images.githubusercontent.com/1830867/262438479-0c876e9a-b406-44e2-878a-ff24ffd7b08c.png)

Awaiting reply

2023-09-14 06:49 UTC, PratyushJayachandran commented
@adamrusted 
![image](https://github.com/simple-icons/simple-icons/assets/35000807/33ab0ef7-4fe7-48c0-8fbb-d312591dd466)

I changed name to lowercase. Will stick with favicon for readability

2023-11-21 16:56 UTC, PeterShaggyNoble requested changes
I'm seeing [hairline differences](https://github.com/simple-icons/simple-icons/assets/15157491/8360d855-b337-4282-8241-c79446dbf546) in the corners, @PratyushJayachandran, which are likely just a precision issue.

We should also just use the website, or guidelines URL, for the source.

2023-11-22 07:33 UTC, PratyushJayachandran commented
> I'm seeing [hairline differences](https://github.com/simple-icons/simple-icons/assets/15157491/8360d855-b337-4282-8241-c79446dbf546) in the corners, @PratyushJayachandran, which are likely just a precision issue.
> 
> We should also just use the website, or guidelines URL, for the source.

I redid the icon and saw no diff, so I bumped up the precision to 4.
As for the source, since it is not present on front page I used the exact link to the icon contributed. Guidelines page doesn't have that icon and I already told the representative that I would be using this source and sent him the PR too.

2023-11-29 10:54 UTC, PeterShaggyNoble requested changes
I'm still seeing those same differences, unfortunately, @PratyushJayachandran 🤔

In the interests of getting this one merged - 'cause I'm on a rampage this week, trying to close out as many stale issues as I can - I've given it a try myself.

2023-11-29 10:54 UTC, PeterShaggyNoble commented on icons/netcup.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>netcup</title><path d="M18.75 0H5.25C2.3505 0 0 2.3505 0 5.25v13.5C0 21.6495 2.3505 24 5.25 24h13.5c2.8995 0 5.25-2.3505
```suggestion
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>netcup</title><path d="M5.25 0A5.239 5.239 0 0 0 0 5.25v13.5A5.239 5.239 0 0 0 5.25 24h13.5A5.239 5.239 0 0 0 24 18.75V5.25A5.239 5.239 0 0 0 18.75 0H5.25zm-.045 5.102h9.482c1.745 0 2.631.907 2.631 2.753v8.352h1.477v2.691h-4.666V8.58c0-.514-.298-.785-.889-.785H9.873v11.103H6.682V7.795H5.205V5.102z"/></svg>
```

2023-12-01 19:11 UTC, adamrusted approved these changes

2023-12-01 19:12 UTC, merged