clerk New logo #9379
simple-icons/simple-icons pull request #9417
Opened 2023-08-26 08:42 UTC by quantumflo

**Issue:** closes #

**Similarweb rank:**
  

### Checklist
  - [ ] I updated the JSON data in `_data/simple-icons.json`
  - [ ] I optimized the icon with SVGO or SVGOMG
  - [ ] The SVG `viewbox` is `0 0 24 24`

### Description

2023-08-26 16:52 UTC, adamrusted requested changes
Hey @quantumflo - thanks so much for your contribution!
I can see the linter is having a few errors with the SVG, and I've got a few changes to the JSON code which I'd suggest.
If you need any help adjusting the SVG, let me know and I should be able to help you out.

2023-08-26 16:52 UTC, adamrusted commented on _data/simple-icons.json
> +            "source": "https://clerk.com/_next/image?url=%2Fimages%2Ffooter-logo.svg&w=32&q=75"
```suggestion
            "hex": "6C47FF",
            "source": "https://clerk.com"
```

Hex code is available as the primary colour of the buttons etc on the site.
URL-wise we can get away with just the homepage.

2023-08-26 16:52 UTC, adamrusted commented on icons/clerk.svg
It looks like the icon hasn't been resized to fit the 24*24 viewport, and still contains additional data (linearGradient, etc).
Could you scale the icon  down to sit in the center of the 24*24 viewport in any vector editing software, and then run `npx svgo icons/clerk.svg` to remove any unnecessary properties - for example, the linearGradient.

2023-08-27 14:45 UTC, quantumflo commented on icons/clerk.svg
I have fixed it now

2023-08-28 09:09 UTC, adamrusted requested changes
Thanks for the quick turnaround @quantumflo!
Looks like the icon has been stretched in both directions to fill the 24x24 viewport - whereas it should only be the longest side, with the aspect ratio maintained. See below for an example using the header logo against your PR.
![image](https://github.com/simple-icons/simple-icons/assets/1830867/b98c44e6-0448-44be-96ec-1fc97f6ce194)


Would you mind having another look at this one? 🙏

2023-08-29 18:46 UTC, adamrusted requested changes
Still seeing [minor differences](https://github.com/simple-icons/simple-icons/assets/1830867/3f9a8dcd-b934-4d94-b947-600d12b1623f) between source and PR. Might be best to regenerate from source with this one @quantumflo.

2023-09-01 04:04 UTC, quantumflo commented
> Still seeing [minor differences](https://github.com/simple-icons/simple-icons/assets/1830867/3f9a8dcd-b934-4d94-b947-600d12b1623f) between source and PR. Might be best to regenerate from source with this one @quantumflo.

Hi I would need help on this. As I am not sure on what changes needs to be done further... @adamrusted

2023-09-02 07:28 UTC, quantumflo commented
> > Still seeing [minor differences](https://github.com/simple-icons/simple-icons/assets/1830867/3f9a8dcd-b934-4d94-b947-600d12b1623f) between source and PR. Might be best to regenerate from source with this one @quantumflo.
> 
> Hi I would need help on this. As I am not sure on what changes needs to be done further... @adamrusted

@adamrusted What needs to be done next? I am trying to use inkspace to fix the issues and steps I followed was -
1) scaled it to vertically(longest side )  and then aligned it to center.

2023-09-02 17:22 UTC, adamrusted commented
Weird - it shouldn't be stretching that much when you edit the file.
Below is the path I've been using to compare against, feel free to use that. It _should_ be optimised and match up.
```xml
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Clerk</title><path d="m21.47 20.829-2.881-2.881a.572.572 0 0 0-.7-.084 6.854 6.854 0 0 1-7.081 0 .576.576 0 0 0-.7.084l-2.881 2.881a.576.576 0 0 0-.103.69.57.57 0 0 0 .166.186 12 12 0 0 0 14.113 0 .58.58 0 0 0 .239-.423.576.576 0 0 0-.172-.453Zm.002-17.668-2.88 2.88a.569.569 0 0 1-.701.084A6.857 6.857 0 0 0 8.724 8.08a6.862 6.862 0 0 0-1.222 3.692 6.86 6.86 0 0 0 .978 3.764.573.573 0 0 1-.083.699l-2.881 2.88a.567.567 0 0 1-.864-.063A11.993 11.993 0 0 1 6.771 2.7a11.99 11.99 0 0 1 14.637-.405.566.566 0 0 1 .232.418.57.57 0 0 1-.168.448Zm-7.118 12.261a3.427 3.427 0 1 0 0-6.854 3.427 3.427 0 0 0 0 6.854Z"/></svg>
```

2023-09-02 18:14 UTC, quantumflo commented
> Weird - it shouldn't be stretching that much when you edit the file. Below is the path I've been using to compare against, feel free to use that. It _should_ be optimised and match up.
> 
> ```
> <svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Clerk</title><path d="m21.47 20.829-2.881-2.881a.572.572 0 0 0-.7-.084 6.854 6.854 0 0 1-7.081 0 .576.576 0 0 0-.7.084l-2.881 2.881a.576.576 0 0 0-.103.69.57.57 0 0 0 .166.186 12 12 0 0 0 14.113 0 .58.58 0 0 0 .239-.423.576.576 0 0 0-.172-.453Zm.002-17.668-2.88 2.88a.569.569 0 0 1-.701.084A6.857 6.857 0 0 0 8.724 8.08a6.862 6.862 0 0 0-1.222 3.692 6.86 6.86 0 0 0 .978 3.764.573.573 0 0 1-.083.699l-2.881 2.88a.567.567 0 0 1-.864-.063A11.993 11.993 0 0 1 6.771 2.7a11.99 11.99 0 0 1 14.637-.405.566.566 0 0 1 .232.418.57.57 0 0 1-.168.448Zm-7.118 12.261a3.427 3.427 0 1 0 0-6.854 3.427 3.427 0 0 0 0 6.854Z"/></svg>
> ```

Cool thanks. Updated now

2023-09-16 06:23 UTC, quantumflo commented
@adamrusted this PR can be merged?

2023-10-29 16:27 UTC, quantumflo commented
> @adamrusted this PR can be merged?

Hey @adamrusted any other changes required?

2023-11-15 12:07 UTC, adamrusted commented
Apologies @quantumflo, I'm not able to review the PR given the path I contributed has been used. @simple-icons/icon-review - anyone able to give this a once over?

2023-11-20 07:26 UTC, PratyushJayachandran approved these changes
Perfect match @adamrusted! Thanks for starting the contribution @quantumflo 🎉

2023-11-20 07:26 UTC, merged