Add HAL icon
simple-icons/simple-icons pull request #9435
Opened 2023-08-29 06:46 UTC by PriyansuMaurya

**Issue:** closes #9365

**Similarweb rank:**
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

2023-08-29 06:59 UTC, PratyushJayachandran requested changes
Missing the SVG itself

2023-08-29 06:59 UTC, PratyushJayachandran commented on _data/simple-icons.json
> +            "title": "Zyte",
Do not add another icon in this PR

2023-08-29 18:43 UTC, PriyansuMaurya commented
> Missing the SVG itself

Would you like me to upload an SVG?

2023-08-29 19:17 UTC, PratyushJayachandran commented
> Would you like me to upload an SVG?

Yes. New icons need both SVG and JSON data.

2023-08-30 06:10 UTC, PriyansuMaurya commented
> Yes. New icons need both SVG and JSON data.

where should I upload svg?

2023-08-30 06:19 UTC, PratyushJayachandran commented
> > Would you like me to upload an SVG?
> 
> Yes. New icons need both SVG and JSON data.

`icons/hal.svg`
Check contributing.md for more details. Check any of the open PRs new icons with all the checks passing for reference.

2023-08-30 12:17 UTC, PriyansuMaurya commented
I closing this one and opening a new one due to merge issues.

2023-08-30 12:17 UTC, closed without merging