Add google dataproc
simple-icons/simple-icons pull request #9451
Opened 2023-08-30 07:40 UTC by PratyushJayachandran

![googledataproc](https://github.com/simple-icons/simple-icons/assets/35000807/726c4b7d-4cb8-4a3e-a270-04f9e5f32dd0)

**Issue:** closes #5133 

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
SVG: Taken from https://cloud.google.com/icons
Color: Taken from logo `#aecbfa`

> **Note**
> The source itself has misaligned objects in the icon. I tried fixing them up

2023-09-03 16:03 UTC, adamrusted requested changes
This one's not particularly nice to work with, but I think if we're removing some of the shadows - we should probably remove [them all](https://github.com/simple-icons/simple-icons/assets/1830867/551ecde8-e1a0-4f45-9c21-c1a4b20126a5).

Could you work your magic on this one again please @PratyushJayachandran? 🙏

2023-09-13 14:43 UTC, PratyushJayachandran commented
> Could you work your magic on this one again please @PratyushJayachandran? 🙏

The objects are misaligned in a lot of their icons. Someone made it in higher precision and then reduced it maybe. I'm not sure about this.
But yeah I'll give it another try. This one looked more symmetrical to me so I went with this approach.

2023-11-08 07:37 UTC, PratyushJayachandran commented
Hello @adamrusted!

I had to use a lot of 'creative liberty' to get this one done as the shapes are misaligned in several places. Attaching some examples
![image](https://github.com/simple-icons/simple-icons/assets/35000807/9ecf3ae4-b73b-4338-9881-c2955dfecf78)
![image](https://github.com/simple-icons/simple-icons/assets/35000807/945abf4d-52af-4d55-b405-d6c9f9f696eb)

2023-11-08 07:38 UTC, PratyushJayachandran commented
New Preview
![googledataproc](https://github.com/simple-icons/simple-icons/assets/35000807/18bcb126-c2cd-40f2-8ce0-31cce84a6ea0)

2023-11-24 15:39 UTC, PeterShaggyNoble submitted a review, later dismissed
Did nobody in Google review any of these icons before releasing them to the public?! 🤦🏻‍♂️ 

I'm OK with the attempt to clean this one up, but we'll need another maintainer to give the OK too.

2023-11-24 16:13 UTC, PratyushJayachandran commented
> Did nobody in Google review any of these icons before releasing them to the public?! 🤦🏻‍♂️
> 
> I'm OK with the attempt to clean this one up, but we'll need another maintainer to give the OK too.

Maybe they made it at a different dimension and then resized it. The objects may have lost their position due to precision issues.

2023-11-25 19:11 UTC, adamrusted commented on _data/simple-icons.json
> +            "hex": "AECBFA",
I think we should go with the primary colour of the icon - in this case, @PratyushJayachandran was correct with `#AECBFA`.

2023-11-25 19:11 UTC, adamrusted approved these changes

2023-11-25 19:13 UTC, merged