Add Actix icon
simple-icons/simple-icons pull request #9461
Opened 2023-08-30 21:03 UTC by IamRezaMousavi

![actix](https://github.com/simple-icons/simple-icons/assets/83984878/392a33bc-a85b-40bc-9205-53e9bc242eb6)

**Issue:** closes #8453 

 [18.4k GitHub ⭐](https://github.com/actix/actix-web)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

2023-09-03 16:10 UTC, adamrusted commented
@IamRezaMousavi is there an SVG version of the icon available on the website? All I can see are PNGs...

2023-09-03 16:15 UTC, IamRezaMousavi commented
> @IamRezaMousavi is there an SVG version of the icon available on the website? All I can see are PNGs...

No, I converted the site icon from png to svg format

2023-09-26 12:18 UTC, IamRezaMousavi commented
@adamrusted What do I need to do?

2023-12-08 01:39 UTC, IamRezaMousavi commented
You can see https://crates.io/crates/actix-web 
This package has +120k downloads in past 4 days (4 Dec - 7 Dec)

2023-12-08 09:44 UTC, PeterShaggyNoble commented
That looks like a good indicator to me, @IamRezaMousavi and puts it on a par with the currently proposed minimum downloads for npm. Would any of the other @simple-icons/maintainers agree that this is popular based on that data? Or should we discuss crates.io downloads further as part of our proposed new metrics first?

2023-12-08 13:46 UTC, service-paradis commented
Looks pretty good to me!

2023-12-08 15:12 UTC, PeterShaggyNoble requested changes
On to reviewing, so 😁 Nice work on this one, @IamRezaMousavi; the differences are _mostly_ minor, which is to be expected with a manual vectorisation, but could you see if you could get the upper part of yours (in red) to line up a little better with the original?

![](https://github.com/simple-icons/simple-icons/assets/15157491/76eb356e-98f7-4c86-876c-a7620c607dce)

2023-12-11 10:54 UTC, PeterShaggyNoble requested changes
Thanks for updating, @IamRezaMousavi, but those differences look [more pronounced](https://github.com/simple-icons/simple-icons/assets/15157491/e4d2db09-ec0f-4d06-93d3-6dac17563bd3) to me now, unfortunately. Of the 2 versions you've tried so far, I think the first is probably our better option if that's as close as you can get 👍🏻

2024-01-11 11:57 UTC, PeterShaggyNoble commented
In the interests of moving this along, I've reverted the SVG to the previous version. But I'd like one of the other @simple-icons/maintainers to have a look over it before proceeding.

2024-01-16 07:19 UTC, PratyushJayachandran commented on icons/actix.svg
There is a minor scaling issue. See:  
![actix-comparison](https://github.com/simple-icons/simple-icons/assets/35000807/26bf83c3-b49d-42d3-b1d1-2fa870cc94c7)

Black being the PNG cropped end to end and red one being the contribution. The vector is pretty spot on but I guess the source was scaled with some extra pixels leading to overall change.

I am okay with it though. Would wait for other maintainers to comment.

2024-02-08 08:38 UTC, adamrusted commented on icons/actix.svg
No, unfortunately I think the issues are too severe, even with lining up the PNG (in black) as closely as I could with the  SVG in red. Would you mind having another look please @IamRezaMousavi?

2024-02-08 18:24 UTC, service-paradis commented
[Well, I found something that might be interesting](https://github.com/actix/actix-website/issues/18) 😅

2024-02-08 18:39 UTC, adamrusted commented
> [Well, I found something that might be interesting](https://github.com/actix/actix-website/issues/18) 😅

<img src="https://media.tenor.com/tvFWFDXRrmMAAAAd/blow-mind-mind-blown.gif" />

2024-02-08 19:18 UTC, service-paradis approved these changes
LGTM now 🎉 

Thanks everyone that works on it!

2024-02-08 19:19 UTC, merged