Add DeepL
simple-icons/simple-icons pull request #9464
Opened 2023-08-31 03:09 UTC by mtrucc

**Issue:** closes #

**Similarweb rank:**
  

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description

2023-09-03 16:14 UTC, adamrusted requested changes
Thanks for the contribution @mtrucc!
There's a couple of changes I'd make to the JSON - and that in turn would impact the icon itself.
Would you mind updating the JSON, and re-generating from the new source? 🙏

2023-09-03 16:14 UTC, adamrusted commented on _data/simple-icons.json
> +            "hex": "002746",
```suggestion
            "hex": "0F2B46",
```

2023-09-03 16:14 UTC, adamrusted commented on _data/simple-icons.json
> +            "source": "https://upload.wikimedia.org/wikipedia/commons/e/ed/DeepL_logo.svg"
```suggestion
            "source": "https://www.deepl.com"
```

2023-09-04 01:20 UTC, mtrucc commented on _data/simple-icons.json
> +            "source": "https://upload.wikimedia.org/wikipedia/commons/e/ed/DeepL_logo.svg"
Thank you for further improvement

2023-11-21 12:59 UTC, PeterShaggyNoble requested changes
They have a [press page](https://www.deepl.com/press.html) so we should probably use what's available there, and update the source accordingly.

Using the  "[Logo DeepL (svg)](https://www.deepl.com/img/press/logo_DeepL.svg?v=1)" file (which the [Wikimedia article](https://commons.wikimedia.org/wiki/File:DeepL_logo.svg) claims to be sourced from) for comparison, there are [significant differences in your version](https://github.com/simple-icons/simple-icons/assets/15157491/37bbc038-14be-410a-bbc1-57f10de8a707) (in red), @mtrucc - would you mind taking another pass at this, please?

2023-12-08 10:55 UTC, PeterShaggyNoble commented
Are you still working on this one, @mtrucc?

2023-12-08 12:37 UTC, PeterShaggyNoble requested changes
Thanks for updating, @mtrucc. However the maximum precision we allow for an icon is 5 decimal places.

2023-12-08 12:46 UTC, PeterShaggyNoble approved these changes
Icon looks good to me now, @mtrucc 👍🏻 And I agree with your choice to use the full logo as they don't make the icon itself available on their press page. Just need to update the `hex` & `source` and this is ready to merge.

2023-12-08 12:46 UTC, PeterShaggyNoble commented on _data/simple-icons.json
> +            "source": "https://www.deepl.com"
```suggestion
            "hex": "0F2B46",
            "source": "https://www.deepl.com/press.html"
```

2023-12-08 12:47 UTC, merged