Add CyberDefenders icon
simple-icons/simple-icons pull request #9490
Opened 2023-09-04 01:31 UTC by marcosquadross

![cyberdefenders](https://github.com/simple-icons/simple-icons/assets/98984018/0d83ca47-bdff-4c62-96c0-005ac5a7d8d8)

**Issue:** closes #9230

**Similarweb rank:** 267,857

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

2023-09-04 07:36 UTC, adamrusted requested changes
Thanks for this @marcosquadross!
I'm seeing [some differences](https://github.com/simple-icons/simple-icons/assets/1830867/ba600928-6e52-49eb-92a9-199daddf7ffb) between your PR in black, and the source icon in blue. Looks like you need to make the height of the path itself 24px, and center it on the canvas.
Would you mind taking another look? 🙏

2023-09-04 09:46 UTC, adamrusted requested changes
Still spotting a [slight difference](https://github.com/simple-icons/simple-icons/assets/1830867/492d5ea5-8205-4a63-b55d-77e2c7d7a023) on this one @marcosquadross. Looks like some points are only 2 decimals of precision. Might be worth exporting higher, and using [SVGOMG](https://jakearchibald.github.io/svgomg/) to optimize to 4 decimals.

2023-09-04 12:21 UTC, adamrusted requested changes

2023-09-04 12:21 UTC, adamrusted commented on icons/cyberdefenders.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>CyberDefenders</title><path d="M18.954 17.477c-.13 2.73-2.392 4.69-5.404 4.69H7.298v-6.103l-2.192-.96V24h8.44c4.363 0 7.5
Still seeing [slight differences](https://github.com/simple-icons/simple-icons/assets/1830867/381bb00e-83bb-4a8a-aee2-f672f5a280cf) (see the edges) between your PR and the source icon. Below icon seems to be matching at 3 decimals of precision, you're welcome to use it - but we'll need another reviewer to sign off on the PR.

```suggestion
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>CyberDefenders</title><path d="M18.918 17.48c-.126 2.727-2.384 4.696-5.364 4.696H7.34v-6.123l-2.185-.957V24h8.381c4.334 0 7.549-2.962 7.549-6.881v-.163c-.65.235-1.372.415-2.167.524Zm1.355-9.501C18.611 4.313 17.726.989 15.432.213c-1.336-.452-2.005-.091-2.637.217-.199.09-.235.361-.072.505.361.307.813.687 1.336 1.174-1.95-1.138-7.333-2.835-7.874-.776-.488 1.86-1.319 4.587-1.319 4.587S.603 5.487.116 7.293c-.488 1.806 3.323 5.274 9.627 7.134 6.303 1.861 11.198 1.373 13.311-.921 2.113-2.294.072-5.473-2.781-5.527Zm-1.247.036c-.487.47-2.077 1.68-5.563 1.427-3.738-.271-6.809-2.474-7.604-3.088-.126-.091-.18-.235-.126-.398.054-.18.126-.469.253-.849.072-.234.343-.343.542-.216 1.571.903 4.1 2.221 6.791 2.402 2.402.163 3.847-.542 4.786-1.066.199-.108.452-.018.542.199l.47 1.156c.036.162.018.325-.091.433Z"/></svg>
```

2023-09-06 08:14 UTC, PratyushJayachandran approved these changes
Spot on now
![cyberdefenders-compare](https://github.com/simple-icons/simple-icons/assets/35000807/91b0dc0a-d3c3-431b-b12d-6cd9a4589fd9)

2023-09-06 08:25 UTC, merged