Add Rocket icon
simple-icons/simple-icons pull request #9492
Opened 2023-09-04 17:59 UTC by IamRezaMousavi

![rocket](https://github.com/simple-icons/simple-icons/assets/83984878/7478f36f-9186-46fe-8899-eb9f43ecfe69)

**Issue:** closes #8185

 [21.4k GitHub ⭐](https://github.com/SergioBenitez/Rocket)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
- Did you manually vectorize the logo? Yes

2023-09-05 07:39 UTC, adamrusted commented
Hey @SergioBenitez - you wouldn't happen to have an SVG/AI version of the icon shown above would you?
It'd be ace to include the original icon as opposed to one of our contributors having to manually vectorize it!

2023-09-05 10:48 UTC, IamRezaMousavi commented
No, The site svg icon is different
This svg is only used for the header and footer of the site:
![logo-small](https://github.com/simple-icons/simple-icons/assets/83984878/8353dd56-32b3-49d5-a89d-5e56ca014561)

Origin icon which used in head of origin html page is this:
![logo-boxed](https://github.com/simple-icons/simple-icons/assets/83984878/9341f06d-00ef-4ff4-9b88-6fbf8b6895da)

2023-09-18 08:04 UTC, adamrusted commented
I don't see the version with the trails behind the rocket used in the current source code of the homepage. We might just need to use the boxed rocket without the trails.

2023-09-19 21:11 UTC, SergioBenitez commented
Here's everything:

![logo-small](https://github.com/simple-icons/simple-icons/assets/1480321/606b7d64-a3f6-45df-ae80-99d6a57a6b0c)
![logo](https://github.com/simple-icons/simple-icons/assets/1480321/f569e538-aeb0-443a-acbc-bbcaf4ba7984)
![logo-boxed](https://github.com/simple-icons/simple-icons/assets/1480321/751f0fd0-b17c-4612-8566-29df8366187e)
![favicon](https://github.com/simple-icons/simple-icons/assets/1480321/63020ac0-9ad6-4a1b-851b-327019a9bdb0)
![rocket-logo@2x](https://github.com/simple-icons/simple-icons/assets/1480321/983be48b-d479-4ecd-88a1-b1e85e082617)
![rocket-logo@3x](https://github.com/simple-icons/simple-icons/assets/1480321/747e07bf-31a9-47c4-9bf5-64ae0213bcad)

2023-09-26 12:18 UTC, IamRezaMousavi commented
@adamrusted What do I need to do?

2023-11-22 12:35 UTC, PeterShaggyNoble commented
@IamRezaMousavi, can you redo your SVG based on [this one](https://user-images.githubusercontent.com/1480321/269096120-63020ac0-9ad6-4a1b-851b-327019a9bdb0.svg) provided above, please?

2023-11-22 14:23 UTC, IamRezaMousavi commented
> @IamRezaMousavi, can you redo your SVG based on [this one](https://user-images.githubusercontent.com/1480321/269096120-63020ac0-9ad6-4a1b-851b-327019a9bdb0.svg) provided above, please?

@PeterShaggyNoble How is it now?

2023-11-22 15:29 UTC, adamrusted commented on _data/simple-icons.json
> +            "source": "https://rocket.rs/images/logo-boxed.png"
```suggestion
            "source": "https://github.com/simple-icons/simple-icons/pull/9492#issuecomment-1726472160"
```

2023-12-07 16:27 UTC, PeterShaggyNoble requested changes
Sorry, @IamRezaMousavi, I should have been clearer: it's that version we should be using but with the square. Like so:
![image](https://github.com/simple-icons/simple-icons/assets/15157491/0634de0b-b1d9-4ec9-bda4-bb2d5944ebf9)

2024-01-11 11:16 UTC, PeterShaggyNoble commented
Are you still working on this one, @IamRezaMousavi?

2024-01-16 00:52 UTC, IamRezaMousavi commented
> Are you still working on this one, @IamRezaMousavi?

I think Rocket is not qualified for [your new review metrics](https://github.com/simple-icons/simple-icons/issues/9979)

Please see [similarweb ranking](https://www.similarweb.com/website/rocket.rs/#overview)

2024-01-16 07:13 UTC, adamrusted commented
> I think Rocket is not qualified for your new review metrics

SimilarWeb rank of 306,696 puts this in scope!

2024-02-04 10:14 UTC, adamrusted commented
Given it's still in scope - are you able to make the changes requested, @IamRezaMousavi?

2024-03-06 06:52 UTC, IamRezaMousavi commented
> Sorry, @IamRezaMousavi, I should have been clearer: it's that version we should be using but but with the square. Like so: ![image](https://private-user-images.githubusercontent.com/15157491/288824180-0634de0b-b1d9-4ec9-bda4-bb2d5944ebf9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MDgxNzcsIm5iZiI6MTcwOTcwNzg3NywicGF0aCI6Ii8xNTE1NzQ5MS8yODg4MjQxODAtMDYzNGRlMGItYjFkOS00ZWM5LWJkYTQtYmIyZDU5NDRlYmY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDA2NTExN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2MzI5N2I3MDMzN2UwN2JjMzU0YTI1NDY3NzUzMmU0OTIwNDc5ZTQ3Y2YyYTU0N2M5NmE5ZDY3MzQ0MGRmNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Cl5MuDTRrzTPu0P4WQ8eLlzEWceO_pDIuJ96d3l6vhE)

I think you wrong about this

2024-03-06 06:57 UTC, IamRezaMousavi commented
I redid the logo based on [this one](https://user-images.githubusercontent.com/1480321/269096120-63020ac0-9ad6-4a1b-851b-327019a9bdb0.svg)

2024-03-09 21:24 UTC, PratyushJayachandran requested changes
Can you please re-do from the logo-small.svg from their official website?
Thank you for your persistent efforts @IamRezaMousavi 😄

2024-03-09 21:24 UTC, PratyushJayachandran commented on icons/rocket.svg
There is a slight bit of scaling issue which could also be due to SVG optimization. [See comparison.](https://github.com/simple-icons/simple-icons/assets/35000807/8f923197-8abe-496a-896c-38f8d9a60db1)
If it still doesn't improve try upping the precision to 4.

2024-03-09 21:24 UTC, PratyushJayachandran commented on _data/simple-icons.json
> +            "source": "https://github.com/simple-icons/simple-icons/pull/9492#issuecomment-1726472160"
We need an actual source from where the logo was picked up. Not a comment from the PR itself. Well if the author or someone had provided in the PR comments, that would have been acceptable.

Anyway, how about we use the logo-small.svg from their own website itself?
```suggestion
            "source": "https://rocket.rs/"
```

2024-03-09 21:24 UTC, PratyushJayachandran commented on icons/rocket.svg
Let's use the new source instead: https://rocket.rs/images/logo-small.svg

2024-03-16 06:25 UTC, PratyushJayachandran commented
> @PratyushJayachandran, we need to use one of [these SVGs](https://github.com/simple-icons/simple-icons/pull/9492#issuecomment-1726472160) as they have been provided to us by an official source. I opted for the one with square corners and without the trails as it would look better at our native size.

I compared the one posted by the creator and the one on the latest website. The alignment of the fit inside the box is different for both. In the interest of not dragging this further, I will apply changes so that you can review and merge.

The changes are based on SVG on the website header itself: https://rocket.rs/images/logo-small.svg

2024-03-16 06:26 UTC, PratyushJayachandran commented on icons/rocket.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Rocket</title><path d="M3.006 10.936c-1.068 1.132-2 2.39-3.001 3.573-.076.62.8.517 1.214.72l2.837.79c.394-.488 1.349-1.49
```suggestion
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Rocket</title><path d="M23.737.237V.236a.247.247 0 0 0-.201-.188C23.28.007 17.2-.877 9.366 7.1l-.001.001c-.039.041-1.043 1.101-2.118 2.575l-4.049 1.166a.246.246 0 0 0-.123.08l-2.856 3.5a.247.247 0 0 0 .124.393l3.89 1.096.483-.565c.177-.208.37-.401.575-.58l.54-.471-.38.607c-.145.231-.307.451-.483.658l-.519.607c.007.79.213 1.489.62 2.069L3.68 19.653c-.147.162-.037.272.122.429l1.108 1.086c.153.16.257.258.41.099l1.505-1.533c.343.122 1.163.333 2.4.14l.75-.576a5.55 5.55 0 0 1 .673-.442l.644-.36-.514.53a5.549 5.549 0 0 1-.601.534l-.62.476 1.425 3.804a.246.246 0 0 0 .403.09l3.243-3.143a.248.248 0 0 0 .072-.136l.697-4.11c.885-.78 1.78-1.686 2.661-2.694 5.072-5.805 5.797-10.315 5.778-12.486-.006-.703-.093-1.095-.1-1.124zm-7.245 10.928c-1.274 1.296-3.101 1.566-4.082.602-.98-.964-.743-2.795.53-4.091 1.274-1.296 3.101-1.566 4.082-.602.98.964.743 2.795-.53 4.091z"/></svg>
```

2024-03-16 06:33 UTC, PratyushJayachandran commented on icons/rocket.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Rocket</title><path d="M23.737.237V.236a.247.247 0 0 0-.201-.188C23.28.007 17.2-.877 9.366 7.1l-.001.001c-.039.041-1.043
```suggestion
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Rocket</title><path d="M23.735.238V.236a.248.248 0 0 0-.2-.188c-.256-.04-6.336-.924-14.17 7.051a28.44 28.44 0 0 0-2.12 2.576l-4.047 1.166a.246.246 0 0 0-.124.08l-2.856 3.5a.248.248 0 0 0 .126.394l3.887 1.096.484-.566c.178-.208.37-.4.574-.58l.54-.472-.38.608a5.556 5.556 0 0 1-.482.66l-.52.606c.008.79.214 1.488.62 2.068L3.68 19.653c-.148.16-.036.272.12.428l1.11 1.086c.153.16.255.258.41.1l1.505-1.534c.34.122 1.162.334 2.4.14l.75-.576c.212-.164.438-.312.672-.442l.644-.36-.514.53c-.187.192-.387.37-.6.534l-.62.476 1.424 3.804a.246.246 0 0 0 .404.09l3.242-3.144a.248.248 0 0 0 .072-.136l.698-4.108c.884-.78 1.78-1.686 2.66-2.694 5.072-5.806 5.798-10.315 5.78-12.487-.008-.702-.094-1.094-.1-1.122h-.002zM16.49 11.165c-1.274 1.296-3.1 1.564-4.082.6-.98-.962-.744-2.794.53-4.09s3.1-1.566 4.08-.602c.982.964.746 2.796-.528 4.092z"/></svg>
```

2024-04-03 07:47 UTC, PratyushJayachandran approved these changes
Matches perfectly @IamRezaMousavi 🎉 
Also thanks to @adamrusted and @PeterShaggyNoble for continued discussions and review!

2024-04-03 07:47 UTC, merged