fineco added!
simple-icons/simple-icons pull request #9495
Opened 2023-09-05 14:34 UTC by nicolgit

**Issue:** closes #8942 

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
nothing to say :-)

2023-09-07 08:33 UTC, adamrusted requested changes
Thanks for the contribution @nicolgit - though I'm spotting a few [differences](https://github.com/simple-icons/simple-icons/assets/1830867/055b2275-91a6-4a10-a8fa-f0ee67193a8b), with your PR in black on top of the header SVG from the website.
Would you mind taking another look? 🙏

2023-09-07 12:46 UTC, nicolgit commented on _data/simple-icons.json
> +            "source": "https://commons.wikimedia.org/wiki/File:FinecoBank_logo.svg"
ok!

2023-09-07 12:46 UTC, nicolgit commented on _data/simple-icons.json
> +            "hex": "155BA0",
ok!

2023-09-07 12:53 UTC, adamrusted commented
There were the differences I'd identified in the linked screenshot - so might be worth regenerating from the new source now you've updated it. Worst case I can lend a hand with the svg path but we'd need to get another maintainer to review.

2023-09-12 14:36 UTC, nicolgit commented
rebuilt the svg starting from https://[images.finecobank.com/common-global/img/logo/logo-fineco.svg](https://images.finecobank.com/common-global/img/logo/logo-fineco.svg)

2023-11-23 14:17 UTC, PeterShaggyNoble approved these changes

2023-11-23 14:19 UTC, merged