Add wikisource icon
simple-icons/simple-icons pull request #9541
Opened 2023-09-13 06:49 UTC by Parthiv-M

**Issue:** closes #9540 

**Similarweb rank:** 7,516

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
 - Hex value `#006699` was chosen in tune with other wiki projects
 - Icon Preview
![wikisource_preview](https://github.com/simple-icons/simple-icons/assets/57034486/ca72828c-1242-490e-a427-ae4e8159f393)

2023-11-29 20:08 UTC, adamrusted requested changes
Thanksfor the contribution @Parthiv-M, though unfortunately it doesn't read particularly well where the lines are. Could you try (feel free to use a bit of artistic liberty with placement) rebuilding with 1px gaps where some of the more major color changes are?

2023-11-29 20:08 UTC, adamrusted commented on _data/simple-icons.json
> +                "url": "https://creativecommons.org/licenses/by-sa/3.0/deed.en"
```suggestion
                "type": "CC-BY-SA-3.0"
```

2023-11-30 09:30 UTC, Parthiv-M commented
Hello @adamrusted, thanks for the review. I have made the changes and updated the preview above as well.

2023-12-08 10:17 UTC, PeterShaggyNoble requested changes
Thanks for your work on this one, @Parthiv-M 👍🏻 However, I'm seeing [some differences](https://github.com/simple-icons/simple-icons/assets/15157491/86fd528a-4e0e-4379-8e58-a52100585d8f) when I overlay your version (in red) with the original.

I wonder, though, if by attempting to retain all the detail of the original is the right way to go in this case and if a more simplified approach might not be a better treatment that more faithfully represents the original in monochrome. Something along the lines, but perhaps not _exactly_ like the below. What do you think?

![](https://github.com/simple-icons/simple-icons/assets/15157491/3981a2d1-e234-47ef-b720-01f79202d2ff)

2023-12-09 03:53 UTC, Parthiv-M commented
Alright, that sounds good to me. I'll make the changes soon!

2024-01-11 11:54 UTC, PeterShaggyNoble commented
Are you still working on this, @Parthiv-M?

2024-01-11 13:16 UTC, Parthiv-M commented
Hey, yes I am, I was just a bit caught up with some personal issues. I'll make sure to make the changes!

2024-01-18 10:14 UTC, PeterShaggyNoble requested changes
That treatment works for me, @Parthiv-M 👍🏻 However, I am seeing [some significant differences](https://github.com/simple-icons/simple-icons/assets/15157491/c5ea4885-9194-4dda-b7ca-c2426b9a75dd) between your version and the source file.

2024-01-28 03:30 UTC, Parthiv-M commented
![wikisource_preview](https://github.com/simple-icons/simple-icons/assets/57034486/ee9d51ee-e24a-4166-8806-37e99a2f3255)


Made the following changes @PeterShaggyNoble 
- Fixed non-overlapping of paths as far as I could, looked alright to me in my tests
- Removed the slight gap in between two of the bigger elements

2024-01-28 04:12 UTC, Parthiv-M commented
Looks like there's a lining error, I'll fix that up

2024-01-28 04:12 UTC, Parthiv-M commented
Looks like there's a lining error, I'll fix that up

2024-03-14 15:28 UTC, closed without merging