Request: Arc Browser
simple-icons/simple-icons pull request #9569
Opened 2023-09-16 10:23 UTC by 5ouma

![arc](https://github.com/simple-icons/simple-icons/assets/101255979/47603b2c-6533-4bb8-b9ba-12dd853504a3)

**Issue:** closes #8094

**Similarweb rank:** 60,873

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
- The issue I link is for Arc Browser and The Browser Company. So you should not close the Issue until both of them are added.
- Please tell me what you think about the color currently `#FCBFBd`.

2023-10-02 07:45 UTC, PratyushJayachandran requested changes

2023-10-02 07:45 UTC, PratyushJayachandran commented on icons/arc.svg
@5ouma I see [some differences between source and contributed icon.](https://github.com/simple-icons/simple-icons/assets/35000807/5069b2f7-0394-4255-8cb5-4843e2a3faec)
Can you please try again?
I used this SVG icon available on their landing page: ![arc net-original](https://github.com/simple-icons/simple-icons/assets/35000807/78f2895d-0de8-4d86-b379-a013ab1b1093)

2023-10-03 07:23 UTC, PratyushJayachandran reviewed
Thank you for contributing @5ouma. Perfect match 🎉

2023-10-03 07:23 UTC, PratyushJayachandran approved these changes

2023-10-03 07:24 UTC, merged

2023-10-03 07:24 UTC, 5ouma commented
Thank you!!!