Add ActivityPub/Fediverse
simple-icons/simple-icons pull request #9586
Opened 2023-09-17 22:59 UTC by ThatOneCalculator

**Issue:** closes #7483

**Similarweb rank:** N/A (decentralized protocol)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Adds Fediverse (network) and ActivityPub (protocol) icons. This is the network that powers Mastodon, Firefish, Pleroma, Misskey, etc which already have icons in SimpleIcons and can be used as either a protocol discriminator (AP) or a generic reference to the Fediverse

2023-10-06 00:22 UTC, ThatOneCalculator commented
As per advice given on Discord, the Fediverse icon will be a separate PR

2023-10-08 06:15 UTC, PratyushJayachandran requested changes
The JSON data is correct. but the icon has minor issues when comparing to the original. Can you take another look @ThatOneCalculator?

2023-10-08 06:15 UTC, PratyushJayachandran commented on icons/activitypub.svg
I see [some differences!](https://github.com/simple-icons/simple-icons/assets/35000807/7c048a71-fbb6-4338-93df-4680f491a71d)

2023-10-08 06:28 UTC, ThatOneCalculator commented on icons/activitypub.svg
Probably SVGOMG again ^^;

2023-10-10 03:59 UTC, PratyushJayachandran approved these changes
Perfect match @ThatOneCalculator 🎉

2023-10-10 04:01 UTC, merged