Rename `OpenTF` to `OpenTofu`
simple-icons/simple-icons pull request #9607
Opened 2023-09-21 12:26 UTC by adamrusted

![opentofu](https://github.com/simple-icons/simple-icons/assets/1830867/bb00e16c-c881-4a0f-8315-10a8a93dfba2)

**Similarweb rank:** [150,453](https://www.similarweb.com/website/opentf.org/#overview) (Old URL, new one not indexed yet)

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
Remove OpenTF icon, replaced with OpenTofu icon.

2023-10-26 15:50 UTC, elliotwutingfeng commented
**New URL Similarweb rank:** [334,602](https://www.similarweb.com/website/opentofu.org/#overview)
The new URL now meets the criteria.

2023-11-23 10:45 UTC, PeterShaggyNoble requested changes
Icon looks good, @adamrusted 👍🏻 Although there are some excess points in the corners of the eyes that you might be able to remove.

Also, is the change to `sdk.mjs` intentional?

2023-11-23 10:45 UTC, PeterShaggyNoble commented on sdk.mjs
> +      (_, ref) => ({ quot: '"', amp: '&', lt: '<', gt: '>' })[ref],
```suggestion
      (_, ref) => ({ quot: '"', amp: '&', lt: '<', gt: '>' })[ref],
```

2023-11-23 13:35 UTC, adamrusted commented on sdk.mjs
> +      (_, ref) => ({ quot: '"', amp: '&', lt: '<', gt: '>' })[ref],
```suggestion
      (_, ref) => ({ quot: '"', amp: '&', lt: '<', gt: '>' }[ref]),
```

2023-11-23 16:29 UTC, PeterShaggyNoble approved these changes

2023-11-23 16:33 UTC, merged