Add Polestar
simple-icons/simple-icons pull request #9627
Opened 2023-09-24 20:17 UTC by PratyushJayachandran

![polestar](https://github.com/simple-icons/simple-icons/assets/35000807/6437096e-dd9e-4f97-8df5-14f644ca7c52)

**Issue:** closes #9513 

**Similarweb rank:** 18,915. See https://www.similarweb.com/website/polestar.com

### Checklist
  - [x] I updated the JSON data in `_data/simple-icons.json`
  - [x] I optimized the icon with SVGO or SVGOMG
  - [x] The SVG `viewbox` is `0 0 24 24`

### Description
SVG: Taken from https://www.polestar.com/w3-assets/safari-pinned-tab.svg
Color: Taken from logo `#000000`

2023-11-01 22:55 UTC, dgomes commented
Thank you soo much for your work :)

2023-11-24 15:12 UTC, PeterShaggyNoble requested changes

2023-11-24 15:12 UTC, PeterShaggyNoble commented on _data/simple-icons.json
> +            "guidelines": "https://media.polestar.com"
```suggestion
            "source": "https://commons.wikimedia.org/wiki/File:Polestar_logo_2020.svg"
```

2023-11-24 15:12 UTC, PeterShaggyNoble commented on icons/polestar.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Polestar</title><path d="M11.911 17.931c0 5.46-.01 5.688-.188 5.906-.158.188-.208.208-.247.089-.02-.08-.455-2.196-.95-4.6
```suggestion
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Polestar</title><path d="m12.549 0-.457.555v11.191h11.19l.554-.457-9.4-1.89zM.719 12.26l-.555.457L9.563 14.6l1.886 9.4.457-.555V12.26Z"/></svg>
```

2023-11-24 18:40 UTC, adamrusted approved these changes

2023-11-24 18:43 UTC, merged

2023-11-24 21:38 UTC, dgomes commented
🎉🙏