Review J letter icons
simple-icons/simple-icons pull request #9638
Opened 2023-09-26 17:11 UTC by jwr1

**Issue:** contributes to #9072

* Jameson - Update SVG
* Jeep - Update source and guidelines
* JFrog - Update hex
* JR Group - Update hex
* JUnit5 - Fix source link to use github.com, not githubusercontent.com

_Icon removals will be in separate PRs_

2023-10-07 20:34 UTC, adamrusted requested changes

2023-10-07 20:34 UTC, adamrusted commented on _data/simple-icons.json
>              "guidelines": "https://jfrog.com/brand-guidelines/"
```suggestion
            "source": "https://jfrog.com/brand-guidelines",
            "guidelines": "https://jfrog.com/brand-guidelines"
```

2023-10-07 20:34 UTC, adamrusted commented on icons/jameson.svg
We still need to keep the outline, as per their website homepage. I'm seeing differences between our version in black, and their website in cream though.
![image](https://github.com/simple-icons/simple-icons/assets/1830867/c68fe80b-6513-42f2-a4f6-2e1f31da5bf9)

2023-10-08 13:04 UTC, jwr1 commented on icons/jameson.svg
You're right, I only saw this version without the outline (before entering your id) and assumed they changed the logo:
![image](https://github.com/simple-icons/simple-icons/assets/47087725/9bc0d398-c40e-4a44-9f9a-d9d11ea0226d)

2023-10-08 13:07 UTC, jwr1 commented on icons/jameson.svg
Also, the simpleicons version doesn't have the trademark on it (™), should I add that too, since it's in the original:

![image](https://github.com/simple-icons/simple-icons/assets/47087725/9f89b819-63fd-4db6-8860-9b30acf7c533)

2023-10-08 13:44 UTC, adamrusted commented on icons/jameson.svg
Nope, we're clear to remove ™️ symbols, but should always keep ®️ icons unless they're used without elsewhere!

2023-10-08 14:31 UTC, jwr1 commented
Actually, don't merge yet. I just noticed the new jeep source doesn't match our current svg.

2023-10-08 14:59 UTC, jwr1 commented
It should be good now :+1:.

Also, what was the reason for my other pull requests being closed (#9639, #9642, and #9640)? There wasn't any real explanation besides:

> We never remove icons in this way. Closing.

and

> Please stop sending these kinds of PRs. Closing.

I can understand for Jenkins X, since they have 4.4k stars, it's already close to the necessary rank, and for JPEG, it's just a popular format, but Jabber has a rank of 2,777,993 and I've never even heard of it before.

2023-10-17 11:47 UTC, adamrusted requested changes

2023-10-17 11:47 UTC, adamrusted commented on _data/simple-icons.json
> +            "source": "https://en.wikipedia.org/wiki/File:Jeep_logo.svg"
```suggestion
            "source": "https://commons.wikimedia.org/wiki/File:Jeep_logo.svg"
```

2023-10-17 11:47 UTC, adamrusted commented on icons/jeep.svg
Seeing a slight difference when comparing to source, could you have another look please @jwr1?
Might just be a precision thing...
![image](https://github.com/simple-icons/simple-icons/assets/1830867/4bd877fe-e2d6-4be5-89f9-7e52e470076e)

2023-10-17 11:47 UTC, adamrusted commented on icons/jameson.svg
SVG is spot on for this one, thanks @jwr1! 🎉

2023-10-17 20:36 UTC, jwr1 commented on icons/jeep.svg
You were right; it needed a precision of 4 to work. It should be good now.

2023-10-18 13:12 UTC, adamrusted approved these changes
LGTM, thanks @jwr1 🎉

2023-10-18 13:14 UTC, merged