Add Hoppscotch
simple-icons/simple-icons pull request #9658
Opened 2023-09-28 14:30 UTC by PratyushJayachandran

![hoppscotch](https://github.com/simple-icons/simple-icons/assets/35000807/9a960a11-bcd4-4381-90cd-c8d6cff8d1a8)

**Issue:** closes #9072 

**Similarweb rank:** 298,826. See https://www.similarweb.com/website/hoppscotch.io

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description
SVG: Old SVG was moved to new location in repository: https://github.com/hoppscotch/hoppscotch/blob/65884293be0f1124c3db0c3fe985fe78b307d787/packages/hoppscotch-common/public/logo.svg
Color: Taken from logo background color `#10b981`

2023-10-25 08:19 UTC, adamrusted requested changes

2023-10-25 08:19 UTC, adamrusted commented on icons/hoppscotch.svg
Applying a 0.5pt outer stroke to the items, I'm spotting some [pretty major](https://github.com/simple-icons/simple-icons/assets/1830867/f35c20f6-7e57-483f-a40a-e3c90042ab43) differences. Any chance you can have another look please @PratyushJayachandran?

2023-10-25 15:47 UTC, PratyushJayachandran commented on icons/hoppscotch.svg
Should I increase it decrease the gap? Which color is the contributed svg

2023-10-26 06:10 UTC, PratyushJayachandran commented on icons/hoppscotch.svg
Looks like the red image is the one with less gap and black one is mine. I kept the gap around 1px so that it looks good on a small badge. Should I change it @adamrusted?

2023-10-26 12:16 UTC, adamrusted commented on icons/hoppscotch.svg
Yeah, the red image uses a 0.5pt gap, as is in our contrib guidelines. If we're moving toward a 1pt/px gap, we should ensure contrib guidelines reflect that - or highlight during the PR :)

2023-10-26 15:25 UTC, PratyushJayachandran commented on icons/hoppscotch.svg
Oh I remember it being 1px gap 😝 
Let's do 1 for this one. I had tried 0.5 first, it didn't seem good.

2023-10-30 08:04 UTC, merged