Update HP
simple-icons/simple-icons pull request #9659
Opened 2023-09-30 05:49 UTC by PratyushJayachandran

![hp](https://github.com/simple-icons/simple-icons/assets/35000807/ceaad787-df10-4f93-9486-00aa29f82fce)

**Issue:** contributes to #9072 

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description
SVG: Taken from https://brandcentral.hp.com/us/en/elements/hp-logo.html. Please review with the logo here. I found three different versions on their own website itself.
Color: Unchanged

2023-10-17 12:12 UTC, adamrusted requested changes

2023-10-17 12:12 UTC, adamrusted commented on icons/hp.svg
I'm spying a slight difference when comparing to `HP_logo_black.svg`.
![image](https://github.com/simple-icons/simple-icons/assets/1830867/71938635-c3e9-4cf2-bcc6-882db4c51e49)

Could you take another look please @PratyushJayachandran? 🙏

2023-10-19 06:56 UTC, PratyushJayachandran commented on icons/hp.svg
Seems like a precision issue. I increased the precision to 4.

2023-10-26 06:08 UTC, PratyushJayachandran commented on icons/hp.svg
Is there still an issue @adamrusted?

2023-10-26 12:17 UTC, adamrusted commented on icons/hp.svg
Not looked at it yet, bear with.

2023-11-03 09:47 UTC, adamrusted approved these changes

2023-11-03 09:48 UTC, merged