Update Hack The Box
simple-icons/simple-icons pull request #9661
Opened 2023-09-30 06:09 UTC by PratyushJayachandran

![hackthebox](https://github.com/simple-icons/simple-icons/assets/35000807/4ae4d2c1-b634-4d26-96b6-b0d70a21f9cd)

**Issue:** contributes to #9072 

**Similarweb rank:** 18,467. See https://www.similarweb.com/website/hackthebox.com

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description
SVG: Taken from zip at https://www.hackthebox.com/contact-us. File `HTB-Logo-RGB_BRC-Site-300.svg`
Color: Taken form logo `#9fef00`

2023-11-03 09:51 UTC, adamrusted requested changes

2023-11-03 09:51 UTC, adamrusted commented on icons/hackthebox.svg
Seeing [quite significant differences](https://github.com/simple-icons/simple-icons/assets/1830867/0855ab0f-2132-411f-af6e-adb83bd0a996) when comparing your PR to the source file you mentioned. Could you take another look please @PratyushJayachandran?

2023-11-06 06:48 UTC, PratyushJayachandran commented on icons/hackthebox.svg
![image](https://github.com/simple-icons/simple-icons/assets/35000807/285fa9f0-723f-4aaa-b8ef-cc1f5172c5eb)
I used the file highlighted in the image above.
I have updated the icon again with precision 4. Please recheck @adamrusted

2023-11-16 09:12 UTC, adamrusted approved these changes

2023-11-16 09:14 UTC, merged