Add SWI Prolog
simple-icons/simple-icons pull request #9687
Opened 2023-10-06 03:17 UTC by DenverCoder1

![image](https://github.com/simple-icons/simple-icons/assets/20955511/fc1e367c-73aa-4907-8794-118c41d7a895)

**Issue:** closes #6110

**Similarweb rank:** 296,571

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

Full logo: https://www.swi-prolog.org/icons/vector/swipl-logo.svg
Full logo without text: https://starbeamrainbowlabs.com/images/logos/swi-prolog.svg
Monochrome: https://seekicon.com/free-icon/prolog_1

The monochrome version was used as a starting point since a lot of the effort is already done including modifications such as the outline around the beak.

Color: `#ed1c24` (from the [JetBrains Prolog extension logo](https://plugins.jetbrains.com/plugin/13954-prolog) which has flat colors)

2023-10-06 03:22 UTC, ThatOneCalculator commented
> https://github.com/simple-icons/simple-icons/actions/runs/6427071279/job/17452170962?pr=9687

Should probably be above Swift (line 12979)

2023-10-06 05:33 UTC, PratyushJayachandran requested changes

2023-10-06 05:33 UTC, PratyushJayachandran commented on _data/simple-icons.json
> +            "source": "https://seekicon.com/free-icon/prolog_1"
```suggestion
            "source": "https://www.swi-prolog.org/icons/vector/swipl-logo.svg"
```
We would prefer to use official source always when available.

2023-10-06 05:33 UTC, PratyushJayachandran commented on icons/swiprolog.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>SWI Prolog</title><path d="M4.584 0c-.28 0-.568.025-.865.076.168.258.337.489.492.723.455.684.489 2.2.123 3.28a10.63 10.63
It doesn't match with the original. [See here!](https://github.com/simple-icons/simple-icons/assets/35000807/10fb07cc-0c5d-473e-9bc4-bbce4166881d)

2023-10-06 05:59 UTC, DenverCoder1 commented
@PratyushJayachandran The latest commit now has a monochrome version I made myself using the original logo from the SWI Prolog website. In order to make it look better in monochrome, I made the beak smaller so it should line up with the original besides the beak.

[image](https://github.com/simple-icons/simple-icons/assets/20955511/2e4550f2-19ff-49e3-b9a2-3999e0a7acc8)

2023-10-06 06:27 UTC, PratyushJayachandran commented
> @PratyushJayachandran The latest commit now has a monochrome version I made myself using the original logo from the SWI Prolog website. In order to make it look better in monochrome, I made the beak smaller so it should line up with the original besides the beak.
> 
> [image](https://github.com/simple-icons/simple-icons/assets/20955511/2e4550f2-19ff-49e3-b9a2-3999e0a7acc8)

Thank you for contributing and taking the effort to make the logo monochrome yourself. Unfortunately I still see some differences like this:
![image](https://github.com/simple-icons/simple-icons/assets/35000807/90062b80-72d3-45b3-8db3-0e17f00899ea)
Could be happening because of scaling issues. Can you take another look. I hope you are using this as source: https://www.swi-prolog.org/icons/vector/swipl-logo.svg

2023-10-06 07:13 UTC, DenverCoder1 commented
Not sure why it would be different, could be from transforming before and after optimizations and rounding errors.

I made a new one following the same steps but without multiple exports and optimizations. Hopefully it is correct now.

It looks to me like it is resolved. [image](https://github.com/simple-icons/simple-icons/assets/20955511/ceb2ac66-6089-466a-a012-aa1fb9c9c799) [image](https://github.com/simple-icons/simple-icons/assets/20955511/b397bc66-ce77-4997-acae-24ab2306bca1)

2023-10-10 04:27 UTC, PratyushJayachandran commented
> I made a new one following the same steps but without multiple exports and optimizations. Hopefully it is correct now.
> 
> It looks to me like it is resolved. [image](https://github.com/simple-icons/simple-icons/assets/20955511/ceb2ac66-6089-466a-a012-aa1fb9c9c799) [image](https://github.com/simple-icons/simple-icons/assets/20955511/b397bc66-ce77-4997-acae-24ab2306bca1)

Unfortunately I still see [some differences here!](https://github.com/simple-icons/simple-icons/assets/35000807/85dddaac-e1e9-4b9a-8bc1-6e56a97b9ab2)
Are you comparing the source to the SVGO optimized image?

2023-10-10 20:49 UTC, DenverCoder1 commented
I've tried doing it again but using the svgo CLI with precision set to 4 (previously I was using https://github.com/jakearchibald/svgomg which may have been causing differences?)

2023-10-10 21:54 UTC, PratyushJayachandran commented
> I've tried doing it again but using the svgo CLI with precision set to 4 (previously I was using https://github.com/jakearchibald/svgomg which may have been causing differences?)

I don't think that was what was causing the issue. It could be precision though.. I'll compare again.

2023-10-12 07:28 UTC, PratyushJayachandran submitted a review, later dismissed

2023-10-12 07:28 UTC, PratyushJayachandran commented on icons/swiprolog.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>SWI Prolog</title><path d="M19.4442.0007c-.9367.0159-2.3649.3131-3.3203 1.786-1.2738-.5732-2.6751-.8757-4.14-.8757-1.481
```suggestion
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>SWI Prolog</title><path d="M7.96 6.793a2.072 2.072 0 1 0 0 4.143 2.072 2.072 0 0 0 0-4.143zm0 3.397a1.326 1.326 0 1 1-.002-2.65 1.326 1.326 0 0 1 .001 2.65zm-.19-1.792a.397.397 0 1 1-.795 0 .397.397 0 0 1 .795 0zm9.953 2.538a2.072 2.072 0 1 0 0-4.143 2.072 2.072 0 0 0 0 4.143zm0-3.397a1.325 1.325 0 1 1 0 2.65 1.325 1.325 0 0 1 0-2.65zm-.984.86a.397.397 0 1 1 .794 0 .397.397 0 0 1-.794 0zm2.981-4.021c-.326-1.047-.718-3.103.705-4.296 0 0-2.746-.648-4.278 1.707A10.178 10.178 0 0 0 12 .907c-1.481 0-2.894.319-4.18.896C6.29-.57 3.532.082 3.532.082c1.457 1.221 1.013 3.345.683 4.366C2.381 6.49 1.253 9.25 1.253 12.29c0 2.42 1.554 5.169 1.865 8.853l1.968-1.705s.547.367 1.612.748A2.482 2.482 0 0 0 6.403 24a1.995 1.995 0 0 1-.01-.199c0-1.03.807-1.865 1.802-1.865.996 0 1.803.835 1.803 1.865l-.002.059a2.474 2.474 0 0 0 .276-2.909 18.31 18.31 0 0 0 3.255.019 2.472 2.472 0 0 0 .288 2.89c-.001-.02-.003-.039-.003-.059 0-1.03.807-1.865 1.803-1.865.996 0 1.803.835 1.803 1.865 0 .067-.004.133-.01.199a2.478 2.478 0 0 0-.234-3.767c1.153-.398 1.74-.795 1.74-.795l1.968 1.705c.312-3.684 1.865-6.434 1.865-8.853 0-3.075-1.155-5.864-3.027-7.912zm-17.683 8.55c-.147.744.63 1.316.63 1.316s.934-.233 1.081-.976c-.184.928-1.217 1.657-1.217 1.657s-.677-1.067-.494-1.996zm.543 2.055c-.147.743.63 1.315.63 1.315s.933-.233 1.08-.976c-.183.929-1.217 1.657-1.217 1.657s-.677-1.067-.493-1.996zm1.937-.367s.934-.233 1.08-.976c-.183.928-1.216 1.657-1.216 1.657s-.677-1.067-.494-1.996c-.147.743.63 1.315.63 1.315zm-.894 4.446s-.677-1.067-.493-1.996c-.147.744.63 1.316.63 1.316s.933-.234 1.08-.976c-.183.928-1.217 1.656-1.217 1.656zm1.3-1.711s-.677-1.067-.493-1.996c-.147.743.629 1.315.629 1.315s.934-.233 1.081-.976c-.184.929-1.217 1.657-1.217 1.657zm1.3-1.684s-.676-1.067-.493-1.996c-.147.744.63 1.316.63 1.316s.934-.234 1.081-.976c-.184.928-1.217 1.656-1.217 1.656zm5.717 1.07c0-1.403-1.908-3.327-2.319-4.891a4.222 4.222 0 0 1-2.542.85 4.247 4.247 0 1 1 4.247-4.246c0 .19-.017.376-.042.56a2.395 2.395 0 0 1 1.354.01 4.263 4.263 0 0 1-.043-.57 4.247 4.247 0 1 1 4.247 4.247c-.97 0-1.862-.33-2.578-.878-.395 1.57-2.324 3.507-2.324 4.918zm8.152-3.436c.184.929-.493 1.996-.493 1.996s-1.034-.729-1.217-1.657c.147.743 1.081.976 1.081.976s.776-.572.63-1.315zm-3.554.71c.148.742 1.082.976 1.082.976s.776-.572.63-1.316c.183.93-.494 1.996-.494 1.996s-1.034-.728-1.218-1.656zm1.302 1.683c.147.743 1.08.976 1.08.976s.777-.572.63-1.315c.184.929-.493 1.996-.493 1.996s-1.034-.728-1.217-1.657zm2.516 3.368s-1.033-.728-1.217-1.656c.147.742 1.082.976 1.082.976s.775-.572.629-1.316c.183.93-.494 1.996-.494 1.996zm.55-2.083s-1.033-.728-1.217-1.657c.147.743 1.081.976 1.081.976s.777-.572.63-1.315c.183.929-.494 1.996-.494 1.996zm-.675-3.711c.148.743 1.082.976 1.082.976s.776-.572.63-1.315c.183.929-.494 1.996-.494 1.996s-1.034-.729-1.218-1.657zm-6.244-1.97c0 .728-.592 1.674-1.166 2.589-.33.526-.65 1.038-.881 1.531-.232-.493-.552-1.005-.882-1.531-.573-.915-1.165-1.861-1.165-2.589A2.04 2.04 0 0 1 11.94 9.27a2.04 2.04 0 0 1 2.047 2.03z"/></svg>
```

Unfortunately I still see [some differences.](https://github.com/simple-icons/simple-icons/assets/35000807/72646c7e-eb81-42c3-aa10-b1e5625b3590)
 This suggestion should fix it but I will request someone else to review @simple-icons/icon-review

2023-12-03 09:34 UTC, PratyushJayachandran commented
> Most of the icon looks spot on - there's just some differences around the beak and eyes, and I think how we've generated the path.
> 
> My general rule-of-thumb is to use an _outer_ stroke of 0.5 or 1px, whereas this appears to use an inner stroke. There is no 'right' way of doing it, but just wanted to confirm with you. See my generated image overlaying your PR below.
> 
> ![image](https://private-user-images.githubusercontent.com/1830867/286281959-c4ed288b-84c7-4dfd-a3b3-35a2aead545b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1OTEzMzMsIm5iZiI6MTcwMTU5MTAzMywicGF0aCI6Ii8xODMwODY3LzI4NjI4MTk1OS1jNGVkMjg4Yi04NGM3LTRkZmQtYTNiMy0zNWEyYWVhZDU0NWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDNUMDgxMDMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2Y4OGU4NTE3YmQ2ZDcwMTY2ZWUwNjRkMmMwZWQ2ZWUxMTRhYTg1MTdiMTUwM2UxMTE5MGJiN2QwMTU0OWUxNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Hx0KyVnz8vjcTWgaVuwViExaH6boWNrSMQv5D5ecOJM)

![image](https://github.com/simple-icons/simple-icons/assets/35000807/d455be61-c763-4fd9-a3d3-4787ea8e94eb)

It is cutting the eyes @adamrusted, that is why I did inner stroke instead

2023-12-07 15:45 UTC, PeterShaggyNoble commented
Are you still working on this one, @DenverCoder1? I agree with your choice of cut-out to avoid cutting into the eyes but I'm still seeing some of the same differences mentioned above.

Also, if there's a page on their website that includes the original SVG then we should use that as `source` URL to avoid potential future link rot.

2023-12-07 17:05 UTC, DenverCoder1 commented
I'll let @PratyushJayachandran or anyone else who wants take over this issue. It seems with my current workflow, it always ends up with slight differences.

2023-12-07 17:26 UTC, closed without merging

2023-12-07 17:26 UTC, PeterShaggyNoble commented
Closing this one, so; if anyone else would like to take it up then please open a new PR for it. Thanks for your work on it so far, @DenverCoder1 👍🏻