add sqlalchemy
simple-icons/simple-icons pull request #9690
Opened 2023-10-06 09:07 UTC by Niccolum

**Issue:** [closes #](https://github.com/simple-icons/simple-icons/issues/5346)

**Similarweb rank:**
https://www.similarweb.com/website/sqlalchemy.org/#overview
Global Rank: 125,029
Country Rank: 153,737
Category Rank: 2,972

### Checklist

- [ x ] I updated the JSON data in `_data/simple-icons.json`
- [ x ] I optimized the icon with SVGO or SVGOMG
- [ x ] The SVG `viewbox` is `0 0 24 24`

2023-10-06 16:41 UTC, adamrusted approved these changes
Icon looks spot on to me, I'd remove the direct link as the source URL, and instead use the guidelines link. Will merge this now, and we can get this closed. Thanks @Niccolum! 🎉

2023-10-06 16:41 UTC, adamrusted commented on _data/simple-icons.json
> +            "guidelines": "https://github.com/sqlalchemy/sqlalchemy/discussions/7672#discussioncomment-2157650",
```suggestion
            "source": "https://github.com/sqlalchemy/sqlalchemy/discussions/7672#discussioncomment-2157650",
```

2023-10-06 16:59 UTC, adamrusted commented on .jsonschema.json
> +        "pattern": "^https://github\\.com/[^/]+/[^/]+/(blob/[a-f\\d]{40}/[^\\s]+)|(tree/[a-f\\d]{40}(/[^\\s]+)?)|(((issues)|(pull)|(discussions))/\\d+#(issuecomment|discussioncomment)-\\d+)$"
@simple-icons/maintainers - can someone confirm the change to the JSON schema is okay for merging? Rest of the PR is fine.

2023-10-12 15:15 UTC, mondeja requested changes

2023-10-12 15:15 UTC, mondeja commented on .jsonschema.json
> +        "pattern": "^https://github\\.com/[^/]+/[^/]+/(blob/[a-f\\d]{40}/[^\\s]+)|(tree/[a-f\\d]{40}(/[^\\s]+)?)|(((issues)|(pull)|(discussions))/\\d+#(issuecomment|discussioncomment)-\\d+)$"
Please, group the words as `(issues)|(pull)|(discussions)`:

```suggestion
        "pattern": "^https://github\\.com/[^/]+/[^/]+/(blob/[a-f\\d]{40}/[^\\s]+)|(tree/[a-f\\d]{40}(/[^\\s]+)?)|(((issues)|(pull)|(discussions))/\\d+#((issuecomment)|(discussioncomment))-\\d+)$"
```

2023-10-20 06:14 UTC, Niccolum commented
Hello everyone!

@adamrusted i updated @mondeja 's suggestion. Can we merge it now?

2023-10-21 02:19 UTC, mondeja approved these changes
Thanks!

2023-10-21 02:21 UTC, merged