Airtel
simple-icons/simple-icons pull request #9709
Opened 2023-10-11 08:42 UTC by sumit2011

**Issue:** closes #

**Similarweb rank:**

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description

2023-10-12 07:02 UTC, PratyushJayachandran commented
@sumit2011 Please add some details to the Pull Request.
1. Where is the SVG taken from?
2. I see some brand guidelines on their page: https://www.airtel.in/logo-tune. Please include guidelines when available.
3. Why did you chose the stacked version of the logo? Just the logo-mark should be enough unless the brand insists.

2023-10-13 15:54 UTC, sumit2011 commented
@PratyushJayachandran   hey i am little bit confused that why i am getting error in uploading the svg file.

2023-11-30 19:10 UTC, adamrusted requested changes
I'm seeing a slight difference at the sides of the icon, potentially from the shape being stretched to fill the `24*24` viewport?
Could you try building from source again with a precision of 4 decimals (`npx svgo icons/airtel.svg -p 4` and see if that gives us a better result @sumit2011?

![image](https://github.com/simple-icons/simple-icons/assets/1830867/e3335929-5acf-41ed-b68a-4dc43a8bdb00)

2023-12-14 10:33 UTC, PeterShaggyNoble submitted a review, later dismissed

2023-12-14 10:33 UTC, PeterShaggyNoble commented on _data/simple-icons.json
> +            "source": "https://www.airtel.in"
```suggestion
            "hex": "E40000",
            "source": "https://www.airtel.in/logo-tune"
```

2023-12-14 10:33 UTC, PeterShaggyNoble commented on icons/airtel.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Airtel</title><path d="M7.133 24c-1.122 0-1.937-.379-2.424-1.134-1.225-1.87.026-4.218.621-5.142a7.835 7.835 0 0 1 1.612-1
```suggestion
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Airtel</title><path d="M7.137 23.862c.79 0 1.708-.19 2.751-.554 1.55-.538 2.784-1.281 3.986-2.009l.316-.205a29.733 29.733 0 0 0 3.764-2.72 16.574 16.574 0 0 0 5.457-7.529c.395-1.138.949-3.384.268-5.487a7.117 7.117 0 0 0-2.862-3.749c-.158-.126-1.898-1.47-5.203-1.47-3.005 0-6.31 1.107-9.806 3.32l-.11.08-.317.205a20.133 20.133 0 0 0-2.309 1.693C1.585 6.813-.091 9.106.004 11.067c.031.79.427 1.534 1.075 2.008a3.472 3.472 0 0 0 2.214.68c1.803 0 3.765-.948 5.109-1.74l.253-.157.696-.443.237-.158c1.898-1.234 3.875-2.515 6.105-3.258a5.255 5.255 0 0 1 1.55-.285 3.163 3.163 0 0 1 .664.08 2.112 2.112 0 0 1 1.47 1.106c.523 1.012.396 2.61-.316 4.08a17.871 17.871 0 0 1-4.887 5.836 19.488 19.488 0 0 1-3.194 2.215l-.095.031a9.634 9.634 0 0 1-1.471.696l-.08.032-.41.158c-2.23.57-.87-1.329-.87-1.329.474-.537.98-1.028 1.518-1.502.316-.269.633-.554.933-.854l.064-.063c.395-.38.933-.902.901-1.645-.047-.98-1.075-1.582-2.056-1.613h-.063c-.95 0-1.819.522-2.404.98a7.27 7.27 0 0 0-1.598 1.74c-.6.901-1.85 3.226-.632 5.077.49.743 1.313 1.123 2.42 1.123z"/></svg>
```

2023-12-14 11:10 UTC, adamrusted approved these changes

2023-12-14 11:11 UTC, merged