Add doxygen
simple-icons/simple-icons pull request #9735
Opened 2023-10-16 05:33 UTC by PratyushJayachandran

![doxygen](https://github.com/simple-icons/simple-icons/assets/35000807/644acabf-f486-428d-b28f-dceece4e02f9)

**Issue:** closes #9734 

**Similarweb rank:** 474,701. See https://www.similarweb.com/website/doxygen.nl
**GitHub Stars:** 5k. See https://github.com/doxygen/doxygen/tree/master

### Checklist

- [x] I updated the JSON data in `_data/simple-icons.json`
- [x] I optimized the icon with SVGO or SVGOMG
- [x] The SVG `viewbox` is `0 0 24 24`

### Description
SVG: Taken from https://github.com/doxygen/doxygen/blob/2e73e6a53abe00a57b7eb0ea5ed6474baf4ebab7/templates/html/doxygen.svg
Color: `#2c4aa8` taken from website header www.doxygen.nl

2023-10-16 07:51 UTC, PratyushJayachandran commented on sdk.mjs
> +      (_, ref) => ({ quot: '"', amp: '&', lt: '<', gt: '>' }[ref]),
I tried several times. The linter is putting it.

2023-11-19 14:12 UTC, adamrusted requested changes

2023-11-19 14:12 UTC, adamrusted commented on icons/doxygen.svg
I'm seeing some differences on this one, @PratyushJayachandran - would you mind taking another look?
![image](https://github.com/simple-icons/simple-icons/assets/1830867/f4dd2fb5-a1d9-48e0-8b6c-748acd38c03e)

2023-11-24 16:18 UTC, PeterShaggyNoble approved these changes
I'm not seeing those differences, @adamrusted, everything lines up perfectly. Could you have another look before merging, though, in case I'm wrong?

2023-11-29 19:18 UTC, service-paradis approved these changes
LGTM 🎉

2023-11-29 19:19 UTC, merged