Update: Read.cv
simple-icons/simple-icons pull request #9784
Opened 2023-10-27 10:09 UTC by 5ouma

### Description

Updated `Read.cv` details below.

- Capitalize the name from `read.cv` to `Read.cv`.
- Update the source URL to a more readable one.

2023-10-30 07:54 UTC, adamrusted requested changes

2023-10-30 07:54 UTC, adamrusted commented on icons/readdotcv.svg
Hey @5ouma - I'm seeing some [slight differences](https://github.com/simple-icons/simple-icons/assets/1830867/58510a97-b20d-46a2-ab1e-bbecf0e875b6) between your PR in black, and the source image in red. Might just be an optimisation issue, but would you mind retrying this?

2023-10-30 08:57 UTC, 5ouma commented on icons/readdotcv.svg
Thank you @adamrusted!
I retried modifying the image, and does it work?

![readdotcv](https://github.com/simple-icons/simple-icons/assets/101255979/4a9d8f3c-58a2-4fe0-b022-3198465b7f48)

2023-10-30 09:59 UTC, adamrusted commented on icons/readdotcv.svg
Hey @5ouma - could you commit your changes to this branch, and I'll compare.

2023-10-30 10:12 UTC, 5ouma commented on icons/readdotcv.svg
I pushed! Could you check it, please @adamrusted?

2023-11-03 09:58 UTC, adamrusted requested changes

2023-11-03 09:58 UTC, adamrusted commented on icons/readdotcv.svg
Thanks for the update @5ouma - though unfortunately I'm still seeing some differences. Could you try building from source again?
![image](https://github.com/simple-icons/simple-icons/assets/1830867/4831ede4-4b36-4159-aff6-02e60db566f4)

2023-11-03 10:07 UTC, 5ouma commented on icons/readdotcv.svg
I think these differences are made when being compressed with SVGO.
How much should I compress the SVG file?

2023-11-03 10:10 UTC, 5ouma commented on icons/readdotcv.svg
This file isn't compressed and passed the `svglint`.
![readdotcv](https://github.com/simple-icons/simple-icons/assets/101255979/c6243459-f001-42d2-b91b-e47b72de4435)

2023-11-03 10:27 UTC, 5ouma commented on icons/readdotcv.svg
Is there no need to compress?

2023-11-03 11:11 UTC, adamrusted commented on icons/readdotcv.svg
If its passing the linter, it's usually good to go!

2023-11-03 11:14 UTC, 5ouma commented
@adamrusted, it must be ready to merge this PR!

2023-11-15 15:57 UTC, adamrusted approved these changes

2023-11-15 15:59 UTC, merged