Request: Ritz Carlton
simple-icons/simple-icons pull request #9872
Opened 2023-11-19 02:55 UTC by khamkarsuraj

**Issue:** closes #

**Similarweb rank:**

### Checklist

- [ ] I updated the JSON data in `_data/simple-icons.json`
- [ ] I optimized the icon with SVGO or SVGOMG
- [ ] The SVG `viewbox` is `0 0 24 24`

### Description

2023-11-19 02:57 UTC, khamkarsuraj commented
Can someone help me out why these test cases are failing?

2023-11-19 04:28 UTC, khamkarsuraj commented
How to convert file format into below format?

User
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Riseup</title><path d="M10.5 24l-1.485-9.007-8.961-1.738L8.16 9.06 7.045 0l6.495 6.414 8.271-3.861-4.093 8.16 6.228 6.673-9.024-1.372z"/></svg>

2023-11-19 13:46 UTC, adamrusted commented
Hey @khamkarsuraj  - please review our [contribution guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) on how to submit icons to the project.
At a glance, it would appear you've left whitespace in the SVG file and the single path is wrapped in a group, which will not pass our linters. Any issues, let me know and one of us can lend a hand.

2023-11-19 16:03 UTC, khamkarsuraj commented
Hello @adamrusted
I read contribution guidelines but not good at preparing svg icon.
I have svg file ready with some other format, if you can help me to clear linters that would be helpful.

Attached unformatted svg for reference,

![ritzcarlton](https://github.com/simple-icons/simple-icons/assets/112414255/1174f226-b804-4496-993a-5dc450c3bb1a)

2023-11-19 17:44 UTC, adamrusted commented
Hey @khamkarsuraj - if you run `npm install` and then `npx svgo icons/ritzcarlton.svg` then most of the heavy lifting should be done for you on the formatting front. Also worth checking it over with `npm run lint` to ensure everything is formatted correctly!

2023-11-19 21:03 UTC, khamkarsuraj commented
Hello @adamrusted 
Thank you for your reply. I used command line tool to optimize the svg file but still getting below error.

```
x icons/ritzcarlton.svg
  x icon-size Size of <path> must be exactly 24 in one dimension; the size is c
              urrently 16.252 x 23.371
  x icon-centered <path> must be centered at (12, 12); the center is currently 
                  (11.658, 12.084) 
```

2023-11-19 21:15 UTC, khamkarsuraj commented
Hello @adamrusted ,
Thank you very much for you help. I am able to clear all test cases and ready to merge. Please, have a look at my commit.

2023-11-19 21:46 UTC, khamkarsuraj commented
Hello @PratyushJayachandran ,
Please, review the files changed and accept my PR.

2023-11-20 08:26 UTC, PratyushJayachandran requested changes

2023-11-20 08:26 UTC, PratyushJayachandran commented on icons/ritzcarlton.svg
The contributed icon is not matching up with the source. [See screenshot!](https://github.com/simple-icons/simple-icons/assets/35000807/e75248bf-01ad-4457-8a87-9a169a8310c5)
Red is the original and black is the contribution.

@khamkarsuraj please scale the SVG proportionally to correct this error. The icon only needs to touch any 2 parallel sides of the 24px by 24px view box. So when scaling, set the largest dimension(height in this particular logo) to 24px and allow the other dimension to be scaled proportionally.

2023-11-20 17:12 UTC, khamkarsuraj commented on icons/ritzcarlton.svg
Hey @PratyushJayachandran,

Thank you for the review comments. I addressed your comments and updated patch accordingly.
Please have a look at the updated icon.

2023-11-21 05:40 UTC, PratyushJayachandran commented on icons/ritzcarlton.svg
I still see [some differences](https://github.com/simple-icons/simple-icons/assets/35000807/1dc4cbfa-1177-446f-ac66-096f5d0101c3) when comparing with the original superimposed on the contribution in black. Please give it another go and compare with original you provided to cross check contribution.

2023-11-22 19:29 UTC, khamkarsuraj commented on icons/ritzcarlton.svg
Hello @PratyushJayachandran,
I worked on this. Please, have a look at updated icon.
BTW, which tool are you using to compare the images.

2023-11-24 00:42 UTC, PratyushJayachandran requested changes

2023-11-24 00:42 UTC, PratyushJayachandran commented on icons/ritzcarlton.svg
The software doesn't matter. Inkscape or Illustrator should be good enough. From what I see, your contribution is of size 16px by 24px whereas the original scaled down should be 16.2524px by 24px. Check on your software if the precision is limited.

To prevent this PR from dragging further, I will commit the correct icon and request @simple-icons/icon-review to take a look.

2023-11-24 00:42 UTC, PratyushJayachandran commented on icons/ritzcarlton.svg
> +<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Ritz Carlton</title><path d="M16.457 22.024c-.138.139-.13.287.034.416.114.096.158.086.306-.06.164-.165.164-.182.033-.32-.
```suggestion
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Ritz Carlton</title><path d="M16.527 22.025c-.14.138-.132.285.036.415.114.096.158.087.308-.06.168-.165.168-.182.036-.32-.177-.165-.238-.174-.38-.035zm-9.27.017c-.08.095-.08.164.009.303.062.104.15.182.203.182.053 0 .14-.078.203-.182.123-.19.017-.424-.203-.424-.062 0-.159.052-.212.12zm6.174-.087c-.079.096-.088.174-.008.303.114.226.194.226.379.026.115-.12.115-.173.026-.303-.14-.182-.264-.19-.397-.026zm-3.078-.017c-.141.139-.132.286.035.416.194.164.477-.104.335-.32-.123-.191-.238-.226-.37-.096zm3.863-.39c-.035.563-.035 1.092 0 1.109.027.017.46.043.97.052l.927.026-.01-.563-.008-.555-.388-.06c-.538-.078-1.49-.087-1.49-.009zm1.165.347c.203.182.203.25-.018.476-.168.182-.176.182-.353.026-.203-.173-.23-.39-.07-.546.14-.138.247-.13.44.044zm-4.19-.356c-.035.035-.062.33-.062.659v.598l.944-.026.944-.026V21.53l-.882-.026c-.485-.009-.909 0-.944.034zm1.12.373c.15.165.15.182-.009.39-.202.277-.211.277-.467.008-.203-.207-.203-.216-.044-.39.203-.216.326-.216.52-.008zm-3.475-.347-.75.052V22.744h1.852v-.607c0-.702.097-.65-1.102-.572zm.37.33c.203.182.203.25-.017.485l-.177.182-.22-.217-.22-.216.176-.191c.22-.225.247-.234.458-.043zm2.602-5.667c-.15.243-.414.503-.688.685-.44.277-.45.277-.211.346.308.078.661.399.661.598 0 .39-.652.494-1.023.156-.212-.19-.23-.2-.309-.052a2.644 2.644 0 0 1-.273.32l-.194.174.264.277c.142.156.265.303.283.32.009.027.097-.043.194-.147.247-.26.732-.26.917 0 .22.304.168.58-.141.884-.441.433-1.438.511-2.126.165-.458-.225-.529-.893-.14-1.291l.184-.19-.29-.148a2.73 2.73 0 0 1-.486-.32c-.185-.165-.185-.165-.344.077-.088.13-.256.312-.37.408l-.212.155.309.286c.264.234.317.338.317.642 0 .64-.388.961-1.164.961-.265 0-.406-.06-.609-.251-.29-.286-.317-.485-.114-.771.158-.225.273-.243.476-.06.141.12.159.103.212-.226.053-.32.035-.399-.16-.572-.281-.251-.37-.251-.44.009-.062.251-.327.355-.573.225-.247-.121-.336-.624-.15-.884.202-.277.176-.329-.124-.329-.353 0-.785-.217-1.032-.502-.23-.269-.37-.2-.185.086.08.113.423.84.767 1.63.344.788.68 1.515.732 1.62.08.155.07.225-.044.355-.194.207-.194.294.07.875.336.762.495 1.49.398 1.828-.044.156-.062.32-.036.355.027.043 2.682.078 5.91.078h5.857v-.598c0-.572.318-1.707.547-1.958.115-.13.08-.494-.062-.598-.114-.086-.053-.286.485-1.481.344-.763.741-1.612.891-1.898.15-.277.238-.528.212-.554-.027-.026-.194.086-.38.25-.379.356-.714.512-1.075.512-.3 0-.327.043-.133.225.282.278.053 1.075-.309 1.075-.105 0-.405-.286-.458-.433-.027-.087-.115-.061-.318.086-.167.121-.264.26-.238.33.027.06.044.233.044.38 0 .26.009.27.168.122.22-.2.458-.147.6.113.088.173.07.268-.062.528-.168.33-.362.433-.82.433-.98 0-1.465-1.013-.759-1.603l.273-.216-.308-.338c-.168-.182-.318-.381-.344-.45-.027-.087-.133-.044-.37.164-.177.147-.38.277-.45.277-.177 0-.168.052.061.373.256.355.256.78-.009 1.048-.45.468-1.86.503-2.32.044-.3-.286-.335-.754-.088-.97.22-.2.662-.183.856.025.15.165.159.165.406-.095.14-.147.255-.295.255-.33 0-.025-.123-.19-.264-.355-.247-.277-.274-.294-.38-.156-.185.234-.529.33-.776.208-.432-.208-.255-.762.283-.875.255-.06.361-.216.14-.216-.193 0-.846-.598-1.022-.927l-.16-.304-.229.39zm.503.659.247.26-.185.234c-.238.294-.238.554 0 .849.097.13.159.277.132.338l-.185.32a1.06 1.06 0 0 0-.132.442c0 .295.326.762.679.97.617.347 1.923.26 2.328-.164.203-.208.433-.278.433-.13 0 .156.467.624.785.788l.317.165h-.264c-.141 0-.644-.035-1.112-.078-2.24-.217-4.251-.2-7.356.052l-.618.052.424-.269c.23-.147.414-.294.414-.329 0-.043.08-.165.168-.277l.168-.217.273.234c.794.65 2.4.485 2.867-.295.194-.32.176-.849-.027-1.117-.167-.208-.167-.217 0-.442.203-.277.212-.59.036-.823s-.168-.381.061-.615c.238-.252.256-.252.547.052zm-3.81 1.828c-.027.286-.089.32-.256.156-.168-.174-.088-.442.123-.399.106.026.15.104.133.243zm7.347-.173c.07.112-.035.433-.14.433-.116 0-.195-.234-.133-.39.053-.147.194-.173.273-.043zm2.593.918c-.079.095-.132.104-.202.035-.071-.07-.053-.13.079-.226.203-.147.3-.017.123.19zm-.396 1.438c.211.477.035.633-.362.33a.983.983 0 0 0-.459-.183c-.194 0-.159-.034.212-.207.247-.113.45-.208.467-.208.018-.01.08.112.142.268zM6.7 20.855c.256.06.344.2.115.2-.097 0-.291.094-.432.216-.274.225-.37.208-.37-.06 0-.287.176-.52.334-.451.08.026.239.078.353.095zm8.618.39c2.408.19 2.382.19 2.346.329l-.211.84-.186.72H6.895l-.053-.243a7.6 7.6 0 0 0-.22-.745c-.088-.286-.168-.563-.168-.615 0-.087 2.064-.286 4.322-.425.733-.043 3.246.026 4.543.139zm-3.264 2.278c4.023 0 5.072-.026 5.231-.112.238-.13.326-.087.256.112-.053.113-.67.13-5.487.13-5.398 0-5.424 0-5.424-.173 0-.164.017-.164.203-.07.15.087 1.287.113 5.221.113zM9.771 3.96c-.08.086-.062.45.035.64.053.087.309.295.573.46.256.165.52.381.574.476.114.217.264.234.264.035 0-.078-.273-.407-.617-.745-.335-.33-.617-.65-.617-.72 0-.13-.133-.224-.212-.146zm-2.54-.312c-.168.095-.221.424-.071.424.053 0 .115 0 .141.009.035 0 .141-.113.23-.26.167-.26.167-.269.008-.269a.675.675 0 0 0-.308.096zm8.397-.217c0 .035.132.2.3.381.458.503.696 1.205.705 2.08 0 .77-.14 1.239-.564 1.828-.212.286-.415.26-.247-.035.14-.26.238-.832.15-.892-.036-.018-.177.173-.3.424-.133.26-.574.91-.988 1.456-.944 1.256-1.164 1.62-1.244 2.08-.114.632-.238.346-.238-.53 0-.866.15-1.325.6-1.793.097-.112.15-.225.114-.26-.132-.13-1.296 1.179-1.578 1.777-.256.537-.283.65-.283 1.447.01.857.15 1.602.31 1.602.043 0 .06-.234.026-.563-.036-.39-.018-.598.061-.693.088-.104.088-.156 0-.26-.114-.13-.061-.676.106-1.1.115-.295.247-.234.247.112 0 .295.141.59.344.746.194.138.397-.052.715-.702.185-.39 1.41-2.14 1.72-2.46.061-.07.661-.062.661.008 0 .034-.335.398-.75.797-.829.806-1.014 1.187-.37.754.688-.468 1.605-1.508 1.967-2.236.309-.606.344-.736.335-1.334 0-.494-.053-.745-.212-1.074-.335-.676-1.587-1.907-1.587-1.56zM14.198.953c-.36.364-.3.702.212 1.144.212.182.424.329.477.329.044 0 .22-.13.38-.295.237-.242.281-.346.255-.623-.018-.191-.062-.321-.115-.295-.044.026-.08.078-.062.121.036.113-.167.312-.335.312-.08 0-.22-.078-.308-.173-.15-.156-.15-.277 0-.633.105-.242-.203-.182-.503.113zm-.202-.606c-.6.294-.794.346-1.261.346-.31 0-.644-.043-.741-.095-.194-.104-.477-.009-.82.277-.124.095-.486.173-1.147.243-.935.086-.98.104-1.235.38a3.928 3.928 0 0 0-.406.547c-.097.173-.415.398-1.103.762-1.56.832-1.72.997-1.402 1.473.08.113.22.494.318.84.202.72.388.98.635.91.114-.026.238.026.335.148.326.39.106.606-.37.372-.433-.216-.98-.182-1.218.07-.115.112-.185.277-.167.372.026.13.097.147.396.13.239-.017.52.035.785.147.221.104.547.182.706.182.168 0 .3.035.3.087 0 .043-.035.087-.08.087-.308 0-.096.805.318 1.239.203.199.282.225.538.181.362-.069.335.026-.123.416-.75.65-1.006 1.517-1.006 3.492 0 1.577-.114 2.002-.608 2.244-.644.33-1.712.043-2.338-.641-.176-.2-.335-.303-.37-.251-.124.199-.036 1.308.132 1.672.653 1.412 2.778 1.785 4.463.788.432-.26.75-.39.944-.39.759 0 2.064-.632 2.355-1.143.185-.32.309-.303.635.052.52.589 1.614.996 2.646 1.005.309 0 .45.052.6.208.309.32 1.12.667 1.729.736 1.658.182 2.69-.511 2.69-1.81 0-.27-.026-.52-.062-.546-.026-.035-.176.017-.326.103-.635.373-1.42.286-1.914-.216-.282-.286-.3-.338-.3-.927 0-.607.018-.641.459-1.317.67-1.014.758-1.274.705-1.967-.035-.416-.017-.606.062-.667.07-.052.23-.338.37-.641.345-.763.353-1.698.01-2.435-.133-.277-.221-.528-.203-.554.026-.018.132.026.247.104.105.078.229.138.264.138.088 0-.458-1.135-.653-1.351-.202-.226-.202-.295.018-.295.23 0 .22-.104-.009-.243-.282-.182-.503-.77-.564-1.568-.053-.745-.168-1.066-.45-1.325-.212-.182-.944-.468-1.42-.546-.283-.044-.424-.13-.609-.373-.335-.442-.74-.797-.908-.797-.08.009-.46.165-.847.347zm1.208.234c.37.398.688.9.688 1.117 0 .234-.458.78-.714.858-.23.078-.212.217.035.217.68 0 1.976 1.057 2.505 2.036.618 1.152.688 2.027.247 2.972-.388.84-.988 1.29-2.752 2.062-.344.156-.353.173-.185.26.176.095.176.112-.177.337-.67.434-.979 1.127-.864 1.907.07.424.415.91.662.91.123 0 .176.13.264.58a4.045 4.045 0 0 0 1.217 2.253c.31.303.52.545.477.545-.044 0-.318-.156-.609-.346-.29-.19-.59-.347-.67-.347-.106 0-.124-.06-.088-.242.044-.217-.027-.304-.609-.823-.803-.702-1.226-1.309-1.579-2.253-.37-1.014-.44-1.083-.397-.39.08 1.118 1.13 2.66 2.17 3.18.873.442-.106.37 [...]

2023-11-24 06:41 UTC, PratyushJayachandran approved these changes

2023-11-24 08:31 UTC, PratyushJayachandran commented
> Attached unformatted svg for reference,
> 
> ![ritzcarlton](https://user-images.githubusercontent.com/112414255/284072803-1174f226-b804-4496-993a-5dc450c3bb1a.svg)

Where did you find the SVG from? I was not able to extract any SVG from the linked url in source

2023-11-24 08:42 UTC, adamrusted requested changes

2023-11-24 08:42 UTC, adamrusted commented on icons/ritzcarlton.svg
Having pulled the path from the icon font, I'm seeing a fair few differences. Mind taking another look @PratyushJayachandran / @khamkarsuraj?
![image](https://github.com/simple-icons/simple-icons/assets/1830867/8087ced7-1aa8-40b7-bbdb-c87b27cf0aca)

2023-11-24 08:42 UTC, adamrusted commented on _data/simple-icons.json
> +            "source": "https://www.ritzcarlton.com/en/about-the-ritz-carlton/"
```suggestion
            "source": "https://www.ritzcarlton.com/en/about-the-ritz-carlton"
```

2023-11-24 08:59 UTC, PratyushJayachandran commented on icons/ritzcarlton.svg
@khamkarsuraj upon generating the icon from the font, it looks very different from the source you attached in the conversation. So my suggestion is not correct. Can you try again by using the font as source and then converting it to outlines to get the icon?

2023-11-24 15:50 UTC, khamkarsuraj commented on icons/ritzcarlton.svg
@PratyushJayachandran @adamrusted ,

I followed below steps to prepare icon.
Used Inscape.

1. Imported original image using Import.
2. Selected only icon area using icon Rectangle Tool and cropped required area.
3. Selected cropped icon, changed viewbox to '0 0 24 24', with height 24 and width 24.
4. Centered icon to viewbox. My new icon dimensions are X:4.000 Y: 0.000 W: 15.892 H: 24.000. I maintained original proportion of icon.
5. Combined all paths using Path > Combine.
Here is [screenshot](<img width="1081" alt="Screenshot 2023-11-24 at 10 30 22 AM" src="https://github.com/simple-icons/simple-icons/assets/112414255/bac98bed-833b-4b6a-a329-8b60f0744840">) for the same.

6. Moved file into simple-icons/icons and optimized using `npx svgo icons/ritzcarlton.svg`.
7. But now have this [icon](![ritzcarlton](https://github.com/simple-icons/simple-icons/assets/112414255/9ca2f14a-dbeb-47fe-8e0e-7d648ed7559b)) 

Will you tell me where it's going wrong?

2023-11-25 06:38 UTC, PratyushJayachandran commented on icons/ritzcarlton.svg
It seems like the source you attached isn't what the font generates, as pointed by @adamrusted. Since the icon on their website is generated using that font and reserved character code, we would need to do the same on our system to produce the original. So the flow failed with Step 1 itself. Rest of your flow is as expected and correct. Just start with installing the font and paste this character: https://codepoints.net/U+E927?lang=en to get the icon. Convert to outlines. Follow the rest of your steps.

To avoid back and forth, re-download your contribution from the PR and compare again with the source SVG laid on top of contribution with color changed to white. This will highlight differences if any.
Don't be discouraged! Sometimes the process gets complicated depending on the source.

2023-11-25 18:42 UTC, khamkarsuraj commented on icons/ritzcarlton.svg
@PratyushJayachandran Did you had a look at [ritzcarlton](https://github.com/simple-icons/simple-icons/assets/112414255/6b1b0d3a-432c-428f-a4fa-46d859cc9861). Does it have still same issue?

2023-11-25 23:39 UTC, PratyushJayachandran requested changes

2023-11-25 23:39 UTC, PratyushJayachandran commented on icons/ritzcarlton.svg
Unfortunately, yes. [Here is the original generated from font on my system overlaid on top of your latest contribution.](https://github.com/simple-icons/simple-icons/assets/35000807/9bf791c8-3299-48d5-9942-4af0b417470e)
You may download the SVG to see the original and contribution is separate layers.

2023-11-26 00:26 UTC, khamkarsuraj commented on icons/ritzcarlton.svg
@PratyushJayachandran, Is black outilne generated from font?

2023-11-26 00:40 UTC, PratyushJayachandran commented on icons/ritzcarlton.svg
Yes... I have named the layers in the SVG.

2023-11-26 00:58 UTC, khamkarsuraj commented on icons/ritzcarlton.svg
Updated, considering your svg. Check it out now.
I hope it works this time. 🙂
@PratyushJayachandran

2023-11-26 03:10 UTC, PratyushJayachandran approved these changes
Thank you for your contribution @khamkarsuraj 🎉

2023-11-26 03:10 UTC, PratyushJayachandran commented on icons/ritzcarlton.svg
@khamkarsuraj 
![image](https://github.com/simple-icons/simple-icons/assets/35000807/6e542290-5ae9-4808-9c9e-dc010ee36ec8)
Perfect match 😄

2023-11-26 03:12 UTC, merged

2023-11-26 03:30 UTC, khamkarsuraj commented
Thank you, @PratyushJayachandran & @adamrusted  for your valuable guidance. I learned something new. 🤝