Add Qase icon
simple-icons/simple-icons pull request #9907
Opened 2023-11-23 19:37 UTC by lananolana

**Issue:** closes #9321

**Similarweb rank:** 267,966. See [here](https://www.similarweb.com/website/qase.io/#overview).

### Checklist

- [ ] I updated the JSON data in `_data/simple-icons.json`
- [ ] I optimized the icon with SVGO or SVGOMG
- [ ] The SVG `viewbox` is `0 0 24 24`

### Description

![Qase](https://github.com/simple-icons/simple-icons/assets/107322490/f6f39c3e-3d26-4ce2-8f65-d41abd77f12b)

Qase is a modern test management platform for manual + automated QA testing, tracking, and reporting that helps deliver higher quality software, faster.

2023-11-24 01:28 UTC, PratyushJayachandran commented
Hello @lananolana 
It looks like we will need thier permission before using the icon. Refer: https://qase.io/terms
Can you inquire them about permission? If granted, just post a sceeenshot here and then we will go from there.

> Intellectual property rights
This Agreement does not transfer to you any intellectual property owned by Qase Inc or third-parties, and all rights, titles, and interests in and to such property will remain (as between the parties) solely with Qase Inc. All trademarks, service marks, graphics and logos used in connection with our Website or Services, are trademarks or registered trademarks of Qase Inc or Qase Inc licensors. Other trademarks, service marks, graphics and logos used in connection with our Website or Services may be the trademarks of other third-parties. Your use of our Website and Services grants you no right or license to reproduce or otherwise use any Qase Inc or third-party trademarks.

2023-11-25 14:25 UTC, UmangLadha commented
![download](https://github.com/simple-icons/simple-icons/assets/84621610/cde457bc-dd24-4315-bc6e-a23542bed2b2)

2023-11-25 14:26 UTC, UmangLadha commented
> ![download](https://private-user-images.githubusercontent.com/84621610/285596902-cde457bc-dd24-4315-bc6e-a23542bed2b2.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5MjI2MzksIm5iZiI6MTcwMDkyMjMzOSwicGF0aCI6Ii84NDYyMTYxMC8yODU1OTY5MDItY2RlNDU3YmMtZGQyNC00MzE1LWJjNmUtYTIzNTQyYmVkMmIyLnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI1VDE0MjUzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjZjBkYTg3Y2NkNWIxNTU4NzNjYWFiYzc5NWUzYjg1NDk2MjNkNTQzZDkzMmE4M2UyYmFjOWI4M2Y0OThlZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xZzbJe3VFJCSBCSprOruY95Wh-4wsxGYZzhd_KAk_MM)

here is your logo sir

2023-11-25 14:27 UTC, UmangLadha approved these changes

2023-11-29 07:47 UTC, n3r commented
Hello @PratyushJayachandran!

My name is Nikita and I'm Qase CEO and founder. I approve logo usage :)

P.S. @lananolana, thanks for adding!

2023-11-29 07:53 UTC, PratyushJayachandran commented
> Hello @PratyushJayachandran!
> 
> My name is Nikita and I'm Qase CEO and founder. I approve logo usage :)
> 
> P.S. @lananolana, thanks for adding!

Thank you for the confirmation chief. Will get this merged 😊

2023-11-30 07:55 UTC, PratyushJayachandran requested changes
Please make the requested changes @lananolana 😄

2023-11-30 07:55 UTC, PratyushJayachandran commented on icons/qase.svg
@lananolana I see [some differences](https://github.com/simple-icons/simple-icons/assets/35000807/311260c5-ad11-4029-aa9c-5607270fc5cb) when laying the source image turned white over your contribution. Can you give it another go? Please be careful to not round off or let your editing application round off the dimensions when scaling and positioning the icon.

2023-11-30 07:55 UTC, PratyushJayachandran commented on _data/simple-icons.json
> +            "source": "https://qase.io"
```suggestion
            "source": "https://qase.io",
            "license": {
                "type": "custom",
                "url": "https://github.com/simple-icons/simple-icons/pull/9907#issuecomment-1831377594"
            }
```
Please add this to indicate special permission granted for use of Qase icon in simple-icons

2023-12-11 10:20 UTC, PeterShaggyNoble commented
Are you still working on this one, @lananolana?

2023-12-12 15:39 UTC, lananolana commented
> [<img alt="@lananolana" width="20" height="20" src="https://avatars.githubusercontent.com/u/107322490?s=40&amp;v=4"> ](/lananolana)
> ` [Qase](/simple-icons/simple-icons/pull/9907/commits/70d59fdfa0d963b5058fc9e0669b9eb41b7c11dc)`

Done!

2023-12-13 09:54 UTC, PeterShaggyNoble requested changes
Thanks for the update, @lananolana, but I'm still seeing the same differences as @PratyushJayachandran above. It looks like this is simply a result of your version becoming vertically stretched - the "Q" in the source SVG (assuming you're using [this one](https://qase.io/images/qase-logo-white.svg) from the website's header isn't perfectly square, so resizing it to 24dp in width should result in a height of ~23.895dp.

2023-12-13 10:54 UTC, lananolana commented
> Thanks for the update, @lananolana, but I'm still seeing the same differences.

I use [this one](https://app.qase.io/assets/main/images/logo-night.698f1aa4.svg), but nevertheless Q is the same. Please check out my new attempt to work with svg.

2023-12-13 11:18 UTC, PeterShaggyNoble approved these changes
That looks spot on now, @lananolana 👍🏻 Thanks for your work on this one.

2023-12-13 11:20 UTC, merged